### ISSUE TITLE
Running "miner info" report error

### ISSUE THREAD

**Issue by Cyanglacier** [filecoin-project/lotus#1010]
When running lotus-storage-miner info, CLI shows that:

```
panic: runtime error: index out of range [9] with length 8

goroutine 1 [running]:
github.com/filecoin-project/lotus/chain/types.BigInt.SizeStr(0xc00000e500, 0xc00003e7f0, 0x3)
        /root/lotus/lotus/chain/types/bigint.go:140 +0x395
main.glob..func1(0xc000498420, 0x0, 0x0)
        /root/lotus/lotus/cmd/lotus-storage-miner/info.go:54 +0x43b
gopkg.in/urfave/cli%2ev2.(*Command).Run(0x2954380, 0xc0004983c0, 0x0, 0x0)
        /root/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/command.go:167 +0x6cf
gopkg.in/urfave/cli%2ev2.(*App).Run(0xc000378600, 0xc000032180, 0x3, 0x3, 0x0, 0x0)
        /root/go/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/app.go:261 +0x68c
main.main()
        /root/lotus/lotus/cmd/lotus-storage-miner/main.go:75 +0x66e
```

PLZ, FIX IT!
![微信图片_20191224222058](https://user-images.githubusercontent.com/47769205/71416505-af3cb880-269b-11ea-8efe-a8c95fe2f288.png)

**Comment by zhy2006** [comment]
fixed size overflow issue
#1012

**Comment by whyrusleeping** [comment]
this is now resolved, thanks for reporting
