### ISSUE TITLE
Constant "panic: runtime error: integer divide by zero" in 1.19.1

### ISSUE THREAD

**Issue by lazavikmaria** [filecoin-project/lotus#10277]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
migration for the nv20 upgrade hyperspace 

from 
Daemon:  1.19.1-dev+hyperspacenet+git.41cec06+api1.5.0
Local: lotus version 1.19.1-dev+hyperspacenet+git.41cec06

to 
Daemon:  1.19.1-dev+hyperspacenet+git.017f328+api1.5.0
Local: lotus version 1.19.1-dev+hyperspacenet+git.017f328
```

### Describe the Bug

During the hyperspace migration to the new version. 
 The nodes began to give strange stuff and the blocks didn't start syncing. ,  error like this

```
"@timestamp": "2023-02-15T08:38:53.402Z",
    "log": "panic: runtime error: integer divide by zero\n",
    "stream": "stderr",
    "time": "2023-02-15T08:38:53.402956124Z"
```
This wasn't before for previous updated
 Temporary solution: was used redeploy from scratch
 
I saw the similar issue but it closed 
 https://github.com/filecoin-project/lotus/issues/5895
 
 We can provide access to Opensearch logs if you want. Please let us know in slack @glif-nodes-team 

### Logging Information

```text
github.com/filecoin-project/lotus/cli/util.FullNodeProxy[...].func1.1()
	/go/lotus/cli/util/api.go:278 +0x1c8
github.com/filecoin-project/lotus/lib/retry.Retry[...]({0x54fac70?, 0x400005a040}, 0x5, 0x4000c1f0e8, {0x4000c1f118?, 0x2, 0x2}, 0x4000c1f138)
	/go/lotus/lib/retry/retry.go:21 +0x138
github.com/filecoin-project/lotus/cli/util.FullNodeProxy[...].func1()
	/go/lotus/cli/util/api.go:277 +0x300
github.com/filecoin-project/lotus/api.(*CommonStruct).Version(0x54dac80?, {0x54fac70?, 0x400005a040?})
	/go/lotus/api/proxy_gen.go:1376 +0x3c
github.com/filecoin-project/lotus/cli/util.GetFullNodeAPIV1(0x4000b7e880, {0x4000651060, 0x1, 0x0?})
	/go/lotus/cli/util/api.go:386 +0x438
main.glob..func2(0x713ab60?)
	/go/lotus/cmd/lotus-gateway/main.go:167 +0x2e4
github.com/urfave/cli/v2.(*Command).Run(0x713ab60, 0x4000b7e580)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/command.go:173 +0x5bc
github.com/urfave/cli/v2.(*App).RunContext(0x4000b7ca80, {0x54fac70?, 0x400005a040}, {0x400004e060, 0x2, 0x2})
	/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:383 +0xbc8
github.com/urfave/cli/v2.(*App).Run(...)
	/go/pkg/mod/github.com/urfave/cli/v2@v2.16.3/app.go:252
main.main()
	/go/lotus/cmd/lotus-gateway/main.go:56 +0x2ac
25
{"level":"info","ts":"2023-02-15T10:56:14.963Z","logger":"gateway","caller":"lotus-gateway/main.go:156","msg":"Starting lotus gateway"}
{"level":"warn","ts":"2023-02-15T10:56:14.967Z","logger":"cliutil","caller":"util/api.go:364","msg":"Not able to establish connection to node with addr: %!(EXTRA string=ws://0.0.0.0:1234/rpc/v1)"}
panic: runtime error: integer divide by zero
```

### Repo Steps

1.  lotus version 1.19.1-dev+hyperspacenet+git.41cec06
2. migrate to new version  lotus version 1.19.1-dev+hyperspacenet+git.017f328
3. See error

**Comment by ArseniiPetrovich** [comment]
Well, basically, we start the on the very same container, so it's the default parameters that are ingested. We run Lotus and then simply start Gateway from the very same place (`lotus-gateway run`)

Our clients starts their Lotus Lite nodes with `FULLNODE_API_INFO=wss://wss.node.glif.io/apigw/lotus lotus daemon --lite`, but we don't use FULLNODE_API_INFO and/or LOTUS_PATH when starting the gateway or the nodes themselves

**Comment by magik6k** [comment]
* Are you able to run other lotus commands in the container?
* Is it possible that you're starting lotus-gateway before the lotus RPC is up? Can you try staring the gateway with `lotus wait-api && lotus-gateway run`?

**Comment by ArseniiPetrovich** [comment]
- Yes, we can run additional commands if necessary 
- Maaaybe. For now we just check lotus daemon in the processes list => https://github.com/glifio/filecoin-docker/blob/master/scripts/launch#L16

We will patch it to `lotus wait-api && lotus-gateway run` and see how it goes, thanks!

**Comment by arajasek** [comment]
Descoping from 1.20.0-rc2 as it's under active investigation

**Comment by parkan** [comment]
seeing this with normal lotus connections currently:

```
$ lotus info

2023-02-23T08:36:17.007-0800    WARN    cliutil util/api.go:342 Not able to establish connection to node with addr: %!(EXTRA string=ws://0.0.0.0:3453/rpc/v1)
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/filecoin-project/lotus/cli/util.FullNodeProxy[...].func1.1()
        /home/user/lotus/cli/util/api.go:278 +0x1d2
github.com/filecoin-project/lotus/lib/retry.Retry[...]({0x5525c90?, 0xc0001a4000}, 0x5, 0x0, {0xc000732b00?, 0x2, 0x2}, 0xc000732b20)
        /home/user/lotus/lib/retry/retry.go:21 +0x1a5
github.com/filecoin-project/lotus/cli/util.FullNodeProxy[...].func1()
        /home/user/lotus/cli/util/api.go:277 +0x3af
github.com/filecoin-project/lotus/api.(*CommonStruct).Version(0x55049f0?, {0x5525c90?, 0xc0001a4000?})
        /home/user/lotus/api/proxy_gen.go:1197 +0x32
github.com/filecoin-project/lotus/cli/util.GetFullNodeAPIV1(0xc000e4cd40)
        /home/user/lotus/cli/util/api.go:364 +0x2e5
github.com/filecoin-project/lotus/cli.infoCmdAct(0x7027840?)
        /home/user/lotus/cli/info.go:32 +0x5a
github.com/urfave/cli/v2.(*Command).Run(0x7027840, 0xc000e4cc80)
        /home/user/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:169 +0x656
github.com/urfave/cli/v2.(*App).RunContext(0xc000703040, {0x5525c90?, 0xc0001a4000}, {0xc0001a2000, 0x2, 0x2})
        /home/user/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:341 +0xbfd
github.com/urfave/cli/v2.(*App).Run(...)
        /home/user/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:247
github.com/filecoin-project/lotus/cli.RunApp(0x3cf5200?)
        /home/user/lotus/cli/helper.go:39 +0x4e
main.main()
        /home/user/lotus/cmd/lotus/main.go:111 +0x929
```
it does appear that the node is hanging

**Comment by lazavikmaria** [comment]
Hi all!
We patched it to the `lotus wait-API && lotus-gateway` run and checked. Seems it works, thanks!
[glifio/filecoin-docker/pull/72]

**Comment by paul8046** [comment]
Possible duplicate [10327](https://github.com/filecoin-project/lotus/issues/10327)

**Comment by segunjkf** [comment]
> Update launch glifio/filecoin-docker#72
I'm experiencing the same problem. As this has been resolved, what are the alternatives?

**Comment by rjan90** [comment]
Closing as this has been solved. At least users running Debian experienced this panic because FD limits has to be set in `/etc/security/limits.conf` and `/etc/systemd/system.conf` and `/etc/systemd/user.conf`.
