### ISSUE TITLE
splitstore_compact fatal error: sync: Unlock of unlocked RWMutex

### ISSUE THREAD

**Issue by marco-storswift** [filecoin-project/lotus#10616]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus fvm/fevm - Lotus FVM and FEVM interactions
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt/WinningPoSt)
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus main branch
```

### Repro Steps

lotus run daemon
...

### Describe the Bug

fatal error: sync: Unlock of unlocked RWMutex

### Logging Information

```text
2023-04-04T04:13:02.986+0800    INFO    chain   chain/sync_manager.go:315       worker 7040 syncing in [bafy2bzaceaxut7cjsqajvahpvhv7wfbxiiglwerequfd4xusev5o4lfhp3bb2]
fatal error: sync: Unlock of unlocked RWMutex

goroutine 2736046 [running]:
sync.fatal({0x4e447d3?, 0x178c326?})
        /usr/local/go/src/runtime/panic.go:1031 +0x1e
sync.(*RWMutex).Unlock(0xc0002b26fc)
        /usr/local/go/src/sync/rwmutex.go:209 +0x4a
sync.(*Cond).Wait(0xc0b39911c0?)
        /usr/local/go/src/sync/cond.go:69 +0x7e
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).waitForSync(0xc0002b2600)
        /mnt/lotus/lotusbuild/20230401165537/marco/blockstore/splitstore/splitstore_compact.go:924 +0xab
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).checkYield(0xc0002b2600)
        /mnt/lotus/lotusbuild/20230401165537/marco/blockstore/splitstore/splitstore_compact.go:930 +0x1e
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObject(0xc0002b2600?, {{0xc21540d320?, 0xc0b3991330?}}, {0x67edb20, 0xa248750}, 0xc0ae153c40)
        /mnt/lotus/lotusbuild/20230401165537/marco/blockstore/splitstore/splitstore_compact.go:1156 +0x1a6
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObject(0xc0002b2600?, {{0xc13fcd91d0?, 0xc0b3991420?}}, {0x67edb20, 0xa248750}, 0xc0ae153c40)
        /mnt/lotus/lotusbuild/20230401165537/marco/blockstore/splitstore/splitstore_compact.go:1173 +0x3e5
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObject(0xc0002b2600?, {{0xc259e1ac90?, 0xc0b3991510?}}, {0x67edb20, 0xa248750}, 0xc0ae153c40)
        /mnt/lotus/lotusbuild/20230401165537/marco/blockstore/splitstore/splitstore_compact.go:1173 +0x3e5
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObject(0xc0002b2600?, {{0xc21afd1e30?, 0xc0b3991600?}}, {0x67edb20, 0xa248750}, 0xc0ae153c40)
        /mnt/lotus/lotusbuild/20230401165537/marco/blockstore/splitstore/splitstore_compact.go:1173 +0x3e5
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObject(0xc0002b2600?, {{0xc1b5790cf0?, 0xc0b39916f0?}}, {0x67edb20, 0xa248750}, 0xc0ae153c40)
        /mnt/lotus/lotusbuild/20230401165537/marco/blockstore/splitstore/splitstore_compact.go:1173 +0x3e5
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObject(0xc0002b2600?, {{0xc1deb043c0?, 0xc0b39917e0?}}, {0x67edb20, 0xa248750}, 0xc0ae153c40)
        /mnt/lotus/lotusbuild/20230401165537/marco/blockstore/splitstore/splitstore_compact.go:1173 +0x3e5
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObject(0xc0002b2600?, {{0xc20d70b7d0?, 0xc0b39918d0?}}, {0x67edb20, 0xa248750}, 0xc0ae153c40)
        /mnt/lotus/lotusbuild/20230401165537/marco/blockstore/splitstore/splitstore_compact.go:1173 +0x3e5
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObject(0xc0002b2600?, {{0xc25268c960?, 0xc0b39919c0?}}, {0x67edb20, 0xa248750}, 0xc0ae153c40)
        /mnt/lotus/lotusbuild/20230401165537/marco/blockstore/splitstore/splitstore_compact.go:1173 +0x3e5
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObject(0xc0002b2600?, {{0xc2667065d0?, 0xc0b3b5fab0?}}, {0x67edb20, 0xa248750}, 0xc0ae153c40)
        /mnt/lotus/lotusbuild/20230401165537/marco/blockstore/splitstore/splitstore_compact.go:1173 +0x3e5
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObject(0xc0002b2600?, {{0xc1d7d0c2d0?, 0xc0b3b5fba0?}}, {0x67edb20, 0xa248750}, 0xc0ae153c40)
        /mnt/lotus/lotusbuild/20230401165537/marco/blockstore/splitstore/splitstore_compact.go:1173 +0x3e5
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObject(0xc0002b2600?, {{0xc1401eca50?, 0x1444bef?}}, {0x67edb20, 0xa248750}, 0xc0ae153c40)
        /mnt/lotus/lotusbuild/20230401165537/marco/blockstore/splitstore/splitstore_compact.go:1173 +0x3e5
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkObject(0xc0840a2150?, {{0xc1fad40420?, 0xc214604f00?}}, {0x67edb20, 0xa248750}, 0xc0ae153c40)
        /mnt/lotus/lotusbuild/20230401165537/marco/blockstore/splitstore/splitstore_compact.go:1173 +0x3e5
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).walkChain.func3({{0xc224429ce0?, 0x0?}})
```

**Comment by ZenGround0** [comment]
> lotus main branch

Can you give us lotus version please.  I am pretty sure you are on `feat/splitstore-gc-wait-for-sync` which introduced the `checkYield` function.  That branch hasn't been merged to the main branch yet (because of this bug) unless we've made a mistake.

**Comment by ZenGround0** [comment]
Also @Stebalien just pushed a fix to `feat/splitstore-gc-wait-for-sync` so if you'd like to keep running the experimental pause compaction feature then you can pull and try that out.

**Comment by marco-storswift** [comment]
> > lotus main branch
> 
> Can you give us lotus version please. I am pretty sure you are on `feat/splitstore-gc-wait-for-sync` which introduced the `checkYield` function. That branch hasn't been merged to the main branch yet (because of this bug) unless we've made a mistake.

sorrry, I just pick the commit from https://github.com/filecoin-project/lotus/pull/10392. Not in main branch

**Comment by rjan90** [comment]
Closing this issue as this was fixed in https://github.com/filecoin-project/lotus/commit/68f402da39d6c66f47115a5c0c07286d66729387
