### ISSUE TITLE
Lotus daemon segmentation violation

### ISSUE THREAD

**Issue by icostan** [filecoin-project/lotus#1079]
**Describe the bug**
Fresh install, followed the https://docs.lotu.sh/en+install-lotus-arch doc but lotus daemon fails to run. Not sure if they are related but I see multiple WARN in logs: protocol not supported, sector size, stream reset, etc. 

**To Reproduce**
1. Run 'lotus daemon'
2. See error

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa8ab7e]

goroutine 497 [running]:
github.com/filecoin-project/lotus/chain/actors.StoragePowerActor.ArbitrateConsensusFault(0xc0358ae780, 0x1f18420, 0xc031ee9c70, 0xc0251694c0, 0x50, 0xc0002e9fd8, 0x5d580c, 0x1a356c0, 0x1a356c0)
	/home/icostan/Repos/lotus/chain/actors/actor_storagepower.go:133 +0x3e

**Expected behavior**
Daemon to run

**Screenshots**

**Version (run `lotus --version`):**
lotus version 0.2.0+git3b34eba6

**Additional context**
system:
OS: Arch Linux x86_64 
Host: 81LF Lenovo Legion Y7000P-1060 
Kernel: 5.4.11-arch1-1 
Shell: zsh 5.7.1 
Resolution: 1920x1080 
WM: i3 
Terminal: kitty  
CPU: Intel i7-8750H (12) @ 4.100GHz 
GPU: NVIDIA GeForce GTX 1060 Mobile 
GPU: Intel UHD Graphics 630 
Memory: 2278MiB / 31991MiB

log and stack trace:

2020-01-14T17:01:38.358+0200	WARN	modules	modules/services.go:31	failed to say hello	{"error": "protocol not supported"}
2020-01-14T17:01:38.358+0200	WARN	pubsub	go-log@v1.0.1/log.go:186	opening new stream to peer: stream reset12D3KooWRicwFBtxumMo1uEP93gPATULZAjySbuaM3Nuw3PFkCiV
2020-01-14T17:01:41.652+0200	WARN	vm	vm/vm.go:470	[from=t3wjxuftije2evjmzo2yoy5ghfe2o42mavrpmwuzooghzcxdhqjdu7kn6dvkzf4ko37w7sfnnzdzstcjmeooea,to=t02,n=2737,m=2,h=795] Send actor error: Unsupported sector size: 1073741824 (RetCode=1):
    github.com/filecoin-project/lotus/chain/actors.StoragePowerActor.CreateStorageMiner
        /home/icostan/Repos/lotus/chain/actors/actor_storagepower.go:70
2020-01-14T17:01:42.981+0200	WARN	modules	modules/services.go:31	failed to say hello	{"error": "stream reset"}
2020-01-14T17:01:44.802+0200	WARN	vm	vm/vm.go:470	[from=t3wjxuftije2evjmzo2yoy5ghfe2o42mavrpmwuzooghzcxdhqjdu7kn6dvkzf4ko37w7sfnnzdzstcjmeooea,to=t02,n=2773,m=2,h=807] Send actor error: Unsupported sector size: 1073741824 (RetCode=1):
    github.com/filecoin-project/lotus/chain/actors.StoragePowerActor.CreateStorageMiner
        /home/icostan/Repos/lotus/chain/actors/actor_storagepower.go:70
2020-01-14T17:01:45.965+0200	INFO	hello	hello/hello.go:105	Got new tipset through Hello: [bafy2bzacebwjqnnp23zibkbg6n5bmerpgqj3kowfhf34qq5r4nwlh4wdx73os bafy2bzaced5zbevjhhi3bpw45ogfavlyjfkt5w6bf5xidclom5fzwqnhncd24 bafy2bzacebr3sbp37n7st4eflvg5fggq5xmk3hdlfnspsdkeru43dohjb36ay] from 12D3KooWFEpSpT1CXkuBorx99T6mPE6FScJQ9kJUuAoo5KACY2ky
2020-01-14T17:01:45.966+0200	INFO	chain	chain/sync_manager.go:283	scheduling incoming tipset sync: [bafy2bzacebwjqnnp23zibkbg6n5bmerpgqj3kowfhf34qq5r4nwlh4wdx73os bafy2bzaced5zbevjhhi3bpw45ogfavlyjfkt5w6bf5xidclom5fzwqnhncd24 bafy2bzacebr3sbp37n7st4eflvg5fggq5xmk3hdlfnspsdkeru43dohjb36ay]
2020-01-14T17:01:46.689+0200	WARN	modules	modules/services.go:31	failed to say hello	{"error": "protocol not supported"}
2020-01-14T17:01:46.691+0200	WARN	pubsub	go-log@v1.0.1/log.go:186	opening new stream to peer: stream reset12D3KooWRicwFBtxumMo1uEP93gPATULZAjySbuaM3Nuw3PFkCiV
2020-01-14T17:01:46.729+0200	WARN	sub	sub/incoming.go:95	failed to add message from network to message pool (From: t3r4nmknkzuyhdfgcpnedafmzntmz47cncdzoama6zivuxxgbi4lr22roa6t6yercq7fomqryde7kqp6reo5eq, To: t03, Nonce: 21, Value: 0): failed to look up actor state nonce: resolution lookup failed (t3r4nmknkzuyhdfgcpnedafmzntmz47cncdzoama6zivuxxgbi4lr22roa6t6yercq7fomqryde7kqp6reo5eq): actor not found
2020-01-14T17:01:48.864+0200	WARN	sub	sub/incoming.go:95	failed to add message from network to message pool (From: t3u53tlnd6syruwkffeb754bfjgzc75k4a6nlku22qj7wu6tufdlt4uglwezf6jzjdxzscmezhr25iecj3fomq, To: t03, Nonce: 12, Value: 0): failed to look up actor state nonce: resolution lookup failed (t3u53tlnd6syruwkffeb754bfjgzc75k4a6nlku22qj7wu6tufdlt4uglwezf6jzjdxzscmezhr25iecj3fomq): actor not found
2020-01-14T17:01:49.925+0200	WARN	modules	modules/services.go:31	failed to say hello	{"error": "protocol not supported"}
2020-01-14T17:01:50.697+0200	WARN	pubsub	go-log@v1.0.1/log.go:186	opening new stream to peer: stream reset12D3KooWRicwFBtxumMo1uEP93gPATULZAjySbuaM3Nuw3PFkCiV
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa8ab7e]

goroutine 497 [running]:
github.com/filecoin-project/lotus/chain/actors.StoragePowerActor.ArbitrateConsensusFault(0xc0358ae780, 0x1f18420, 0xc031ee9c70, 0xc0251694c0, 0x50, 0xc0002e9fd8, 0x5d580c, 0x1a356c0, 0x1a356c0)
	/home/icostan/Repos/lotus/chain/actors/actor_storagepower.go:133 +0x3e
reflect.Value.call(0x1a28860, 0xc02512acd0, 0x13, 0x1bf41e9, 0x4, 0xc0002ea358, 0x3, 0x3, 0x1, 0x1a356c0, ...)
	/usr/lib/go/src/reflect/value.go:460 +0x5f6
reflect.Value.Call(0x1a28860, 0xc02512acd0, 0x13, 0xc0002ea358, 0x3, 0x3, 0x0, 0x7f532440d2f8, 0x7f54543b72d0)
	/usr/lib/go/src/reflect/value.go:321 +0xb4
github.com/filecoin-project/lotus/chain/vm.(*invoker).transform.func2(0xc01dea2000, 0x3, 0x3, 0xc01dea2000, 0x30, 0xc02c185c20)
	/home/icostan/Repos/lotus/chain/vm/invoker.go:144 +0x226
reflect.callReflect(0xc02940d620, 0xc0002ea518, 0xc0002ea500)
	/usr/lib/go/src/reflect/value.go:549 +0x322
reflect.makeFuncStub(0xc0358ae780, 0x1f18420, 0xc031ee9c70, 0xc025287bfa, 0x3, 0x3, 0xc02c185c20, 0xc0002ea598, 0x62db1d, 0xc02c185c20, ...)
	/usr/lib/go/src/reflect/asm_amd64.s:20 +0x42
github.com/filecoin-project/lotus/chain/vm.(*invoker).Invoke(0xc0255ff090, 0xc0358ae780, 0x1f18420, 0xc031ee9c70, 0x3, 0xc025287bfa, 0x3, 0x3, 0xc0358ae9c0, 0xc02558e000, ...)
	/home/icostan/Repos/lotus/chain/vm/invoker.go:58 +0x1c2
github.com/filecoin-project/lotus/chain/vm.(*VM).Invoke(0xc02e8e7f80, 0xc0358ae780, 0xc031ee9c70, 0x3, 0xc025287bfa, 0x3, 0x3, 0x0, 0x0, 0x0, ...)

**Comment by magik6k** [comment]
Already fixed in 0.2.1
