### ISSUE TITLE
lotus daemon

### ISSUE THREAD

**Issue by noguiber** [filecoin-project/lotus#1357]
```
2020-03-08T18:22:19.063+0900	WARN	vm	vm/vm.go:498	Send actor error	{"from": "t3so2ryai2df2kmkzyjyvinbbkx44mt4fh2p3htrgoteuhnneanoc7wliwnrtyi34txnq2zbf6dkrknmw6zx7a", "to": "t01031", "nonce": 109, "method": 4, "height": 1100, "error": "submit fallback PoSt called too early (1100 < 1130) (RetCode=1):\n    github.com/filecoin-project/lotus/chain/actors.StorageMinerActor.SubmitFallbackPoSt\n        /home/noh/lotus/chain/actors/actor_miner.go:453"}
2020-03-08T18:22:19.064+0900	WARN	vm	vm/vm.go:498	Send actor error	{"from": "t3so2ryai2df2kmkzyjyvinbbkx44mt4fh2p3htrgoteuhnneanoc7wliwnrtyi34txnq2zbf6dkrknmw6zx7a", "to": "t01031", "nonce": 111, "method": 4, "height": 1100, "error": "submit fallback PoSt called too early (1100 < 1130) (RetCode=1):\n    github.com/filecoin-project/lotus/chain/actors.StorageMinerActor.SubmitFallbackPoSt\n        /home/noh/lotus/chain/actors/actor_miner.go:453"}
2020-03-08T18:22:19.142+0900	WARN	vm	vm/vm.go:498	Send actor error	{"from": "t3qb46i34s7wsli5q7ntgc57npox6iey6mefh7zpreebyyra67iwba3d7giqumgov4q7kafxsriy7uc73eqkuq", "to": "t03133", "nonce": 16, "method": 14, "height": 1100, "error": "could not create account (RetCode=1):\n    github.com/filecoin-project/lotus/chain/vm.(*VM).send\n        /home/noh/lotus/chain/vm/vm.go:387\n  - no actor with given ID: t03133 (RetCode=1):\n    github.com/filecoin-project/lotus/chain/vm.makeActor\n        /home/noh/lotus/chain/vm/mkactor.go:51"}
**panic: runtime error: invalid memory address or nil pointer dereference**
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xad6c27]

goroutine 511 [running]:
github.com/filecoin-project/lotus/chain/vm.(*VM).ApplyMessage(0xc075bab0e0, 0x1f6f360, 0xc03d3b3e00, 0xc04cd820c0, 0x0, 0x0, 0x0)
	/home/noh/lotus/chain/vm/vm.go:542 +0xd57
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).computeTipSetState(0xc01dd23e00, 0x1f6f360, 0xc02e227740, 0xc048969020, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, ...)
	/home/noh/lotus/chain/stmgr/stmgr.go:245 +0x1853
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).TipSetState(0xc01dd23e00, 0x1f6f360, 0xc02e227710, 0xc04788c100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/noh/lotus/chain/stmgr/stmgr.go:103 +0x6f7
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock(0xc01dd1f320, 0x1f6f360, 0xc02e2272f0, 0xc03d9e4340, 0x0, 0x0)
	/home/noh/lotus/chain/sync.go:584 +0x515
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet(0xc01dd1f320, 0x1f6f360, 0xc02e226d20, 0xc046bcdbc0, 0x0, 0x0)
	/home/noh/lotus/chain/sync.go:453 +0x233
github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1(0x1f6f360, 0xc0613c00f0, 0xc046bcdbc0, 0xc05e23d0e0, 0x14)
	/home/noh/lotus/chain/sync.go:1038 +0x1df
github.com/filecoin-project/lotus/chain.(*Syncer).iterFullTipsets(0xc01dd1f320, 0x1f6f360, 0xc0613c00f0, 0xc04347e000, 0x18565, 0x1d800, 0xc000721b88, 0x0, 0x0)
	/home/noh/lotus/chain/sync.go:1098 +0x4b8
github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState(0xc01dd1f320, 0x1f6f360, 0xc034d6e600, 0xc04347e000, 0x18565, 0x1d800, 0x1, 0x1)
	/home/noh/lotus/chain/sync.go:1036 +0x112
github.com/filecoin-project/lotus/chain.(*Syncer).collectChain(0xc01dd1f320, 0x1f6f360, 0xc034d6e5d0, 0xc034d4a940, 0x0, 0x0)
	/home/noh/lotus/chain/sync.go:1172 +0x5ff
github.com/filecoin-project/lotus/chain.(*Syncer).Sync(0xc01dd1f320, 0x1f6f360, 0xc034d6e5d0, 0xc034d4a940, 0x0, 0x0)
	/home/noh/lotus/chain/sync.go:407 +0x1be
github.com/filecoin-project/lotus/chain.(*SyncManager).syncWorker(0xc0000c7760, 0x0)
	/home/noh/lotus/chain/sync_manager.go:386 +0x16f
created by github.com/filecoin-project/lotus/chain.(*SyncManager).Start
	/home/noh/lotus/chain/sync_manager.go:74 +0x6f
```

v0.2.10  lotus daemon  error~

**Comment by whyrusleeping** [comment]
This has been resolved, thanks for reporting!
