### ISSUE TITLE
Lotus crashing when transaction has not enough gas

### ISSUE THREAD

**Issue by rllola** [filecoin-project/lotus#1407]
**Describe the bug**
Lotus has crashed when I tried to send a transaction through JSONRPC.

**Expected behavior**
Expect an error being returned and lotus still up.

**Log**

```
2020-03-13T09:30:22.299+0100	WARN	vm	vm/vm.go:498	Send actor error	{"from": "t1lv32q33y64xs64pnyn6om7ftirax5ikspkumwsa", "to": "t1b4zd6ryj5dsnwda5jtjxj6ptkia5e35s52ox7ka", "nonce": 2, "method": 0, "height": 112390, "error": "sending funds (RetCode=200):\n    github.com/filecoin-project/lotus/chain/vm.(*VM).send\n        /home/lola/Workspace/lotus/chain/vm/vm.go:410\n  - not enough gas: used=118, available=0 (RetCode=200):\n    github.com/filecoin-project/lotus/chain/vm.(*VMContext).ChargeGas\n        /home/lola/Workspace/lotus/chain/vm/vm.go:198"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0xad6c27]

goroutine 459 [running]:
github.com/filecoin-project/lotus/chain/vm.(*VM).ApplyMessage(0xc0240823c0, 0x1f6e800, 0xc02edb2c60, 0xc01d6c7830, 0x0, 0x0, 0x0)
	/home/lola/Workspace/lotus/chain/vm/vm.go:542 +0xd57
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).computeTipSetState(0xc01a680090, 0x1f6e800, 0xc0240751a0, 0xc000124330, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/home/lola/Workspace/lotus/chain/stmgr/stmgr.go:245 +0x1853
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).TipSetState(0xc01a680090, 0x1f6e800, 0xc024075170, 0xc022dcc600, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/lola/Workspace/lotus/chain/stmgr/stmgr.go:103 +0x6f7
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock(0xc03bc55aa0, 0x1f6e800, 0xc0240750b0, 0xc024055240, 0x0, 0x0)
	/home/lola/Workspace/lotus/chain/sync.go:584 +0x515
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet(0xc03bc55aa0, 0x1f6e800, 0xc024074e40, 0xc0240559c0, 0x0, 0x0)
	/home/lola/Workspace/lotus/chain/sync.go:453 +0x233
github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1(0x1f6e800, 0xc0238d14d0, 0xc0240559c0, 0x0, 0x0)
	/home/lola/Workspace/lotus/chain/sync.go:1038 +0x1df
github.com/filecoin-project/lotus/chain.(*Syncer).iterFullTipsets(0xc03bc55aa0, 0x1f6e800, 0xc0238d14d0, 0xc01e7a6000, 0x5b8, 0x6a0, 0xc02444fb88, 0x0, 0x0)
	/home/lola/Workspace/lotus/chain/sync.go:1064 +0xcbb
github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState(0xc03bc55aa0, 0x1f6e800, 0xc01b2aa690, 0xc01e7a6000, 0x5b8, 0x6a0, 0x3, 0x3)
	/home/lola/Workspace/lotus/chain/sync.go:1036 +0x112
github.com/filecoin-project/lotus/chain.(*Syncer).collectChain(0xc03bc55aa0, 0x1f6e800, 0xc01b2aa660, 0xc01a7c4dc0, 0x0, 0x0)
	/home/lola/Workspace/lotus/chain/sync.go:1172 +0x5ff
github.com/filecoin-project/lotus/chain.(*Syncer).Sync(0xc03bc55aa0, 0x1f6e800, 0xc01b2aa660, 0xc01a7c4dc0, 0x0, 0x0)
	/home/lola/Workspace/lotus/chain/sync.go:407 +0x1be
github.com/filecoin-project/lotus/chain.(*SyncManager).syncWorker(0xc00049a840, 0x0)
	/home/lola/Workspace/lotus/chain/sync_manager.go:386 +0x16f
created by github.com/filecoin-project/lotus/chain.(*SyncManager).Start
	/home/lola/Workspace/lotus/chain/sync_manager.go:74 +0x6f
```

**Version (run `lotus --version`):**
```
lotus version 0.2.8+gitd4c0dfa8
```

**Additional context**
If I try to relaunch the daemon it crash with the same. Can I clean the transaction pool somewhere ?

**Comment by arajasek** [comment]
Thanks for the catch! This has been fixed :)
