### ISSUE TITLE
Testnet/3 lotus daemon crash with unknown reason

### ISSUE THREAD

**Issue by Cyanglacier** [filecoin-project/lotus#1437]
When running lotus daemon, it will crash in a hours, the reason is unknown.

No expected behavior to trigger this problem.

Crash log is updated as below.
[Lotus testnet3 crashlog.txt](https://github.com/filecoin-project/lotus/files/4358886/Lotus.testnet3.crashlog.txt)

Lotus version is 
0.3.0+git852ad2c8+api0.2.0
lotus version 0.3.0+git852ad2c8

My computer is not using a server motherboard and ram is 2133 16G*8, CPU is ryzen 3700X, GPU is rtx 2080ti, with 1t Nvme SSD and 10T HDD.

A part of crash log:
```
2020-03-20T17:48:07.713+0800	[33mWARN[0m	pubsub	go-log@v1.0.2/log.go:175	opening new stream to peer: stream reset12D3KooWDqbxoeQPWqXDUfZRUUxZ8Y5TvUL5Aq9PtND2fU2ZYUAL
unexpected fault address 0x801d5f1ac0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x801d5f1ac0 pc=0xd600d6]

goroutine 411 [running]:
runtime.throw(0x1dbbc07, 0x5)
	/usr/lib/go-1.13/src/runtime/panic.go:774 +0x72 fp=0xc0185d3b40 sp=0xc0185d3b10 pc=0x525ca2
runtime.sigpanic()
	/usr/lib/go-1.13/src/runtime/signal_unix.go:401 +0x3de fp=0xc0185d3b70 sp=0xc0185d3b40 pc=0x53b72e
github.com/dgraph-io/badger/v2/table.(*Iterator).seekFrom.func1(0xbfe, 0x14000000140001)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200120142413-c3333a5a830e/table/iterator.go:244 +0x46 fp=0xc0185d3bb8 sp=0xc0185d3b70 pc=0xd600d6
sort.Search(0x297d, 0xc0185d3c20, 0xc0185d3c70)
	/usr/lib/go-1.13/src/sort/search.go:66 +0x58 fp=0xc0185d3bf0 sp=0xc0185d3bb8 pc=0x5c2478
github.com/dgraph-io/badger/v2/table.(*Iterator).seekFrom(0xc0186375c0, 0xc04cf91aa0, 0x54, 0x54, 0x0)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200120142413-c3333a5a830e/table/iterator.go:242 +0xef fp=0xc0185d3c58 sp=0xc0185d3bf0 pc=0xd5aa2f
github.com/dgraph-io/badger/v2/table.(*Iterator).seek(...)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200120142413-c3333a5a830e/table/iterator.go:275
github.com/dgraph-io/badger/v2/table.(*Iterator).Seek(0xc0186375c0, 0xc04cf91aa0, 0x54, 0x54)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200120142413-c3333a5a830e/table/iterator.go:385 +0x94 fp=0xc0185d3c90 sp=0xc0185d3c58 pc=0xd5b494
github.com/dgraph-io/badger/v2.(*levelHandler).get(0xc0004f4480, 0xc04cf91aa0, 0x54, 0x54, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200120142413-c3333a5a830e/level_handler.go:275 +0x274 fp=0xc0185d3da0 sp=0xc0185d3c90 pc=0xd7c7a4
github.com/dgraph-io/badger/v2.(*levelsController).get(0xc00043e080, 0xc04cf91aa0, 0x54, 0x54, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200120142413-c3333a5a830e/levels.go:982 +0xcf fp=0xc0185d3e80 sp=0xc0185d3da0 pc=0xd8543f
github.com/dgraph-io/badger/v2.(*DB).get(0xc000016800, 0xc04cf91aa0, 0x54, 0x54, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200120142413-c3333a5a830e/db.go:608 +0x337 fp=0xc0185d3ff0 sp=0xc0185d3e80 pc=0xd6c697
github.com/dgraph-io/badger/v2.(*Txn).Get(0xc038ae3080, 0xc0391e4410, 0x4c, 0x50, 0x4c, 0x50, 0xc0185d4140)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200120142413-c3333a5a830e/txn.go:407 +0xe7 fp=0xc0185d40e0 sp=0xc0185d3ff0 pc=0xd94257
github.com/ipfs/go-ds-badger2.(*txn).get(0xc0185d4200, 0xc0391e43c0, 0x4c, 0xc0391e43c0, 0xc0391e43c7, 0xc0185d41f8, 0x45, 0x45)
	/root/go/pkg/mod/github.com/ipfs/go-ds-badger2@v0.0.0-20200211201106-609c9d2a39c7/datastore.go:476 +0x75 fp=0xc0185d4150 sp=0xc0185d40e0 pc=0xdb3345
github.com/ipfs/go-ds-badger2.(*Datastore).Get(0xc01f19b380, 0xc0391e43c0, 0x4c, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/ipfs/go-ds-badger2@v0.0.0-20200211201106-609c9d2a39c7/datastore.go:277 +0x163 fp=0xc0185d4228 sp=0xc0185d4150 pc=0xdb15d3
github.com/ipfs/go-datastore/keytransform.(*Datastore).Get(0xc00000e040, 0xc0391e4370, 0x45, 0xc0391e4370, 0x45, 0x3d, 0x3e, 0xc020fc68c0)
	/root/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.2/keytransform/keytransform.go:47 +0x76 fp=0xc0185d4278 sp=0xc0185d4228 pc=0xad4ea6
github.com/ipfs/go-datastore/keytransform.(*Datastore).Get(0xc00000e120, 0xc020fc6900, 0x3e, 0xc020fc6900, 0x3e, 0x30, 0x20, 0x2a)
	/root/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.2/keytransform/keytransform.go:47 +0x76 fp=0xc0185d42c8 sp=0xc0185d4278 pc=0xad4ea6
github.com/ipfs/go-ipfs-blockstore.(*blockstore).Get(0xc00000e140, 0xc029acc2d0, 0x26, 0x0, 0x0, 0x0, 0xc050f42cf0)
	/root/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v0.1.4/blockstore.go:123 +0xaf fp=0xc0185d4398 sp=0xc0185d42c8 pc=0xad787f
github.com/ipfs/go-ipfs-blockstore.(*idstore).Get(0xc01f1836a0, 0xc029acc2d0, 0x26, 0xc04c379920, 0x20c5dc0, 0xc0185d4430, 0xb121e4)
	/root/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v0.1.4/idstore.go:57 +0xd7 fp=0xc0185d43e8 sp=0xc0185d4398 pc=0xad8b67
github.com/filecoin-project/lotus/lib/bufbstore.(*BufferedBS).Get(0xc02d779ce0, 0xc029acc2d0, 0x26, 0x2, 0xc039124f79, 0xc04c379920, 0x1)
	/filecoin/testnet3/lotus/lib/bufbstore/buf_bstore.go:79 +0x4b fp=0xc0185d4440 sp=0xc0185d43e8 pc=0xb0523b
github.com/filecoin-project/lotus/chain/vm.(*gasChargingBlocks).Get(0xc04963b700, 0xc029acc2d0, 0x26, 0x0, 0x0, 0xc039124ac8, 0x1)
	/filecoin/testnet3/lotus/chain/vm/vm.go:100 +0x61 fp=0xc0185d4498 sp=0xc0185d4440 pc=0xb0c591
github.com/ipfs/go-ipld-cbor.(*BasicIpldStore).Get(0xc04963b720, 0x20f0c40, 0xc0000420b0, 0xc029acc2d0, 0x26, 0x1d550a0, 0xc02d839200, 0x1be94a0, 0x1d550a0)
	/root/go/pkg/mod/github.com/ipfs/go-ipld-cbor@v0.0.5-0.20200204214505-252690b78669/store.go:44 +0x62 fp=0xc0185d4548 sp=0xc0185d4498 pc=0x7289a2
github.com/filecoin-project/lotus/chain/vm.(*Runtime).Get(0xc0472ada40, 0xc029acc2d0, 0x26, 0x7efb99c167c0, 0xc02d839200, 0xc02d839200)
	/filecoin/testnet3/lotus/chain/vm/runtime.go:60 +0x87 fp=0xc0185d45b0 sp=0xc0185d4548 pc=0xb08167
github.com/filecoin-project/specs-actors/actors/util/adt.rtStore.Get(0x210c120, 0xc0472ada40, 0x20f0cc0, 0xc049784210, 0xc029acc2d0, 0x26, 0x1d550a0, 0xc02d839200, 0x7efb99c16701, 0xc02d839200)
	/root/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.0.0-20200312030511-3f5510bf6130/actors/util/adt/store.go:40 +0xa1 fp=0xc0185d4608 sp=0xc0185d45b0 pc=0x9c30c1
github.com/filecoin-project/specs-actors/actors/util/adt.(*rtStore).Get(0xc0422d5000, 0x20f0cc0, 0xc049784210, 0xc029acc2d0, 0x26, 0x1d550a0, 0xc02d839200, 0xc049784210, 0xc0185d46e8)
	<autogenerated>:1 +0x92 fp=0xc0185d4668 sp=0xc0185d4608 pc=0x9c4032
github.com/ipfs/go-hamt-ipld.LoadNode(0x20f0cc0, 0xc049784210, 0x7efb99c16778, 0xc0422d5000, 0xc029acc2d0, 0x26, 0x0, 0x0, 0x0, 0xc02d839180, ...)
	/root/go/pkg/mod/github.com/ipfs/go-hamt-ipld@v0.0.15-0.20200204200533-99b8553ef242/hamt.go:144 +0x91 fp=0xc0185d46d0 sp=0xc0185d4668 pc=0x9bb501
github.com/ipfs/go-hamt-ipld.(*Pointer).loadChild(0xc050f42de0, 0x20f0cc0, 0xc049784210, 0x7efb99c16778, 0xc0422d5000, 0x5, 0xc037012ba0, 0x26, 0x0)
	/root/go/pkg/mod/github.com/ipfs/go-hamt-ipld@v0.0.15-0.20200204200533-99b8553ef242/hamt.go:132 +0x8b fp=0xc0185d4740 sp=0xc0185d46d0 pc=0x9bb3bb
github.com/ipfs/go-hamt-ipld.(*Node).getValue(0xc02d839180, 0x20f0cc0, 0xc049784210, 0xc0185d48a0, 0xc039124aa8, 0x2, 0xc0185d4888, 0x0, 0x0)
	/root/go/pkg/mod/github.com/ipfs/go-hamt-ipld@v0.0.15-0.20200204200533-99b8553ef242/hamt.go:110 +0x1e6 fp=0xc0185d47c0 sp=0xc0185d4740 pc=0x9bb216
github.com/ipfs/go-hamt-ipld.(*Node).getValue(0xc02d839100, 0x20f0cc0, 0xc049784210, 0xc0185d48a0, 0xc039124aa8, 0x2, 0xc0185d4888, 0x8, 0xc039124aa8)
	/root/go/pkg/mod/github.com/ipfs/go-hamt-ipld@v0.0.15-0.20200204200533-99b8553ef242/hamt.go:115 +0x26b fp=0xc0185d4840 sp=0xc0185d47c0 pc=0x9bb29b
github.com/ipfs/go-hamt-ipld.(*Node).Find(0xc02d839100, 0x20f0cc0, 0xc049784210, 0xc039124aa8, 0x2, 0x1bdebc0, 0xc037f03840, 0x20c6240, 0xc000091420)
	/root/go/pkg/mod/github.com/ipfs/go-hamt-ipld@v0.0.15-0.20200204200533-99b8553ef242/hamt.go:71 +0x11a fp=0xc0185d48d0 sp=0xc0185d4840 pc=0x9baeea
github.com/filecoin-project/specs-actors/actors/util/adt.(*Map).Get(0xc04c378d20, 0x20c9260, 0xc039124a60, 0x20c7d80, 0xc037f03840, 0x1c44340, 0x0, 0x100000000000000)
	/root/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.0.0-20200312030511-3f5510bf6130/actors/util/adt/map.go:68 +0xfe fp=0xc0185d4990 sp=0xc0185d48d0 pc=0x9c189e
github.com/filecoin-project/specs-actors/actors/util/adt.(*Multimap).Get(0xc0185d4ac0, 0x20c9260, 0xc039124a60, 0x10, 0x1b45960, 0x0, 0xc039124a60)
	/root/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.0.0-20200312030511-3f5510bf6130/actors/util/adt/multimap.go:87 +0x88 fp=0xc0185d4a28 sp=0xc0185d4990 pc=0x9c2b78
github.com/filecoin-project/specs-actors/actors/util/adt.(*Multimap).ForEach(0xc0185d4ac0, 0x20c9260, 0xc039124a60, 0x20c6de0, 0xc050f42630, 0xc0185d4ae8, 0x0, 0x0)
	/root/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.0.0-20200312030511-3f5510bf6130/actors/util/adt/multimap.go:75 +0x43 fp=0xc0185d4a70 sp=0xc0185d4a28 pc=0x9c2a53
github.com/filecoin-project/specs-actors/actors/builtin/power.(*State).loadCronEvents(0xc050d84f00, 0x20ea800, 0xc0422d5000, 0x1114, 0x0, 0x0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.0.0-20200312030511-3f5510bf6130/actors/builtin/power/power_state.go:311 +0x198 fp=0xc0185d4b28 sp=0xc0185d4a70 pc=0xa52048
github.com/filecoin-project/specs-actors/actors/builtin/power.Actor.processDeferredCronEvents.func1(0xc0472ada40, 0xc020734cc0)
	/root/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.0.0-20200312030511-3f5510bf6130/actors/builtin/power/power_actor.go:559 +0x102 fp=0xc0185d4c10 sp=0xc0185d4b28 pc=0xa555d2
github.com/filecoin-project/lotus/chain/vm.(*shimStateHandle).Transaction(0xc02b114930, 0x20dcb40, 0xc050d84f00, 0xc049784240, 0xc050d84ea0, 0xc0422d4fd0)
	/filecoin/testnet3/lotus/chain/vm/runtime.go:377 +0x102 fp=0xc0185d4ca0 sp=0xc0185d4c10 pc=0xb0aff2
github.com/filecoin-project/specs-actors/actors/builtin/power.Actor.processDeferredCronEvents(0x210c120, 0xc0472ada40, 0x1, 0x1)
	/root/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.0.0-20200312030511-3f5510bf6130/actors/builtin/power/power_actor.go:555 +0x160 fp=0xc0185d4d98 sp=0xc0185d4ca0 pc=0xa4f450
github.com/filecoin-project/specs-actors/actors/builtin/power.Actor.OnEpochTickEnd(0x210c120, 0xc0472ada40, 0x30064f0, 0x1d8c0e0)
	/root/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.0.0-20200312030511-3f5510bf6130/actors/builtin/power/power_actor.go:540 +0x9e fp=0xc0185d4df0 sp=0xc0185d4d98 pc=0xa4f20e
github.com/filecoin-project/specs-actors/actors/builtin/power.Actor.OnEpochTickEnd-fm(0x210c120, 0xc0472ada40, 0x30064f0, 0x0)
	/root/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.0.0-20200312030511-3f5510bf6130/actors/builtin/power/power_actor.go:537 +0x3f fp=0xc0185d4e20 sp=0xc0185d4df0 pc=0xa56eff
runtime.call32(0xc046c04fc0, 0xc01ffd1ba0, 0xc04963b7a0, 0x1800000020)
	/usr/lib/go-1.13/src/runtime/asm_amd64.s:539 +0x3b fp=0xc0185d4e50 sp=0xc0185d4e20 pc=0x55417b
reflect.Value.call(0x1b94440, 0xc01ffd1ba0, 0x13, 0x1dbaae8, 0x4, 0xc0185d5148, 0x2, 0x2, 0xc0185d5110, 0x54cd87, ...)
	/usr/lib/go-1.13/src/reflect/value.go:460 +0x5f6 fp=0xc0185d5070 sp=0xc0185d4e50 pc=0x5ad3d6
reflect.Value.Call(0x1b94440, 0xc01ffd1ba0, 0x13, 0xc0185d5148, 0x2, 0x2, 0x1c17bc0, 0x189240, 0x1bd8e40)
	/usr/lib/go-1.13/src/reflect/value.go:321 +0xb4 fp=0xc0185d50f0 sp=0xc0185d5070 pc=0x5acb94
github.com/filecoin-project/lotus/chain/vm.(*invoker).transform.func2.1(0xc0185d51c8, 0xc0422d4fc0)
	/filecoin/testnet3/lotus/chain/vm/invoker.go:155 +0x111 fp=0xc0185d5188 sp=0xc0185d50f0 pc=0xb10ab1
github.com/filecoin-project/lotus/chain/vm.(*Runtime).shimCall(0xc0472ada40, 0xc0185d5328, 0x0, 0x0, 0x0, 0x0, 0x0)
	/filecoin/testnet3/lotus/chain/vm/runtime.go:92 +0x92 fp=0xc0185d5220 sp=0xc0185d5188 pc=0xb083d2
github.com/filecoin-project/lotus/chain/vm.(*invoker).transform.func2(0xc03475f6d0, 0x3, 0x3, 0xc03475f6d0, 0x203012, 0x3e)
	/filecoin/testnet3/lotus/chain/vm/invoker.go:154 +0x26e fp=0xc0185d5378 sp=0xc0185d5220 pc=0xb10dbe
reflect.callReflect(0xc0232d21b0, 0xc0185d54e0, 0xc0185d54c8)
	/usr/lib/go-1.13/src/reflect/value.go:549 +0x322 fp=0xc0185d54b0 sp=0xc0185d5378 pc=0x5ae6d2
reflect.makeFuncStub(0xc0234af980, 0x210c120, 0xc0472ada40, 0x0, 0x0, 0x0, 0xc049784210, 0xc04976ca00, 0x0, 0x0, ...)
	/usr/lib/go-1.13/src/reflect/asm_amd64.s:20 +0x42 fp=0xc0185d54e0 sp=0xc0185d54b0 pc=0x5ba222
github.com/filecoin-project/lotus/chain/vm.(*invoker).Invoke(0xc0484166f0, 0xc0234af980, 0x210c120, 0xc0472ada40, 0xf, 0x0, 0x0, 0x0, 0xc049784210, 0xc035317480, ...)
	/filecoin/testnet3/lotus/chain/vm/invoker.go:74 +0x1c2 fp=0xc0185d55e0 sp=0xc0185d54e0 pc=0xb06292
github.com/filecoin-project/lotus/chain/vm.(*VM).Invoke(0xc04ca20c40, 0xc0234af980, 0xc0472ada40, 0xf, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/filecoin/testnet3/lotus/chain/vm/vm.go:551 +0x205 fp=0xc0185d5760 sp=0xc0185d55e0 pc=0xb101d5
github.com/filecoin-project/lotus/chain/vm.(*VM).send(0xc04ca20c40, 0x20f0cc0, 0xc04933ae10, 0xc04180dc20, 0xc0472ad7c0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/filecoin/testnet3/lotus/chain/vm/vm.go:235 +0x239 fp=0xc0185d5840 sp=0xc0185d5760 pc=0xb0cf79
github.com/filecoin-project/lotus/chain/vm.(*Runtime).internalSend(0xc0472ad7c0, 0xc04938ad10, 0x2, 0xf, 0xc0491c7440, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/filecoin/testnet3/lotus/chain/vm/runtime.go:318 +0x384 fp=0xc0185d5a20 sp=0xc0185d5840 pc=0xb0a584
github.com/filecoin-project/lotus/chain/vm.(*Runtime).Send(0xc0472ad7c0, 0xc04938ad10, 0x2, 0xf, 0x0, 0x0, 0xc0491c7440, 0xc0185d5c18, 0x5b6c4c, 0x1bd8e40)
	/filecoin/testnet3/lotus/chain/vm/runtime.go:281 +0x9d fp=0xc0185d5b30 sp=0xc0185d5a20 pc=0xb09e0d
github.com/filecoin-project/specs-actors/actors/builtin/cron.Actor.EpochTick(0x210c120, 0xc0472ad7c0, 0x30064f0, 0x1d8c0e0)
	/root/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.0.0-20200312030511-3f5510bf6130/actors/builtin/cron/cron_actor.go:39 +0x1ac fp=0xc0185d5bc8 sp=0xc0185d5b30 pc=0xaf7b0c
github.com/filecoin-project/specs-actors/actors/builtin/cron.Actor.EpochTick-fm(0x210c120, 0xc0472ad7c0, 0x30064f0, 0x0)
	/root/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.0.0-20200312030511-3f5510bf6130/actors/builtin/cron/cron_actor.go:33 +0x3f fp=0xc0185d5bf8 sp=0xc0185d5bc8 pc=0xaf7d0f
runtime.call32(0xc046c04fc0, 0xc01ffd1ab0, 0xc0491c7380, 0x1800000020)
	/usr/lib/go-1.13/src/runtime/asm_amd64.s:539 +0x3b fp=0xc0185d5c28 sp=0xc0185d5bf8 pc=0x55417b
reflect.Value.call(0x1b94440, 0xc01ffd1ab0, 0x13, 0x1dbaae8, 0x4, 0xc0185d5f20, 0x2, 0x2, 0xc0185d5ee8, 0x54cd87, ...)
	/usr/lib/go-1.13/src/reflect/value.go:460 +0x5f6 fp=0xc0185d5e48 sp=0xc0185d5c28 pc=0x5ad3d6
reflect.Value.Call(0x1b94440, 0xc01ffd1ab0, 0x13, 0xc0185d5f20, 0x2, 0x2, 0x1c17bc0, 0x189240, 0x1bd8e40)
	/usr/lib/go-1.13/src/reflect/value.go:321 +0xb4 fp=0xc0185d5ec8 sp=0xc0185d5e48 pc=0x5acb94
github.com/filecoin-project/lotus/chain/vm.(*invoker).transform.func2.1(0xc0185d5fa0, 0xc0422d4390)
	/filecoin/testnet3/lotus/chain/vm/invoker.go:155 +0x111 fp=0xc0185d5f60 sp=0xc0185d5ec8 pc=0xb10ab1
github.com/filecoin-project/lotus/chain/vm.(*Runtime).shimCall(0xc0472ad7c0, 0xc0185d6100, 0x0, 0x0, 0x0, 0x0, 0x0)
	/filecoin/testnet3/lotus/chain/vm/runtime.go:92 +0x92 fp=0xc0185d5ff8 sp=0xc0185d5f60 pc=0xb083d2
github.com/filecoin-project/lotus/chain/vm.(*invoker).transform.func2(0xc03475f630, 0x3, 0x3, 0xc03475f630, 0x203012, 0x5032d8)
	/filecoin/testnet3/lotus/chain/vm/invoker.go:154 +0x26e fp=0xc0185d6150 sp=0xc0185d5ff8 pc=0xb10dbe
reflect.callReflect(0xc0231c9e90, 0xc0185d62b8, 0xc0185d62a0)
	/usr/lib/go-1.13/src/reflect/value.go:549 +0x322 fp=0xc0185d6288 sp=0xc0185d6150 pc=0x5ae6d2
reflect.makeFuncStub(0xc04933a390, 0x210c120, 0xc0472ad7c0, 0x0, 0x0, 0x0, 0xc04933ad20, 0x0, 0x0, 0x0, ...)
	/usr/lib/go-1.13/src/reflect/asm_amd64.s:20 +0x42 fp=0xc0185d62b8 sp=0xc0185d6288 pc=0x5ba222
github.com/filecoin-project/lotus/chain/vm.(*invoker).Invoke(0xc0484166f0, 0xc04933a390, 0x210c120, 0xc0472ad7c0, 0x2, 0x0, 0x0, 0x0, 0xc04933ad20, 0xc033488d00, ...)
	/filecoin/testnet3/lotus/chain/vm/invoker.go:74 +0x1c2 fp=0xc0185d63b8 sp=0xc0185d62b8 pc=0xb06292
github.com/filecoin-project/lotus/chain/vm.(*VM).Invoke(0xc04ca20c40, 0xc04933a390, 0xc0472ad7c0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/filecoin/testnet3/lotus/chain/vm/vm.go:551 +0x205 fp=0xc0185d6538 sp=0xc0185d63b8 pc=0xb101d5
github.com/filecoin-project/lotus/chain/vm.(*VM).send(0xc04ca20c40, 0x20f0cc0, 0xc048e93440, 0xc04180c900, 0x0, 0x26, 0x0, 0x0, 0x0, 0x0, ...)
	/filecoin/testnet3/lotus/chain/vm/vm.go:235 +0x239 fp=0xc0185d6618 sp=0xc0185d6538 pc=0xb0cf79
github.com/filecoin-project/lotus/chain/vm.(*VM).ApplyMessage(0xc04ca20c40, 0x20f0cc0, 0xc048e93440, 0xc04180c900, 0x0, 0x0, 0x0)
	/filecoin/testnet3/lotus/chain/vm/vm.go:336 +0x57d fp=0xc0185d6978 sp=0xc0185d6618 pc=0xb0daad
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).ApplyBlocks(0xc01f1e9350, 0x20f0cc0, 0xc041b1ac30, 0xc01d66a8d0, 0x26, 0xc01fafaeb0, 0x1, 0x1, 0x11dc, 0x20c6500, ...)
	/filecoin/testnet3/lotus/chain/stmgr/stmgr.go:267 +0xa76 fp=0xc0185d6df8 sp=0xc0185d6978 pc=0xbabb16
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).computeTipSetState(0xc01f1e9350, 0x20f0cc0, 0xc041b1ac30, 0xc04a585988, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
	/filecoin/testnet3/lotus/chain/stmgr/stmgr.go:353 +0xa9e fp=0xc0185d7008 sp=0xc0185d6df8 pc=0xbad65e
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).TipSetState(0xc01f1e9350, 0x20f0cc0, 0xc041b1ac00, 0xc01d50d2c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/filecoin/testnet3/lotus/chain/stmgr/stmgr.go:112 +0x69d fp=0xc0185d71e0 sp=0xc0185d7008 pc=0xbaabcd
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock(0xc01f208660, 0x20f0cc0, 0xc041b1ab40, 0xc035a1e280, 0x0, 0x0)
	/filecoin/testnet3/lotus/chain/sync.go:583 +0x514 fp=0xc0185d75d0 sp=0xc0185d71e0 pc=0xdcae44
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet(0xc01f208660, 0x20f0cc0, 0xc041b1a990, 0xc040ed4740, 0x0, 0x0)
	/filecoin/testnet3/lotus/chain/sync.go:459 +0x242 fp=0xc0185d7718 sp=0xc0185d75d0 pc=0xdca272
github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1(0x20f0cc0, 0xc0204307b0, 0xc040ed4740, 0xc05287a000, 0x21)
	/filecoin/testnet3/lotus/chain/sync.go:1076 +0x1df fp=0xc0185d7830 sp=0xc0185d7718 pc=0xdd895f
github.com/filecoin-project/lotus/chain.(*Syncer).iterFullTipsets(0xc01f208660, 0x20f0cc0, 0xc0204307b0, 0xc01fdbc000, 0x1ba, 0x200, 0xc0185d7b48, 0x0, 0x0)
	/filecoin/testnet3/lotus/chain/sync.go:1136 +0x4fc fp=0xc0185d7af8 sp=0xc0185d7830 pc=0xdd202c
github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState(0xc01f208660, 0x20f0cc0, 0xc01f26cea0, 0xc01fdbc000, 0x1ba, 0x200, 0x1, 0x1)
	/filecoin/testnet3/lotus/chain/sync.go:1074 +0x112 fp=0xc0185d7b70 sp=0xc0185d7af8 pc=0xdd1ad2
github.com/filecoin-project/lotus/chain.(*Syncer).collectChain(0xc01f208660, 0x20f0cc0, 0xc01f26ce70, 0xc01f893bc0, 0x0, 0x0)
	/filecoin/testnet3/lotus/chain/sync.go:1210 +0x60e fp=0xc0185d7d80 sp=0xc0185d7b70 pc=0xdd339e
github.com/filecoin-project/lotus/chain.(*Syncer).Sync(0xc01f208660, 0x20f0cc0, 0xc01f26ce70, 0xc01f893bc0, 0x0, 0x0)
	/filecoin/testnet3/lotus/chain/sync.go:413 +0x1d5 fp=0xc0185d7ee8 sp=0xc0185d7d80 pc=0xdc9915
github.com/filecoin-project/lotus/chain.(*Syncer).Sync-fm(0x20f0cc0, 0xc01f26ce40, 0xc01f893bc0, 0x30064f0, 0x1c5c1a0)
	/filecoin/testnet3/lotus/chain/sync.go:394 +0x48 fp=0xc0185d7f28 sp=0xc0185d7ee8 pc=0xdd9358
github.com/filecoin-project/lotus/chain.(*SyncManager).syncWorker(0xc000373d90, 0x0)
	/filecoin/testnet3/lotus/chain/sync_manager.go:386 +0x16f fp=0xc0185d7fd0 sp=0xc0185d7f28 pc=0xdd606f
runtime.goexit()
	/usr/lib/go-1.13/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0185d7fd8 sp=0xc0185d7fd0 pc=0x555e91
created by github.com/filecoin-project/lotus/chain.(*SyncManager).Start
	/filecoin/testnet3/lotus/chain/sync_manager.go:74 +0x6f
```
[Lotus testnet3 crashlog.txt](https://github.com/filecoin-project/lotus/files/4358886/Lotus.testnet3.crashlog.txt)

**Comment by whyrusleeping** [comment]
This is some weird badger issue looks like... going to label it as such and leave it open

**Comment by jennijuju** [comment]
@whyrusleeping do you think this issue still exists?

**Comment by arajasek** [comment]
Hopefully fixed by badger updates since...hopefully...
