### ISSUE TITLE
bench crashed on  Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz

### ISSUE THREAD

**Issue by mostcute** [filecoin-project/lotus#1545]
[errbench.txt](https://github.com/filecoin-project/lotus/files/4475147/errbench.txt)
**Describe the bug**
the bench crashed on  Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz
**To Reproduce**
1. Run `export FIL_PROOFS_MAXIMIZE_CACHING=1 `
`./bench sealing --sector-size=34359738368`
2. See error

```
2020-04-14T02:51:04.523+0800    INFO    lotus-bench     lotus-bench/main.go:225 Writing piece into sector...
2020-04-14T03:05:24.512+0800    INFO    lotus-bench     lotus-bench/main.go:239 Running replication(1)...
SIGILL: illegal instruction
PC=0x12d8fe9 m=0 sigcode=2

goroutine 0 [idle]:
runtime: unknown pc 0x12d8fe9
stack: frame={sp:0x7ffef61c4068, fp:0x0} stack=[0x7ffef5fc6028,0x7ffef61c5060)
00007ffef61c3f68:  0000000000000006  0000000000000000 
00007ffef61c3f78:  00007ffef61c46b0  0000000000000007 
00007ffef61c3f88:  00007ffef61c4188  8f03a57223f42e01 
00007ffef61c3f98:  dbe91091a5234e02  b397030000000031 
00007ffef61c3fa8:  0000000000000000  00007ffef61c4008 
00007ffef61c3fb8:  0000000000000000  a0512b96c0ef6000 
00007ffef61c3fc8:  6955ab9da41e53bd  8f03a57223f42e01 
00007ffef61c3fd8:  dbe91091a5234e02  b397030000000031 
00007ffef61c3fe8:  0000000000000008  0000000000000000 
00007ffef61c3ff8:  000000000000001f  00a0512b96c0ef60 
00007ffef61c4008:  0000000000000001  0000000000000001 
00007ffef61c4018:  0000000002269a38  8f03a57223f42e01 
00007ffef61c4028:  dbe91091a5234e02  b397030000000031 
00007ffef61c4038:  0000000fffffffe0  b397030000000006 
00007ffef61c4048:  0000000000000001  000000007fffffff 
00007ffef61c4058:  0000000000000020  0000000fffffffe0 
00007ffef61c4068: <00007ffef61c4378  0000000003b4ab20 
00007ffef61c4078:  00007ffef61c46b0  00007ffef61c44f0 
00007ffef61c4088:  00007ffef61c4110  00007ffef61c4100 
00007ffef61c4098:  00000000012d8dc5  0000000000000000 
00007ffef61c40a8:  0000000000000000  0000000000000000 
00007ffef61c40b8:  0000000000000000  00007ffef61c44b0 
00007ffef61c40c8:  0000000000d738d6  00007ffef61c4121 
00007ffef61c40d8:  00007ffef61c41c0  00007ffef61c44f0 
00007ffef61c40e8:  00007ffef61c46b0  0000000003b4ab20 
00007ffef61c40f8:  00007ffef61c41c0  00007ffef61c4210 
00007ffef61c4108:  00000000012c2a49  bda0512b96c0ef60 
00007ffef61c4118:  016955ab9da41e53  028f03a57223f42e 
00007ffef61c4128:  31dbe91091a5234e  0000000003b38d00 
00007ffef61c4138:  000014e5b3bb1d58  0000000000000032 
00007ffef61c4148:  0000000003b39b90  0000000000000006 
00007ffef61c4158:  0000000000000006  0000000000000000 
runtime: unknown pc 0x12d8fe9
stack: frame={sp:0x7ffef61c4068, fp:0x0} stack=[0x7ffef5fc6028,0x7ffef61c5060)
00007ffef61c3f68:  0000000000000006  0000000000000000 
00007ffef61c3f78:  00007ffef61c46b0  0000000000000007 
00007ffef61c3f88:  00007ffef61c4188  8f03a57223f42e01 
00007ffef61c3f98:  dbe91091a5234e02  b397030000000031 
00007ffef61c3fa8:  0000000000000000  00007ffef61c4008 
00007ffef61c3fb8:  0000000000000000  a0512b96c0ef6000 
00007ffef61c3fc8:  6955ab9da41e53bd  8f03a57223f42e01 
00007ffef61c3fd8:  dbe91091a5234e02  b397030000000031 
00007ffef61c3fe8:  0000000000000008  0000000000000000 
00007ffef61c3ff8:  000000000000001f  00a0512b96c0ef60 
00007ffef61c4008:  0000000000000001  0000000000000001 
00007ffef61c4018:  0000000002269a38  8f03a57223f42e01 
00007ffef61c4028:  dbe91091a5234e02  b397030000000031 
00007ffef61c4038:  0000000fffffffe0  b397030000000006 
00007ffef61c4048:  0000000000000001  000000007fffffff 
00007ffef61c4058:  0000000000000020  0000000fffffffe0 
00007ffef61c4068: <00007ffef61c4378  0000000003b4ab20 
00007ffef61c4078:  00007ffef61c46b0  00007ffef61c44f0 
00007ffef61c4088:  00007ffef61c4110  00007ffef61c4100 
00007ffef61c4098:  00000000012d8dc5  0000000000000000 
00007ffef61c40a8:  0000000000000000  0000000000000000 
00007ffef61c40b8:  0000000000000000  00007ffef61c44b0 
00007ffef61c40c8:  0000000000d738d6  00007ffef61c4121 
00007ffef61c40d8:  00007ffef61c41c0  00007ffef61c44f0 
00007ffef61c40e8:  00007ffef61c46b0  0000000003b4ab20 
00007ffef61c40f8:  00007ffef61c41c0  00007ffef61c4210 
00007ffef61c4108:  00000000012c2a49  bda0512b96c0ef60 
00007ffef61c4118:  016955ab9da41e53  028f03a57223f42e 
00007ffef61c4128:  31dbe91091a5234e  0000000003b38d00 
00007ffef61c4138:  000014e5b3bb1d58  0000000000000032 
00007ffef61c4148:  0000000003b39b90  0000000000000006 
00007ffef61c4158:  0000000000000006  0000000000000000 

goroutine 1 [syscall]:
runtime.cgocall(0xc44c40, 0xc0002dcae8, 0xbda0512b96c0ef60)
        /usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc0002dca90 sp=0xc0002dca58 pc=0x5046ab
github.com/filecoin-project/filecoin-ffi/generated._Cfunc_fil_seal_pre_commit_phase1(0xc000000003, 0xc0004c4180, 0xc0004c41c0, 0xc0004c4200, 0x1, 0x7e8, 0x0, 0x0, 0x0, 0x141cfc9842c4b0e3, ...)
        _cgo_gotypes.go:1434 +0x51 fp=0xc0002dcae8 sp=0xc0002dca90 pc=0xa74b51
github.com/filecoin-project/filecoin-ffi/generated.FilSealPreCommitPhase1(0xc000000003, 0xc0004c40c0, 0x32, 0xc0004c4040, 0x35, 0xc0004c4080, 0x33, 0x1, 0x7e8, 0x0, ...)
        /mnt/c/data/gopath/src/github.com/filecoin-project/lotus/extern/filecoin-ffi/generated/generated.go:460 +0x382 fp=0xc0002dcc70 sp=0xc0002dcae8 pc=0xa7ff82
github.com/filecoin-project/filecoin-ffi.SealPreCommitPhase1(0x1, 0xc0004c40c0, 0x32, 0xc0004c4040, 0x35, 0xc0004c4080, 0x33, 0x1, 0x3e8, 0xc0004c6060, ...)
        /mnt/c/data/gopath/src/github.com/filecoin-project/lotus/extern/filecoin-ffi/proofs.go:238 +0x314 fp=0xc0002dce90 sp=0xc0002dcc70 pc=0xa886f4
github.com/filecoin-project/sector-storage/ffiwrapper.(*Sealer).SealPreCommit1(0xc000362ba0, 0x190a880, 0xc00010e008, 0x3e8, 0x1, 0xc0004c6060, 0x20, 0x20, 0xc0004d2040, 0x1, ...)
        /mnt/c/data/gopath/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200406195014-a6d093838576/ffiwrapper/sealer_cgo.go:222 +0x466 fp=0xc0002dd068 sp=0xc0002dce90 pc=0xa95426
main.glob..func2(0xc0003625a0, 0x0, 0x0)
        /mnt/c/data/gopath/src/github.com/filecoin-project/lotus/cmd/lotus-bench/main.go:241 +0x943 fp=0xc0002ddc80 sp=0xc0002dd068 pc=0xc3f583
gopkg.in/urfave/cli%2ev2.(*Command).Run(0x22c3040, 0xc000362510, 0x0, 0x0)
        /mnt/c/data/gopath/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/command.go:167 +0x6cf fp=0xc0002dddc0 sp=0xc0002ddc80 pc=0xc287cf
gopkg.in/urfave/cli%2ev2.(*App).Run(0xc0000eed80, 0xc000108150, 0x3, 0x3, 0x0, 0x0)
        /mnt/c/data/gopath/pkg/mod/gopkg.in/urfave/cli.v2@v2.0.0-20180128182452-d3ae77c26ac8/app.go:261 +0x68c fp=0xc0002dded8 sp=0xc0002dddc0 pc=0xc25ebc
main.main()
        /mnt/c/data/gopath/src/github.com/filecoin-project/lotus/cmd/lotus-bench/main.go:82 +0x218 fp=0xc0002ddf60 sp=0xc0002dded8 pc=0xc3d6d8
runtime.main()
        /usr/local/go/src/runtime/proc.go:203 +0x21e fp=0xc0002ddfe0 sp=0xc0002ddf60 pc=0x53171e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0002ddfe8 sp=0xc0002ddfe0 pc=0x55df21

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 20 [select]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc0001099b0)
        /mnt/c/data/gopath/pkg/mod/github.com/ipfs/go-log@v1.0.3/writer/writer.go:71 +0x144
created by github.com/ipfs/go-log/writer.NewMirrorWriter
        /mnt/c/data/gopath/pkg/mod/github.com/ipfs/go-log@v1.0.3/writer/writer.go:36 +0xb9

goroutine 22 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00012e9b0)
        /mnt/c/data/gopath/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
        /mnt/c/data/gopath/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:32 +0x57

rax    0x0
rbx    0x168c2c8717273a20
rcx    0x7ffef61c40a0
rdx    0xbda0512b96c0ef60
rdi    0x7ffef61c4110
rsi    0x1999700
rbp    0x7ffef61c4100
rsp    0x7ffef61c4068
r8     0x60cbcb072ac46be0
r9     0x9554e18e052bcc73
r10    0x202a9d68be67ae37
r11    0x206
r12    0x7ffef61c44f0
r13    0x7ffef61c46b0
r14    0x3b4ab20
r15    0x7ffef61c4378
rip    0x12d8fe9
rflags 0x10246
cs     0x33
fs     0x0
gs     0x0
```

**Version (run ` ./bench --version`):**
root@els-gnx-005:~# ./bench --version
2020-04-14T20:13:53.121+0800    INFO    lotus-bench     lotus-bench/main.go:67  Starting lotus-bench
lotus-bench version 0.3.0

**Comment by magik6k** [comment]
Did you build the binary on the same machine?
