### ISSUE TITLE
Lotus daemon crash when running over 5 hours

### ISSUE THREAD

**Issue by Cyanglacier** [filecoin-project/lotus#1613]
This Bug occurred when running lotus daemon over 5 hours, cause lotus daemon crash. 

Here is a part of error code:

```
`goroutine 1363428 [select, 22 minutes]:
github.com/ipfs/go-bitswap/sessionmanager.(*SessionManager).NewSession.func1(0xc0ed20a020, 0xc0006c4b80, 0x1f715c0, 0xc0e1a20c00, 0x1f74840, 0xc091e4aaa0, 0x1f68b80, 0xc0df231260, 0x1f71200, 0xc0000420b0)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionmanager/sessionmanager.go:86 +0x103
created by github.com/ipfs/go-bitswap/sessionmanager.(*SessionManager).NewSession
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionmanager/sessionmanager.go:84 +0x339

goroutine 1287101 [select]:
github.com/ipfs/go-bitswap/sessionpeermanager.(*SessionPeerManager).run(0xc0880a6f00, 0x1f711c0, 0xc15628afc0)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionpeermanager/sessionpeermanager.go:149 +0xfd
created by github.com/ipfs/go-bitswap/sessionpeermanager.New
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionpeermanager/sessionpeermanager.go:72 +0x20d

goroutine 1742762 [IO wait]:
internal/poll.runtime_pollWait(0x7eecb7a7d978, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0e0358218, 0x72, 0x1100, 0x1190, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0e0358200, 0xc0534d0c00, 0x1190, 0x1190, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0e0358200, 0xc0534d0c00, 0x1190, 0x1190, 0x203046, 0x74ec40, 0xc12b618138)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc171df0cd8, 0xc0534d0c00, 0x1190, 0x1190, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc11925f2a0, 0xc0534d0c00, 0x1190, 0x1190, 0x1d, 0x1169, 0xc046ffac00)
        /usr/local/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc12b618258, 0x1f48ea0, 0xc11925f2a0, 0x4f4a05, 0x1aa2580, 0x1c0a480)
        /usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc12b618000, 0x7efbd42510b0, 0xc02c3c2360, 0x5, 0xc02c3c2360, 0xc)
        /usr/local/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc12b618000, 0x0, 0x0, 0x3)
        /usr/local/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc12b618000, 0xc1258440d0, 0xc, 0xc, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1233 +0x15b
io.ReadAtLeast(0x7efbd42cd150, 0xc121e7c7d0, 0xc1258440d0, 0xc, 0xc, 0xc, 0xc, 0x0, 0x0)
        /usr/local/go/src/io/io.go:310 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:329
github.com/libp2p/go-yamux.(*Session).recvLoop(0xc0a9dd3ee0, 0x0, 0x0)
        /root/local/gopath/pkg/mod/github.com/libp2p/go-yamux@v1.2.3/session.go:507 +0xda
github.com/libp2p/go-yamux.(*Session).recv(0xc0a9dd3ee0)
        /root/local/gopath/pkg/mod/github.com/libp2p/go-yamux@v1.2.3/session.go:486 +0x2b
created by github.com/libp2p/go-yamux.newSession
        /root/local/gopath/pkg/mod/github.com/libp2p/go-yamux@v1.2.3/session.go:129 +0x379

goroutine 1625646 [select]:
github.com/ipfs/go-bitswap/session.(*Session).run(0xc0deecf000, 0x1f711c0, 0xc122fd4800)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/session/session.go:207 +0x24c
created by github.com/ipfs/go-bitswap/session.New
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/session/session.go:125 +0x321

goroutine 1490172 [select, 16 minutes]:
github.com/ipfs/go-bitswap/sessionrequestsplitter.(*SessionRequestSplitter).run(0xc0daade180)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionrequestsplitter/sessionrequestsplitter.go:86 +0xf4
created by github.com/ipfs/go-bitswap/sessionrequestsplitter.New
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionrequestsplitter/sessionrequestsplitter.go:43 +0xa6

goroutine 1447500 [select, 18 minutes]:
github.com/ipfs/go-bitswap/sessionmanager.(*SessionManager).NewSession.func1(0xc152158370, 0xc0006c4b80, 0x1f715c0, 0xc0d386aa00, 0x1f74840, 0xc08f67f0e0, 0x1f68b80, 0xc0c8edfc20, 0x1f71200, 0xc0000420b0)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionmanager/sessionmanager.go:86 +0x103
created by github.com/ipfs/go-bitswap/sessionmanager.(*SessionManager).NewSession
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionmanager/sessionmanager.go:84 +0x339

goroutine 1837672 [select]:
github.com/ipfs/go-bitswap/sessionrequestsplitter.(*SessionRequestSplitter).run(0xc0db5aba40)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionrequestsplitter/sessionrequestsplitter.go:86 +0xf4
created by github.com/ipfs/go-bitswap/sessionrequestsplitter.New
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionrequestsplitter/sessionrequestsplitter.go:43 +0xa6

goroutine 1814363 [select, 2 minutes]:
github.com/ipfs/go-bitswap/sessionrequestsplitter.(*SessionRequestSplitter).run(0xc0cbe3d830)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionrequestsplitter/sessionrequestsplitter.go:86 +0xf4
created by github.com/ipfs/go-bitswap/sessionrequestsplitter.New
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionrequestsplitter/sessionrequestsplitter.go:43 +0xa6

goroutine 1828358 [select]:
github.com/libp2p/go-yamux.(*Session).sendLoop(0xc09c6cbd40, 0x0, 0x0)
        /root/local/gopath/pkg/mod/github.com/libp2p/go-yamux@v1.2.3/session.go:438 +0x1b4
github.com/libp2p/go-yamux.(*Session).send(0xc09c6cbd40)
        /root/local/gopath/pkg/mod/github.com/libp2p/go-yamux@v1.2.3/session.go:384 +0x2b
created by github.com/libp2p/go-yamux.newSession
        /root/local/gopath/pkg/mod/github.com/libp2p/go-yamux@v1.2.3/session.go:130 +0x39b

goroutine 1694593 [select]:
github.com/ipfs/go-bitswap/messagequeue.(*MessageQueue).runQueue(0xc0781722c0)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/messagequeue/messagequeue.go:104 +0x101
created by github.com/ipfs/go-bitswap/messagequeue.(*MessageQueue).Startup
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/messagequeue/messagequeue.go:94 +0x98

goroutine 1704282 [select]:
github.com/ipfs/go-bitswap/sessionpeermanager.(*SessionPeerManager).run(0xc0faceed20, 0x1f711c0, 0xc10126d500)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionpeermanager/sessionpeermanager.go:149 +0xfd
created by github.com/ipfs/go-bitswap/sessionpeermanager.New
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionpeermanager/sessionpeermanager.go:72 +0x20d

goroutine 1493334 [select, 16 minutes]:
github.com/ipfs/go-bitswap/sessionrequestsplitter.(*SessionRequestSplitter).run(0xc10e639dd0)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionrequestsplitter/sessionrequestsplitter.go:86 +0xf4
created by github.com/ipfs/go-bitswap/sessionrequestsplitter.New
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionrequestsplitter/sessionrequestsplitter.go:43 +0xa6

goroutine 1826253 [select, 1 minutes]:
github.com/ipfs/go-bitswap/sessionrequestsplitter.(*SessionRequestSplitter).run(0xc0ea1404b0)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionrequestsplitter/sessionrequestsplitter.go:86 +0xf4
created by github.com/ipfs/go-bitswap/sessionrequestsplitter.New
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionrequestsplitter/sessionrequestsplitter.go:43 +0xa6

goroutine 1743534 [select, 5 minutes]:
github.com/ipfs/go-graphsync/responsemanager/peerresponsemanager.(*peerResponseSender).run(0xc07c2ce140)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-graphsync@v0.0.4/responsemanager/peerresponsemanager/peerresponsesender.go:191 +0xce
created by github.com/ipfs/go-graphsync/responsemanager/peerresponsemanager.(*peerResponseSender).Startup
        /root/local/gopath/pkg/mod/github.com/ipfs/go-graphsync@v0.0.4/responsemanager/peerresponsemanager/peerresponsesender.go:82 +0x3f

goroutine 1647226 [select]:
github.com/ipfs/go-bitswap/session.(*Session).run(0xc115f9d100, 0x1f711c0, 0xc0da4bc7c0)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/session/session.go:207 +0x24c
created by github.com/ipfs/go-bitswap/session.New
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/session/session.go:125 +0x321

goroutine 1695185 [select, 7 minutes]:
github.com/libp2p/go-yamux.(*Stream).Read(0xc03d9d2e00, 0xc03e362000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /root/local/gopath/pkg/mod/github.com/libp2p/go-yamux@v1.2.3/stream.go:113 +0x1d8
github.com/libp2p/go-libp2p-swarm.(*Stream).Read(0xc07724f040, 0xc03e362000, 0x1000, 0x1000, 0x528a78, 0x7efbd4db5af0, 0xc03d6d35b0)
        /root/local/gopath/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm_stream.go:64 +0x61
github.com/multiformats/go-multistream.(*lazyClientConn).Read(0xc0637aaa80, 0xc03e362000, 0x1000, 0x1000, 0x8, 0xc1643c5680, 0x4f390b)
        /root/local/gopath/pkg/mod/github.com/multiformats/go-multistream@v0.1.1/lazyClient.go:75 +0xa8
github.com/libp2p/go-libp2p/p2p/host/basic.(*streamWrapper).Read(0xc098e3e5e0, 0xc03e362000, 0x1000, 0x1000, 0x7efb9c00ad70, 0x7efb9c00ad70, 0xc03d6d35e0)
        /root/local/gopath/pkg/mod/github.com/libp2p/go-libp2p@v0.4.2/p2p/host/basic/basic_host.go:765 +0x52
bufio.(*Reader).fill(0xc03b7c67e0)
        /usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).ReadByte(0xc03b7c67e0, 0xc1643c5680, 0x1000, 0x60)
        /usr/local/go/src/bufio/bufio.go:252 +0x39
encoding/binary.ReadUvarint(0x1f48c60, 0xc03b7c67e0, 0x1000, 0x1000, 0x7efbd42cd3a8)
        /usr/local/go/src/encoding/binary/varint.go:110 +0x7b
github.com/gogo/protobuf/io.(*varintReader).ReadMsg(0xc1643c5680, 0x1f695c0, 0xc0637aaaf0, 0x1f5ddc0, 0xc1643c5680)
        /root/local/gopath/pkg/mod/github.com/gogo/protobuf@v1.3.1/io/varint.go:110 +0x3e
github.com/libp2p/go-libp2p-pubsub.(*PubSub).handlePeerEOF(0xc0000e82c0, 0x1f711c0, 0xc0226b1900, 0x1f84760, 0xc098e3e5e0)
        /root/local/gopath/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.2.6/comm.go:91 +0x1d0
created by github.com/libp2p/go-libp2p-pubsub.(*PubSub).handleNewPeer
        /root/local/gopath/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.2.6/comm.go:80 +0x414

goroutine 1829968 [select, 1 minutes]:
github.com/ipfs/go-graphsync/responsemanager/peerresponsemanager.(*peerResponseSender).run(0xc0882c74a0)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-graphsync@v0.0.4/responsemanager/peerresponsemanager/peerresponsesender.go:191 +0xce
created by github.com/ipfs/go-graphsync/responsemanager/peerresponsemanager.(*peerResponseSender).Startup
        /root/local/gopath/pkg/mod/github.com/ipfs/go-graphsync@v0.0.4/responsemanager/peerresponsemanager/peerresponsesender.go:82 +0x3f

goroutine 1647227 [select, 8 minutes]:
github.com/ipfs/go-bitswap/sessionmanager.(*SessionManager).NewSession.func1(0xc0c7ddcbf0, 0xc0006c4b80, 0x1f715c0, 0xc115f9d100, 0x1f74840, 0xc1182b32c0, 0x1f68b80, 0xc0bea74c00, 0x1f71200, 0xc0000420b0)
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionmanager/sessionmanager.go:86 +0x103
created by github.com/ipfs/go-bitswap/sessionmanager.(*SessionManager).NewSession
        /root/local/gopath/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/sessionmanager/sessionmanager.go:84 +0x339

goroutine 1829130 [select, 1 minutes]:
github.com/libp2p/go-libp2p-pubsub.(*PubSub).handleSendingMessages(0xc0000e82c0, 0x1f711c0, 0xc0226b1900, 0x1f84760, 0xc0b1c21400, 0xc05899ec00)
        /root/local/gopath/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.2.6/comm.go:118 +0x283
created by github.com/libp2p/go-libp2p-pubsub.(*PubSub).handleNewPeer
        /root/local/gopath/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.2.6/comm.go:79 +0x3be
`
```
![捕获](https://user-images.githubusercontent.com/47769205/80361983-706e7780-88b4-11ea-8acc-6b91971143e9.PNG)

My go version is:
  go version *go1.14.2 linux/amd64* , 

Lotus version is:
*0.2.8+git1120298b+api0.1.7
lotus version 0.2.8+git1120298b*

OS: CentOS8 **ps: Ubuntu 16.04LTS will occur this problems too.**
 
pps: It make no sense cause  this problem is fixed in past version...but it still occur, i have no idea how to deal it.

**Comment by magik6k** [comment]
Can you upload full log to somewhere like https://gist.github.com/?

**Comment by Cyanglacier** [comment]
> Can you upload full log to somewhere like https://gist.github.com/?

It take too long to uploading(and my explore is crashed...), may caused by the huge file size, it is 84.9MB
Here is the crash log which i uploaded in Google Drive
[https://drive.google.com/file/d/1nTjGxJ9FD6H4OQ4xjY0rfYSXSOK1bwEJ/view?usp=sharing](https://drive.google.com/file/d/1nTjGxJ9FD6H4OQ4xjY0rfYSXSOK1bwEJ/view?usp=sharing)

**Comment by magik6k** [comment]
Please open a new issue if this still happpens
