### ISSUE TITLE
panic by nil in wdpost_run.go

### ISSUE THREAD

**Issue by IPFS-grandhelmsman** [filecoin-project/lotus#1905]
@magik6k 
```
interopnet
lotus version 0.4.0+git.c8d43e4b.dirty
```
panic by nil
```
2020-06-02T21:51:30.293Z    ^[[33mWARN^[[0m storageminer    Checked sectors {"checked": 189, "good": 0}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa15ec6]

goroutine 411108 [running]:
github.com/filecoin-project/go-bitfield.SubtractBitField(0xc001e129f0, 0x0, 0xc006d7fb90, 0xc001e129f0, 0x0)
    /root/go/pkg/mod/github.com/filecoin-project/go-bitfield@v0.0.2-0.20200518150651-562fdb554b6e/bitfield.go:498 +0xb6
github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost(0xc00084c200, 0x2a93ea0, 0xc006d7fb90, 0xc4e, 0xc4e, 0x0, 0xc4e, 0xcde, 0xc3a, 0xc3a, ...)
    /root/go/src/github.com/filecoin-project/lotus/storage/wdpost_run.go:429 +0x10c0
github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).doPost.func1(0xc007485420, 0x2a93de0, 0xc00a0478c0, 0xc00084c200, 0xc0077a2c00, 0xc009560c40)
    /root/go/src/github.com/filecoin-project/lotus/storage/wdpost_run.go:82 +0x171
created by github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).doPost
    /root/go/src/github.com/filecoin-project/lotus/storage/wdpost_run.go:76 +0xa0
```

actual refer to
https://github.com/filecoin-project/lotus/blob/06670f4caecc9b37fc4b1467e4447359f92852f0/storage/wdpost_run.go#L392

here has return the nil
https://github.com/filecoin-project/lotus/blob/06670f4caecc9b37fc4b1467e4447359f92852f0/storage/wdpost_run.go#L103

**Comment by magik6k** [comment]
Fixed in https://github.com/filecoin-project/lotus/pull/2171
