### ISSUE TITLE
Chain broke upon lack of diskspace

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#1958]
**Describe the problem**

Running on the *interopnet* (6.8) with miner `t01805`. Doing several sectors of 512MB because my 64GB RAM is not sufficient. Had a script running that pledged about 400 sectors (~200GB) on a disk with 400GB free diskspace (entire SSD is 500GB). After a while the `lotus-storage-miner sectors pledge` got `connection refused` errors. In the main daemon log I saw a lot of the following issues;

```
(...)
2020-06-09T19:13:08.281+0200	INFO	chain	scheduling incoming tipset sync: [bafy2bzacea4xsn7vxiaxs3veolz6ehqkhknwins5fnkue6s4vchqlbfj3drjk]
2020-06-09T19:13:08.281+0200	ERROR	chain	sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /home/z840/lotus/chain/sync.go:429
  - chain linked to block marked previously as bad ([bafy2bzacea4xsn7vxiaxs3veolz6ehqkhknwins5fnkue6s4vchqlbfj3drjk], bafy2bzaceabbxicipaapjfmlehqhtsbdcdazlgmurjehzrrhoqgckoakk3foa) (reason: linked to bafy2bzaceakmaz6cngs6uacxomtpxf7axoazub4wxtesuzz7u6llkrewdlnia):
    github.com/filecoin-project/lotus/chain.(*Syncer).collectHeaders
        /home/z840/lotus/chain/sync.go:993
2020-06-09T19:13:09.857+0200	INFO	pubsub	received message from router graylisted peer 12D3KooWMGTCYVBbxWGgrpkUSqstnwhZdP4MzuNF2AVtDMRZhCAG. Dropping RPC
2020-06-09T19:13:10.106+0200	INFO	pubsub	received message from router graylisted peer 12D3KooWSEeAc265SbtyyvSVbStAtaFMpycZBu3V3hffWmZpsLrb. Dropping RPC
2020-06-09T19:13:12.105+0200	INFO	pubsub	received message from router graylisted peer 12D3KooWSEeAc265SbtyyvSVbStAtaFMpycZBu3V3hffWmZpsLrb. Dropping RPC
2020-06-09T19:13:13.857+0200	INFO	pubsub	received message from router graylisted peer 12D3KooWMGTCYVBbxWGgrpkUSqstnwhZdP4MzuNF2AVtDMRZhCAG. Dropping RPC
(...)
```

The `lotus-storage-miner run` didn't run anymore. After running it again it showed something that I lost in the CLI history, but also a failure.

**Sectors list**

```
can't run now, will fill in after restart
```

**Sectors status**

```
Miner: t01805
Sector Size: 512 MiB
Byte Power:   87 GiB / 16.1 TiB (0.5283%)
Actual Power: 87 Gi / 16.1 Ti (0.5272%)
	Committed: 87 GiB
	Proving: 87 GiB
Expected block win rate: 91.1002/day (every 15m48s)

Miner Balance: 891.803301562153489603
	PreCommit:   0
	Locked:      891.696402954232779822
	Available:   0.106898607920709781
Worker Balance: 46.902311697105959948
Market (Escrow):  0.000000001065353216
Market (Locked):  0.000000000532676608

Sectors:
	Total: 275
	Proving: 174
	PreCommit1: 64
	PreCommit2: 20
	Committing: 5
	SealPreCommit1Failed: 12
```

**Lotus storage miner logs**
After restarting the storage miner I get the following output;
```
2020-06-09T19:13:16.053+0200	INFO	main	lotus repo: /home/z840/.lotus
2020-06-09T19:13:16.056+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0170db1f394b35d995252228ee359194b13199d259380541dc529fb0099096b0.vk is ok
2020-06-09T19:13:16.057+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-7d739b8cf60f1b0709eeebee7730e297683552e4b69cab6984ec0285663c5781.vk is ok
2020-06-09T19:13:16.057+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.vk is ok
2020-06-09T19:13:16.056+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-032d3138d22506ec0082ed72b2dcba18df18477904e35bafee82b3793b06832f.vk is ok
2020-06-09T19:13:16.058+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0cfb4f178bbb71cf2ecfcd42accce558b27199ab4fb59cb78f2483fe21ef36d9.vk is ok
2020-06-09T19:13:16.058+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-5294475db5237a2e83c3e52fd6c2b03859a1831d45ed08c4f35dbf9a803165a9.vk is ok
2020-06-09T19:13:16.055+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-ecd683648512ab1765faa2a5f14bab48f676e633467f0aa8aad4b55dcb0652bb.vk is ok
2020-06-09T19:13:16.056+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-6babf46ce344ae495d558e7770a585b2382d54f225af8ed0397b8be7c3fcd472.vk is ok
2020-06-09T19:13:16.056+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.vk is ok
2020-06-09T19:13:16.058+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-b62098629d07946e9028127e70295ed996fe3ed25b0f9f88eb610a0ab4385a3c.vk is ok
2020-06-09T19:13:16.059+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-2-sha256_hasher-96f1b4a04c5c51e4759bbf224bbc2ef5a42c7100f16ec0637123f16a845ddfb2.vk is ok
2020-06-09T19:13:16.059+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-3ea05428c9d11689f23529cde32fd30aabd50f7d2c93657c1d3650bca3e8ea9e.vk is ok
2020-06-09T19:13:16.059+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-50c7368dea9593ed0989e70974d28024efa9d156d585b7eea1be22b2e753f331.vk is ok
2020-06-09T19:13:16.072+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-2627e4006b67f99cef990c0a47d5426cb7ab0a0ad58fc1061547bf2d28b09def.vk is ok
2020-06-09T19:13:16.073+0200	INFO	build	Parameter file /var/tmp/filecoin-proof-parameters/v26-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c4509eedae8a27555733edc.vk is ok
2020-06-09T19:13:16.073+0200	INFO	build	parameter and key-fetching complete
2020-06-09T19:13:16.118+0200	INFO	badger	All 0 tables opened in 0s

2020-06-09T19:13:16.121+0200	INFO	badger	Replaying file id: 0 at offset: 0

2020-06-09T19:13:16.121+0200	INFO	badger	Replay took: 11.547µs

2020-06-09T19:13:16.123+0200	INFO	badger	All 0 tables opened in 0s

2020-06-09T19:13:16.125+0200	INFO	badger	Replaying file id: 0 at offset: 0

2020-06-09T19:13:16.125+0200	INFO	badger	Replay took: 6.979µs

2020-06-09T19:13:16.174+0200	INFO	badger	All 14 tables opened in 45ms

2020-06-09T19:13:16.177+0200	INFO	badger	Replaying file id: 0 at offset: 238846953

2020-06-09T19:13:16.515+0200	INFO	badger	Replay took: 338.106105ms

2020-06-09T19:13:16.515+0200	INFO	badger	Replaying file id: 1 at offset: 0

2020-06-09T19:13:16.515+0200	WARN	badger	Found an incomplete txn at timestamp 82046. Discarding it.

2020-06-09T19:13:16.517+0200	INFO	badger	Replay took: 1.944464ms

2020-06-09T19:13:16.517+0200	INFO	badger	Replaying file id: 2 at offset: 0

2020-06-09T19:13:16.518+0200	INFO	badger	Replay took: 1.540846ms

2020-06-09T19:13:16.519+0200	WARN	modules	loading chain state from disk: loading tipset: get block bafy2bzacecey275fqzhlnb3xesm2bldb2nf73g4hy2gjhgvbnl43abgpb5ggu: blockstore: block not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x15cca7a]

goroutine 1 [running]:
github.com/filecoin-project/lotus/chain/types.(*TipSet).ParentState(...)
	/home/z840/lotus/chain/types/tipset.go:208
github.com/filecoin-project/lotus/node/modules.NetworkName(0x7f460cc2b660, 0xc0000400a8, 0x2acca20, 0xc0004d4c18, 0xc000166140, 0x0, 0x0, 0x0, 0x0)
	/home/z840/lotus/node/modules/chain.go:148 +0x19a
reflect.Value.call(0x24af640, 0x28bb138, 0x13, 0x2712dbe, 0x4, 0xc0045abce0, 0x4, 0x4, 0x203001, 0x248ba80, ...)
	/usr/local/go/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x24af640, 0x28bb138, 0x13, 0xc0045abce0, 0x4, 0x4, 0x10, 0x10, 0xc0045aca00)
	/usr/local/go/src/reflect/value.go:321 +0xb4
(....)
```
The `lotus sync wait` kept showing `error` and block 0.

**Version**

branch `interopnet` 
`lotus version 0.4.0+git.96a5e579.dirty`

**Solution**
I ran `rm ~/.lotus -rf` and am re-syncing the entire chain again now.

**Comment by RobQuistNL** [comment]
Oops, that shouldv'e been `rm ~/.lotus/datastore -rf`... My keys are now gone :sunglasses: 

```
2020-06-09T19:40:11.019+0200	WARN	main	starting node:
    github.com/filecoin-project/lotus/node.New
        /home/z840/lotus/node/builder.go:493
  - could not build arguments for function "github.com/filecoin-project/lotus/node/modules".HandleDeals (/home/z840/lotus/node/modules/storageminer.go:176): failed to build storagemarket.StorageProvider: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12): failed to build *storedask.StoredAsk: function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:12) returned a non-nil error: failed to sign: signing using key 't3s77dxs6fh3l6bvcetoalak4lph4ohmvpj7ujhthckdbnijy72hj3viam4cuwgleaaknvhoku672nx3ye2wtq': key info not found
```

**Comment by RobQuistNL** [comment]
> Mmmm, we really should keep keys in a different directory.

Thats a good idea :) To be fair, in a real production environment I'd probably have them backed up ASAP as well as triple-checking what I'm deleting. Maybe its also nice to add some informative notices to users that tells them to back up their keys once they are generated?

**Comment by jennijuju** [comment]
keys are now in `keystore` folder.
and disk space full sync issue is duplicated in @2760
