### ISSUE TITLE
invalid memory address or nil pointer dereference when checkCommit

### ISSUE THREAD

**Issue by IPFS-grandhelmsman** [filecoin-project/lotus#2009]
@magik6k 
catch a panic when i restart my lotus-storage-miner on the version interop.6.8.1.

panic by the pci is nil:

https://github.com/filecoin-project/storage-fsm/blob/aa405b2176aa2cf0493a4e7dfa098bf74be37099/checks.go#L112 

and have a nil by here:
https://github.com/filecoin-project/lotus/blob/90665889681f01b746a8f95a00232a26aa113693/storage/adapter_storage_miner.go#L172

but the deep reason maybe it's time to reset interopnet \o/

log
```
2020-06-12T13:44:12.024Z        ^[[34mINFO^[[0m ffiwrapper      DEBUG:SealPreCommit2 prefer remote,{1970 139}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x106dc7a]

goroutine 1628 [running]:
github.com/filecoin-project/storage-fsm.(*Sealing).checkCommit(0xc005440480, 0x2c53640, 0xc000040070, 0xc006321290, 0xc, 0xc0, 0x1, 0xc0002f2040, 0x1, 0x1, ...)
        /root/go/pkg/mod/git.grandhelmsman.com/filecoin-project/storage-fsm@v0.0.0-20200606030417-d4e5e0a37601/checks.go:112 +0x21a
github.com/filecoin-project/storage-fsm.(*Sealing).handleCommitFailed(0xc005440480, 0x2c53640, 0xc000040070, 0xc000801590, 0xc006321290, 0xc, 0xc0, 0x1, 0xc0002f2040, 0x1, ...)
        /root/go/pkg/mod/git.grandhelmsman.com/filecoin-project/storage-fsm@v0.0.0-20200606030417-d4e5e0a37601/states_failed.go:162 +0x44b
github.com/filecoin-project/storage-fsm.(*Sealing).Plan.func1(0x2c53640, 0xc000040070, 0xc000801590, 0xc006321290, 0xc, 0xc0, 0x1, 0xc0002f2040, 0x1, 0x1, ...)
        /root/go/pkg/mod/git.grandhelmsman.com/filecoin-project/storage-fsm@v0.0.0-20200606030417-d4e5e0a37601/fsm.go:24 +0x81
reflect.Value.call(0x2569380, 0xc000577bf0, 0x13, 0x2844b8a, 0x4, 0xc00081bf70, 0x2, 0x2, 0x5330bf, 0x2653280, ...)
        /usr/local/go/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x2569380, 0xc000577bf0, 0x13, 0xc000301f70, 0x2, 0x2, 0x1, 0xc000301f40, 0x52e473)
        /usr/local/go/src/reflect/value.go:321 +0xb4
github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc000577a40, 0x2c53640, 0xc000040070, 0xc000801590, 0xc000577a50, 0xc0003dcea0)
        /root/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200226041606-2074af6d51d9/machine.go:91 +0x2bf
created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
        /root/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200226041606-2074af6d51d9/machine.go:89 +0x3a0
```

**Comment by IPFS-grandhelmsman** [comment]
refer to https://github.com/filecoin-project/lotus/issues/1998
