### ISSUE TITLE
Miner aborted with memory address exception. 

### ISSUE THREAD

**Issue by yangjian102621** [filecoin-project/lotus#2035]
The miner aborted with memory address exception after 2 days of normal running.
@whyrusleeping @magik6k 

```bash
2020-06-15T23:15:24.029+0800    ^[[34mINFO^[[0m sectors Sector precommitted: 49
2020-06-15T23:15:24.029+0800    ^[[34mINFO^[[0m sectors Sector precommitted: 50
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb69b64]

goroutine 1055 [running]:
github.com/filecoin-project/storage-fsm.(*Sealing).handlePreCommitWait(0xc005319080, 0x2aefd80, 0xc000044048, 0xc0003ea210, 0xc006460b80, 0xd, 0x31, 0x1, 0xc0059a3180, 0x13, ...)
        /golang/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200605082304-aa405b2176aa/states.go:187 +0x104
github.com/filecoin-project/storage-fsm.(*Sealing).Plan.func1(0x2aefd80, 0xc000044048, 0xc0003ea210, 0xc006460b80, 0xd, 0x31, 0x1, 0xc0059a3180, 0x13, 0x13, ...)
        /golang/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200605082304-aa405b2176aa/fsm.go:24 +0x81
reflect.Value.call(0x242fda0, 0xc0006fedd0, 0x13, 0x27033c0, 0x4, 0xc000557f70, 0x2, 0x2, 0x52717f, 0x25171e0, ...)
        /usr/local/go/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x242fda0, 0xc0006fedd0, 0x13, 0xc0052c6f70, 0x2, 0x2, 0xc005187320, 0xc0052c6ef8, 0x522015)
        /usr/local/go/src/reflect/value.go:321 +0xb4
github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc0006fed30, 0x2aefd80, 0xc000044048, 0xc0003ea210, 0xc0006fed40, 0xc00504fd40)
        /golang/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200226041606-2074af6d51d9/machine.go:91 +0x2bf
created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
        /golang/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200226041606-2074af6d51d9/machine.go:89 +0x3a0
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0xb69b64]

goroutine 1210 [running]:
github.com/filecoin-project/storage-fsm.(*Sealing).handlePreCommitWait(0xc005319080, 0x2aefd80, 0xc000044048, 0xc0001a1910, 0xc0063674a0, 0xd, 0x32, 0x1, 0xc005c0e280, 0x13, ...)
        /golang/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200605082304-aa405b2176aa/states.go:187 +0x104
github.com/filecoin-project/storage-fsm.(*Sealing).Plan.func1(0x2aefd80, 0xc000044048, 0xc0001a1910, 0xc0063674a0, 0xd, 0x32, 0x1, 0xc005c0e280, 0x13, 0x13, ...)
        /golang/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200605082304-aa405b2176aa/fsm.go:24 +0x81
reflect.Value.call(0x242fda0, 0xc005c04a60, 0x13, 0x27033c0, 0x4, 0xc00074af70, 0x2, 0x2, 0x52717f, 0x25171e0, ...)
        /usr/local/go/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x242fda0, 0xc005c04a60, 0x13, 0xc00529bf70, 0x2, 0x2, 0x0, 0x0, 0xc000392000)
        /usr/local/go/src/reflect/value.go:321 +0xb4
github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc005c049c0, 0x2aefd80, 0xc000044048, 0xc0001a1910, 0xc005c049d0, 0xc005c08de0)
        /golang/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200226041606-2074af6d51d9/machine.go:91 +0x2bf
created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
        /golang/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200226041606-2074af6d51d9/machine.go:89 +0x3a0
```

The maximum sector number is 43 on my machine.

```bash
root@miner1:/gamma/lotus-storage-miner/data/cache# ll
total 144
drwxr-xr-x 36 root root 4096 Jun 15 17:17 ./
drwxrwxrwx  9 root root 4096 Jun 16 09:41 ../
drwxr-xr-x  2 root root 4096 Jun 13 09:40 s-t02405-10/
drwxr-xr-x  2 root root 4096 Jun 13 08:51 s-t02405-11/
drwxr-xr-x  2 root root 4096 Jun 13 11:22 s-t02405-12/
drwxr-xr-x  2 root root 4096 Jun 13 08:41 s-t02405-13/
drwxr-xr-x  2 root root 4096 Jun 15 17:08 s-t02405-14/
drwxr-xr-x  2 root root 4096 Jun 14 07:12 s-t02405-15/
drwxr-xr-x  2 root root 4096 Jun 14 08:24 s-t02405-16/
drwxr-xr-x  2 root root 4096 Jun 14 21:46 s-t02405-17/
drwxr-xr-x  2 root root 4096 Jun 13 21:33 s-t02405-21/
drwxr-xr-x  2 root root 4096 Jun 13 21:25 s-t02405-22/
drwxr-xr-x  2 root root 4096 Jun 13 21:41 s-t02405-23/
drwxr-xr-x  2 root root 4096 Jun 14 14:20 s-t02405-24/
drwxr-xr-x  2 root root 4096 Jun 14 08:53 s-t02405-25/
drwxr-xr-x  2 root root 4096 Jun 14 15:42 s-t02405-26/
drwxr-xr-x  2 root root 4096 Jun 14 20:10 s-t02405-27/
drwxr-xr-x  2 root root 4096 Jun 14 20:22 s-t02405-28/
drwxr-xr-x  2 root root 4096 Jun 14 21:39 s-t02405-29/
drwxr-xr-x  2 root root 4096 Jun 15 05:39 s-t02405-30/
drwxr-xr-x  2 root root 4096 Jun 15 02:01 s-t02405-31/
drwxr-xr-x  2 root root 4096 Jun 15 01:51 s-t02405-32/
drwxr-xr-x  2 root root 4096 Jun 15 02:15 s-t02405-33/
drwxr-xr-x  2 root root 4096 Jun 15 02:58 s-t02405-34/
drwxr-xr-x  2 root root 4096 Jun 15 04:06 s-t02405-35/
drwxr-xr-x  2 root root 4096 Jun 15 06:50 s-t02405-36/
drwxr-xr-x  2 root root 4096 Jun 15 07:18 s-t02405-37/
drwxr-xr-x  2 root root 4096 Jun 15 16:05 s-t02405-38/
drwxr-xr-x  2 root root 4096 Jun 15 10:29 s-t02405-39/
drwxr-xr-x  2 root root 4096 Jun 15 12:03 s-t02405-40/
drwxr-xr-x  2 root root 4096 Jun 15 12:34 s-t02405-41/
drwxr-xr-x  2 root root 4096 Jun 15 17:18 s-t02405-43/
drwxr-xr-x  2 root root 4096 Jun 14 10:06 s-t02405-5/
drwxr-xr-x  2 root root 4096 Jun 14 10:06 s-t02405-6/
drwxr-xr-x  2 root root 4096 Jun 13 11:21 s-t02405-7/
drwxr-xr-x  2 root root 4096 Jun 13 09:47 s-t02405-8/
```
So, what is the sector 51 come from?

My miner machine config:

CPU: Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz
RAM: 512GB + 256GB Swap
Disk: 8TBx4 raid0

Miner configurage file
```
# Default config:
[API]
  ListenAddress = "/ip4/192.168.0.15/tcp/2345/http"
  RemoteListenAddress = "192.168.0.15:2345"
#  Timeout = "30s"
#
[Libp2p]
#  ListenAddresses = ["/ip4/0.0.0.0/tcp/0", "/ip6/::/tcp/0"]
#  ConnMgrLow = 150
#  ConnMgrHigh = 180
#  ConnMgrGrace = "20s"
#
[Pubsub]
#  Bootstrapper = false
#  RemoteTracer = "/ip4/147.75.67.199/tcp/4001/p2p/QmTd6UvR47vUidRNZ1ZKXHrAFhqTJAD27rKL9XYghEKgKX"
#
[Storage]
  AllowPreCommit1 = false
  AllowPreCommit2 = false
#  AllowCommit = true
#  AllowUnseal = false
```

AMD worker x 3 for P1

Intel worker x 5 for P2 (with 2080Ti for per worker)

Oh, my miner ID is t02405. Thanks.

**Comment by magik6k** [comment]
Fixed in master
