### ISSUE TITLE
debug advance-block fails beacon validation

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/lotus#2091]
```
2020-06-20T20:50:25.876Z        WARN    chain   chain/sync.go:561       insecure test validation is enabled, if you see this outside of a test, it is a severe bug!
panic: runtime error: index out of range [-1]goroutine 1275 [running]:
github.com/filecoin-project/lotus/chain/beacon.ValidateBlockValues(0x2b391c0, 0xc0005f8190, 0xc00082f930, 0x0, 0xc0000a6da0, 0x20, 0x20, 0x0, 0x0)
        /lotus/chain/beacon/beacon.go:35 +0x514
github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func7(0xc00085c7b8, 0xabeb0c)
        /lotus/chain/sync.go:706 +0xc1
github.com/Gurpartap/async.Err.func1(0xc004fc94a0, 0xc0051dca40, 0xc004fe3910)
        /go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:29 +0x53
created by github.com/Gurpartap/async.Err
        /go/pkg/mod/github.com/!gurpartap/async@v0.0.0-20180927173644-4f7f499dd9ee/error.go:27 +0x8a
```

**Comment by jennijuju** [comment]
oh no this seems scary  - confirm before close

**Comment by arajasek** [comment]
Since fixed, skimming the code i don't see a way for this to happen.
