### ISSUE TITLE
parent state root did not match computed stat when lotus syncing

### ISSUE THREAD

**Issue by waynewyang** [filecoin-project/lotus#2185]
**Describe the bug**
sync error  when syncing
```
sync status:
Error: chain linked to block marked previously as bad 
```

**To Reproduce**
not clear now, and  now my fault environment is gone, to continue to observe

**Expected behavior**
sync works well 

**Screenshots**
the point of 
[lotus-daemon.log](https://github.com/filecoin-project/lotus/files/4851372/lotus-daemon.log)
log:
```
2020-06-30T05:38:52.703Z	[33mWARN[0m	chain	chain/sync.go:693	Message[459]: from=t3wm5i5i466m5kp5pt7qbkm37q3qscumptbuy3cila6ms4sy6reqhglgmkh7qqkrox7yl4qoyx7edwy2cpu74q to=t039272 method=6 params=86031935b8d82a5826000155c21f209e8ba456f71f170d7d9ebc8105c311a7969ea5b89f7346e86215f04b4b64b13c1991a4801a00993e89
2020-06-30T05:38:52.703Z	[34mINFO[0m	chain	chain/sync.go:610	block validation	{"took": 14.261471398, "height": "38828"}
2020-06-30T05:38:52.703Z	[31mERROR[0m	chain	chain/sync.go:1261	failed to validate tipset: validating block bafy2bzacea5r4wyrwic5poa3x726qbqiayt2saduzhih3qdsh6z5aqxa2gnvm:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet
        /home/waynewyang/go/src/github.com/filecoin-project/lotus/chain/sync.go:530
  - parent state root did not match computed state (bafy2bzaceawi43ib6n6gn4jlelxokvcu3gekjbmf7qbz4spnkhmkuucw624is != bafy2bzacebfhqmn4c24ud6vylhjpjx7x5zslyidbvgmbix57u2m6rpe2xskvk):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock
        /home/waynewyang/go/src/github.com/filecoin-project/lotus/chain/sync.go:697
2020-06-30T05:38:52.703Z	[31mERROR[0m	chain	chain/sync_manager.go:389	sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /home/waynewyang/go/src/github.com/filecoin-project/lotus/chain/sync.go:484
  - collectChain syncMessages:
    github.com/filecoin-project/lotus/chain.(*Syncer).collectChain
        /home/waynewyang/go/src/github.com/filecoin-project/lotus/chain/sync.go:1405
  - message processing failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1
        /home/waynewyang/go/src/github.com/filecoin-project/lotus/chain/sync.go:1262
  - validating block bafy2bzacea5r4wyrwic5poa3x726qbqiayt2saduzhih3qdsh6z5aqxa2gnvm:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet
        /home/waynewyang/go/src/github.com/filecoin-project/lotus/chain/sync.go:530
  - parent state root did not match computed state (bafy2bzaceawi43ib6n6gn4jlelxokvcu3gekjbmf7qbz4spnkhmkuucw624is != bafy2bzacebfhqmn4c24ud6vylhjpjx7x5zslyidbvgmbix57u2m6rpe2xskvk):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock
        /home/waynewyang/go/src/github.com/filecoin-project/lotus/chain/sync.go:697

```

**Version (run `lotus --version`):**
```
lotus version
Daemon:  0.4.0+git.3f9bd91.dirty+api0.3.0
Local: lotus version 0.4.0+git.3f9bd91.dirty
```

**Additional context**
1  the right ParentStateRoot cid of block `bafy2bzacea5r4wyrwic5poa3x726qbqiayt2saduzhih3qdsh6z5aqxa2gnvm`  is `bafy2bzacebfhqmn4c24ud6vylhjpjx7x5zslyidbvgmbix57u2m6rpe2xskvk`, and the block is valid.but the result when syncing is not match it.
```
block cid: bafy2bzacea5r4wyrwic5poa3x726qbqiayt2saduzhih3qdsh6z5aqxa2gnvm
  "Height": 38828,
  "ParentStateRoot": {
    "/": "bafy2bzacebfhqmn4c24ud6vylhjpjx7x5zslyidbvgmbix57u2m6rpe2xskvk"
  },
```
```
parent state root did not match computed state (bafy2bzaceawi43ib6n6gn4jlelxokvcu3gekjbmf7qbz4spnkhmkuucw624is != bafy2bzacebfhqmn4c24ud6vylhjpjx7x5zslyidbvgmbix57u2m6rpe2xskvk):
```

2 the count of messages in baseTs when syncing (used to compute stateroot) is 459, it seems not match with the chain.
```
2020-06-30T05:38:52.703Z	[33mWARN[0m	chain	chain/sync.go:693	Message[459]: from=t3wm5i5i466m5kp5pt7qbkm37q3qscumptbuy3cila6ms4sy6reqhglgmkh7qqkrox7yl4qoyx7edwy2cpu74q to=t039272 method=6 params=86031935b8d82a5826000155c21f209e8ba456f71f170d7d9ebc8105c311a7969ea5b89f7346e86215f04b4b64b13c1991a4801a00993e89
```
![image](https://user-images.githubusercontent.com/25957795/86118971-3adc4980-bb04-11ea-83a0-870d1d49941c.png)

```
	if stateroot != h.ParentStateRoot {
		msgs, err := syncer.store.MessagesForTipset(baseTs)
		if err != nil {
			log.Error("failed to load messages for tipset during tipset state mismatch error: ", err)
		} else {
			log.Warn("Messages for tipset with mismatching state:")
			for i, m := range msgs {
				mm := m.VMMessage()
				log.Warnf("Message[%d]: from=%s to=%s method=%d params=%x", i, mm.From, mm.To, mm.Method, mm.Params)
			}
		}

		return xerrors.Errorf("parent state root did not match computed state (%s != %s)", stateroot, h.ParentStateRoot)
	}

```
3 refer to
#2104 #2147

**Comment by waynewyang** [comment]
@whyrusleeping @magik6k 
I met this issue again
```
2020-07-02T13:16:42.433Z        INFO    chain   chain/sync.go:610       block validation        {"took": 0.009419732, "height": "46840"}
2020-07-02T13:16:42.433Z        ERROR   chain   chain/sync.go:1261      failed to validate tipset: validating block bafy2bzacebzrltnemserxt7tyfkx4hijlxg32v3max22chki2p54lr7slykfs:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet
        /home/hans/go/src/github.com/filecoin-project/lotus/chain/sync.go:530
  - parent state root did not match computed state (bafy2bzacea7ivks5kx5uyxwyxcsjcsjnjudxurtfvfojh2mrmlbnyezkpaagc != bafy2bzaceaentqfnyfvf3o5bjmetstag2o2rgvtkp6kjyatmwyiupnagygpco):
```

```
lotus chain list --height 46840 --count 5
46836: (Jul  2 13:15:00) [ bafy2bzacebvk6a3s24omqg3axqbfqzwnd5izchpzvx5ctfzuixasqbzoq2osa: t01009,bafy2bzacebspjxzdxniyl6lt2vhxtyuan7ywibkx5ouvursvyemkz5gjhidyi: t02020, ]
46837: (Jul  2 13:15:25) [ bafy2bzacecjwzpaancwk64ls2l7crnjgft6aocq7qfvplq2f4hmxrl64wi32o: t02020,bafy2bzacea4dp25rqjabum54widif3oiwj5we4wrz7atygtcyrojdwk2xrk7g: t01009, ]
46838: (Jul  2 13:15:50) [ bafy2bzaceatxsknrhb5nchlsoblvylriizdqqqgrbidlcbejwwnlqtwxvu3kw: t01009,bafy2bzacebegvpi34is5vzas6c2jfuafafez65gris7mxj5kjmzjddv6uxfca: t02020, ]
46839: (Jul  2 13:16:15) [ bafy2bzacecr5zag6smoeholkpgfv6xbnwheacvse4y2q7uvvp42yfgrpg7dj6: t01009, ]
46840: (Jul  2 13:16:40) [ bafy2bzaceciplokdmrzvc4eef7s3o2hq7wbzpm2pvwxgjfyeab3iw2puihqjm: t02020, ]
```

and I trying to compute the state in #46839, the result is abnormal.
```
root@hos:~# lotus state --tipset @46839 compute-state
computed state cid:  bafy2bzaceayhg244fgu7qgqhvwxt7znotn5g3trjcositbhdtnvlatth7uelc
root@hos:~# lotus state --tipset @46839 compute-state
computed state cid:  bafy2bzacecxtr754rgp266gpsyc3ymqj5ijm4ma6s3rpb3ogpd7ba47cys4dc
root@hos:~# lotus state --tipset @46839 compute-state
computed state cid:  bafy2bzacecjgle3c37zziqqiwyskhpz377eu4ut3lpt2qw2mzmqka2cqs7wgo
```

**Comment by arajasek** [comment]
This was due to nondeterminism in specs-actors code...since fixed!

**Comment by waynewyang** [comment]
![image](https://user-images.githubusercontent.com/25957795/90238441-92d2d380-de58-11ea-9b99-c8b192a95b21.png)

**Comment by arajasek** [comment]
@waynewyang Can you please post those logs (or similar logs) as plaintext, and also share your `lotus version`?

**Comment by waynewyang** [comment]
> @waynewyang Can you please post those logs (or similar logs) as plaintext, and also share your `lotus version`?

No problem, I'll share it later.

**Comment by waynewyang** [comment]
Hi @arajasek 
```
Aug 16 10:15:29 hos lotus[43205]: 2020-08-16T10:15:29.187Z        INFO        chain        chain/sync.go:731        block validation        {"took": 0.038448088, "height": "7877"}
Aug 16 10:15:29 hos lotus[43205]: 2020-08-16T10:15:29.187Z        ERROR        chain        chain/sync.go:1481        failed to validate tipset: validating block bafy2bzacea5stydgrikwgssxmfvhvgqzdufwynfmx4bmqzb7lhpe2nf6473zk:
Aug 16 10:15:29 hos lotus[43205]:     github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet.func1
Aug 16 10:15:29 hos lotus[43205]:         /home/hans/go/src/github.com/filecoin-project/lotus/chain/sync.go:646
Aug 16 10:15:29 hos lotus[43205]:   - parent state root did not match computed state (bafy2bzacebsk4zsbqdjrdadgqjdwmyrizr7fnmdk5ggvn5fvnyvnd2lkl6w6q != bafy2bzacecanyngj3yspg2cp5qwrtnbrerbxvwggxlinimutksx26hs3bzxdu):
Aug 16 10:15:29 hos lotus[43205]:     github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock
Aug 16 10:15:29 hos lotus[43205]:         /home/hans/go/src/github.com/filecoin-project/lotus/chain/sync.go:830
Aug 16 10:15:29 hos lotus[43205]: 2020-08-16T10:15:29.187Z        ERROR        chain        chain/sync_manager.go:389        sync error: collectChain failed:
Aug 16 10:15:29 hos lotus[43205]:     github.com/filecoin-project/lotus/chain.(*Syncer).Sync
Aug 16 10:15:29 hos lotus[43205]:         /home/hans/go/src/github.com/filecoin-project/lotus/chain/sync.go:596
Aug 16 10:15:29 hos lotus[43205]:   - collectChain syncMessages:
Aug 16 10:15:29 hos lotus[43205]:     github.com/filecoin-project/lotus/chain.(*Syncer).collectChain
Aug 16 10:15:29 hos lotus[43205]:         /home/hans/go/src/github.com/filecoin-project/lotus/chain/sync.go:1643
Aug 16 10:15:29 hos lotus[43205]:   - message processing failed:
Aug 16 10:15:29 hos lotus[43205]:     github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1
Aug 16 10:15:29 hos lotus[43205]:         /home/hans/go/src/github.com/filecoin-project/lotus/chain/sync.go:1482
Aug 16 10:15:29 hos lotus[43205]:   - validating block bafy2bzacea5stydgrikwgssxmfvhvgqzdufwynfmx4bmqzb7lhpe2nf6473zk:
Aug 16 10:15:29 hos lotus[43205]:     github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet.func1
Aug 16 10:15:29 hos lotus[43205]:         /home/hans/go/src/github.com/filecoin-project/lotus/chain/sync.go:646
Aug 16 10:15:29 hos lotus[43205]:   - parent state root did not match computed state (bafy2bzacebsk4zsbqdjrdadgqjdwmyrizr7fnmdk5ggvn5fvnyvnd2lkl6w6q != bafy2bzacecanyngj3yspg2cp5qwrtnbrerbxvwggxlinimutksx26hs3bzxdu):
Aug 16 10:15:29 hos lotus[43205]:     github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock
Aug 16 10:15:29 hos lotus[43205]:         /home/hans/go/src/github.com/filecoin-project/lotus/chain/sync.go:830
Aug 16 10:15:29 hos lotus[43205]: 2020-08-16T10:15:29.329Z        INFO        pubsub        go-libp2p-pubsub@v0.3.4/pubsub.go:927        received message from router graylisted peer 12D3KooWECLnWahWf3fqLmiiUVonNkUraKyu6j2sXKJ3vMk9tFAK. Dropping RPC
Aug 16 10:15:29 hos lotus[43205]: 2020-08-16T10:15:29.586Z        INFO        pubsub        go-libp2p-pubsub@v0.3.4/pubsub.go:927        received message from router graylisted peer 12D3KooWECLnWahWf3fqLmiiUVonNkUraKyu6j2sXKJ3vMk9tFAK. Dropping RPC
```
```
lotus version
Daemon:  0.4.5+git.d7c9c2b.dirty+api0.11.0
Local: lotus version 0.4.5+git.d7c9c2b.dirty
```

**Comment by waynewyang** [comment]
and there are these log befor the parent state root issue.

```
Aug 16 09:53:34 hos lotus[46076]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /home/sky/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rs:427:80
Aug 16 09:53:34 hos lotus[46076]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aug 16 09:53:34 hos lotus[46076]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /home/sky/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rs:427:thread '80<unnamed>
Aug 16 09:53:34 hos lotus[46076]: ' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /home/sky/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rsthread ':<unnamed>427thread '' panicked at ':thread 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }80<unnamed>',
Aug 16 09:53:34 hos lotus[46076]: <unnamed>' panicked at 'thread '/home/sky/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rscalled `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }' panicked at ':<unnamed>thread '', 427called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }thread '' panicked at ':<unnamed>/home/sky/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rs', 80<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }:
```

**Comment by arajasek** [comment]
@waynewyang Still looking into this (no repro myself unfortunately, though others have run into similar problems). Can you please share your hardware specs (mostly interested in your CPU)?

**Comment by waynewyang** [comment]
Hi @arajasek I have found the root cause, which is related to  our OS, thank you very much.

**Comment by icodeface** [comment]
> Hi @arajasek I have found the root cause, which is related to our OS, thank you very much.

Hi @waynewyang , i met the same issue, what did u do for your OS, could u share your solutions ?

**Comment by DomrachevIvan** [comment]
I have got the same problem and I can reproduce it every time I run lotus.

starts with 
```
thread '<unnamed>thread '' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }<unnamed>', ' panicked at '/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rsthread ':<unnamed>427thread ':called `Result::unwrap()` on an `Err` value: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }<unnamed>thread '', <unnamed>' panicked at 'thread '/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rs<unnamed>called `Result::unwrap()` on an `Err` value: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }', ', /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rs/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rsthread ':<unnamed>427' panicked at ':13
thread '<unnamed>' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }', called `Result::unwrap()` on an `Err` value: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }thread '', <unnamed>/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rsthread ':427:<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }called `Result::unwrap()` on an `Err` value: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }' panicked at '', ', called `Result::unwrap()` on an `Err` value: Os { code: 35, kind: WouldBlock, message: "Resource temporarily unavailable" }/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rs/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rs', :427:13/home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rs
:427:427::1313
13
```
and after it:
```
2020-10-25T14:31:42.878+0300	ERROR	chain	chain/sync.go:1502	failed to validate tipset: validating block bafy2bzacecndmi57sdtsubgwcsx6bjojk2fqcvdc4fkwdjkuvyjdttpvosvma:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet.func1
        /home/user/tmp/lotussrc/lotus/chain/sync.go:630
  - 1 error occurred:
	* invalid election post:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func11
        /home/user/tmp/lotussrc/lotus/chain/sync.go:932
  - winning post was invalid:
    github.com/filecoin-project/lotus/chain.(*Syncer).VerifyWinningPoStProof
        /home/user/tmp/lotussrc/lotus/chain/sync.go:1032


2020-10-25T14:31:42.878+0300	ERROR	chain	chain/sync_manager.go:454	sync error: collectChain failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).Sync
        /home/user/tmp/lotussrc/lotus/chain/sync.go:580
  - collectChain syncMessages:
    github.com/filecoin-project/lotus/chain.(*Syncer).collectChain
        /home/user/tmp/lotussrc/lotus/chain/sync.go:1727
  - message processing failed:
    github.com/filecoin-project/lotus/chain.(*Syncer).syncMessagesAndCheckState.func1
        /home/user/tmp/lotussrc/lotus/chain/sync.go:1503
  - validating block bafy2bzacecndmi57sdtsubgwcsx6bjojk2fqcvdc4fkwdjkuvyjdttpvosvma:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateTipSet.func1
        /home/user/tmp/lotussrc/lotus/chain/sync.go:630
  - 1 error occurred:
	* invalid election post:
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func11
        /home/user/tmp/lotussrc/lotus/chain/sync.go:932
  - winning post was invalid:
    github.com/filecoin-project/lotus/chain.(*Syncer).VerifyWinningPoStProof
        /home/user/tmp/lotussrc/lotus/chain/sync.go:1032
```

also i have got another hardware where this bug i can't reproduce.
lotus binary, OS, environment is the same. both lotus started from the same snapshot file.
hardware is different:
good one:
```
FreeBSD 11.3-RELEASE-p3 #0: Mon Aug 19 21:08:43 UTC 2019
    root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC amd64
FreeBSD clang version 8.0.0 (tags/RELEASE_800/final 356365) (based on LLVM 8.0.0)
VT(vga): resolution 640x480
CPU: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (3599.84-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0x906ed  Family=0x6  Model=0x9e  Stepping=13
  Features=0xf83fbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,MMX,FXSR,SSE,SSE2,SS>
  Features2=0xfffa3203<SSE3,PCLMULQDQ,SSSE3,FMA,CX16,PCID,SSE4.1,SSE4.2,x2APIC,MOVBE,POPCNT,TSCDLT,AESNI,XSAVE,OSXSAVE,AVX,F16C,RDRAND,HV>
  AMD Features=0x2c100800<SYSCALL,NX,Page1GB,RDTSCP,LM>
  AMD Features2=0x121<LAHF,ABM,Prefetch>
  Structured Extended Features=0x1c67ab<FSGSBASE,TSCADJ,BMI1,AVX2,SMEP,BMI2,ERMS,INVPCID,NFPUSG,MPX,RDSEED,ADX,SMAP>
  Structured Extended Features3=0xbc000400<MD_CLEAR,IBPB,STIBP,L1DFL,ARCH_CAP,SSBD>
  XSAVE Features=0xb<XSAVEOPT,XSAVEC,XSAVES>
  IA32_ARCH_CAPS=0x2b<RDCL_NO,IBRS_ALL,SKIP_L1DFL_VME>
  TSC: P-state invariant
```
bad one:
```
FreeBSD 11.3-RELEASE-p3 #0: Mon Aug 19 21:08:43 UTC 2019
    root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC amd64
FreeBSD clang version 8.0.0 (tags/RELEASE_800/final 356365) (based on LLVM 8.0.0)
VT(vga): resolution 640x480
CPU: Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz (2200.06-MHz K8-class CPU)
  Origin="GenuineIntel"  Id=0x50657  Family=0x6  Model=0x55  Stepping=7
  Features=0xbfebfbff<FPU,VME,DE,PSE,TSC,MSR,PAE,MCE,CX8,APIC,SEP,MTRR,PGE,MCA,CMOV,PAT,PSE36,CLFLUSH,DTS,ACPI,MMX,FXSR,SSE,SSE2,SS,HTT,TM,PBE>
  Features2=0x7ffefbff<SSE3,PCLMULQDQ,DTES64,MON,DS_CPL,VMX,SMX,EST,TM2,SSSE3,SDBG,FMA,CX16,xTPR,PDCM,PCID,DCA,SSE4.1,SSE4.2,x2APIC,MOVBE,POPCNT,TSCDLT,AESNI,XSAVE,OSXSAVE,AVX,F16C,RDRAND>
  AMD Features=0x2c100800<SYSCALL,NX,Page1GB,RDTSCP,LM>
  AMD Features2=0x121<LAHF,ABM,Prefetch>
  Structured Extended Features=0xd39ffffb<FSGSBASE,TSCADJ,BMI1,HLE,AVX2,FDPEXC,SMEP,BMI2,ERMS,INVPCID,RTM,PQM,NFPUSG,MPX,PQE,AVX512F,AVX512DQ,RDSEED,ADX,SMAP,CLFLUSHOPT,CLWB,PROCTRACE,AVX512CD,AVX512BW,AVX512VL>
  Structured Extended Features2=0x808<PKU>
  Structured Extended Features3=0xbc000400<MD_CLEAR,IBPB,STIBP,L1DFL,ARCH_CAP,SSBD>
  XSAVE Features=0xf<XSAVEOPT,XSAVEC,XINUSE,XSAVES>
  IA32_ARCH_CAPS=0xab<RDCL_NO,IBRS_ALL,SKIP_L1DFL_VME>
  VT-x: PAT,HLT,MTF,PAUSE,EPT,UG,VPID,VID,PostIntr
  TSC: P-state invariant, performance statistics
```

version:
```
Daemon:  1.1.0+git.194f5637+api0.17.0
Local: lotus version 1.1.0+git.194f5637

```

logs from both:
[logs.bad.txt](https://github.com/filecoin-project/lotus/files/5434634/logs.bad.txt)
[logs.ok.txt](https://github.com/filecoin-project/lotus/files/5434635/logs.ok.txt)

I tried many things: BLST_PORTABLE, target-cpu=cascadelake, GODEBUG=cpu.all=off, -mno-aes -mno-vaes but it didn't help.

**Comment by clemsos** [comment]
```
[filecoin-lotus ~] ⨎ lotus sync status
sync status:
worker 8202:
	Base:	[bafy2bzacebmgnjngunevpdldnf3dvay7xhexqkzwcq4t5vafhdduwytxp7j2m bafy2bzaceacx23lh5saob5loyzemwsyr6esqszrtpgzasekhvgp2le75tduvq bafy2bzacebdccwmpex7jock3bddczfdi5q5udkqwn3cx6ips7l7a6zrdnrzdi]
	Target:	[bafy2bzacecqfy4wpifdt6iq4phbtrtm6bjkzbjrcoxri7dqdx4ueqhh4v36fc] (692511)
	Height diff:	2409
	Stage: error
	Height: 0
	Elapsed: 96.456µs
	Error: chain linked to block marked previously as bad ([bafy2bzacecqfy4wpifdt6iq4phbtrtm6bjkzbjrcoxri7dqdx4ueqhh4v36fc], bafy2bzaceabt4gpivpluciye7b2kzal7xgrx7a22ykih4sn2r6tfesb7ourgy) (reason: linked to bafy2bzacecbi22mbmyvoyd5rc3wf5grghcaw3li5q4ee3ogco34lp7qpode3a caused by: [bafy2bzacecscyy4litbsvxoi2akyc7upiavozjwk4k24x4qo3gfjlrd3zyxh6] 1 error occurred:
	* parent state root did not match computed state (bafy2bzaceb7nncqoapxouvee7qcxakaw3gr2wti53t5zmwgfm7lexsygeektm != bafy2bzaceajb4ad5p2ztgpu5xjqdr6jzgjcymz6qxw273jornug4mtnq2s5qc):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /home/circleci/project/chain/sync.go:806

)
worker 8203:
	Base:	[bafy2bzacebmgnjngunevpdldnf3dvay7xhexqkzwcq4t5vafhdduwytxp7j2m bafy2bzaceacx23lh5saob5loyzemwsyr6esqszrtpgzasekhvgp2le75tduvq bafy2bzacebdccwmpex7jock3bddczfdi5q5udkqwn3cx6ips7l7a6zrdnrzdi]
	Target:	[bafy2bzacedrzzutmw6jqw627aautiqwh5kdd4kbx6on3ie6jq5roxdl334zke] (692511)
	Height diff:	2409
	Stage: error
	Height: 0
	Elapsed: 103.592µs
	Error: chain linked to block marked previously as bad ([bafy2bzacedrzzutmw6jqw627aautiqwh5kdd4kbx6on3ie6jq5roxdl334zke], bafy2bzaceabt4gpivpluciye7b2kzal7xgrx7a22ykih4sn2r6tfesb7ourgy) (reason: linked to bafy2bzacecbi22mbmyvoyd5rc3wf5grghcaw3li5q4ee3ogco34lp7qpode3a caused by: [bafy2bzacecscyy4litbsvxoi2akyc7upiavozjwk4k24x4qo3gfjlrd3zyxh6] 1 error occurred:
	* parent state root did not match computed state (bafy2bzaceb7nncqoapxouvee7qcxakaw3gr2wti53t5zmwgfm7lexsygeektm != bafy2bzaceajb4ad5p2ztgpu5xjqdr6jzgjcymz6qxw273jornug4mtnq2s5qc):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /home/circleci/project/chain/sync.go:806

)
worker 8204:
	Base:	[bafy2bzacebmgnjngunevpdldnf3dvay7xhexqkzwcq4t5vafhdduwytxp7j2m bafy2bzaceacx23lh5saob5loyzemwsyr6esqszrtpgzasekhvgp2le75tduvq bafy2bzacebdccwmpex7jock3bddczfdi5q5udkqwn3cx6ips7l7a6zrdnrzdi]
	Target:	[bafy2bzacea33ptdtuypfpu7ef4tnd466tqruvoztdot2j4hzar4xze4y2lhdc] (692511)
	Height diff:	2409
	Stage: error
	Height: 0
	Elapsed: 96.723µs
	Error: chain linked to block marked previously as bad ([bafy2bzacea33ptdtuypfpu7ef4tnd466tqruvoztdot2j4hzar4xze4y2lhdc], bafy2bzaceabt4gpivpluciye7b2kzal7xgrx7a22ykih4sn2r6tfesb7ourgy) (reason: linked to bafy2bzacecbi22mbmyvoyd5rc3wf5grghcaw3li5q4ee3ogco34lp7qpode3a caused by: [bafy2bzacecscyy4litbsvxoi2akyc7upiavozjwk4k24x4qo3gfjlrd3zyxh6] 1 error occurred:
	* parent state root did not match computed state (bafy2bzaceb7nncqoapxouvee7qcxakaw3gr2wti53t5zmwgfm7lexsygeektm != bafy2bzaceajb4ad5p2ztgpu5xjqdr6jzgjcymz6qxw273jornug4mtnq2s5qc):
    github.com/filecoin-project/lotus/chain.(*Syncer).ValidateBlock.func6
        /home/circleci/project/chain/sync.go:806

)
```

getting that bug too on Digital Ocean fresh install

**Comment by RobHeijligersHolland** [comment]
I had the same issue. 
I solved it by commenting this environment variable: 
FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1 # precommit2 GPU acceleration
Not sure how this will impact my GPU mining rate.

lotus version 1.10.1+mainnet+git.d920b47e7
CPU: AMD Ryzen 7 5800X
GPU: Inno3D GeForce RTX 2080 X2 OC

Any tips or better solutions are welcome.

**Comment by happyhq** [comment]
> reopened

Guck luck for you!
