### ISSUE TITLE
Performing sector replication crashes

### ISSUE THREAD

**Issue by flyworker** [filecoin-project/lotus#2287]
**Describe the bug**
Performing sector replication crashes while starting the miner

**To Reproduce**
1. Run 'lotus-storage-miner run'
2. lotus-storage-miner sectors pledge  15 sectors on p1 worker
3. See error after several hours
2020-07-07T04:33:21.659Z	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/fsm.go:240	Proving sector 6
2020-07-07T04:33:21.659Z	ERROR	evtsm	go-statemachine@v0.0.0-20200612181802-4eb3d0c68eba/machine.go:83	Executing event planner failed: planner for state FailedUnrecoverable not found:
    github.com/filecoin-project/storage-fsm.(*Sealing).plan
        /home/peware/go/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200625160832-379a4655b044/fsm.go:149
2020-07-07T04:33:21.659Z	ERROR	evtsm	go-statemachine@v0.0.0-20200612181802-4eb3d0c68eba/machine.go:83	Executing event planner failed: planner for state FailedUnrecoverable not found:
    github.com/filecoin-project/storage-fsm.(*Sealing).plan
        /home/peware/go/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200625160832-379a4655b044/fsm.go:149
2020-07-07T04:33:21.659Z	ERROR	evtsm	go-statemachine@v0.0.0-20200612181802-4eb3d0c68eba/machine.go:83	Executing event planner failed: planner for state FailedUnrecoverable not found:
    github.com/filecoin-project/storage-fsm.(*Sealing).plan
        /home/peware/go/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200625160832-379a4655b044/fsm.go:149
2020-07-07T04:33:21.664Z	INFO	main	lotus-storage-miner/run.go:137	Remote version 0.4.1+git.5de7b62d+api0.5.0
2020-07-07T04:33:21.679Z	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/states_failed.go:19	SealPreCommit1Failed(38), waiting 59.320075596s before retrying
2020-07-07T04:33:21.679Z	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/states_failed.go:19	SealPreCommit1Failed(31), waiting 59.320079724s before retrying
2020-07-07T04:33:21.679Z	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/states_failed.go:19	SealPreCommit1Failed(39), waiting 59.320060457s before retrying
2020-07-07T04:33:21.679Z	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/states_failed.go:19	SealPreCommit1Failed(37), waiting 59.320054326s before retrying
2020-07-07T04:33:21.689Z	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/states_sealing.go:96	performing sector replication...	{"sector": "40"}
2020-07-07T04:33:21.689Z	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/states_sealing.go:96	performing sector replication...	{"sector": "45"}
2020-07-07T04:33:21.689Z	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/states_sealing.go:96	performing sector replication...	{"sector": "46"}
2020-07-07T04:33:21.690Z	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/states_sealing.go:96	performing sector replication...	{"sector": "51"}
2020-07-07T04:33:21.690Z	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/states_sealing.go:96	performing sector replication...	{"sector": "50"}
2020-07-07T04:33:21.690Z	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/states_sealing.go:96	performing sector replication...	{"sector": "47"}
2020-07-07T04:33:21.690Z	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/states_sealing.go:96	performing sector replication...	{"sector": "43"}
2020-07-07T04:33:21.690Z	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/states_sealing.go:96	performing sector replication...	{"sector": "42"}
2020-07-07T04:33:21.691Z	INFO	sectors	storage-fsm@v0.0.0-20200625160832-379a4655b044/states_sealing.go:96	performing sector replication...	{"sector": "44"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x105a58d]

goroutine 896 [running]:
github.com/filecoin-project/storage-fsm.checkPrecommit(0x2bdf580, 0xc0000440d8, 0xc000411e4c, 0x4, 0xc00576b820, 0xf, 0x29, 0x3, 0xc0003f6c00, 0x1, ...)
	/home/peware/go/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200625160832-379a4655b044/checks.go:80 +0x1ed
github.com/filecoin-project/storage-fsm.(*Sealing).handlePreCommitFailed(0xc00079bc00, 0x2bdf580, 0xc0000440d8, 0xc004f95fe0, 0xc00576b820, 0xf, 0x29, 0x3, 0xc0003f6c00, 0x1, ...)
	/home/peware/go/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200625160832-379a4655b044/states_failed.go:73 +0x1dd
github.com/filecoin-project/storage-fsm.(*Sealing).Plan.func1(0x2bdf580, 0xc0000440d8, 0xc004f95fe0, 0xc00576b820, 0xf, 0x29, 0x3, 0xc0003f6c00, 0x1, 0x1, ...)
	/home/peware/go/pkg/mod/github.com/filecoin-project/storage-fsm@v0.0.0-20200625160832-379a4655b044/fsm.go:24 +0x81
reflect.Value.call(0x2536ba0, 0xc0002caed0, 0x13, 0x27fd574, 0x4, 0xc00062bf70, 0x2, 0x2, 0x53dfbf, 0x261d680, ...)
	/usr/lib/go-1.14/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x2536ba0, 0xc0002caed0, 0x13, 0xc000077770, 0x2, 0x2, 0xc0000776e0, 0x5b7424, 0xc00599fd08)
	/usr/lib/go-1.14/src/reflect/value.go:321 +0xb4
github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc0002cae30, 0x2bdf580, 0xc0000440d8, 0xc004f95fe0, 0xc0002cae40, 0xc00081ed80)
	/home/peware/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200612181802-4eb3d0c68eba/machine.go:102 +0x2bf
created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
	/home/peware/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200612181802-4eb3d0c68eba/machine.go:100 +0x3da

**Version (run `lotus version`):**
lotus version
Daemon:  0.4.1+git.5de7b62d+api0.5.0
Local: lotus version 0.4.1+git.5de7b62d

I want to do a work around to save my miner by delete those sectors,but I don't know how.

**Comment by magik6k** [comment]
This is fixed
