### ISSUE TITLE
Run 'sudo -E lotus-storage-miner run' return "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by github-0paul** [filecoin-project/lotus#2316]
**Describe the bug**
Run 'sudo -E lotus-storage-miner run' return "panic: runtime error: invalid memory address or nil pointer dereference"

**To Reproduce**
1. Run 'sudo -E lotus-storage-miner run'
2. See error
2020-07-08T09:13:52.355Z	WARN	dht/RtRefreshManager	rtrefresh/rt_refresh_manager.go:191	failed when refreshing routing table	{"error": "2 errors occurred:\n\t* failed to query for self, err=failed to run refresh DHT query for key=\u0000$\u0008\u0001\u0012 !=\ufffd-\ufffd^\u000f¬\r\ufffdK\ufffdk<ޫ\ufffd\\\ufffdr\ufffd\ufffdVi\ufffdI\ufffdIܼ\u001a, err=failed to find any peer in table\n\t* failed to refresh cpl=0, err=failed to run refresh DHT query for key=\u0012 \u0000\u0000\u001d\u001a\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000, err=failed to find any peer in table\n\n"}
2020-07-08T09:15:13.022Z	INFO	build	go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138	Parameter file /var/tmp/filecoin-proof-parameters/v27-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.params is ok
2020-07-08T09:15:36.104Z	INFO	build	go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138	Parameter file /var/tmp/filecoin-proof-parameters/v27-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c4509eedae8a27555733edc.params is ok
2020-07-08T09:15:36.104Z	INFO	build	go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:162	parameter and key-fetching complete
2020-07-08T09:15:36.107Z	INFO	stores	stores/index.go:137	New sector storage: 17aa2159-511c-4ddc-ad97-4db9e5698ceb
2020-07-08T09:15:37.612Z	INFO	storageminer	storage/miner.go:130	starting up miner t0118631, worker addr t3wuz44r6wdwcpdv2futkvoi6s3nyjqt7w6i7mgebo4woajslj7fk5qxr57pxruavlc4fr7zism2vheqpgy5aa
2020-07-08T09:15:37.617Z	INFO	storageminer	storage/wdpost_sched.go:200	at 66997, doPost for P 64407, dd 26
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x117cc22]

goroutine 850 [running]:
github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).checkNextRecoveries(0xc0007ae100, 0x2bcb1e0, 0xc001fdf290, 0x1b, 0x0, 0xc000399480, 0x98, 0xc001fe26c0)
	/opt/programs/lotus/storage/wdpost_run.go:116 +0x152
github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).runPost(0xc0007ae100, 0x2bcb1e0, 0xc001fdf290, 0x105b5, 0xfb97, 0x1a, 0x10557, 0x105b7, 0x10543, 0x10543, ...)
	/opt/programs/lotus/storage/wdpost_run.go:330 +0x2a0
github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).doPost.func1(0xc0051881f0, 0x2bcb120, 0xc000399a40, 0xc0007ae100, 0xc00518a480, 0xc000399480)
	/opt/programs/lotus/storage/wdpost_run.go:47 +0x171
created by github.com/filecoin-project/lotus/storage.(*WindowPoStScheduler).doPost
	/opt/programs/lotus/storage/wdpost_run.go:41 +0xa0
**Expected behavior**
Successful result.

**Screenshots**
<img width="1440" alt="截屏2020-07-08 17 23 07" src="https://user-images.githubusercontent.com/17583815/86901858-c1fe7280-c13f-11ea-8987-4f0a0c234475.png">
<img width="1440" alt="截屏2020-07-08 17 23 13" src="https://user-images.githubusercontent.com/17583815/86901866-c32f9f80-c13f-11ea-8e82-c02b754e7ab5.png">

**Version (run `lotus version`):**
Daemon:  0.4.1+git.5de7b62d+api0.5.0
Local: lotus version 0.4.1+git.5de7b62d
**Additional context**

**Comment by github-0paul** [comment]
After update to 0.4.1+git.5de7b62d, problem disappear!
