### ISSUE TITLE
Intel CPU SIGILL: illegal instruction

### ISSUE THREAD

**Issue by noprom** [filecoin-project/lotus#2332]
**Describe the bug**
When I have download the `filecoin-proof-parameters` and run `lotus daemon`, the program crash with `SIGILL: illegal instruction`
**To Reproduce**
1. Run 'lotus fetch-params 32GiB'
2. Wait the download progress
3. Run `lotus daemon`

**Expected behavior**
You will see the error below:
```
SIGILL: illegal instruction
PC=0x2070f18 m=11 sigcode=2

goroutine 0 [idle]:
runtime: unknown pc 0x2070f18
stack: frame={sp:0x7f46ddff9940, fp:0x0} stack=[0x7f46dd7faf08,0x7f46ddffab08)
00007f46ddff9840:  f706f33cfd7d6a66  5a795adddb6df7e9 
00007f46ddff9850:  d3462d193c420289  633b942d5450bf7d 
00007f46ddff9860:  1315e20d97c1dbe2  0170f1375b3a7c22 
00007f46ddff9870:  0000000000000000  0000000000000000 
00007f46ddff9880:  ee7fbfffffffeaaa  07aaffffac54ffff 
00007f46ddff9890:  d9cc34a83dac3d89  b94d71e0b605c2c2 
00007f46ddff98a0:  b6cb1036ffea9600  b94d71e0b605c200 
00007f46ddff98b0:  0008448496f366bd  f1e3131e8eab6aff 
00007f46ddff98c0:  123758f000685a00  00007f46ddff9b10 
00007f46ddff98d0:  f0032a4363f07b89  944dbf8e9c376283 
00007f46ddff98e0:  bb25abee3c810257  2893f74edb0ff70a 
00007f46ddff98f0:  cf9750a537f3be9c  00a90749db65e3bf 
00007f46ddff9900:  87a3db6630dcacee  00007f46ddff9940 
00007f46ddff9910:  00007f46ddff9a80  00007f46ddff9b10 
00007f46ddff9920:  00007f46ddff9ae0  00007f46ddff99a0 
00007f46ddff9930:  00007f46ddff9c60  0000000002070d26 
00007f46ddff9940: <0000000000000000  0000000000000000 
00007f46ddff9950:  0000000000000000  0000000000000000 
00007f46ddff9960:  0000000000000000  0000000000000000 
00007f46ddff9970:  0000000000000000  0000000000000000 
00007f46ddff9980:  0000000000000000  0000000000000000 
00007f46ddff9990:  0000000000000000  0000000000000000 
00007f46ddff99a0:  d192940c17937c3c  36d24b9460ad5044 
00007f46ddff99b0:  38256770abfe2654  15453d6d28268895 
00007f46ddff99c0:  445066fb080c8302  009b889b8ec760ab 
00007f46ddff99d0:  0000000000000000  00007f46ddff9e30 
00007f46ddff99e0:  147e4778f7061c79  75ad326028ff4d29 
00007f46ddff99f0:  87bc7ed6713bf901  377ee51e49b2abe3 
00007f46ddff9a00:  67326d3fd6794c87  1397d28757f126cb 
00007f46ddff9a10:  28e69c48c0e3effb  4b246e81239583dc 
00007f46ddff9a20:  a2dda84a45159761  cb56a596441618b0 
00007f46ddff9a30:  b3808b1ba4c61eec  071246acbcf4a38e 
runtime: unknown pc 0x2070f18
stack: frame={sp:0x7f46ddff9940, fp:0x0} stack=[0x7f46dd7faf08,0x7f46ddffab08)
00007f46ddff9840:  f706f33cfd7d6a66  5a795adddb6df7e9 
00007f46ddff9850:  d3462d193c420289  633b942d5450bf7d 
00007f46ddff9860:  1315e20d97c1dbe2  0170f1375b3a7c22 
00007f46ddff9870:  0000000000000000  0000000000000000 
00007f46ddff9880:  ee7fbfffffffeaaa  07aaffffac54ffff 
00007f46ddff9890:  d9cc34a83dac3d89  b94d71e0b605c2c2 
00007f46ddff98a0:  b6cb1036ffea9600  b94d71e0b605c200 
00007f46ddff98b0:  0008448496f366bd  f1e3131e8eab6aff 
00007f46ddff98c0:  123758f000685a00  00007f46ddff9b10 
00007f46ddff98d0:  f0032a4363f07b89  944dbf8e9c376283 
00007f46ddff98e0:  bb25abee3c810257  2893f74edb0ff70a 
00007f46ddff98f0:  cf9750a537f3be9c  00a90749db65e3bf 
00007f46ddff9900:  87a3db6630dcacee  00007f46ddff9940 
00007f46ddff9910:  00007f46ddff9a80  00007f46ddff9b10 
00007f46ddff9920:  00007f46ddff9ae0  00007f46ddff99a0 
00007f46ddff9930:  00007f46ddff9c60  0000000002070d26 
00007f46ddff9940: <0000000000000000  0000000000000000 
00007f46ddff9950:  0000000000000000  0000000000000000 
00007f46ddff9960:  0000000000000000  0000000000000000 
00007f46ddff9970:  0000000000000000  0000000000000000 
00007f46ddff9980:  0000000000000000  0000000000000000 
00007f46ddff9990:  0000000000000000  0000000000000000 
00007f46ddff99a0:  d192940c17937c3c  36d24b9460ad5044 
00007f46ddff99b0:  38256770abfe2654  15453d6d28268895 
00007f46ddff99c0:  445066fb080c8302  009b889b8ec760ab 
00007f46ddff99d0:  0000000000000000  00007f46ddff9e30 
00007f46ddff99e0:  147e4778f7061c79  75ad326028ff4d29 
00007f46ddff99f0:  87bc7ed6713bf901  377ee51e49b2abe3 
00007f46ddff9a00:  67326d3fd6794c87  1397d28757f126cb 
00007f46ddff9a10:  28e69c48c0e3effb  4b246e81239583dc 
00007f46ddff9a20:  a2dda84a45159761  cb56a596441618b0 
00007f46ddff9a30:  b3808b1ba4c61eec  071246acbcf4a38e 

goroutine 9432 [syscall]:
runtime.cgocall(0x15ca360, 0xc00679d5c8, 0xc005e51600)
	/usr/lib/go-1.14/src/runtime/cgocall.go:133 +0x5b fp=0xc00679d598 sp=0xc00679d560 pc=0x536f8b
github.com/filecoin-project/filecoin-ffi/generated._Cfunc_fil_hash_verify(0xc0007456c0, 0xc006682ba0, 0x26, 0xc005e5d020, 0x1, 0xc005e51600, 0x30, 0x0)
	_cgo_gotypes.go:1470 +0x4d fp=0xc00679d5c8 sp=0xc00679d598 pc=0xc117fd
github.com/filecoin-project/filecoin-ffi/generated.FilHashVerify(0xc005725560, 0x60, 0xc006682b10, 0x26, 0x26, 0xc005e5d020, 0x1, 0x1, 0x1, 0xc006682b70, ...)
	/home/ps/share/ssd/code/test.0.4.1.community/extern/filecoin-ffi/generated/generated.go:443 +0x277 fp=0xc00679d6d8 sp=0xc00679d5c8 pc=0xc1fa87
github.com/filecoin-project/filecoin-ffi.HashVerify(0xc00679d8e0, 0xc00679d940, 0x1, 0x1, 0xc00679d8b0, 0x1, 0x1, 0x20)
	/home/ps/share/ssd/code/test.0.4.1.community/extern/filecoin-ffi/bls.go:59 +0x392 fp=0xc00679d820 sp=0xc00679d6d8 pc=0xc28562
github.com/filecoin-project/lotus/lib/sigs/bls.blsSigner.Verify(0xc000745651, 0x60, 0x60, 0xc005e514c0, 0x31, 0xc006682ab0, 0x26, 0x30, 0x0, 0xc0003ae280)
	/home/ps/share/ssd/code/test.0.4.1.community/lib/sigs/bls/init.go:45 +0x1d0 fp=0xc00679d968 sp=0xc00679d820 pc=0xf571b0
github.com/filecoin-project/lotus/lib/sigs/bls.(*blsSigner).Verify(0x517fe88, 0xc000745651, 0x60, 0x60, 0xc005e514c0, 0x31, 0xc006682ab0, 0x26, 0x30, 0x30, ...)
	<autogenerated>:1 +0x9d fp=0xc00679d9c8 sp=0xc00679d968 pc=0xf5771d
github.com/filecoin-project/lotus/lib/sigs.Verify(0xc002057388, 0xc005e514c0, 0x31, 0xc006682ab0, 0x26, 0x30, 0xc0000408d0, 0x2)
	/home/ps/share/ssd/code/test.0.4.1.community/lib/sigs/sigs.go:48 +0xf0 fp=0xc00679da40 sp=0xc00679d9c8 pc=0xc0fd40
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).VerifyMsgSig(0xc0004bd8c0, 0xc002057320, 0xffffffffffffffff, 0x0)
	/home/ps/share/ssd/code/test.0.4.1.community/chain/messagepool/messagepool.go:372 +0xd1 fp=0xc00679daa0 sp=0xc00679da40 pc=0x10ee581
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).Add(0xc0004bd8c0, 0xc002057320, 0x0, 0x0)
	/home/ps/share/ssd/code/test.0.4.1.community/chain/messagepool/messagepool.go:335 +0xdc fp=0xc00679db60 sp=0xc00679daa0 pc=0x10ede7c
github.com/filecoin-project/lotus/chain/sub.(*MessageValidator).Validate(0xc0006345e8, 0x2c07940, 0xc000417400, 0xc0065e8b10, 0x26, 0xc005e5f4a0, 0xc004ed75b8)
	/home/ps/share/ssd/code/test.0.4.1.community/chain/sub/incoming.go:368 +0x34f fp=0xc00679dc90 sp=0xc00679db60 pc=0x158ab6f
github.com/filecoin-project/lotus/chain/sub.(*MessageValidator).Validate-fm(0x2c07940, 0xc000417400, 0xc0065e8b10, 0x26, 0xc005e5f4a0, 0x0)
	/home/ps/share/ssd/code/test.0.4.1.community/chain/sub/incoming.go:358 +0x5c fp=0xc00679dcd8 sp=0xc00679dc90 pc=0x159731c
github.com/libp2p/go-libp2p-pubsub.(*topicVal).validateMsg(0xc0002fe000, 0x2c07940, 0xc000417400, 0xc0065e8b10, 0x26, 0xc005e5f4a0, 0x0)
	/home/ps/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.3.2/validation.go:423 +0xb3 fp=0xc00679dd68 sp=0xc00679dcd8 pc=0x10d7383
github.com/libp2p/go-libp2p-pubsub.(*validation).validateSingleTopic(0xc0002e0ba0, 0xc0002fe000, 0xc0065e8b10, 0x26, 0xc005e5f4a0, 0xc004ed7640)
	/home/ps/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.3.2/validation.go:406 +0xa6 fp=0xc00679dde8 sp=0xc00679dd68 pc=0x10d71d6
github.com/libp2p/go-libp2p-pubsub.(*validation).validateTopic(0xc0002e0ba0, 0xc0001189f8, 0x1, 0x1, 0xc0065e8b10, 0x26, 0xc005e5f4a0, 0x0)
	/home/ps/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.3.2/validation.go:355 +0x395 fp=0xc00679deb0 sp=0xc00679dde8 pc=0x10d70e5
github.com/libp2p/go-libp2p-pubsub.(*validation).doValidateTopic(0xc0002e0ba0, 0xc0001189f8, 0x1, 0x1, 0xc0065e8b10, 0x26, 0xc005e5f4a0, 0x0)
	/home/ps/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.3.2/validation.go:326 +0x8e fp=0xc00679df60 sp=0xc00679deb0 pc=0x10d696e
github.com/libp2p/go-libp2p-pubsub.(*validation).validate.func1(0xc0002e0ba0, 0xc006788420, 0xc0065e8b10, 0x26, 0xc005e5f4a0, 0xc005e5cf48)
	/home/ps/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.3.2/validation.go:296 +0x79 fp=0xc00679dfb0 sp=0xc00679df60 pc=0x10dab39
runtime.goexit()
	/usr/lib/go-1.14/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00679dfb8 sp=0xc00679dfb0 pc=0x59bbd1
created by github.com/libp2p/go-libp2p-pubsub.(*validation).validate
	/home/ps/go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.3.2/validation.go:295 +0x4a6

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f46e4482998, 0x72, 0x0)
	/usr/lib/go-1.14/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc002034218, 0x72, 0x0, 0x0, 0x2825f18)
	/usr/lib/go-1.14/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go-1.14/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc002034200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go-1.14/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc002034200, 0x203000, 0xc000398b90, 0xc0004654f8)
	/usr/lib/go-1.14/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc0020149c0, 0x50, 0x50, 0x26a51a0)
	/usr/lib/go-1.14/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc0020149c0, 0x2706220, 0x7f470d9569b8, 0xc000400000, 0x30)
	/usr/lib/go-1.14/src/net/tcpsock.go:261 +0x64
github.com/multiformats/go-multiaddr-net.(*maListener).Accept(0xc002014a40, 0xc002016aa0, 0xc0004655d8, 0x540f18, 0x30)
	/home/ps/go/pkg/mod/github.com/multiformats/go-multiaddr-net@v0.1.5/net.go:243 +0x37
github.com/multiformats/go-multiaddr-net.(*netListenerAdapter).Accept(0xc000398b40, 0x2706220, 0xc0002f2a80, 0x257ade0, 0x4fccdf0)
	/home/ps/go/pkg/mod/github.com/multiformats/go-multiaddr-net@v0.1.5/net.go:222 +0x33
net/http.(*Server).Serve(0xc0002d0540, 0x2bfe480, 0xc000398b40, 0x0, 0x0)
	/usr/lib/go-1.14/src/net/http/server.go:2901 +0x25d
main.serveRPC(0x2c3d4a0, 0xc00018a500, 0xc004e734d0, 0x2c278e0, 0xc004e76d80, 0xc0004df020, 0x0, 0x0)
	/home/ps/share/ssd/code/test.0.4.1.community/cmd/lotus/rpc.go:83 +0x5c8
main.glob..func2(0xc000491700, 0x0, 0x0)
	/home/ps/share/ssd/code/test.0.4.1.community/cmd/lotus/daemon.go:276 +0x1247
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc0003c7080, 0xc000491300, 0x0, 0x0)
	/home/ps/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:432 +0x993
github.com/urfave/cli/v2.(*Command).startApp(0x4fea260, 0xc000491300, 0x7ffde536c713, 0x6)
	/home/ps/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x68c
github.com/urfave/cli/v2.(*Command).Run(0x4fea260, 0xc000491300, 0x0, 0x0)
	/home/ps/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:94 +0xa12
github.com/urfave/cli/v2.(*App).RunContext(0xc0003c6f00, 0x2c07980, 0xc0000420e8, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
	/home/ps/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
	/home/ps/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/home/ps/share/ssd/code/test.0.4.1.community/cmd/lotus/main.go:72 +0x677

```
**Version (run `lotus version`):**
```
Daemon:  0.4.1+git.ee7bdf38+api0.5.0--1-1594346602
Local: lotus version 0.4.1+git.ee7bdf38
```

# Full logs
[lotus.log](https://github.com/noprom/lotus-error/blob/master/lotus.log)

**Comment by magik6k** [comment]
This can be caused by building lotus on a machine with a newer CPU than the one you run lotus on

**Comment by noprom** [comment]
Solved by re-compile lotus.

**Comment by jcomeauictx** [comment]
I had to `export CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"` and 
`export CGO_CFLAGS="-D__BLST_PORTABLE__"` as detailed at https://docs.filecoin.io/get-started/lotus/installation/#build-and-install-lotus, `make clean all` and `sudo make install` again.
