### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by qiluge** [filecoin-project/lotus#2355]
**Describe the bug**
runtime panic

**To Reproduce**
1. Run 'lotus daemon'
2. See error

```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x282b448, 0x16)
        /data/go/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc0e4000000, 0x8000000, 0x517de78)
        /data/go/src/runtime/mem_linux.go:169 +0xc5
runtime.(*mheap).sysAlloc(0x5166a60, 0x4800000, 0x5166a68, 0x2280)
        /data/go/src/runtime/malloc.go:715 +0x1cd
runtime.(*mheap).grow(0x5166a60, 0x2280, 0x0)
        /data/go/src/runtime/mheap.go:1286 +0x11c
runtime.(*mheap).allocSpan(0x5166a60, 0x2280, 0x45b0100, 0x517de88, 0x45bdd08)
        /data/go/src/runtime/mheap.go:1124 +0x6a0
runtime.(*mheap).alloc.func1()
        /data/go/src/runtime/mheap.go:871 +0x64
runtime.(*mheap).alloc(0x5166a60, 0x2280, 0x2c5960101, 0xc019fd6780)
        /data/go/src/runtime/mheap.go:865 +0x81
runtime.largeAlloc(0x4500000, 0xc01a1b0101, 0x57ab25)
        /data/go/src/runtime/malloc.go:1152 +0x92
runtime.mallocgc.func1()
        /data/go/src/runtime/malloc.go:1047 +0x46
runtime.systemstack(0x0)
        /data/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /data/go/src/runtime/proc.go:1041

goroutine 508 [running]:
runtime.systemstack_switch()
        /data/go/src/runtime/asm_amd64.s:330 fp=0xc01a1b8f60 sp=0xc01a1b8f58 pc=0x576c80
runtime.mallocgc(0x4500000, 0x24e3440, 0xc027dc8301, 0xc01c211c20)
        /data/go/src/runtime/malloc.go:1046 +0x895 fp=0xc01a1b9000 sp=0xc01a1b8f60 pc=0x51dc95
runtime.makeslice(0x24e3440, 0x4500000, 0x4500000, 0xedf0160)
        /data/go/src/runtime/slice.go:49 +0x6c fp=0xc01a1b9030 sp=0xc01a1b9000 pc=0x55db9c
github.com/dgraph-io/badger/v2/table.NewTableBuilder(0x4000000, 0x0, 0x2, 0x3f847ae147ae147b, 0x1000, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
        /data/code/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/table/builder.go:99 +0x95 fp=0xc01a1b9098 sp=0xc01a1b9030 pc=0xe33655
github.com/dgraph-io/badger/v2.(*levelsController).compactBuildTables(0xc000564000, 0x1, 0x2c07be0, 0xc000456b60, 0xc000436ea0, 0xc000437140, 0xc000133c90, 0x1, 0x1, 0xc027dc8210, ...)
        /data/code/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/levels.go:535 +0x11a5 fp=0xc01a1b9798 sp=0xc01a1b9098 pc=0xe5d8b5
github.com/dgraph-io/badger/v2.(*levelsController).runCompactDef(0xc000564000, 0x1, 0x2c07be0, 0xc000456b60, 0xc000436ea0, 0xc000437140, 0xc000133c90, 0x1, 0x1, 0xc027dc8210, ...)
        /data/code/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/levels.go:837 +0xe1 fp=0xc01a1b99a0 sp=0xc01a1b9798 pc=0xe5ff51
github.com/dgraph-io/badger/v2.(*levelsController).doCompact(0xc000564000, 0x1, 0x3ff08239ce000000, 0x0, 0x0, 0x0, 0x0, 0x0)
        /data/code/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/levels.go:906 +0x49d fp=0xc01a1b9e10 sp=0xc01a1b99a0 pc=0xe609bd
github.com/dgraph-io/badger/v2.(*levelsController).runWorker(0xc000564000, 0xc0002d9c60)
        /data/code/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/levels.go:367 +0x2fd fp=0xc01a1b9fd0 sp=0xc01a1b9e10 pc=0xe5bdfd
runtime.goexit()
        /data/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc01a1b9fd8 sp=0xc01a1b9fd0 pc=0x578d91
created by github.com/dgraph-io/badger/v2.(*levelsController).startCompact
        /data/code/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/levels.go:342 +0x88

goroutine 1 [IO wait]:
internal/poll.runtime_pollWait(0x7f01aa635b58, 0x72, 0x0)
        /data/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc01b39e398, 0x72, 0x0, 0x0, 0x281457e)
        /data/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /data/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Accept(0xc01b39e380, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /data/go/src/internal/poll/fd_unix.go:384 +0x1d4
net.(*netFD).accept(0xc01b39e380, 0x203006, 0xc019b79260, 0xc0000e54e0)
        /data/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc000269440, 0x50, 0x50, 0x2693720)
        /data/go/src/net/tcpsock_posix.go:139 +0x32
net.(*TCPListener).Accept(0xc000269440, 0x26f4be0, 0x7f01aa7ad108, 0xc000400a80, 0x30)
        /data/go/src/net/tcpsock.go:261 +0x64
github.com/multiformats/go-multiaddr-net.(*maListener).Accept(0xc0002694c0, 0xc00008fd10, 0xc0000e55c0, 0x51df88, 0x30)
        /data/code/pkg/mod/github.com/multiformats/go-multiaddr-net@v0.1.5/net.go:243 +0x37
github.com/multiformats/go-multiaddr-net.(*netListenerAdapter).Accept(0xc019b79210, 0x26f4be0, 0xc01ad71350, 0x2569700, 0x4fc7de0)
        /data/code/pkg/mod/github.com/multiformats/go-multiaddr-net@v0.1.5/net.go:222 +0x33
net/http.(*Server).Serve(0xc000370700, 0x2beccc0, 0xc019b79210, 0x0, 0x0)
        /data/go/src/net/http/server.go:2901 +0x25d
main.serveRPC(0x2c2be00, 0xc00021a000, 0xc01b1cb4c0, 0x2c16300, 0xc01b1cf040, 0xc00010e780, 0x0, 0x0)
        /data/code/src/github.com/filecoin-project/lotus/cmd/lotus/rpc.go:86 +0x60a
main.glob..func2(0xc0004182c0, 0x0, 0x0)
        /data/code/src/github.com/filecoin-project/lotus/cmd/lotus/daemon.go:274 +0x1218
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000001e00, 0xc000083d00, 0x0, 0x0)
        /data/code/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:432 +0x993
github.com/urfave/cli/v2.(*Command).startApp(0x4fe5240, 0xc000083d00, 0x7fff9c8ad689, 0x6)
        /data/code/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x68c
github.com/urfave/cli/v2.(*Command).Run(0x4fe5240, 0xc000083d00, 0x0, 0x0)
        /data/code/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:94 +0xa12
github.com/urfave/cli/v2.(*App).RunContext(0xc000001c80, 0x2bf6280, 0xc000122000, 0xc00012c020, 0x2, 0x2, 0x0, 0x0)
        /data/code/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
        /data/code/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
        /data/code/src/github.com/filecoin-project/lotus/cmd/lotus/main.go:72 +0x677

goroutine 19 [select]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc00011d200)
        /data/code/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:71 +0x128
created by github.com/ipfs/go-log/writer.NewMirrorWriter
        /data/code/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:36 +0xb9

goroutine 20 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000174af0)
        /data/code/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:154 +0x100
created by go.opencensus.io/stats/view.init.0
        /data/code/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:32 +0x57

goroutine 3908 [select]:
github.com/libp2p/go-yamux.(*Stream).Read(0xc01c6b12c0, 0xc053304000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /data/code/pkg/mod/github.com/libp2p/go-yamux@v1.3.7/stream.go:108 +0x19f
github.com/libp2p/go-libp2p-yamux.(*stream).Read(0xc01c6b12c0, 0xc053304000, 0x1000, 0x1000, 0xc000000008, 0xc01ac19b08, 0x58556a)
        /data/code/pkg/mod/github.com/libp2p/go-libp2p-yamux@v0.2.8/stream.go:14 +0x4d
github.com/libp2p/go-libp2p-swarm.(*Stream).Read(0xc0489c2fc0, 0xc053304000, 0x1000, 0x1000, 0x58556a, 0xc04035b3d4, 0xc000000001)
        /data/code/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.7/swarm_stream.go:71 +0x62
github.com/multiformats/go-multistream.(*lazyClientConn).Read(0xc04035b3b0, 0xc053304000, 0x1000, 0x1000, 0x8, 0xc01ac19bd0, 0xc01ac19c00)
        /data/code/pkg/mod/github.com/multiformats/go-multistream@v0.1.1/lazyClient.go:75 +0xa8
github.com/libp2p/go-libp2p/p2p/host/basic.(*streamWrapper).Read(0xc0488c6260, 0xc053304000, 0x1000, 0x1000, 0xc04035b3b0, 0xc0488c4150, 0x63)
        /data/code/pkg/mod/github.com/libp2p/go-libp2p@v0.10.0/p2p/host/basic/basic_host.go:952 +0x52
bufio.(*Reader).fill(0xc05317e900)
        /data/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).ReadByte(0xc05317e900, 0x63, 0x0, 0x20)
        /data/go/src/bufio/bufio.go:252 +0x39
encoding/binary.ReadUvarint(0x2bc0b40, 0xc05317e900, 0x0, 0x0, 0x62)
        /data/go/src/encoding/binary/varint.go:110 +0x7b
github.com/gogo/protobuf/io.(*varintReader).ReadMsg(0xc05317b100, 0x2beb080, 0xc05317b300, 0x0, 0x0)
        /data/code/pkg/mod/github.com/gogo/protobuf@v1.3.1/io/varint.go:110 +0x3e
github.com/libp2p/go-libp2p-autonat.(*client).DialBack(0xc048987100, 0x2bf62c0, 0xc0489bc240, 0xc03ccefdd0, 0x26, 0x0, 0x0, 0x0, 0x0)
        /data/code/pkg/mod/github.com/libp2p/go-libp2p-autonat@v0.2.3/client.go:57 +0x3c7
github.com/libp2p/go-libp2p-autonat.(*AmbientAutoNAT).probe(0xc00011f450, 0xc0489b8b10)
        /data/code/pkg/mod/github.com/libp2p/go-libp2p-autonat@v0.2.3/autonat.go:372 +0x108
created by github.com/libp2p/go-libp2p-autonat.(*AmbientAutoNAT).tryProbe
        /data/code/pkg/mod/github.com/libp2p/go-libp2p-autonat@v0.2.3/autonat.go:361 +0x29c

goroutine 10 [chan receive]:
github.com/filecoin-project/lotus/cli.ReqContext.func1(0xc0003762a0, 0xc000238f10)
        /data/code/src/github.com/filecoin-project/lotus/cli/cmd.go:205 +0x34
created by github.com/filecoin-project/lotus/cli.ReqContext
        /data/code/src/github.com/filecoin-project/lotus/cli/cmd.go:204 +0x103

goroutine 11 [syscall]:
os/signal.signal_recv(0x0)
        /data/go/src/runtime/sigqueue.go:147 +0x9c
os/signal.loop()
        /data/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.Notify.func1
        /data/go/src/os/signal/signal.go:127 +0x44

goroutine 507 [runnable]:
github.com/dgraph-io/badger/v2/y.(*ValueStruct).EncodedSize(0xc015323050, 0xc0dcbfff22)
        /data/code/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/y/iterator.go:47 +0x74
github.com/dgraph-io/badger/v2/table.(*Builder).addHelper(0xc0bff3f980, 0xc07cd1b2c0, 0x4a, 0x50, 0x40, 0x0, 0x7efd9463af25, 0x5c8, 0x226f94e, 0x0, ...)
        /data/code/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/table/builder.go:225 +0x295
github.com/dgraph-io/badger/v2/table.(*Builder).Add(0xc0bff3f980, 0xc07cd1b2c0, 0x4a, 0x50, 0x40, 0x0, 0x7efd9463af25, 0x5c8, 0x226f94e, 0x0, ...)
        /data/code/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/table/builder.go:339 +0xe0
github.com/dgraph-io/badger/v2.(*levelsController).compactBuildTables(0xc000564000, 0x2, 0x2c07be0, 0xc0003ccd00, 0xc000437140, 0xc000437200, 0xc00056a3d8, 0x1, 0x1, 0xc03b0c21f0, ...)
        /data/code/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/levels.go:609 +0x908
github.com/dgraph-io/badger/v2.(*levelsController).runCompactDef(0xc000564000, 0x2, 0x2c07be0, 0xc0003ccd00, 0xc000437140, 0xc000437200, 0xc00056a3d8, 0x1, 0x1, 0xc03b0c21f0, ...)
        /data/code/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/levels.go:837 +0xe1
github.com/dgraph-io/badger/v2.(*levelsController).doCompact(0xc000564000, 0x2, 0x3ff17192e54ccccd, 0x0, 0x0, 0x0, 0x0, 0x0)
        /data/code/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/levels.go:906 +0x49d
github.com/dgraph-io/badger/v2.(*levelsController).runWorker(0xc000564000, 0xc0002d9c60)
        /data/code/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/levels.go:367 +0x2fd
created by github.com/dgraph-io/badger/v2.(*levelsController).startCompact
        /data/code/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.3/levels.go:342 +0x88

goroutine 6639 [select]:
github.com/libp2p/go-yamux.(*Stream).Read(0xc01fc675e0, 0xc0b9d0f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /data/code/pkg/mod/github.com/libp2p/go-yamux@v1.3.7/stream.go:108 +0x19f
github.com/libp2p/go-libp2p-yamux.(*stream).Read(0xc01fc675e0, 0xc0b9d0f000, 0x1000, 0x1000, 0xc000000008, 0xc00032bb08, 0x58556a)
        /data/code/pkg/mod/github.com/libp2p/go-libp2p-yamux@v0.2.8/stream.go:14 +0x4d
github.com/libp2p/go-libp2p-swarm.(*Stream).Read(0xc0b91a8fc0, 0xc0b9d0f000, 0x1000, 0x1000, 0x58556a, 0xc0b91a91a4, 0xc000000001)
        /data/code/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.7/swarm_stream.go:71 +0x62
github.com/multiformats/go-multistream.(*lazyClientConn).Read(0xc0b91a9180, 0xc0b9d0f000, 0x1000, 0x1000, 0x8, 0xc00032bbd0, 0xc00032bc00)
        /data/code/pkg/mod/github.com/multiformats/go-multistream@v0.1.1/lazyClient.go:75 +0xa8
github.com/libp2p/go-libp2p/p2p/host/basic.(*streamWrapper).Read(0xc0b97f5340, 0xc0b9d0f000, 0x1000, 0x1000, 0xc0b91a9180, 0xc08ca3f9d0, 0x63)
        /data/code/pkg/mod/github.com/libp2p/go-libp2p@v0.10.0/p2p/host/basic/basic_host.go:952 +0x52
bufio.(*Reader).fill(0xc0b9557f80)
        /data/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).ReadByte(0xc0b9557f80, 0x63, 0x0, 0x20)
        /data/go/src/bufio/bufio.go:252 +0x39
encoding/binary.ReadUvarint(0x2bc0b40, 0xc0b9557f80, 0x0, 0x0, 0x62)
        /data/go/src/encoding/binary/varint.go:110 +0x7b
github.com/gogo/protobuf/io.(*varintReader).ReadMsg(0xc0b97ddac0, 0x2beb080, 0xc0b97ddcc0, 0x0, 0x0)
        /data/code/pkg/mod/github.com/gogo/protobuf@v1.3.1/io/varint.go:110 +0x3e
github.com/libp2p/go-libp2p-autonat.(*client).DialBack(0xc0b91aad60, 0x2bf62c0, 0xc0b9556e40, 0xc08f18a480, 0x26, 0x0, 0x0, 0x0, 0x0)
        /data/code/pkg/mod/github.com/libp2p/go-libp2p-autonat@v0.2.3/client.go:57 +0x3c7
github.com/libp2p/go-libp2p-autonat.(*AmbientAutoNAT).probe(0xc00011f450, 0xc0b97e41e0)
        /data/code/pkg/mod/github.com/libp2p/go-libp2p-autonat@v0.2.3/autonat.go:372 +0x108
created by github.com/libp2p/go-libp2p-autonat.(*AmbientAutoNAT).tryProbe
        /data/code/pkg/mod/github.com/libp2p/go-libp2p-autonat@v0.2.3/autonat.go:361 +0x29c

goroutine 37 [select]:
github.com/libp2p/go-libp2p-connmgr.(*BasicConnMgr).background(0xc00039c000)
        /data/code/pkg/mod/github.com/libp2p/go-libp2p-connmgr@v0.2.4/connmgr.go:246 +0x163
created by github.com/libp2p/go-libp2p-connmgr.NewConnManager
        /data/code/pkg/mod/github.com/libp2p/go-libp2p-connmgr@v0.2.4/connmgr.go:140 +0x2bc

goroutine 519 [runnable]:
github.com/ipfs/go-ds-badger2.(*txn).query.func1(0x2c10d80, 0xc05370afc0)
        /data/code/pkg/mod/github.com/ipfs/go-ds-badger2@v0.1.1-0.20200708190120-187fc06f714e/datastore.go:746 +0x975
github.com/jbenet/goprocess.(*process).Go.func1(0xc000176380, 0xc05370afc0, 0xc05370b020)
        /data/code/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:134 +0x3c
created by github.com/jbenet/goprocess.(*process).Go
        /data/code/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:133 +0x1f6

goroutine 36 [select]:
github.com/libp2p/go-libp2p-connmgr.(*decayer).process(0xc000176100)
        /data/code/pkg/mod/github.com/libp2p/go-libp2p-connmgr@v0.2.4/decay.go:165 +0x287
created by github.com/libp2p/go-libp2p-connmgr.NewDecayer
        /data/code/pkg/mod/github.com/libp2p/go-libp2p-connmgr@v0.2.4/decay.go:95 +0x214

goroutine 497 [runnable]:
github.com/multiformats/go-base32.(*Encoding).decode(0xc00015a480, 0xc0258e44c0, 0x3a, 0x40, 0xc0258e44c0, 0x3a, 0x40, 0x40, 0x40, 0x3a, ...)
        /data/code/pkg/mod/github.com/multiformats/go-base32@v0.0.3/base32.go:278 +0x4a3
github.com/multiformats/go-base32.(*Encoding).decodeInPlace(0xc00015a480, 0xc0258e44c0, 0x3a, 0x40, 0x3a, 0x40, 0xf17)
        /data/code/pkg/mod/github.com/multiformats/go-base32@v0.0.3/base32.go:394 +0x90
github.com/multiformats/go-base32.(*Encoding).DecodeString(0xc00015a480, 0xc0161b6c3e, 0x3a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /data/code/pkg/mod/github.com/multiformats/go-base32@v0.0.3/base32.go:401 +0x78
github.com/ipfs/go-ipfs-ds-help.BinaryFromDsKey(...)
        /data/code/pkg/mod/github.com/ipfs/go-ipfs-ds-help@v1.0.0/key.go:22
github.com/ipfs/go-ipfs-blockstore.(*blockstore).AllKeysChan.func1(0x2c031a0, 0xc0001ec0e0, 0xc04184aea0, 0x2bf6300, 0xc019215290)
        /data/code/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v1.0.0/blockstore.go:222 +0x15c
created by github.com/ipfs/go-ipfs-blockstore.(*blockstore).AllKeysChan
        /data/code/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v1.0.0/blockstore.go:205 +0x177
```

**Comment by travisperson** [comment]
How much memory do you have?

```
$ free -m
```

**Comment by qiluge** [comment]
> How much memory do you have?
> 
> ```
> $ free -m
> ```

![image](https://user-images.githubusercontent.com/19525062/87122763-1a588000-c2b8-11ea-8863-e0861e3ff01d.png)

**Comment by qiluge** [comment]
And other question:
![image](https://user-images.githubusercontent.com/19525062/87122822-30fed700-c2b8-11ea-9694-3ad0327bf5d7.png)

Thank you.

**Comment by qiluge** [comment]
![image](https://user-images.githubusercontent.com/19525062/87122920-5f7cb200-c2b8-11ea-8f5f-7c8e0903168d.png)
It took more than one day that I couldn't sync the whole lotus block....

**Comment by qiluge** [comment]
after increased memory to 8G, the problem is solved.

**Comment by qiluge** [comment]
but the `bad handshake` still exist.
https://github.com/filecoin-project/lotus/issues/2360
