### ISSUE TITLE
Lotus appears to deadlock when trying to gracefully shut it down

### ISSUE THREAD

**Issue by nonsense** [filecoin-project/lotus#2406]
**Describe the bug**
I am trying to gracefully shut down a Lotus node that I have started programatically, by calling the `StopFunc` function, returned when calling `node.New`. Relevant code on usage of Lotus API at: https://github.com/filecoin-project/oni/blob/master/lotus-soup/testkit/role_miner.go#L225

I notice in the goroutine stack dump, that there are two functions trying to acquire the same lock:

1.
```
goroutine 1214 [semacquire, 13 minutes]:
sync.runtime_SemacquireMutex(0xc0007965c4, 0x2c181e6200, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0007965c0)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/filecoin-project/lotus/miner.(*Miner).GetBestMiningCandidate(0xc0007965a0, 0x2f63080, 0xc000681200, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/filecoin-project/lotus@v0.4.2-0.20200713113510-a77891780614/miner/miner.go:222 +0x475
github.com/filecoin-project/lotus/miner.(*Miner).mine(0xc0007965a0, 0x2f63080, 0xc000681200)
	/go/pkg/mod/github.com/filecoin-project/lotus@v0.4.2-0.20200713113510-a77891780614/miner/miner.go:149 +0x304
created by github.com/filecoin-project/lotus/miner.(*Miner).Start
	/go/pkg/mod/github.com/filecoin-project/lotus@v0.4.2-0.20200713113510-a77891780614/miner/miner.go:88 +0xe4
```

2.
```
goroutine 13724 [select, 13 minutes]:
github.com/filecoin-project/lotus/miner.(*Miner).Stop(0xc0007965a0, 0x2f63000, 0xc000124000, 0x0, 0x0)
	/go/pkg/mod/github.com/filecoin-project/lotus@v0.4.2-0.20200713113510-a77891780614/miner/miner.go:100 +0x15a
github.com/filecoin-project/lotus/node/modules.SetupBlockProducer.func2(0x2f63000, 0xc000124000, 0xa, 0xc002605460)
	/go/pkg/mod/github.com/filecoin-project/lotus@v0.4.2-0.20200713113510-a77891780614/node/modules/storageminer.go:307 +0x3e
go.uber.org/fx/internal/lifecycle.(*Lifecycle).Stop(0xc001053e30, 0x2f63000, 0xc000124000, 0x1007f6ad8002520, 0x54e6a6)
	/go/pkg/mod/go.uber.org/fx@v1.9.0/internal/lifecycle/lifecycle.go:86 +0x132
go.uber.org/fx.withTimeout.func1(0xc0007e5620, 0xc0026053f0, 0x2f63000, 0xc000124000)
	/go/pkg/mod/go.uber.org/fx@v1.9.0/app.go:600 +0x3a
created by go.uber.org/fx.withTimeout
	/go/pkg/mod/go.uber.org/fx@v1.9.0/app.go:600 +0x91
```

2 has acquired a lock and blocked on a select, while 1 is trying to acquire the same lock.

**To Reproduce**
1. Run the test plan from https://github.com/filecoin-project/oni/pull/95 although the bug is non-deterministic and only occasionally manifests.

**Expected behavior**
Lotus shuts down properly immediately or after a few seconds after calling the `app.Stop` method.

**Screenshots**

**Version (run `lotus version`):**
Commit: `a77891780614a34d94484a0327a46d3cbd508ad4` from branch `next`.

**Additional context**
Goroutine dump 
[miner-biserk.txt](https://github.com/filecoin-project/lotus/files/4918891/miner-biserk.txt)

**Comment by nonsense** [comment]
I believe this has been addressed in https://github.com/filecoin-project/lotus/pull/2478

Will re-open if it happens again.
