### ISSUE TITLE
error in RPC call to 'Filecoin.SealPreCommit2': presealing sector 4 

### ISSUE THREAD

**Issue by noprom** [filecoin-project/lotus#2464]
**Describe the problem**

sector 4 precommit2 error
**Sectors list**
```
root@amd01:~# lotus-storage-miner sectors list
0: Proving    sSet: YES pSet: YES tktH: 97350 seedH: 98915 deals: [0]
1: Proving    sSet: YES pSet: YES tktH: 97362 seedH: 98968 deals: [0]
2: Proving    sSet: YES pSet: YES tktH: 98188 seedH: 99751 deals: [0]
3: Proving    sSet: YES pSet: YES tktH: 98290 seedH: 99930 deals: [0]
4: PreCommit2 sSet: NO  pSet: NO  tktH: 98985 seedH: 0     deals: [0]
5: PreCommit1 sSet: NO  pSet: NO  tktH: 0     seedH: 0     deals: [0]
6: PreCommit1 sSet: NO  pSet: NO  tktH: 0     seedH: 0     deals: [0]
7: PreCommit1 sSet: NO  pSet: NO  tktH: 0     seedH: 0     deals: [0]
```
**Sectors status**

```
lotus-storage-miner sectors status --log 4
```

```
SectorID:	4
Status:	PreCommit2
CommD:		<nil>
CommR:		<nil>
Ticket:		797f62d0aae87251af30ae012634fcc1f52c30b8c34ace847140bd35685c14c4
TicketH:		98985
Seed:
SeedH:		0
Proof:
Deals:		[0]
Retries:		0
--------
Event Log:
0.	2020-07-18 05:38:47 +0800 CST:	[event;sealing.SectorStart]	{"User":{"ID":4,"SectorType":3,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"bafk4chzaa57f7xrvyufjga5fkae6gsmkj27n7444ik3rbnzq3dwhvr5puy7a"}},"DealInfo":null}]}}
1.	2020-07-18 05:38:47 +0800 CST:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":null}}
2.	2020-07-18 09:49:25 +0800 CST:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzMyR2lCVjEiLCJsYWJlbHMiOnsiU3RhY2tlZERyZzMyR2lCVjEiOnsibGFiZWxzIjpbeyJwYXRoIjoiL2RhdGEvbG90dXN3b3JrZXIvY2FjaGUvcy10MDEyMjQ5MS00IiwiaWQiOiJsYXllci0xIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YS9sb3R1c3dvcmtlci9jYWNoZS9zLXQwMTIyNDkxLTQiLCJpZCI6ImxheWVyLTIiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzd29ya2VyL2NhY2hlL3MtdDAxMjI0OTEtNCIsImlkIjoibGF5ZXItMyIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEvbG90dXN3b3JrZXIvY2FjaGUvcy10MDEyMjQ5MS00IiwiaWQiOiJsYXllci00Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YS9sb3R1c3dvcmtlci9jYWNoZS9zLXQwMTIyNDkxLTQiLCJpZCI6ImxheWVyLTUiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzd29ya2VyL2NhY2hlL3MtdDAxMjI0OTEtNCIsImlkIjoibGF5ZXItNiIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEvbG90dXN3b3JrZXIvY2FjaGUvcy10MDEyMjQ5MS00IiwiaWQiOiJsYXllci03Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvZGF0YS9sb3R1c3dvcmtlci9jYWNoZS9zLXQwMTIyNDkxLTQiLCJpZCI6ImxheWVyLTgiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii9kYXRhL2xvdHVzd29ya2VyL2NhY2hlL3MtdDAxMjI0OTEtNCIsImlkIjoibGF5ZXItOSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEvbG90dXN3b3JrZXIvY2FjaGUvcy10MDEyMjQ5MS00IiwiaWQiOiJsYXllci0xMCIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL2RhdGEvbG90dXN3b3JrZXIvY2FjaGUvcy10MDEyMjQ5MS00IiwiaWQiOiJsYXllci0xMSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N31dLCJfaCI6bnVsbH19LCJjb25maWciOnsicGF0aCI6Ii9kYXRhL2xvdHVzd29ya2VyL2NhY2hlL3MtdDAxMjI0OTEtNCIsImlkIjoidHJlZS1kIiwic2l6ZSI6MjE0NzQ4MzY0Nywicm93c190b19kaXNjYXJkIjo3fSwiY29tbV9kIjpbNywxMjYsOTUsMjIyLDUzLDE5NywxMCwxNDcsMywxNjUsODAsOSwyMjcsNzMsMTM4LDc4LDE5MCwyMjMsMjQzLDE1Niw2NiwxODMsMTYsMTgzLDQ4LDIxNiwyMzYsMTIyLDE5OSwxNzUsMTY2LDYyXX0=","TicketValue":"eX9i0KroclGvMK4BJjT8wfUsMLjDSs6EcUC9NWhcFMQ=","TicketEpoch":98985}}
3.	2020-07-18 10:05:37 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
4.	2020-07-18 10:05:37 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: maybeSchedRequest didn't find any good workers
5.	2020-07-18 10:06:37 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
6.	2020-07-18 10:06:37 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: maybeSchedRequest didn't find any good workers
7.	2020-07-18 10:07:37 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
8.	2020-07-18 10:07:57 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: handler: websocket connection closed
9.	2020-07-18 10:08:57 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
10.	2020-07-18 10:08:57 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: maybeSchedRequest didn't find any good workers
11.	2020-07-18 10:09:57 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
12.	2020-07-18 10:13:03 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: presealing sector 4 (): Rust panic: no unwind information
13.	2020-07-18 10:14:03 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
14.	2020-07-18 10:16:39 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: presealing sector 4 (): Rust panic: no unwind information
15.	2020-07-18 10:17:39 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
16.	2020-07-18 10:20:01 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: presealing sector 4 (): Rust panic: no unwind information
17.	2020-07-18 10:21:01 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
18.	2020-07-18 10:23:34 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: presealing sector 4 (): Rust panic: no unwind information
19.	2020-07-18 10:24:34 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
20.	2020-07-18 10:27:06 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: presealing sector 4 (): Rust panic: no unwind information
21.	2020-07-18 10:28:06 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
22.	2020-07-18 10:30:27 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: presealing sector 4 (): Rust panic: no unwind information
23.	2020-07-18 10:31:27 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
24.	2020-07-18 10:33:48 +0800 CST:	[event;sealing.SectorSealPreCommit2Failed]	{"User":{}}
	seal pre commit(2) failed: presealing sector 4 (): Rust panic: no unwind information
25.	2020-07-18 10:34:48 +0800 CST:	[event;sealing.SectorRetrySealPreCommit2]	{"User":{}}
```

**Lotus storage miner logs**

```
2020-07-18T10:35:37.712+0800    INFO    main    lotus-storage-miner/run.go:258  Start to pledge 1 sectors
2020-07-18T10:35:37.712+0800    INFO    sectors storage-fsm/garbage.go:96       pending sector numbers %!w([]abi.SectorNumber=[11 8 9])
2020-07-18T10:35:37.712+0800    WARN    advmgr  sector-storage/manager.go:257   stub NewSector
2020-07-18T10:35:37.712+0800    INFO    sectors storage-fsm/garbage.go:25       Pledge {122491 10}, contains []
2020-07-18T10:35:37.714+0800    ERROR   sectors storage-fsm/garbage.go:130      add piece:
    github.com/filecoin-project/storage-fsm.(*Sealing).pledgeSector
        /home/ps/share/ssd/code/test.0.4.1.community/extern/storage-fsm/garbage.go:31
  - maybeSchedRequest didn't find any good workers:
    github.com/filecoin-project/sector-storage.(*scheduler).maybeSchedRequest
        /home/ps/share/ssd/code/test.0.4.1.community/extern/sector-storage/sched.go:293
2020-07-18T10:35:37.714+0800    INFO    sectors storage-fsm/garbage.go:80       pending sector numbers %!w([]abi.SectorNumber=[11 8 9 10])
2020-07-18T10:35:40.807+0800    INFO    dht/RtRefreshManager    rtrefresh/rt_refresh_manager.go:272     finished refreshing cpl 1, routing table size is now 87
2020-07-18T10:36:42.713+0800    INFO    main    lotus-storage-miner/run.go:258  Start to pledge 1 sectors
2020-07-18T10:36:42.713+0800    INFO    sectors storage-fsm/garbage.go:96       pending sector numbers %!w([]abi.SectorNumber=[8 9 10])
2020-07-18T10:36:42.713+0800    WARN    advmgr  sector-storage/manager.go:257   stub NewSector
2020-07-18T10:36:42.713+0800    INFO    sectors storage-fsm/garbage.go:25       Pledge {122491 11}, contains []
2020-07-18T10:36:42.715+0800    ERROR   sectors storage-fsm/garbage.go:130      add piece:
    github.com/filecoin-project/storage-fsm.(*Sealing).pledgeSector
        /home/ps/share/ssd/code/test.0.4.1.community/extern/storage-fsm/garbage.go:31
  - maybeSchedRequest didn't find any good workers:
    github.com/filecoin-project/sector-storage.(*scheduler).maybeSchedRequest
        /home/ps/share/ssd/code/test.0.4.1.community/extern/sector-storage/sched.go:293
2020-07-18T10:36:42.715+0800    INFO    sectors storage-fsm/garbage.go:80       pending sector numbers %!w([]abi.SectorNumber=[8 9 10 11])
```

**Worker Log**
```
2020-07-18T10:22:31.340 INFO filcrypto::proofs::api > generate_data_commitment: start
2020-07-18T10:22:31.340 INFO filecoin_proofs::api::seal > compute_comm_d:start
2020-07-18T10:22:31.340 INFO filecoin_proofs::pieces > verifying 8192 pieces
2020-07-18T10:22:31.341 INFO filecoin_proofs::api::seal > compute_comm_d:finish
2020-07-18T10:22:31.341 INFO filcrypto::proofs::api > generate_data_commitment: finish
2020-07-18T10:22:31.369 INFO filcrypto::proofs::api > seal_pre_commit_phase1: start
2020-07-18T10:22:31.369 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:start
2020-07-18T10:23:17.556 INFO filecoin_proofs::api::seal > building merkle tree for the original data
2020-07-18T10:23:28.022 INFO storage_proofs_porep::stacked::vanilla::proof > persisting base tree_c 1/8 of length 153391689
thread '<unnamed>' panicked at 'failed to flatten and write store: Bad file descriptor (os error 9)', /home/ps/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-4.0.2/src/stacked/vanilla/proof.rs:608:25
stack backtrace:
   0:          0x1a232d4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
   1:          0x1a572dc - core::fmt::write::h5f6d7d8de88b4173
   2:          0x1a14ff3 - <unknown>
   3:          0x1a28105 - <unknown>
   4:          0x1a27e52 - <unknown>
   5:          0x1a28762 - std::panicking::rust_panic_with_hook::h1f2449d529a25f22
   6:          0x1a2834b - rust_begin_unwind
   7:          0x1a53f71 - core::panicking::panic_fmt::h2c05f81b567d1861
   8:          0x1a53be3 - core::result::unwrap_failed::hf55905ddfc1a7715
   9:          0x103ca38 - <unknown>
  10:          0x1a8815c - <unknown>
  11:          0x1a39ac7 - __rust_maybe_catch_panic
  12:          0x12523ec - <unknown>
  13:          0x19a165e - <unknown>
  14:          0x19a26f2 - rayon_core::scope::ScopeBase::steal_till_jobs_complete::h7707e0a042161ca5
  15:          0x1044cab - <unknown>
  16:          0x1a88efe - <unknown>
  17:          0x1a39ac7 - __rust_maybe_catch_panic
  18:          0x1265b50 - <unknown>
  19:          0x19a165e - <unknown>
  20:          0x199fac4 - rayon_core::registry::ThreadBuilder::run::h849c229b1407c068
  21:          0x19a847f - <unknown>
  22:          0x19a205e - <unknown>
  23:          0x1a39ac7 - __rust_maybe_catch_panic
  24:          0x19a87c3 - <unknown>
  25:          0x1a04a9f - <unknown>
  26:          0x1a3840d - <unknown>
  27:     0x7f4f6b8cb6db - <unknown>
  28:     0x7f4f6adc5a3f - clone
  29:                0x0 - <unknown>
thread '<unnamed>' panicked at 'failed to send columns: "SendError(..)"', /home/ps/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-4.0.2/src/stacked/vanilla/proof.rs:528:29
stack backtrace:
   0:          0x1a232d4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
   1:          0x1a572dc - core::fmt::write::h5f6d7d8de88b4173
   2:          0x1a14ff3 - <unknown>
   3:          0x1a28105 - <unknown>
   4:          0x1a27e52 - <unknown>
   5:          0x1a28762 - std::panicking::rust_panic_with_hook::h1f2449d529a25f22
   6:          0x1a2834b - rust_begin_unwind
   7:          0x1a53f71 - core::panicking::panic_fmt::h2c05f81b567d1861
   8:          0x1a53be3 - core::result::unwrap_failed::hf55905ddfc1a7715
   9:          0x102b5cb - <unknown>
  10:          0x1a83c63 - <unknown>
  11:          0x1a39ac7 - __rust_maybe_catch_panic
  12:          0x12505e3 - <unknown>
  13:          0x19a165e - <unknown>
  14:          0x199fac4 - rayon_core::registry::ThreadBuilder::run::h849c229b1407c068
  15:          0x19a847f - <unknown>
  16:          0x19a205e - <unknown>
  17:          0x1a39ac7 - __rust_maybe_catch_panic
  18:          0x19a87c3 - <unknown>
  19:          0x1a04a9f - <unknown>
  20:          0x1a3840d - <unknown>
  21:     0x7f4f6b8cb6db - <unknown>
  22:     0x7f4f6adc5a3f - clone
  23:                0x0 - <unknown>
2020-07-18T10:23:34.890+0800    ^[[33mWARN^[[0m rpc     go-jsonrpc/handler.go:226       error in RPC call to 'Filecoin.SealPreCommit2': presealing sector 4 ():
    github.com/filecoin-project/sector-storage/ffiwrapper.(*Sealer).SealPreCommit2
        /home/ps/share/ssd/code/test.0.4.1.community/extern/sector-storage/ffiwrapper/sealer_cgo.go:492
  - Rust panic: no unwind information
    github.com/filecoin-project/filecoin-ffi.SealPreCommitPhase2
        /home/ps/share/ssd/code/test.0.4.1.community/extern/filecoin-ffi/proofs.go:309
    github.com/filecoin-project/sector-storage/ffiwrapper.(*Sealer).SealPreCommit2
        /home/ps/share/ssd/code/test.0.4.1.community/extern/sector-storage/ffiwrapper/sealer_cgo.go:490
    github.com/filecoin-project/sector-storage.(*LocalWorker).SealPreCommit2
        /home/ps/share/ssd/code/test.0.4.1.community/extern/sector-storage/localworker.go:164
    reflect.Value.call
        /usr/lib/go-1.14/src/reflect/value.go:460
    reflect.Value.Call
        /usr/lib/go-1.14/src/reflect/value.go:321
    github.com/filecoin-project/go-jsonrpc/auth.PermissionedProxy.func1
        /home/ps/share/ssd/code/test.0.4.1.community/extern/go-jsonrpc/auth/auth.go:62
    reflect.callReflect
        /usr/lib/go-1.14/src/reflect/value.go:549
    reflect.makeFuncStub
        /usr/lib/go-1.14/src/reflect/asm_amd64.s:20
    github.com/filecoin-project/lotus/api/apistruct.(*WorkerStruct).SealPreCommit2
        /home/ps/share/ssd/code/test.0.4.1.community/api/apistruct/struct.go:969
    reflect.Value.call
        /usr/lib/go-1.14/src/reflect/value.go:460
    reflect.Value.Call
        /usr/lib/go-1.14/src/reflect/value.go:321
    github.com/filecoin-project/go-jsonrpc.doCall
        /home/ps/share/ssd/code/test.0.4.1.community/extern/go-jsonrpc/handler.go:130
    github.com/filecoin-project/go-jsonrpc.handlers.handle
        /home/ps/share/ssd/code/test.0.4.1.community/extern/go-jsonrpc/handler.go:206
    runtime.goexit
        /usr/lib/go-1.14/src/runtime/asm_amd64.s:1373
2020-07-18T10:24:02.688 INFO filecoin_proofs::api::seal > verifying pieces
2020-07-18T10:24:02.688 INFO filecoin_proofs::pieces > verifying 1 pieces
2020-07-18T10:24:02.688 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase1
2020-07-18T10:24:02.688 INFO storage_proofs_porep::stacked::vanilla::proof > generate labels
2020-07-18T10:24:02.688 INFO storage_proofs_porep::stacked::vanilla::graph > using parent_cache[2048 / 1073741824]
2020-07-18T10:24:02.688 INFO storage_proofs_porep::stacked::vanilla::cache > parent cache: opening /var/tmp/filecoin-parents/v27-sdr-parent-e1fa5d5b811ddbd118be3412c4a8c329156b8b8acc72632bca459455b5a05a13.cache
2020-07-18T10:24:02.688 INFO storage_proofs_porep::stacked::vanilla::cache > parent cache: opened
2020-07-18T10:24:02.688 INFO storage_proofs_porep::stacked::vanilla::proof > generating layer: 1
2020-07-18T10:24:34.018 INFO filcrypto::proofs::api > seal_pre_commit_phase2: start
2020-07-18T10:24:34.018 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:start
2020-07-18T10:24:34.018 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:finish
2020-07-18T10:24:34.018 INFO filecoin_proofs::api::seal > seal_pre_commit_phase2:start
2020-07-18T10:24:34.018 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase2
2020-07-18T10:24:34.018 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree c using the GPU
2020-07-18T10:24:34.018 INFO storage_proofs_porep::stacked::vanilla::proof > Building column hashes
```
**Version**
```
lotus version 0.4.1+git.24d8a84a
```

**Comment by liangping** [comment]
```
2020-08-04T11:02:29.471Z	WARN	rpc	go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/handler.go:226	error in RPC call to 'Filecoin.SealPreCommit2': presealing sector 10 ():
    github.com/filecoin-project/sector-storage/ffiwrapper.(*Sealer).SealPreCommit2
        /home/hu/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200730203805-7153e1dd05b5/ffiwrapper/sealer_cgo.go:478
  - Rust panic: no unwind information
    github.com/filecoin-project/filecoin-ffi.SealPreCommitPhase2
    	/home/hu/go/src/github.com/filecoin-project/lotus/extern/filecoin-ffi/proofs.go:319
    github.com/filecoin-project/sector-storage/ffiwrapper.(*Sealer).SealPreCommit2
    	/home/hu/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200730203805-7153e1dd05b5/ffiwrapper/sealer_cgo.go:476
    github.com/filecoin-project/sector-storage.(*LocalWorker).SealPreCommit2
    	/home/hu/go/pkg/mod/github.com/filecoin-project/sector-storage@v0.0.0-20200730203805-7153e1dd05b5/localworker.go:151
    reflect.Value.call
    	/usr/local/go/src/reflect/value.go:460
    reflect.Value.Call
    	/usr/local/go/src/reflect/value.go:321
    github.com/filecoin-project/go-jsonrpc/auth.PermissionedProxy.func1
    	/home/hu/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/auth/auth.go:62
    reflect.callReflect
    	/usr/local/go/src/reflect/value.go:549
    reflect.makeFuncStub
    	/usr/local/go/src/reflect/asm_amd64.s:20
    github.com/filecoin-project/lotus/api/apistruct.(*WorkerStruct).SealPreCommit2
    	/home/hu/go/src/github.com/filecoin-project/lotus/api/apistruct/struct.go:1103
    reflect.Value.call
    	/usr/local/go/src/reflect/value.go:460
    reflect.Value.Call
    	/usr/local/go/src/reflect/value.go:321
    github.com/filecoin-project/go-jsonrpc.doCall
    	/home/hu/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/handler.go:130
    github.com/filecoin-project/go-jsonrpc.handlers.handle
    	/home/hu/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/handler.go:206
    runtime.goexit
    	/usr/local/go/src/runtime/asm_amd64.s:1373

```
four of my workers had this issue.

**Comment by magik6k** [comment]
> Rust panic: no unwind information

Usually indicates some hardware issue, usually RAM clocks being too high
