### ISSUE TITLE
Miner without standalone seal-worker reports error of `Once has panicked` when compute proof.

### ISSUE THREAD

**Issue by xrdavies** [filecoin-project/lotus#2599]
**Describe the problem**

One miner without standalone seal-worker connecting to lotus node on another machine reports errors of `Once has panicked` while committing.

**Sectors list**

The output of `./lotus-storage-miner sectors list`.
```
./lotus-storage-miner sectors list
0: PreCommit1  sSet: NO pSet: NO tktH: 117867 seedH: 126250 deals: [0]
1: PreCommit1  sSet: NO pSet: NO tktH: 117869 seedH: 126448 deals: [0]
2: PreCommit2  sSet: NO pSet: NO tktH: 117949 seedH: 0      deals: [0]
3: PreCommit2  sSet: NO pSet: NO tktH: 117964 seedH: 0      deals: [0]
4: PreCommit2  sSet: NO pSet: NO tktH: 118388 seedH: 0      deals: [0]
5: PreCommit2  sSet: NO pSet: NO tktH: 118418 seedH: 0      deals: [0]
6: PreCommit1  sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
7: PreCommit2  sSet: NO pSet: NO tktH: 118470 seedH: 0      deals: [0]
8: PreCommit1  sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
9: PreCommit1  sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
10: PreCommit2 sSet: NO pSet: NO tktH: 118527 seedH: 0      deals: [0]
11: PreCommit2 sSet: NO pSet: NO tktH: 118575 seedH: 0      deals: [0]
12: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
13: PreCommit2 sSet: NO pSet: NO tktH: 118623 seedH: 0      deals: [0]
14: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
15: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
16: PreCommit2 sSet: NO pSet: NO tktH: 119159 seedH: 0      deals: [0]
17: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
18: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
19: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
20: PreCommit1 sSet: NO pSet: NO tktH: 118836 seedH: 126348 deals: [0]
21: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
22: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
23: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
24: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
25: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
26: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
27: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
28: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
29: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
30: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
31: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
32: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
33: PreCommit1 sSet: NO pSet: NO tktH: 0      seedH: 0      deals: [0]
```

**Sectors status**

The output of `./lotus-storage-miner sectors status --log <sectorId>` for the failed sector(s).
```
./lotus-storage-miner sectors status --log 0
SectorID:	0
Status:	PreCommit1
CommD:		6261666b3463687a6161353766377872767975666a676135666b61653667736d6b6a32376e37343434696b3372626e7a71336477687672357075793761
CommR:		6261666b3465687a617a61626d6e767773763365756775756a36726d7135663374717037627334666170346135347a72657377626a717a326375726471
Ticket:		62cd5491f6a800ed5aa794e6c159c28b6d9414da17d164dfe425e5ba0a647169
TicketH:		117867
Seed:		fc2c010e487994415b6d6f2ebc99e6903fdcb54ed9714f2c439dee816b677749
SeedH:		126250
Proof:
Deals:		[0]
Retries:		0
--------
Event Log:
0.	2020-07-23 16:47:07 +0800 CST:	[event;sealing.SectorStart]	{"User":{"ID":0,"SectorType":3,"Pieces":[{"Piece":{"Size":34359738368,"PieceCID":{"/":"bafk4chzaa57f7xrvyufjga5fkae6gsmkj27n7444ik3rbnzq3dwhvr5puy7a"}},"DealInfo":null}]}}
1.	2020-07-23 16:47:07 +0800 CST:	[event;sealing.SectorPacked]	{"User":{"FillerPieces":null}}
2.	2020-07-24 04:08:22 +0800 CST:	[event;sealing.SectorPreCommit1]	{"User":{"PreCommit1Out":"eyJyZWdpc3RlcmVkX3Byb29mIjoiU3RhY2tlZERyZzMyR2lCVjEiLCJsYWJlbHMiOnsiU3RhY2tlZERyZzMyR2lCVjEiOnsibGFiZWxzIjpbeyJwYXRoIjoiL3RhbmsxL21hc3Rlci9sb3R1c3N0b3JhZ2UvY2FjaGUvcy10MDEyNTk1Ny0wIiwiaWQiOiJsYXllci0xIiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvdGFuazEvbWFzdGVyL2xvdHVzc3RvcmFnZS9jYWNoZS9zLXQwMTI1OTU3LTAiLCJpZCI6ImxheWVyLTIiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii90YW5rMS9tYXN0ZXIvbG90dXNzdG9yYWdlL2NhY2hlL3MtdDAxMjU5NTctMCIsImlkIjoibGF5ZXItMyIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL3RhbmsxL21hc3Rlci9sb3R1c3N0b3JhZ2UvY2FjaGUvcy10MDEyNTk1Ny0wIiwiaWQiOiJsYXllci00Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvdGFuazEvbWFzdGVyL2xvdHVzc3RvcmFnZS9jYWNoZS9zLXQwMTI1OTU3LTAiLCJpZCI6ImxheWVyLTUiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii90YW5rMS9tYXN0ZXIvbG90dXNzdG9yYWdlL2NhY2hlL3MtdDAxMjU5NTctMCIsImlkIjoibGF5ZXItNiIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL3RhbmsxL21hc3Rlci9sb3R1c3N0b3JhZ2UvY2FjaGUvcy10MDEyNTk1Ny0wIiwiaWQiOiJsYXllci03Iiwic2l6ZSI6MTA3Mzc0MTgyNCwicm93c190b19kaXNjYXJkIjo3fSx7InBhdGgiOiIvdGFuazEvbWFzdGVyL2xvdHVzc3RvcmFnZS9jYWNoZS9zLXQwMTI1OTU3LTAiLCJpZCI6ImxheWVyLTgiLCJzaXplIjoxMDczNzQxODI0LCJyb3dzX3RvX2Rpc2NhcmQiOjd9LHsicGF0aCI6Ii90YW5rMS9tYXN0ZXIvbG90dXNzdG9yYWdlL2NhY2hlL3MtdDAxMjU5NTctMCIsImlkIjoibGF5ZXItOSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL3RhbmsxL21hc3Rlci9sb3R1c3N0b3JhZ2UvY2FjaGUvcy10MDEyNTk1Ny0wIiwiaWQiOiJsYXllci0xMCIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N30seyJwYXRoIjoiL3RhbmsxL21hc3Rlci9sb3R1c3N0b3JhZ2UvY2FjaGUvcy10MDEyNTk1Ny0wIiwiaWQiOiJsYXllci0xMSIsInNpemUiOjEwNzM3NDE4MjQsInJvd3NfdG9fZGlzY2FyZCI6N31dLCJfaCI6bnVsbH19LCJjb25maWciOnsicGF0aCI6Ii90YW5rMS9tYXN0ZXIvbG90dXNzdG9yYWdlL2NhY2hlL3MtdDAxMjU5NTctMCIsImlkIjoidHJlZS1kIiwic2l6ZSI6MjE0NzQ4MzY0Nywicm93c190b19kaXNjYXJkIjo3fSwiY29tbV9kIjpbNywxMjYsOTUsMjIyLDUzLDE5NywxMCwxNDcsMywxNjUsODAsOSwyMjcsNzMsMTM4LDc4LDE5MCwyMjMsMjQzLDE1Niw2NiwxODMsMTYsMTgzLDQ4LDIxNiwyMzYsMTIyLDE5OSwxNzUsMTY2LDYyXX0=","TicketValue":"Ys1UkfaoAO1ap5TmwVnCi22UFNoX0WTf5CXlugpkcWk=","TicketEpoch":117867}}
3.	2020-07-25 19:52:49 +0800 CST:	[event;sealing.SectorRestart]	{"User":{}}
4.	2020-07-25 20:39:50 +0800 CST:	[event;sealing.SectorPreCommit2]	{"User":{"Sealed":{"/":"bafk4ehzazabmnvwsv3euguuj6rmq5f3tqp7bs4fap4a54zreswbjqz2curdq"},"Unsealed":{"/":"bafk4chzaa57f7xrvyufjga5fkae6gsmkj27n7444ik3rbnzq3dwhvr5puy7a"}}}
5.	2020-07-25 20:39:50 +0800 CST:	[event;sealing.SectorPreCommitted]	{"User":{"Message":{"/":"bafy2bzacebkotfjm7cggcwtefq5bbjmwyyskdfcoloiaigdxjtvcwvgnnaoai"}}}
6.	2020-07-25 20:43:17 +0800 CST:	[event;sealing.SectorPreCommitLanded]	{"User":{"TipSet":"AXGg5AIghYPyG2cm3MWR4i7QCW5k7Vms+1ZeIm+GbmeCmWOXieI="}}
7.	2020-07-25 20:53:14 +0800 CST:	[event;sealing.SectorSeedReady]	{"User":{"SeedValue":"/CwBDkh5lEFbbW8uvJnmkD/ctU7ZcU8sQ53ugWtnd0k=","SeedEpoch":126250}}
8.	2020-07-25 22:22:08 +0800 CST:	[event;sealing.SectorComputeProofFailed]	{"User":{}}
	computing seal proof failed(2): Rust panic: Invalid BELLMAN_CUSTOM_GPU!
9.	2020-07-25 22:23:08 +0800 CST:	[event;sealing.SectorRetryComputeProof]	{"User":{}}
10.	2020-07-25 23:21:46 +0800 CST:	[event;sealing.SectorComputeProofFailed]	{"User":{}}
	computing seal proof failed(2): Rust panic: no unwind information
11.	2020-07-25 23:22:46 +0800 CST:	[event;sealing.SectorRetryComputeProof]	{"User":{}}
12.	2020-07-26 00:22:03 +0800 CST:	[event;sealing.SectorComputeProofFailed]	{"User":{}}
	computing seal proof failed(2): Rust panic: no unwind information
13.	2020-07-26 00:23:03 +0800 CST:	[event;sealing.SectorSealPreCommit1Failed]	{"User":{}}
	consecutive compute fails
14.	2020-07-26 00:24:03 +0800 CST:	[event;sealing.SectorRetrySealPreCommit1]	{"User":{}}
```

**Lotus storage miner logs**

```
2020-07-26T01:01:02.694 DEBUG bellperson::gpu::locks > GPU lock released!
2020-07-26T01:01:48.047 INFO bellperson::gpu::locks > GPU is available for Multiexp!
2020-07-26T01:01:48.048 DEBUG bellperson::gpu::locks > Acquiring GPU lock...
2020-07-26T01:01:48.048 DEBUG bellperson::gpu::locks > GPU lock acquired!
thread '<unnamed>' panicked at 'Once has panicked', <::core::macros::panic macros>:2:2
stack backtrace:
   0:          0x2051644 - backtrace::backtrace::libunwind::trace::h5d52ba5f20882f09
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:          0x2051644 - backtrace::backtrace::trace_unsynchronized::hceee092869668a74
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:          0x2051644 - std::sys_common::backtrace::_print_fmt::ha312c2904605e4d5
                               at src/libstd/sys_common/backtrace.rs:78
   3:          0x2051644 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
                               at src/libstd/sys_common/backtrace.rs:59
   4:          0x208564c - core::fmt::write::h5f6d7d8de88b4173
                               at src/libcore/fmt/mod.rs:1063
   5:          0x2043363 - std::io::Write::write_fmt::h893169117de3cc15
                               at src/libstd/io/mod.rs:1426
   6:          0x2056475 - std::sys_common::backtrace::_print::h8ab61d4120f7a335
                               at src/libstd/sys_common/backtrace.rs:62
   7:          0x2056475 - std::sys_common::backtrace::print::h8aae19fbb153bf2a
                               at src/libstd/sys_common/backtrace.rs:49
   8:          0x2056475 - std::panicking::default_hook::{{closure}}::h1ee5b7d8b6f83429
                               at src/libstd/panicking.rs:204
   9:          0x20561c2 - std::panicking::default_hook::hd6c32c13403f9210
                               at src/libstd/panicking.rs:224
  10:          0x2056ad2 - std::panicking::rust_panic_with_hook::h1f2449d529a25f22
                               at src/libstd/panicking.rs:470
  11:          0x20566bb - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:          0x20822e1 - core::panicking::panic_fmt::h2c05f81b567d1861
                               at src/libcore/panicking.rs:85
  13:          0x208222d - core::panicking::panic::h8a9eda1e10298363
                               at src/libcore/panicking.rs:52
  14:          0x1ed5449 - spin::once::Once<T>::call_once::h4e8391177be40625
  15:          0x1ece473 - bellperson::gpu::utils::get_core_count::h3d365472dcf49d56
  16:          0x1b3631c - bellperson::gpu::multiexp::SingleMultiexpKernel<E>::create::hea873edc01980d4b
  17:          0x1a306de - <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::h4023b4410135a6f8
  18:          0x215f447 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h3d93a9febcdcd830
  19:          0x1b3565a - bellperson::gpu::multiexp::MultiexpKernel<E>::create::hce86ff3ae2d2416f
  19:          0x1b3565a - bellperson::gpu::multiexp::MultiexpKernel<E>::create::hce86ff3ae2d2416f
  20:          0x218040c - bellperson::multiexp::create_multiexp_kernel::hc0b1ea8c398a485b
  21:          0x2193583 - bellperson::gpu::locks::LockedMultiexpKernel<E>::init::h9cc4dab3f882cdb2
  22:          0x2193b56 - bellperson::gpu::locks::LockedMultiexpKernel<E>::with::h50979bdcff9015db
  23:          0x2180b04 - bellperson::multiexp::multiexp::he0c4b81143abad7a
  24:          0x19ef602 - <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next::h2120fb8159e7f168
  25:          0x216181c - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h594b4b92e1780a5a
  26:          0x1a1c9af - core::iter::adapters::process_results::h2feac8049456016e
  27:          0x1b3fdc6 - bellperson::groth16::prover::create_proof_batch_priority_inner::hb33aa17087d12ca1
  28:          0x1aa0514 - std::panicking::try::do_call::h87a7803cce8f1bf1
  29:          0x2067e37 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  30:          0x2388191 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h8be91dc5911b8a3f
  31:          0x1fce02e - rayon_core::registry::WorkerThread::wait_until_cold::h18fec92cb756dc34
  32:          0x1fcc69e - rayon_core::registry::ThreadBuilder::run::h0274de327983fafe
  33:          0x1fd5181 - std::sys_common::backtrace::__rust_begin_short_backtrace::h4683d2eea02b6622
  34:          0x1fcece0 - std::panicking::try::do_call::h719c4137fe2a7864
  35:          0x2067e37 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  36:          0x1fd4c17 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hcdea3bbd0e855c0a
  37:          0x2032e0f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h36e46972b1b7f7b7
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/boxed.rs:1017
  38:          0x206677d - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hdde89c32ce6999de
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/boxed.rs:1017
  39:          0x206677d - std::sys_common::thread::start_thread::h5ae3fdd4dad03dd5
                               at src/libstd/sys_common/thread.rs:13
  40:          0x206677d - std::sys::unix::thread::Thread::new::thread_start::h76b2403b2434c4c0
                               at src/libstd/sys/unix/thread.rs:80
  41:     0x7f3c094866db - start_thread
  42:     0x7f3c08f97a3f - __clone
  43:                0x0 - <unknown>
2020-07-26T01:01:48.208 DEBUG bellperson::gpu::locks > GPU lock released!
2020-07-26T01:01:54.079 INFO filcrypto::proofs::api > seal_pre_commit_phase2: start
2020-07-26T01:01:54.081 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:start
2020-07-26T01:01:54.081+0800    ESC[34mINFOESC[0m       sectors storage-fsm@v0.0.0-20200625160832-379a4655b044/states_failed.go:19      ComputeProofFailed(1), waiting 59.918699517s before retrying
```

The output of `lotus-storage-miner info`

```
Miner: t0125957
Sector Size: 32 GiB
Byte Power:   0 B / 32.54 PiB (0.0000%)
Actual Power: 0  / 26.6 Pi (0.0000%)
	Committed: 0 B
	Proving: 0 B
Below minimum power threshold, no blocks will be won
Miner Balance: 0 FIL
	PreCommit:   0 FIL
	Locked:      0 FIL
	Available:   0 FIL
Worker Balance: 99.999999999999961692 FIL
Market (Escrow):  0 FIL
Market (Locked):  0 FIL

Sectors:
	Total: 34
	PreCommit1: 24
	PreCommit2: 9
	ComputeProofFailed: 1
```

**Version**

The output of `./lotus --version` is 
```
./lotus version
Daemon:  0.4.1+git.c459a13d.dirty+api0.6.0
Local: lotus version 0.4.1+git.c459a13d
```

Code version is:
```
git log | head
commit c459a13dcac66941c61b0c67105468e83e1bf873
Merge: f69cce40 b409c8f2
Author: Łukasz Magiera <magik6k@users.noreply.github.com>
Date:   Sat Jul 25 09:54:54 2020 +0200

    Merge pull request #2593 from mgoelzer/paych_get_parse_as_fil

    Parse amount as FIL in paych get

commit b409c8f2beca7b19e29c8854a0f7286e8d730c2a
```

Worker status:
```
Worker 0, host lin-10-0-1-173
	CPU:  [||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||] 32 core(s) in use
	RAM:  [||||                                                            ] 7% 36.21 GiB/503.8 GiB
	VMEM: [|||                                                             ] 6% 36.21 GiB/567.8 GiB
	GPU: GeForce RTX 2080 Ti, used
```

**Comment by xrdavies** [comment]
With ntwk-calibration-7.29.0 still met this issue.

```
2020-07-29T17:46:32.130 INFO bellperson::gpu::locks > GPU is available for Multiexp!
2020-07-29T17:46:32.130 DEBUG bellperson::gpu::locks > Acquiring GPU lock...
2020-07-29T17:46:32.130 DEBUG bellperson::gpu::locks > GPU lock acquired!
thread '<unnamed>' panicked at 'Once has panicked', <::core::macros::panic macros>:2:2
stack backtrace:
   0:          0x2103254 - backtrace::backtrace::libunwind::trace::h5d52ba5f20882f09
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:          0x2103254 - backtrace::backtrace::trace_unsynchronized::hceee092869668a74
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:          0x2103254 - std::sys_common::backtrace::_print_fmt::ha312c2904605e4d5
                               at src/libstd/sys_common/backtrace.rs:78
   3:          0x2103254 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
                               at src/libstd/sys_common/backtrace.rs:59
   4:          0x213725c - core::fmt::write::h5f6d7d8de88b4173
                               at src/libcore/fmt/mod.rs:1063
   5:          0x20f4f73 - std::io::Write::write_fmt::h893169117de3cc15
                               at src/libstd/io/mod.rs:1426
   6:          0x2108085 - std::sys_common::backtrace::_print::h8ab61d4120f7a335
                               at src/libstd/sys_common/backtrace.rs:62
   7:          0x2108085 - std::sys_common::backtrace::print::h8aae19fbb153bf2a
                               at src/libstd/sys_common/backtrace.rs:49
   8:          0x2108085 - std::panicking::default_hook::{{closure}}::h1ee5b7d8b6f83429
                               at src/libstd/panicking.rs:204
   9:          0x2107dd2 - std::panicking::default_hook::hd6c32c13403f9210
                               at src/libstd/panicking.rs:224
  10:          0x21086e2 - std::panicking::rust_panic_with_hook::h1f2449d529a25f22
                               at src/libstd/panicking.rs:470
  11:          0x21082cb - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:          0x2133ef1 - core::panicking::panic_fmt::h2c05f81b567d1861
                               at src/libcore/panicking.rs:85
  13:          0x2133e3d - core::panicking::panic::h8a9eda1e10298363
                               at src/libcore/panicking.rs:52
  14:          0x1f8957c - spin::once::Once<T>::call_once::h1be124493bef654e
  15:          0x1f84964 - bellperson::gpu::utils::get_core_count::hb8f3c3e891270d28
  16:          0x1c5c396 - bellperson::gpu::multiexp::SingleMultiexpKernel<E>::create::h62cbd00dee467cc7
  17:          0x1b7043e - <core::iter::adapters::Map<I,F> as core::iter::traits::iterator::Iterator>::try_fold::h7fae104ab33daefc
  18:          0x21f6dd7 - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::hd39e601b0f91d51c
  19:          0x1c5b49a - bellperson::gpu::multiexp::MultiexpKernel<E>::create::hc950f4c307e848a9
  20:          0x22104ba - bellperson::multiexp::create_multiexp_kernel::h276409585faae49a
  21:          0x22230a3 - bellperson::gpu::locks::LockedMultiexpKernel<E>::init::h9d29b657188b7192
  22:          0x22231c6 - bellperson::gpu::locks::LockedMultiexpKernel<E>::with::h40fedce463337f32
  23:          0x22109b4 - bellperson::multiexp::multiexp::h7c7ee9341e7d2114
  24:          0x1b26cde - <core::iter::adapters::ResultShunt<I,E> as core::iter::traits::iterator::Iterator>::next::h11b59a1d79c32c2e
  25:          0x21eda7c - <alloc::vec::Vec<T> as alloc::vec::SpecExtend<T,I>>::from_iter::h5d80dbd172436068
  26:          0x1b59f44 - core::iter::adapters::process_results::h77ae2ef7a26c98a9
  27:          0x1caf33d - bellperson::groth16::prover::create_proof_batch_priority_inner::ha0cca33ca8388528
  28:          0x1c4d003 - std::panicking::try::do_call::h66a0c79a3fed6388
  29:          0x2119a47 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  30:          0x242cf51 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::he24b834a12337cdc
  31:          0x208187e - rayon_core::registry::WorkerThread::wait_until_cold::h87dae8074bf41112
  32:          0x207fce4 - rayon_core::registry::ThreadBuilder::run::he0cb607c3b57fa19
  33:          0x2088c3f - std::sys_common::backtrace::__rust_begin_short_backtrace::hc565645e4aeea2f2
  34:          0x208225e - std::panicking::try::do_call::h09d367bb9fbacce6
  35:          0x2119a47 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  36:          0x20886a3 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hb3e5f6483e244da4
  37:          0x20e4a1f - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h36e46972b1b7f7b7
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/boxed.rs:1017
  38:          0x211838d - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hdde89c32ce6999de
                               at /rustc/8d69840ab92ea7f4d323420088dd8c9775f180cd/src/liballoc/boxed.rs:1017
  39:          0x211838d - std::sys_common::thread::start_thread::h5ae3fdd4dad03dd5
                               at src/libstd/sys_common/thread.rs:13
  40:          0x211838d - std::sys::unix::thread::Thread::new::thread_start::h76b2403b2434c4c0
                               at src/libstd/sys/unix/thread.rs:80
  41:     0x7efd02cd66db - start_thread
  42:     0x7efd027e7a3f - __clone
  43:                0x0 - <unknown>
2020-07-29T17:46:32.285 DEBUG bellperson::gpu::locks > GPU lock released!

```

**Comment by xrdavies** [comment]
```
# Seal Worker related.
export FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1
export FIL_PROOFS_USE_GPU_TREE_BUILDER=1
export FIL_PROOFS_MAXIMIZE_CACHING=1
export BELLMAN_CUSTOM_GPU="GeForce RTX 2080 Ti"
export RUST_BACKTRACE=full
export RUST_LOG=debug
```

**Comment by xrdavies** [comment]
Update:

Well, after I
```
unset FIL_PROOFS_USE_GPU_TREE_BUILDER
unset BELLMAN_CUSTOM_GPU
```

The error is gone.  @magik6k

**Comment by RobQuistNL** [comment]
It might be because you didn't declare the CUDA core count in your `BELLMAN_CUSTOM_GPU` line. I don't need it for my RTX, and I do have the `FIL_PROOFS_USE_GPU_TREE_BUILDER` enabled.

**Comment by xrdavies** [comment]
@RobQuistNL  Maybe.  I will try it on another machine with 32GiB sectors. Thank you!
