### ISSUE TITLE
sched stuck

### ISSUE THREAD

**Issue by yaohcn** [filecoin-project/lotus#3001]
**Describe the bug**
after run for about one day, tasks not sched anymore. sched stuck there.
worker can not connect to miner, also can not drop a worker(kill a worker, lotus-miner sealing  workers still can see),
 and lotus-miner sealing sched-diag stuck there all the time

**Version (run `lotus version`):**
ntwk-calibration

**Additional context**
one miner and hundreds of workers.
workers have two types, one for P1, another for P2,C1,C2.
some workers not stable, sometimes reconnect after lose connection(restart itself).

**Comment by yaohcn** [comment]
kill -3 pid. Get this log
```shell
goroutine 879 [select, 192 minutes]:
github.com/filecoin-project/sector-storage.(*scheduler).newWorker(0xc0005b2640, 0xc127465970)
        /root/go/pkg/mod/github.com/diancun/sector-storage@v0.0.0-20200810094040-5e8c5b88a7eb/sched.go:634 +0x1e7
github.com/filecoin-project/sector-storage.(*scheduler).runSched(0xc0005b2640)
        /root/go/pkg/mod/github.com/diancun/sector-storage@v0.0.0-20200810094040-5e8c5b88a7eb/sched.go:227 +0x47c
created by github.com/filecoin-project/sector-storage.New
        /root/go/pkg/mod/github.com/diancun/sector-storage@v0.0.0-20200810094040-5e8c5b88a7eb/manager.go:123 +0x69b
```
it stuck in here: https://github.com/filecoin-project/lotus/blob/next/extern/sector-storage/sched.go#L621

can you have a look please? @magik6k
