### ISSUE TITLE
calibration-8.13.1: lotus node panic on retrieval attempt

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#3045]
**Describe the bug**

I tried to retrieve a file I had stored, and failed + the node panicked.

CLI:

```
(TIMESTAMP=`date +%s`; /usr/bin/time timeout -k 11m 10m lotus client retrieve --miner=t01076 bafk2bzaced46oxzzhcm6lagpjo6tvqzayedoykt5prxi4c46wwnimxwc5zuxw /home/lotus1/downloads/t01076-2304-$TIMESTAMP.jpg 2>&1 | tee /home/lotus1/downloads/t01076-2304-$TIMESTAMP.log); sleep 5
> Recv: 0 B, Paid %!s(PANIC=Format method: runtime error: invalid memory address or nil pointer dereference), ClientEventOpen (DealStatusNew)
Success
0.03user 0.00system 0:00.06elapsed 58%CPU (0avgtext+0avgdata 38376maxresident)k
0inputs+0outputs (0major+3585minor)pagefaults 0swaps
```

Node log:

```
2020-08-13T14:58:42.614-0700    ESC[34mINFOESC[0m       markets loggers/loggers.go:24   retrieval event {"name": "ClientEventOpen", "deal ID": "2", "state": "D
ealStatusNew", "message": ""}
panic: send on closed channel

goroutine 597135 [running]:
github.com/filecoin-project/lotus/node/impl/client.(*API).clientRetrieve.func2(0x0, 0xc016542cf0, 0x26, 0x2, 0xc0197f4560, 0x0, 0xc0197f45a0, 0x100000, 0x10000
0, 0xc0197f45c0, ...)
        /home/lotus1/lotus/node/impl/client/client.go:451 +0xd2
github.com/filecoin-project/go-fil-markets/retrievalmarket/impl.dispatcher(0x2798aa0, 0xc0004ffe60, 0x26d72a0, 0xc01e491580, 0x0, 0x0)
        /home/lotus1/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v0.5.5/retrievalmarket/impl/client.go:58 +0x10e
github.com/hannahhoward/go-pubsub.(*PubSub).Publish(0xc0062d01c0, 0x2798aa0, 0xc0004ffe60, 0x0, 0x0)
        /home/lotus1/go/pkg/mod/github.com/hannahhoward/go-pubsub@v0.0.0-20200423002714-8d62886cc36e/pubsub.go:76 +0xd1
github.com/filecoin-project/go-fil-markets/retrievalmarket/impl.(*Client).notifySubscribers(0xc00031ab60, 0x2636980, 0x2d39430, 0x29594c0, 0xc011e1a480)
        /home/lotus1/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v0.5.5/retrievalmarket/impl/client.go:243 +0x178
github.com/filecoin-project/go-statemachine/fsm.fsmHandler.Init.func1(0xc019203740, 0x2dd9f40, 0x29594c0, 0x29977ce, 0x6, 0xc0062a5650, 0xc0062778c0, 0x2da15e0
, 0xc0062d85d0, 0xc0062d8600, ...)
        /home/lotus1/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200730031800-c3336614d2a7/fsm/fsm.go:127 +0x65
created by github.com/filecoin-project/go-statemachine/fsm.fsmHandler.Init
        /home/lotus1/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200730031800-c3336614d2a7/fsm/fsm.go:123 +0x121
```

**Version (run `lotus version`):**

```
Daemon:  0.4.4+git.4c5e9614+api0.10.0
Local: lotus version 0.4.4+git.4c5e9614
```

**Comment by rjan90** [comment]
I don't think the deamon panicks when you try to retrieve a file on newer Lotus-versions? So I think this issue can be closed now? #rengjøring

**Comment by Reiers** [comment]
**Issue outdated.** 

If you are still experiencing problems. Please visit our Discussion forum or ask for help in Slack #fil-lotus-help.
Closing this ticket.
