### ISSUE TITLE
calibration: node crashes when calling StateMinerPower API call repeatedly with badly formatted address

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#3051]
**Describe the bug**

My web client loops over the list of miners to get the power of each. It appears to be triggering the node to crash.

```
2020-08-13T22:14:14.443-0700    ERROR   rpc     go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/server.go:78    RPC Error: unmarshaling params for 'Filecoin.St
ateMinerPower' (param: *address.Address): illegal base32 data at input byte 1
2020-08-13T22:14:14.443-0700    WARN    rpc     go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/server.go:84    rpc error: unmarshaling params for 'Filecoin.St
ateMinerPower' (param: *address.Address): illegal base32 data at input byte 1
panic: runtime error: slice bounds out of range [:-4]

goroutine 519862 [running]:
github.com/filecoin-project/go-address.decode(0xc01a0940d8, 0x5, 0x600, 0x25f99e0, 0xc019deaa30, 0x0)
        /home/lotus1/go/pkg/mod/github.com/filecoin-project/go-address@v0.0.3/address.go:316 +0x7e1
github.com/filecoin-project/go-address.(*Address).UnmarshalJSON(0xc019deaa20, 0xc008831800, 0x7, 0x600, 0x7f01fe3622f0, 0xc019deaa20)
        /home/lotus1/go/pkg/mod/github.com/filecoin-project/go-address@v0.0.3/address.go:122 +0x97
encoding/json.(*decodeState).literalStore(0xc008829788, 0xc008831800, 0x7, 0x600, 0x28bf600, 0xc019deaa20, 0x16, 0x0, 0x7, 0xc0088297b0)
        /usr/local/go/src/encoding/json/decode.go:860 +0x2ac5
encoding/json.(*decodeState).value(0xc008829788, 0x28bf600, 0xc019deaa20, 0x16, 0xc01d864a60, 0x640684)
        /usr/local/go/src/encoding/json/decode.go:384 +0x1de
encoding/json.(*decodeState).unmarshal(0xc008829788, 0x28bf600, 0xc019deaa20, 0x0, 0xc0211bb901)
        /usr/local/go/src/encoding/json/decode.go:180 +0x1f0
encoding/json.(*Decoder).Decode(0xc008829760, 0x28bf600, 0xc019deaa20, 0xc019deaa01, 0x28bf600)
        /usr/local/go/src/encoding/json/stream.go:73 +0x166
github.com/filecoin-project/go-jsonrpc.handlers.handle(0xc00a922600, 0x2daa340, 0xc0211bad00, 0xc019eefe50, 0x3, 0xc019eefe58, 0xc01fc48f40, 0x18, 0xc008801440
, 0x2, ...)
        /home/lotus1/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/handler.go:195 +0x6a7
created by github.com/filecoin-project/go-jsonrpc.(*wsConn).handleCall
        /home/lotus1/go/pkg/mod/github.com/filecoin-project/go-jsonrpc@v0.1.1-0.20200602181149-522144ab4e24/websocket.go:407 +0x295
```

Before the crash, the websocket was getting messages that look like:

```
{"jsonrpc":"2.0","id":124,"error":{"code":-32700,"message":"unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 1"}}
```

It appears this only starts to happen after bunch of successful calls have been made on the websocket. Here are some console logs from my web app.

```
index.js:407 Miner Power t01024
index.js:422 Miner power result, sectors (p/s) t01024 26306674688 undefined undefined
index.js:407 Miner Power t01025
index.js:422 Miner power result, sectors (p/s) t01025 162135015424 undefined undefined
index.js:407 Miner Power t01065
index.js:422 Miner power result, sectors (p/s) t01065 1073741824 undefined undefined
index.js:407 Miner Power t01076
index.js:422 Miner power result, sectors (p/s) t01076 1073741824 undefined undefined
index.js:407 Miner Power t01036
index.js:407 Miner Power t01037
index.js:422 Miner power result, sectors (p/s) t01037 1889785610240 undefined undefined
index.js:407 Miner Power t01045
index.js:422 Miner power result, sectors (p/s) t01045 34359738368 undefined undefined
index.js:407 Miner Power t01046
index.js:422 Miner power result, sectors (p/s) t01046 68719476736 undefined undefined
index.js:407 Miner Power t01051
index.js:422 Miner power result, sectors (p/s) t01051 5463198400512 undefined undefined
index.js:407 Miner Power t01087
index.js:422 Miner power result, sectors (p/s) t01087 60679297957888 undefined undefined
index.js:407 Miner Power t01125
index.js:407 Miner Power t01139
index.js:407 Miner Power t01187
index.js:407 Miner Power t01209
index.js:407 Miner Power t01213
index.js:422 Miner power result, sectors (p/s) t01213 34359738368 undefined undefined
index.js:407 Miner Power t01214
index.js:407 Miner Power t01227
index.js:422 Miner power result, sectors (p/s) t01227 1099511627776 undefined undefined
index.js:407 Miner Power t01229
index.js:422 Miner power result, sectors (p/s) t01229 52076478464 undefined undefined
index.js:407 Miner Power t01231
index.js:407 Miner Power t01235
index.js:422 Miner power result, sectors (p/s) t01235 171798691840 undefined undefined
index.js:407 Miner Power t01238
index.js:407 Miner Power t01259
index.js:407 Miner Power t01269
index.js:407 Miner Power t01290
index.js:422 Miner power result, sectors (p/s) t01290 18790481920 undefined undefined
index.js:407 Miner Power t01294
index.js:407 Miner Power t01299
index.js:407 Miner Power t01313
index.js:407 Miner Power t01315
index.js:407 Miner Power t01318
index.js:407 Miner Power t01332
index.js:422 Miner power result, sectors (p/s) t01332 84825604096 undefined undefined
index.js:407 Miner Power t01363
index.js:407 Miner Power t01412
index.js:407 Miner Power t01413
index.js:422 Miner power result, sectors (p/s) t01413 11274289152 undefined undefined
index.js:407 Miner Power t01038
index.js:422 Miner power result, sectors (p/s) t01038 86586540687360 undefined undefined
index.js:407 Miner Power t01176
index.js:422 Miner power result, sectors (p/s) t01176 52613349376 undefined undefined
index.js:407 Miner Power t01335
index.js:407 Miner Power t1039
index.js:407 Miner Power t1047
index.js:209 Uncaught (in promise) Error: unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 0
    at BrowserProvider.receive (index.js:209)
receive @ index.js:209
index.js:407 Miner Power t1053
index.js:209 Uncaught (in promise) Error: unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 0
    at BrowserProvider.receive (index.js:209)
receive @ index.js:209
index.js:407 Miner Power t1089
index.js:209 Uncaught (in promise) Error: unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 0
    at BrowserProvider.receive (index.js:209)
receive @ index.js:209
index.js:407 Miner Power t1093
index.js:209 Uncaught (in promise) Error: unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 0
    at BrowserProvider.receive (index.js:209)
receive @ index.js:209
index.js:407 Miner Power t1105
index.js:209 Uncaught (in promise) Error: unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 0
    at BrowserProvider.receive (index.js:209)
receive @ index.js:209
index.js:407 Miner Power t1109
index.js:209 Uncaught (in promise) Error: unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 0
    at BrowserProvider.receive (index.js:209)
receive @ index.js:209
index.js:407 Miner Power t1114
index.js:209 Uncaught (in promise) Error: unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 0
    at BrowserProvider.receive (index.js:209)
receive @ index.js:209
index.js:407 Miner Power t1121
index.js:209 Uncaught (in promise) Error: unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 0
    at BrowserProvider.receive (index.js:209)
receive @ index.js:209
index.js:407 Miner Power t1127
index.js:209 Uncaught (in promise) Error: unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 0
    at BrowserProvider.receive (index.js:209)
receive @ index.js:209
index.js:407 Miner Power t1133
index.js:209 Uncaught (in promise) Error: unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 0
    at BrowserProvider.receive (index.js:209)
receive @ index.js:209
index.js:407 Miner Power t1148
index.js:209 Uncaught (in promise) Error: unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 0
    at BrowserProvider.receive (index.js:209)
receive @ index.js:209
index.js:407 Miner Power t1240
index.js:209 Uncaught (in promise) Error: unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 0
    at BrowserProvider.receive (index.js:209)
receive @ index.js:209
index.js:407 Miner Power t1202
index.js:209 Uncaught (in promise) Error: unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 2
    at BrowserProvider.receive (index.js:209)
receive @ index.js:209
index.js:407 Miner Power t1345
index.js:209 Uncaught (in promise) Error: unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 1
    at BrowserProvider.receive (index.js:209)
receive @ index.js:209
```

Notice that there are many successful calls before it starts to fail.

I tried to replicate the condition using `curl` but I can't trigger it ... it might be websocket specific:

```
for m in `lotus state list-miners`; do echo $m; curl -X POST -H 'Content-Type: application/javascript' --data-raw "{\"jsonrpc\": \"2.0\", \"method\": \"Filecoin.StateMinerPower\", \"params\": [\"$m\", [{\"/\":\"bafy2bzacecskk6bq2tpd4ab4vzpapktonvsvmmwwtfbbfue4xzeaqrujikcm2\"},{\"/\":\"bafy2bzacecuejydx7dtsxywv3feoo6w4dcncdbr4wykhxtg6nq2tdwbkjh65i\"}]], \"id\": 1}" http://127.0.0.1:1234/rpc/v0; done
```

The web code that is triggering it is here: https://github.com/jimpick/workshop-client-testnet/blob/calibration/src/06-state-power-miners/index.js

I've been using this code for several months so it appears to be a new regression.

**Version (run `lotus version`):**

```
$ ./lotus version
Daemon:  0.4.4+git.f094273f+api0.10.0
Local: lotus version 0.4.4+git.f094273f
```

**Comment by jimpick** [comment]
Update ... it wasn't due to websockets. I could reproduce it with curl:

```
curl -X POST -H 'Content-Type: application/javascript' --data-raw "{\"jsonrpc\": \"2.0\", \"method\": \"Filecoin.StateMinerPower\", \"params\": [\"t1819\", [{\"/\":\"bafy2bzacecskk6bq2tpd4ab4vzpapktonvsvmmwwtfbbfue4xzeaqrujikcm2\"},{\"/\":\"bafy2bzacecuejydx7dtsxywv3feoo6w4dcncdbr4wykhxtg6nq2tdwbkjh65i\"}]], \"id\": 1}" http://127.0.0.1:1234/rpc/v0
{"jsonrpc":"2.0","id":1,"error":{"code":-32700,"message":"unmarshaling params for 'Filecoin.StateMinerPower' (param: *address.Address): illegal base32 data at input byte 0"}}
```

I made a mistake ... I hand-typed some miner addresses, and that's querying for `t1819` when it should be querying for `t01819`. Doh!

There's still a bug in that I managed to kill my node by passing in a number of these incorrect addresses to the StateMinerPower API call.

**Comment by Reiers** [comment]
Hi @jimpick 

Thanks for the report. The issue is outdated. 

Is this a issue in the current release?

Thank you !
