### ISSUE TITLE
lotus-miner will shutdown when lotus-worker is killed.    panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by askender** [filecoin-project/lotus#3096]
**Describe the bug**
lotus-miner will shutdown when lotus-worker is killed by running `kill pid` .

**To Reproduce**
Kill one of the lotus-worker, the lotus-miner will shutdown too.
It is not always happen. But I believe it is a bug of `sched.go`

**LOGS**
```
2020-08-16T23:59:11.219+0800	DEBUG	advmgr	sector-storage/sched.go:286	SCHED 3 queued; 8 open windows
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdbce93]

goroutine 937 [running]:
github.com/filecoin-project/sector-storage.(*scheduler).trySched(0xc000232a00)
	/home/lb/lotus/extern/sector-storage/sched.go:301 +0x283
github.com/filecoin-project/sector-storage.(*scheduler).runSched(0xc000232a00)
	/home/lb/lotus/extern/sector-storage/sched.go:234 +0x257
created by github.com/filecoin-project/sector-storage.New
	/home/lb/lotus/extern/sector-storage/manager.go:117 +0x643
```

**Version (run `lotus version`):**
lotus version
Daemon:  0.4.5+git.bfc8f9b+api0.11.0
Local: lotus version 0.4.5+git.bfc8f9b

**Comment by magik6k** [comment]
This got fixed
