### ISSUE TITLE
lotus-miner crash 

### ISSUE THREAD

**Issue by irocn** [filecoin-project/lotus#3167]
lotus version 0.4.6+git.009e14b6.dirty

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xde0163]
goroutine 24738 [running]:
github.com/filecoin-project/lotus/extern/sector-storage.(*scheduler).trySched(0xc013c74be0)
        /home/adminroot/workspace/lotus/lotus-src-z/extern/sector-storage/sched.go:301 +0x283
github.com/filecoin-project/lotus/extern/sector-storage.(*scheduler).runSched(0xc013c74be0)
        /home/adminroot/workspace/lotus/lotus-src-z/extern/sector-storage/sched.go:234 +0x257
created by github.com/filecoin-project/lotus/extern/sector-storage.New
        /home/adminroot/workspace/lotus/lotus-src-z/extern/sector-storage/manager.go:119 +0x64c
```

[https://filecoinproject.slack.com/archives/CPFTWMY7N/p1597834918014000](url)

**Comment by magik6k** [comment]
Please reopen if you can still reproduce
