### ISSUE TITLE
lotus daemon crash: "unknown caller pc" from golang GC

### ISSUE THREAD

**Issue by damonhung** [filecoin-project/lotus#3390]
Daemon:  0.5.4+git.d4fef1b5+api0.12.0
Local: lotus version 0.5.4+git.d4fef1b5
System: 3700X, 128GB RAM, single-node rig, LUbuntu 20
go version go1.14.7 linux/amd64

Daemon crashed unexpectedly.  No apparent cause.  Daemon seems fine after restarting (it was down ~25 minutes before I noticed), but miner now has a sector stuck in `Packing`.

The stack trace is weird.  Looks like it died inside the Golang GC:

```
runtime: unexpected return pc for runtime.sigpanic called from 0x173f7e7
stack: frame={sp:0xc0adabb600, fp:0xc0adabb630} stack=[0xc0adab6000,0xc0adabe000)
000000c0adabb500:  000000000054775b <runtime.addOneOpenDeferFrame+123>  000000c0adabb510
000000c0adabb510:  0000000000577cd0 <runtime.addOneOpenDeferFrame.func1+0>  000000000055f4ca <runtime.sigpanic+986>
000000c0adabb520:  000000c0adabb600  000000c023a8ec00
000000c0adabb530:  0000000000000000  000000c0adabb5f0
000000c0adabb540:  0000000000547dec <runtime.gopanic+252>  000000c023a8ec00
000000c0adabb550:  000000000055f4ca <runtime.sigpanic+986>  000000c0adabb600
000000c0adabb560:  0020300500000000  00007f3ff8cf2fff
000000c0adabb570:  00007f3f53cc9d78  4000020000000000
000000c0adabb580:  0000000000000000  000000c0adabb5d0
000000c0adabb590:  000000000052b3be <runtime.(*mcentral).cacheSpan+414>  000000c023a8ec00
000000c0adabb5a0:  0000000000000000  0000000000000008
000000c0adabb5b0:  00002e5200000000  0000000000000000
000000c0adabb5c0:  0000000002747a20  0000000005083170
000000c0adabb5d0:  0000000000000000  0000000000000000
000000c0adabb5e0:  0000000000000000  0000000000000000
000000c0adabb5f0:  000000c0adabb620  000000000055f4ca <runtime.sigpanic+986>
000000c0adabb600: <0000000002747a20  0000000005083170
000000c0adabb610:  0000000002661bc0  000000c0c94798a0
000000c0adabb620:  0000000000000003 !000000000173f7e7
000000c0adabb630: >0000000000203032  0000000000203032
000000c0adabb640:  0000000000000008  000000c015b36000
000000c0adabb650:  0000000000203032  0000000000203002
000000c0adabb660:  0000000000203032  0000000000520096 <runtime.mallocgc+790>
000000c0adabb670:  0000000000203002  0000000000203002
000000c0adabb680:  0000000000203002  00000000027e6880
000000c0adabb690:  000000c0adabb730  0000000000520096 <runtime.mallocgc+790>
000000c0adabb6a0:  000000c0c94798c0  0000000000000020
000000c0adabb6b0:  0000000000000008  0000000000520096 <runtime.mallocgc+790>
000000c0adabb6c0:  000000c00a3b4b00  000000c0adabb710
000000c0adabb6d0:  0000000000744a8d <github.com/filecoin-project/go-bitfield/rle.(*addIt).prep.func1+269>  000000c0c9479840
000000c0adabb6e0:  0000000000000001  0000000000000001
000000c0adabb6f0:  0000000000000000  0000000000000002
000000c0adabb700:  00000000fffffffd  0000000000000008
000000c0adabb710:  0000000000000008  000000000174396e
000000c0adabb720:  0000000000000000  00000000fffffffd
fatal error: unknown caller pc

runtime stack:
runtime.throw(0x29f8c0c, 0x11)
        /usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.gentraceback(0x55f4ca, 0xc0adabb600, 0x0, 0xc023a8ec00, 0x0, 0x0, 0x7fffffff, 0x7f403c8c7ad0, 0x0, 0x0, ...)
        /usr/local/go/src/runtime/traceback.go:273 +0x19fb
runtime.addOneOpenDeferFrame.func1()
        /usr/local/go/src/runtime/panic.go:721 +0x91
runtime.systemstack(0x7f4014000020)
        /usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1041

goroutine 4292 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc0adabb508 sp=0xc0adabb500 pc=0x579600
runtime.addOneOpenDeferFrame(0xc023a8ec00, 0x55f4ca, 0xc0adabb600)
        /usr/local/go/src/runtime/panic.go:720 +0x7b fp=0xc0adabb548 sp=0xc0adabb508 pc=0x54775b
panic(0x2747a20, 0x5083170)
        /usr/local/go/src/runtime/panic.go:929 +0xfc fp=0xc0adabb600 sp=0xc0adabb548 pc=0x547dec
runtime: unexpected return pc for runtime.sigpanic called from 0x173f7e7
stack: frame={sp:0xc0adabb600, fp:0xc0adabb630} stack=[0xc0adab6000,0xc0adabe000)
000000c0adabb500:  000000000054775b <runtime.addOneOpenDeferFrame+123>  000000c0adabb510
000000c0adabb510:  0000000000577cd0 <runtime.addOneOpenDeferFrame.func1+0>  000000000055f4ca <runtime.sigpanic+986>
000000c0adabb520:  000000c0adabb600  000000c023a8ec00
000000c0adabb530:  0000000000000000  000000c0adabb5f0
000000c0adabb540:  0000000000547dec <runtime.gopanic+252>  000000c023a8ec00
000000c0adabb550:  000000000055f4ca <runtime.sigpanic+986>  000000c0adabb600
000000c0adabb560:  0020300500000000  00007f3ff8cf2fff
000000c0adabb570:  00007f3f53cc9d78  4000020000000000
000000c0adabb580:  0000000000000000  000000c0adabb5d0
000000c0adabb590:  000000000052b3be <runtime.(*mcentral).cacheSpan+414>  000000c023a8ec00
000000c0adabb5a0:  0000000000000000  0000000000000008
000000c0adabb5b0:  00002e5200000000  0000000000000000
000000c0adabb5c0:  0000000002747a20  0000000005083170
000000c0adabb5d0:  0000000000000000  0000000000000000
000000c0adabb5e0:  0000000000000000  0000000000000000
000000c0adabb5f0:  000000c0adabb620  000000000055f4ca <runtime.sigpanic+986>
000000c0adabb600: <0000000002747a20  0000000005083170
000000c0adabb610:  0000000002661bc0  000000c0c94798a0
000000c0adabb620:  0000000000000003 !000000000173f7e7
000000c0adabb630: >0000000000203032  0000000000203032
000000c0adabb640:  0000000000000008  000000c015b36000
000000c0adabb650:  0000000000203032  0000000000203002
000000c0adabb660:  0000000000203032  0000000000520096 <runtime.mallocgc+790>
000000c0adabb670:  0000000000203002  0000000000203002
000000c0adabb680:  0000000000203002  00000000027e6880
000000c0adabb690:  000000c0adabb730  0000000000520096 <runtime.mallocgc+790>
000000c0adabb6a0:  000000c0c94798c0  0000000000000020
000000c0adabb6b0:  0000000000000008  0000000000520096 <runtime.mallocgc+790>
000000c0adabb6c0:  000000c00a3b4b00  000000c0adabb710
000000c0adabb6d0:  0000000000744a8d <github.com/filecoin-project/go-bitfield/rle.(*addIt).prep.func1+269>  000000c0c9479840
000000c0adabb6e0:  0000000000000001  0000000000000001
000000c0adabb6f0:  0000000000000000  0000000000000002
000000c0adabb700:  00000000fffffffd  0000000000000008
000000c0adabb710:  0000000000000008  000000000174396e
000000c0adabb720:  0000000000000000  00000000fffffffd
runtime.panicmem(...)
        /usr/local/go/src/runtime/panic.go:212
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:695 +0x3da fp=0xc0adabb630 sp=0xc0adabb600 pc=0x55f4ca
created by github.com/filecoin-project/lotus/chain/events.NewEvents
        /home/moo/lotus/chain/events/events.go:82 +0x560
```

I can attach the rest of the stack dump if you like.

**Comment by Reiers** [comment]
Hi @damonhung 

Thanks for the report. The issue is outdated, and I have not seen reports of this recently. 

For the stuck sector:
`lotus-miner sectors update-state --really-do-it <sectornumb> Packing
`
If the files are there, it should start up again. 

If you encounter this issue in the [current release](https://github.com/filecoin-project/lotus/releases/tag/v1.14.4) - please open a new ticket. Thank you!
