### ISSUE TITLE
Badger: `panic: slice bounds out of range`

### ISSUE THREAD

**Issue by Wondertan** [filecoin-project/lotus#3487]
### Describe the bug
Regular `slice bounds of range` panic that happened within `lotus` app somewhere in the BadgerDS while reading ipfs.Block from the Blockstore. Read was fired by Bitswap.

```
2020-09-02T14:09:21.695Z        ERROR   badger  v2@v2.0.1-rc1.0.20200716180832-3ab515320794/iterator.go:127     Unable to read: Key: [47 98 108 111 99 107 115 47 85 68 83 65 69 73 68 82 76 85 87 53 51 81 66 68 81 87 54 53 76 54 85 78 55 84 54 70 90 54 77 87 72 77 52 68 67 52 85 80 50 90 83 85 67 82 68 54 87 54 88 72 69 77 80 52 68 81], Version : 12944561,
                                meta: 66, userMeta: 0
2020-09-02T14:09:21.695Z        ERROR   engine  decision/blockstoremanager.go:99        blockstore.Get(bafy2bzacebyv2lo5yarylpov7kg7z7c47gldwobrokh5mzkbir7lpltsgh6by) error: Invalid read: Len: 2091 read at:[2219:2232]
2020-09-02T14:09:21.695Z        ERROR   engine  decision/blockstoremanager.go:99        blockstore.Get(bafy2bzacearlkpn2bsruoh5sjkoxmr6vlbjovp6pobwee26mjsbvpyrfplles) error: Invalid read: Len: 2081 read at:[1319797170:1319813231]
panic: runtime error: slice bounds out of range [-6:]

goroutine 901 [running]:
github.com/dgraph-io/badger/v2.(*valueLog).Read(0xc0004fddd0, 0x82e00000093, 0x1fd070d4, 0xc4acf61be0, 0xc601a6e251, 0x520056, 0x486b0a8, 0xc582d7, 0x30, 0x0)
        /root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200716180832-3ab515320794/value.go:1561 +0x858
github.com/dgraph-io/badger/v2.(*Item).yieldItemValue(0xc038a2c8f0, 0x486b0a8, 0xc582d7, 0x0, 0x0, 0xc, 0xc17960e902)
        /root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200716180832-3ab515320794/iterator.go:170 +0x12e
github.com/dgraph-io/badger/v2.(*Item).ValueCopy(0xc038a2c8f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.0.1-rc1.0.20200716180832-3ab515320794/iterator.go:127 +0x179
github.com/ipfs/go-ds-badger2.(*txn).get(0xc00c7e3a80, 0xc17960e870, 0x42, 0xc17960e870, 0x42, 0xc00c7e3a90, 0x56ab49, 0xaa6a0da9f76c)
        /root/go/pkg/mod/github.com/ipfs/go-ds-badger2@v0.1.1-0.20200708190120-187fc06f714e/datastore.go:512 +0xe1
github.com/ipfs/go-ds-badger2.(*Datastore).Get(0xc00048a9c0, 0xc17960e870, 0x42, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/ipfs/go-ds-badger2@v0.1.1-0.20200708190120-187fc06f714e/datastore.go:302 +0x16e
github.com/ipfs/go-ds-measure.(*measure).Get(0xc00017f800, 0xc17960e870, 0x42, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/ipfs/go-ds-measure@v0.1.0/measure.go:198 +0xf5
github.com/ipfs/go-datastore/keytransform.(*Datastore).Get(0xc0001917c0, 0xc0dbed5f00, 0x3b, 0xc0dbed5f00, 0x3b, 0x0, 0x0, 0x1)
        /root/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.4/keytransform/keytransform.go:47 +0x76
github.com/ipfs/go-ipfs-blockstore.(*blockstore).Get(0xc0001917e0, 0xc225619110, 0x26, 0x0, 0x0, 0x0, 0xc00048ac60)
        /root/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v1.0.1/blockstore.go:124 +0xa5
```
### To Reproduce
IDK exactly.

I was just running `lotus` and few `lotus-miner`, then I realized something is broken after not earning power and found out that unfortunately `lotus` panicked 😞.

### Screenshots
<img width="1621" alt="Screen Shot 2020-09-02 at 5 18 27 PM" src="https://user-images.githubusercontent.com/22449364/91996740-ece5fb00-ed6b-11ea-8311-d5ee25f7075c.png">

## Version
```
Daemon:  0.5.7+git.49d64f7f+api0.14.0
Local: lotus version 0.5.7+git.49d64f7f
```

## Additional context
Restarting 'lotus' just helped and I am not receiving that again. However, I am really really sad that this prevented me from sealing lots of sectors 😭

**Comment by jennijuju** [comment]
duplicate #4693
