### ISSUE TITLE
Bad file descriptor crash in PC2

### ISSUE THREAD

**Issue by karalabe** [filecoin-project/lotus#3893]
Not sure what more to produce but the crash dump. Lotus 0.7.0.

```
2020-09-17T07:08:37.208 INFO storage_proofs_porep::stacked::vanilla::proof > persisting base tree_c 1/8 of length 153391689
thread '<unnamed>' panicked at 'failed to flatten and write store: Bad file descriptor (os error 9)', /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.1.1/src/stacked/vanilla/proof.rs:612:25
stack backtrace:
2020-09-17T07:08:37.554 INFO bellperson::gpu::locks > GPU is available for FFT!
2020-09-17T07:08:37.555 WARN bellperson::domain > Cannot instantiate GPU FFT kernel! Error: GPUError: No working GPUs found!
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  15: std::panicking::try::do_call
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  17: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
  18: rayon_core::registry::WorkerThread::wait_until_cold
  19: rayon_core::scope::ScopeBase::steal_till_jobs_complete
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  21: std::panicking::try::do_call
  22: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  23: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute
  24: rayon_core::registry::WorkerThread::wait_until_cold
  25: rayon_core::registry::ThreadBuilder::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread '<unnamed>' panicked at 'failed to send columns: "SendError(..)"', /home/circleci/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.1.1/src/stacked/vanilla/proof.rs:532:29
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::option::expect_none_failed
             at src/libcore/option.rs:1211
  14: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  15: std::panicking::try::do_call
  16: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  17: <rayon_core::job::HeapJob<BODY> as rayon_core::job::Job>::execute
  18: rayon_core::registry::WorkerThread::wait_until_cold
  19: rayon_core::registry::ThreadBuilder::run
```

**Comment by yydfjt** [comment]
Yes， happens after  resstart; maybe PC2 is terminated and leave some files, then rust will panic on retry PC2

**Comment by cryptonemo** [comment]
Make sure that you're not running out of file descriptors and that you set the `ulimit` for open files to be higher than standard if needed.

**Comment by Reiers** [comment]
Hi @karalabe 

Thanks for the report. The issue is outdated, and Im not able to reproduce.
If this is a issue in current release (v1.15.1) - please open a new ticket.
Thank you !
