### ISSUE TITLE
SIGILL error with Intel

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#3920]
Lotus version: 0.7.1
Miners who are using Intel is getting SIGILL error when launching the lotus daemon.

```
2020-09-18T11:16:14.343+0800    INFO    badger  v2@v2.2007.2/value.go:1158      Replaying file id: 0 at offset: 0

2020-09-18T11:16:14.343+0800    INFO    badger  v2@v2.2007.2/value.go:1178      Replay took: 4.995µs

2020-09-18T11:16:14.346+0800    INFO    badger  v2@v2.2007.2/levels.go:183      All 0 tables opened in 0s

2020-09-18T11:16:14.358+0800    INFO    badger  v2@v2.2007.2/value.go:1158      Replaying file id: 0 at offset: 0

2020-09-18T11:16:14.359+0800    INFO    badger  v2@v2.2007.2/value.go:1178      Replay took: 1.653507ms

2020-09-18T11:16:14.421+0800    INFO    p2pnode lp2p/addrs.go:114       Swarm listening at: [/ip6/::1/tcp/39485 /ip4/127.0.0.1/tcp/34165 /ip4/58.220.66.74/tcp/34165 /ip4/172.16.64.10/tcp/34165]
2020-09-18T11:16:14.639+0800    INFO    drand   log/log.go:109          {"level": "info", "optimizing_client": "watching on client", "client": "HTTP(\"https://pl-eu.incentinet.drand.sh/\").(+verifier)"}
2020-09-18T11:16:14.641+0800    INFO    drand   log/log.go:109          {"level": "info", "optimizing_client": "watching on client", "client": "HTTP(\"https://api.drand.sh/\").(+verifier)"}
SIGILL: illegal instruction
PC=0x1868b2e m=33 sigcode=2
instruction bytes: 0xf3 0x4c 0xf 0x38 0xf6 0xcf 0x66 0x4c 0xf 0x38 0xf6 0xd5 0xc4 0xe2 0xc3 0xf6

goroutine 0 [idle]:
runtime: unknown pc 0x1868b2e
stack: frame={sp:0x7fef8bffe888, fp:0x0} stack=[0x7fef8b7fee88,0x7fef8bffea88)
00007fef8bffe788:  000000c0ca517398  000000c0ca518000
00007fef8bffe798:  000000c0ca517000  000000c0ca517000
00007fef8bffe7a8:  000000c0ca518000  0000000000108000
00007fef8bffe7b8:  0000000000b384c6 <github.com/ipfs/go-datastore/query.(*resultsIter).useLegacyResults.func1+166>  0000000100382f25
00007fef8bffe7c8:  00000000010522e4 <github.com/syndtr/goleveldb/leveldb/table.(*indexIter).Get+644>  00000004005f2829
00007fef8bffe7d8:  0000000000000000  0000000000000000
00007fef8bffe7e8:  0000000001042621 <github.com/syndtr/goleveldb/leveldb/iterator.(*indexedIterator).setData+65>  00000000005e6fa6 <time.Date+518>
00007fef8bffe7f8:  000000000103ff64 <github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).Get+996>  00000002005e53bc
00007fef8bffe808:  00000000010439e6 <github.com/syndtr/goleveldb/leveldb/iterator.(*mergedIterator).First+134>  00000001005e857d
00007fef8bffe818:  0000000001054737 <github.com/syndtr/goleveldb/leveldb/table.(*Reader).getDataIterErr+311>  00000002005f3703
00007fef8bffe828:  0000000000000000  0000000000000000
00007fef8bffe838:  0000000000b337db <github.com/jbenet/goprocess.(*process).Go.func1+59>  00000001003804f7
00007fef8bffe848:  0000000000000000  0000000000000000
00007fef8bffe858:  000000000104bf89 <github.com/syndtr/goleveldb/leveldb/cache.(*Cache).Get+649>  00000005005edb57
00007fef8bffe868:  000000000108f07e <github.com/ipfs/go-ds-leveldb.(*accessor).Query.func2+222>  0000000100610353
00007fef8bffe878:  0000000000b3695c <github.com/ipfs/go-datastore/query.(*resultsIter).NextSync+188>  0000000000382276
00007fef8bffe888: <0000000001868aab  89f3fffcfffcfffd
00007fef8bffe898:  dd1882bd1faafa18  00000000005f35c9 <math.cos+73>
00007fef8bffe8a8:  00007fef8bffe8e0  00007fef8bffe910
00007fef8bffe8b8:  0000000002c2e880  0000000002c2eb20
00007fef8bffe8c8:  000000c0ca838000  00000000000000b7
00007fef8bffe8d8:  000000000185dafa  e87e22e2e0f25f84
00007fef8bffe8e8:  6d50e1834e4deb58  6b6ff8cf6624fe91
00007fef8bffe8f8:  86b7b77f7f0154db  a9f6269a3e79502c
00007fef8bffe908:  107b73fa20ec5cc5  e87e22e2e0f25f84
00007fef8bffe918:  6d50e1834e4deb58  6b6ff8cf6624fe91
00007fef8bffe928:  86b7b77f7f0154db  a9f6269a3e79502c
00007fef8bffe938:  107b73fa20ec5cc5  b40938f8081da6b4
00007fef8bffe948:  2761e0468af56a50  193271fce994a0f0
00007fef8bffe958:  79379dc1deb40d8d  95db8325d738090d
00007fef8bffe968:  17ece1fbe906e727  00007fef8bffe990
00007fef8bffe978:  0000000000579bcb <runtime.newAllocBits+43>  000000000000002a
runtime: unknown pc 0x1868b2e
stack: frame={sp:0x7fef8bffe888, fp:0x0} stack=[0x7fef8b7fee88,0x7fef8bffea88)
00007fef8bffe788:  000000c0ca517398  000000c0ca518000
00007fef8bffe798:  000000c0ca517000  000000c0ca517000
00007fef8bffe7a8:  000000c0ca518000  0000000000108000
00007fef8bffe7b8:  0000000000b384c6 <github.com/ipfs/go-datastore/query.(*resultsIter).useLegacyResults.func1+166>  0000000100382f25
00007fef8bffe7c8:  00000000010522e4 <github.com/syndtr/goleveldb/leveldb/table.(*indexIter).Get+644>  00000004005f2829
00007fef8bffe7d8:  0000000000000000  0000000000000000
00007fef8bffe7e8:  0000000001042621 <github.com/syndtr/goleveldb/leveldb/iterator.(*indexedIterator).setData+65>  00000000005e6fa6 <time.Date+518>
00007fef8bffe7f8:  000000000103ff64 <github.com/syndtr/goleveldb/leveldb/util.(*BufferPool).Get+996>  00000002005e53bc
00007fef8bffe808:  00000000010439e6 <github.com/syndtr/goleveldb/leveldb/iterator.(*mergedIterator).First+134>  00000001005e857d
00007fef8bffe818:  0000000001054737 <github.com/syndtr/goleveldb/leveldb/table.(*Reader).getDataIterErr+311>  00000002005f3703
00007fef8bffe828:  0000000000000000  0000000000000000
00007fef8bffe838:  0000000000b337db <github.com/jbenet/goprocess.(*process).Go.func1+59>  00000001003804f7
00007fef8bffe848:  0000000000000000  0000000000000000
00007fef8bffe858:  000000000104bf89 <github.com/syndtr/goleveldb/leveldb/cache.(*Cache).Get+649>  00000005005edb57
00007fef8bffe868:  000000000108f07e <github.com/ipfs/go-ds-leveldb.(*accessor).Query.func2+222>  0000000100610353
00007fef8bffe878:  0000000000b3695c <github.com/ipfs/go-datastore/query.(*resultsIter).NextSync+188>  0000000000382276
00007fef8bffe888: <0000000001868aab  89f3fffcfffcfffd
00007fef8bffe898:  dd1882bd1faafa18  00000000005f35c9 <math.cos+73>
00007fef8bffe8a8:  00007fef8bffe8e0  00007fef8bffe910
00007fef8bffe8b8:  0000000002c2e880  0000000002c2eb20
00007fef8bffe8c8:  000000c0ca838000  00000000000000b7
00007fef8bffe8d8:  000000000185dafa  e87e22e2e0f25f84
00007fef8bffe8e8:  6d50e1834e4deb58  6b6ff8cf6624fe91
00007fef8bffe8f8:  86b7b77f7f0154db  a9f6269a3e79502c
00007fef8bffe908:  107b73fa20ec5cc5  e87e22e2e0f25f84
00007fef8bffe918:  6d50e1834e4deb58  6b6ff8cf6624fe91
00007fef8bffe928:  86b7b77f7f0154db  a9f6269a3e79502c
00007fef8bffe938:  107b73fa20ec5cc5  b40938f8081da6b4
00007fef8bffe948:  2761e0468af56a50  193271fce994a0f0
00007fef8bffe958:  79379dc1deb40d8d  95db8325d738090d
00007fef8bffe968:  17ece1fbe906e727  00007fef8bffe990
00007fef8bffe978:  0000000000579bcb <runtime.newAllocBits+43>  000000000000002a

goroutine 1 [syscall]:
runtime.cgocall(0x18542b0, 0xc000e05b78, 0xc0ca836000)
        /usr/lib/go-1.15/src/runtime/cgocall.go:133 +0x5b fp=0xc000e05b48 sp=0xc000e05b10 pc=0x55339b
github.com/supranational/blst/bindings/go._Cfunc_blst_p2_uncompress(0xc0ca838000, 0xc0ca830001, 0xc000000000)
        _cgo_gotypes.go:694 +0x4d fp=0xc000e05b78 sp=0xc000e05b48 pc=0x119804d
github.com/supranational/blst/bindings/go.(*_Ctype_struct___5).Uncompress(0xc0ca838000, 0xc0ca830001, 0x60, 0x60, 0x25e7fc0)
        /mnt/lotus/marco/extern/fil-blst/blst/bindings/go/blst.go:1598 +0x48 fp=0xc000e05ba0 sp=0xc000e05b78 pc=0x119e668
github.com/supranational/blst/bindings/go.(*_Ctype_struct___5).AggregateVerifyCompressed.func1(0x25e7fc0)
        /mnt/lotus/marco/extern/fil-blst/blst/bindings/go/blst.go:357 +0xc5 fp=0xc000e05be8 sp=0xc000e05ba0 pc=0x11a03e5
github.com/supranational/blst/bindings/go.coreAggregateVerifyPkInG1(0xc000e05d70, 0xc0ca80a2a0, 0xc0ca80e1a0, 0x1, 0x1, 0xc0ca810930, 0x2b, 0x2b, 0xc000e05d6f, 0x1, ...)
        /mnt/lotus/marco/extern/fil-blst/blst/bindings/go/blst.go:461 +0x2a2 fp=0xc000e05d08 sp=0xc000e05be8 pc=0x119a642
github.com/supranational/blst/bindings/go.(*_Ctype_struct___5).AggregateVerifyCompressed(0xc000e05ed8, 0xc0ca830001, 0x60, 0x60, 0xc0ca80e180, 0x1, 0x1, 0xc0ca80e1a0, 0x1, 0x1, ...)

**Comment by jennijuju** [comment]
From Kees: I'm also getting a SIGILL with lotus daemon v0.7.1, using Intel(R) Core(TM) i7-4770K CPU (not compiled with native FFI). See snippet. I'm trrying a snapshot import to see if that resolves the problem.

"optimizing_client": "watch ended", "client": "HTTP(\"https://pl-eu.incentinet.drand.sh/\").(+verifier)"}
2020-09-18T10:14:37.132+0200    WARN    vm  vm/syscalls.go:286  seal verify in batch failed {"miner": "t014386", "index": 0, "err": "invalid proof"}
2020-09-18T10:14:39.365+0200    WARN    vm  vm/runtime.go:295   Abortf: all prove commits failed to validate
2020-09-18T10:14:39.365+0200    WARN    vm  vm/runtime.go:120   VM.Call failure: all prove commits failed to validate (RetCode=16):
    github.com/filecoin-project/specs-actors/actors/builtin/miner.Actor.ConfirmSectorProofsValid
        /home/kees/go/pkg/mod/github.com/filecoin-project/specs-actors@v0.9.10/actors/builtin/miner/miner_actor.go:714
2020-09-18T10:14:39.366+0200    WARN    vm  vm/runtime.go:347   vmctx send failed: to: t014386, method: 17: ret: [], err: all prove commits failed to validate (RetCode=16)
SIGILL: illegal instruction
PC=0x17644ee m=10 sigcode=2

goroutine 0 [idle]:
runtime: unknown pc 0x17644ee
stack: frame={sp:0x7f3187ffe938, fp:0x0} stack=[0x7f31877feec8,0x7f3187ffeac8)
00007f3187ffe838:  0000000000541dd6 <runtime.(*pageAlloc).find+2710>  0000000000000000 
00007f3187ffe848:  0000000000134000  00000000005800d1 <runtime.goexit+1> 
00007f3187ffe858:  00000000000fb047  0000000000000000 
00007f3187ffe868:  0000000000000000  0000000000524c61 <runtime.mallocgc+1137> 
00007f3187ffe878:  000000c0004ab880  0000000000000001 
00007f3187ffe888:  00007f3187ffe8c0  00007f3187ffe8b0 
00007f3187ffe898:  00007ffedfda0918  0000000000000000 
00007f3187ffe8a8:  0000000000000002  00007f3187ffe8d0 
00007f3187ffe8b8:  0000000000581e55 <runtime.nanotime1+101>  0000000000000e29 
00007f3187ffe8c8:  0000000022fb5e30  0000000000ad463c <github.com/jbenet/goprocess.(*process).Go.func1+60> 
00007f3187ffe8d8:  00007f3187ffe928  0000000000555905 <runtime.checkTimers+533> 
00007f3187ffe8e8:  000000c08cd2d800  00007f3187ffe928 
...

**Comment by jennijuju** [comment]
go version go1.14.7 linux/amd64

**Comment by jennijuju** [comment]
may work with `CGO_CFLAGS="-D__BLST_PORTABLE__" make all`
