### ISSUE TITLE
sealing workers,panic: strings: negative Repeat count

### ISSUE THREAD

**Issue by btcioner** [filecoin-project/lotus#3931]
**Describe the bug**

**To Reproduce**
1. Run 'lotus-miner sealing workers'
2. See error
```
Worker 65, host 5d7b62f4957b
        CPU:  [                                                                ] 0 core(s) in use
panic: strings: negative Repeat count

goroutine 1 [running]:
strings.Repeat(0x2b400a8, 0x1, 0xfffffffffffffffc, 0x0, 0x0)
        /snap/go/6439/src/strings/strings.go:529 +0x5e5
main.glob..func36(0xc000520740, 0x0, 0x0)
        /lotus/cmd/lotus-storage-miner/sealing.go:89 +0x947
github.com/urfave/cli/v2.(*Command).Run(0x5139400, 0xc000520640, 0x0, 0x0)
     /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4ed
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000580900, 0xc000520500, 0x0, 0x0)
       /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:427 +0xa9f
github.com/urfave/cli/v2.(*Command).startApp(0x5139760, 0xc000520500, 0x2b45d74, 0x7ffc260986e7)
   /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x6bb
github.com/urfave/cli/v2.(*Command).Run(0x5139760, 0xc000520500, 0x0, 0x0)
    /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:94 +0x9cd
github.com/urfave/cli/v2.(*App).RunContext(0xc000580780, 0x2eccee0, 0xc0000440a0, 0xc00003c180, 0x3, 0x3, 0x0, 0x0)
      /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x81f
github.com/urfave/cli/v2.(*App).Run(...)
  /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
github.com/filecoin-project/lotus/cli.RunApp(0xc000580780)
  /126/lotus/cli/helper.go:34 +0x7c
main.main()
        /126/lotus/cmd/lotus-storage-miner/main.go:105 +0xa12
```
**Expected behavior**

**Screenshots**

**Version (run `lotus version`):**
v0.7.0
**Additional context**

**Comment by askender** [comment]
same issue here:   lotus 0.7.2
```
panic: strings: negative Repeat count

goroutine 1 [running]:
strings.Repeat(0x2b33668, 0x1, 0xfffffffffffffffe, 0x0, 0x0)
	/usr/lib/go-1.14/src/strings/strings.go:533 +0x5a9
main.glob..func36(0xc000179700, 0x0, 0x0)
	/home/xxx/lotus/cmd/lotus-storage-miner/sealing.go:89 +0x903
github.com/urfave/cli/v2.(*Command).Run(0x52d95a0, 0xc000179600, 0x0, 0x0)
	/home/xxx/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000982d80, 0xc0001794c0, 0x0, 0x0)
	/home/xxx/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:427 +0xa68
github.com/urfave/cli/v2.(*Command).startApp(0x52d9900, 0xc0001794c0, 0x7fff18b89612, 0x7)
	/home/xxx/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x68c
github.com/urfave/cli/v2.(*Command).Run(0x52d9900, 0xc0001794c0, 0x0, 0x0)
	/home/xxx/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:94 +0xa12
github.com/urfave/cli/v2.(*App).RunContext(0xc000982c00, 0x2f709a0, 0xc0001b0030, 0xc0001b8000, 0x5, 0x5, 0x0, 0x0)
	/home/xxx/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
	/home/xxx/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
github.com/filecoin-project/lotus/cli.RunApp(0xc000982c00)
	/home/xxx/lotus/cli/helper.go:34 +0x7c
main.main()
	/home/xxx/lotus/cmd/lotus-storage-miner/main.go:105 +0xa26
```
