### ISSUE TITLE
panic: strings: negative Repeat count for sealing workers cmd

### ISSUE THREAD

**Issue by lionsoul2014** [filecoin-project/lotus#3987]
Lotus 0.7.1

Well, for over a month this is the first time i see this error, when i am running: 'lotus-miner sealing workers'
```
panic: strings: negative Repeat count

goroutine 1 [running]:
strings.Repeat(0x2add048, 0x1, 0xffffffffffffffff, 0xc0006b2000, 0x41)
	/usr/local/go/src/strings/strings.go:533 +0x5a9
main.glob..func36(0xc0004ff300, 0x0, 0x0)
	/golang/src/lotus/cmd/lotus-storage-miner/sealing.go:81 +0x73b
github.com/urfave/cli/v2.(*Command).Run(0x543a140, 0xc0004ff200, 0x0, 0x0)
	/golang/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000702d80, 0xc0004ff0c0, 0x0, 0x0)
	/golang/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:427 +0xa68
github.com/urfave/cli/v2.(*Command).startApp(0x543a4a0, 0xc0004ff0c0, 0x7ffe737d0679, 0x7)
	/golang/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x68c
github.com/urfave/cli/v2.(*Command).Run(0x543a4a0, 0xc0004ff0c0, 0x0, 0x0)
	/golang/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:94 +0xa12
github.com/urfave/cli/v2.(*App).RunContext(0xc000702c00, 0x2f14d60, 0xc0000400f8, 0xc00003c180, 0x3, 0x3, 0x0, 0x0)
	/golang/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
	/golang/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
github.com/filecoin-project/lotus/cli.RunApp(0xc000702c00)
	/golang/src/lotus/cli/helper.go:34 +0x7c
main.main()
	/golang/src/lotus/cmd/lotus-storage-miner/main.go:105 +0xa26
```

**Comment by jennijuju** [comment]
Duplicate #3931
