### ISSUE TITLE
lotus-seed pre-seal SIGILL: illegal instruction

### ISSUE THREAD

**Issue by spacetimedevx** [filecoin-project/lotus#4059]
Lotus version: 0.8.0
When I run this command:
lotus-seed pre-seal --sector-size 2048 --num-sectors=2

Env: 
macOS Catalina 10.15.7
MacBook Pro (Reina, 15-inch, Mid 2015)
2.5 GHz 4Core Intel Core i7

2020-09-27T16:50:48.402 INFO filecoin_proofs::api > generate_piece_commitment:start
2020-09-27T16:50:48.419 INFO filecoin_proofs::api > generate_piece_commitment:finish
sector-id: {1000 0}, piece info: {2048 baga6ea4seaqbtkjzuh54s5dwhhwitexwa7zgzf5bgsexvyowhxljfhbibmqlejy}
2020-09-27T16:50:48.424 INFO filcrypto::proofs::api > seal_pre_commit_phase1: start
2020-09-27T16:50:48.424 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:start
2020-09-27T16:50:48.425 INFO filecoin_proofs::api::seal > building merkle tree for the original data
2020-09-27T16:50:48.435 INFO filecoin_proofs::api::seal > verifying pieces
2020-09-27T16:50:48.436 INFO filecoin_proofs::pieces > verifying 1 pieces
2020-09-27T16:50:48.436 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase1
2020-09-27T16:50:48.436 INFO storage_proofs_porep::stacked::vanilla::proof > generate labels
2020-09-27T16:50:48.436 INFO storage_proofs_porep::stacked::vanilla::graph > using parent_cache[64 / 64]
2020-09-27T16:50:48.436 INFO storage_proofs_porep::stacked::vanilla::cache > parent cache: opening /var/tmp/filecoin-parents/v28-sdr-parent-3f0eef38bb48af1f48ad65e14eb85b4ebfc167cec18cd81764f6d998836c9899.cache
2020-09-27T16:50:48.436 INFO storage_proofs_porep::stacked::vanilla::cache > parent cache: opened
2020-09-27T16:50:48.436 INFO storage_proofs_porep::stacked::vanilla::proof > generating layer: 1
2020-09-27T16:50:48.437 INFO storage_proofs_porep::stacked::vanilla::proof >   storing labels on disk
2020-09-27T16:50:48.437 INFO storage_proofs_porep::stacked::vanilla::proof >   generated layer 1 store with id layer-1
2020-09-27T16:50:48.437 INFO storage_proofs_porep::stacked::vanilla::proof >   setting exp parents
2020-09-27T16:50:48.437 INFO storage_proofs_porep::stacked::vanilla::proof > generating layer: 2
2020-09-27T16:50:48.437 INFO storage_proofs_porep::stacked::vanilla::proof >   storing labels on disk
2020-09-27T16:50:48.442 INFO storage_proofs_porep::stacked::vanilla::proof >   generated layer 2 store with id layer-2
2020-09-27T16:50:48.442 INFO storage_proofs_porep::stacked::vanilla::proof >   setting exp parents
2020-09-27T16:50:48.442 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:finish
2020-09-27T16:50:48.442 INFO filcrypto::proofs::api > seal_pre_commit_phase1: finish
2020-09-27T16:50:48.443 INFO filcrypto::proofs::api > seal_pre_commit_phase2: start
2020-09-27T16:50:48.443 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:start
2020-09-27T16:50:48.443 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:finish
2020-09-27T16:50:48.443 INFO filecoin_proofs::api::seal > seal_pre_commit_phase2:start
2020-09-27T16:50:48.443 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase2
2020-09-27T16:50:48.443 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree c using the CPU
2020-09-27T16:50:48.443 INFO storage_proofs_porep::stacked::vanilla::proof > Building column hashes
2020-09-27T16:50:48.453 INFO storage_proofs_porep::stacked::vanilla::proof > building base tree_c 1/1
2020-09-27T16:50:48.498 INFO storage_proofs_porep::stacked::vanilla::proof > tree_c done
2020-09-27T16:50:48.498 INFO storage_proofs_porep::stacked::vanilla::proof > building tree_r_last
2020-09-27T16:50:48.498 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree r last using the CPU
2020-09-27T16:50:48.498 INFO storage_proofs_porep::stacked::vanilla::proof > building base tree_r_last with CPU 1/1
2020-09-27T16:50:48.522 INFO storage_proofs_porep::stacked::vanilla::proof > tree_r_last done
2020-09-27T16:50:48.522 INFO storage_proofs_core::data > dropping data /Users/spacetimedevx/.genesis-sectors/sealed/s-t01000-0
2020-09-27T16:50:48.522 INFO filecoin_proofs::api::seal > seal_pre_commit_phase2:finish
2020-09-27T16:50:48.523 INFO filcrypto::proofs::api > seal_pre_commit_phase2: finish
2020-09-27T16:50:48.523 INFO filecoin_proofs::api::post > clear_cache:start
2020-09-27T16:50:48.524 INFO filecoin_proofs::api::post > clear_cache:finish
2020-09-27T16:50:48.524+0800	WARN	preseal	seed/seed.go:179	PreCommitOutput: {1000 0} bagboea4b5abcb2wilcq34tok4b6rzzdjzsj63siwbl4nqtkw64gmdraphhx2spj5 baga6ea4seaqbtkjzuh54s5dwhhwitexwa7zgzf5bgsexvyowhxljfhbibmqlejy
2020-09-27T16:50:48.525 INFO filecoin_proofs::api > generate_piece_commitment:start
2020-09-27T16:50:48.537 INFO filecoin_proofs::api > generate_piece_commitment:finish
sector-id: {1000 1}, piece info: {2048 baga6ea4seaqhm77zzm5uhouswkyhidhsgxxw3ueyuzbrbwboe4syef5wqi6u6my}
2020-09-27T16:50:48.538 INFO filcrypto::proofs::api > seal_pre_commit_phase1: start
2020-09-27T16:50:48.538 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:start
2020-09-27T16:50:48.539 INFO filecoin_proofs::api::seal > building merkle tree for the original data
2020-09-27T16:50:48.550 INFO filecoin_proofs::api::seal > verifying pieces
2020-09-27T16:50:48.550 INFO filecoin_proofs::pieces > verifying 1 pieces
2020-09-27T16:50:48.551 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase1
2020-09-27T16:50:48.551 INFO storage_proofs_porep::stacked::vanilla::proof > generate labels
2020-09-27T16:50:48.551 INFO storage_proofs_porep::stacked::vanilla::graph > using parent_cache[64 / 64]
2020-09-27T16:50:48.551 INFO storage_proofs_porep::stacked::vanilla::cache > parent cache: opening /var/tmp/filecoin-parents/v28-sdr-parent-3f0eef38bb48af1f48ad65e14eb85b4ebfc167cec18cd81764f6d998836c9899.cache
2020-09-27T16:50:48.551 INFO storage_proofs_porep::stacked::vanilla::cache > parent cache: opened
2020-09-27T16:50:48.551 INFO storage_proofs_porep::stacked::vanilla::proof > generating layer: 1
2020-09-27T16:50:48.551 INFO storage_proofs_porep::stacked::vanilla::proof >   storing labels on disk
2020-09-27T16:50:48.552 INFO storage_proofs_porep::stacked::vanilla::proof >   generated layer 1 store with id layer-1
2020-09-27T16:50:48.552 INFO storage_proofs_porep::stacked::vanilla::proof >   setting exp parents
2020-09-27T16:50:48.552 INFO storage_proofs_porep::stacked::vanilla::proof > generating layer: 2
2020-09-27T16:50:48.552 INFO storage_proofs_porep::stacked::vanilla::proof >   storing labels on disk
2020-09-27T16:50:48.557 INFO storage_proofs_porep::stacked::vanilla::proof >   generated layer 2 store with id layer-2
2020-09-27T16:50:48.557 INFO storage_proofs_porep::stacked::vanilla::proof >   setting exp parents
2020-09-27T16:50:48.557 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:finish
2020-09-27T16:50:48.557 INFO filcrypto::proofs::api > seal_pre_commit_phase1: finish
2020-09-27T16:50:48.557 INFO filcrypto::proofs::api > seal_pre_commit_phase2: start
2020-09-27T16:50:48.557 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:start
2020-09-27T16:50:48.557 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:finish
2020-09-27T16:50:48.557 INFO filecoin_proofs::api::seal > seal_pre_commit_phase2:start
2020-09-27T16:50:48.557 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase2
2020-09-27T16:50:48.557 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree c using the CPU
2020-09-27T16:50:48.557 INFO storage_proofs_porep::stacked::vanilla::proof > Building column hashes
2020-09-27T16:50:48.558 INFO storage_proofs_porep::stacked::vanilla::proof > building base tree_c 1/1
2020-09-27T16:50:48.570 INFO storage_proofs_porep::stacked::vanilla::proof > tree_c done
2020-09-27T16:50:48.571 INFO storage_proofs_porep::stacked::vanilla::proof > building tree_r_last
2020-09-27T16:50:48.571 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree r last using the CPU
2020-09-27T16:50:48.571 INFO storage_proofs_porep::stacked::vanilla::proof > building base tree_r_last with CPU 1/1
2020-09-27T16:50:48.591 INFO storage_proofs_porep::stacked::vanilla::proof > tree_r_last done
2020-09-27T16:50:48.591 INFO storage_proofs_core::data > dropping data /Users/spacetimedevx/.genesis-sectors/sealed/s-t01000-1
2020-09-27T16:50:48.591 INFO filecoin_proofs::api::seal > seal_pre_commit_phase2:finish
2020-09-27T16:50:48.592 INFO filcrypto::proofs::api > seal_pre_commit_phase2: finish
2020-09-27T16:50:48.592 INFO filecoin_proofs::api::post > clear_cache:start
2020-09-27T16:50:48.593 INFO filecoin_proofs::api::post > clear_cache:finish
2020-09-27T16:50:48.593+0800	WARN	preseal	seed/seed.go:179	PreCommitOutput: {1000 1} bagboea4b5abcbizj4yep4le66hr37n7hqqnlbshzvjodsvdglhkwp7iw3qcxr5tl baga6ea4seaqhm77zzm5uhouswkyhidhsgxxw3ueyuzbrbwboe4syef5wqi6u6my
SIGILL: illegal instruction
PC=0x495ae17 m=0 sigcode=1

goroutine 0 [idle]:
runtime: unknown pc 0x495ae17
stack: frame={sp:0x7ffeefbff5f8, fp:0x0} stack=[0x7ffeefb80808,0x7ffeefbff870)
00007ffeefbff4f8:  0000000000000000  00007ffeefbff740
00007ffeefbff508:  0000000000000000  0000000000000000
00007ffeefbff518:  00007ffeefbff700  00007ffeefbff650
00007ffeefbff528:  9b05688c510e527f  00007ffeefbff650
00007ffeefbff538:  00007ffeefbff700  00007ffeefbff740
00007ffeefbff548:  000000000494d93f  bb67ae856a09e667
00007ffeefbff558:  00007ffeefbff700  00007ffeefbff700
00007ffeefbff568:  0000000000000018  00007ffeefbff678
00007ffeefbff578:  00007ffeefbff650  00007ffeefbff5c0
00007ffeefbff588:  000000000494d851  0000000000000002
00007ffeefbff598:  00007ffeefbff650  00007ffeefbff5d0
00007ffeefbff5a8:  0000000000000000  00007ffeefbff780
00007ffeefbff5b8:  00007ffeefbff700  00007ffeefbff630
00007ffeefbff5c8:  000000000493c932  0000000000023000
00007ffeefbff5d8:  000000000493c821  00007ffeefbff678
00007ffeefbff5e8:  00007ffeefbff760  00007ffeefbff6c0
00007ffeefbff5f8: <000000000495ad39  aac4647bdb490014
00007ffeefbff608:  000000000619cc80  fffffffeffffffff
00007ffeefbff618:  00007ffeefbff740  0000000000000000
00007ffeefbff628:  000000c0000361e0  00007ffeefbff800
00007ffeefbff638:  000000000493c5c2  000000c0000361e0
00007ffeefbff648:  0000004800362085  2c34ac54f226cd13
00007ffeefbff658:  0457411c7266c9f5  0ffed9cc91c8af48
00007ffeefbff668:  361f6a78e03f398a  0000000000000063
00007ffeefbff678:  05301e357c33082b  e3c01b7de17a50fe
00007ffeefbff688:  e58d9865e5c74522  919f77a613895c43
00007ffeefbff698:  0000000080023000  0000000000000000
00007ffeefbff6a8:  0000000000000000  1803000000000000
00007ffeefbff6b8:  0000000000000023  41d32213969feba8
00007ffeefbff6c8:  dbbdc9837fa292d2  a0c8e2dd70808b38
00007ffeefbff6d8:  68f88aeacb78f535  4599639097618496
00007ffeefbff6e8:  e961e9a41540d6ff  c433e14ccb226b58
runtime: unknown pc 0x495ae17
stack: frame={sp:0x7ffeefbff5f8, fp:0x0} stack=[0x7ffeefb80808,0x7ffeefbff870)
00007ffeefbff4f8:  0000000000000000  00007ffeefbff740
00007ffeefbff508:  0000000000000000  0000000000000000
00007ffeefbff518:  00007ffeefbff700  00007ffeefbff650
00007ffeefbff528:  9b05688c510e527f  00007ffeefbff650
00007ffeefbff538:  00007ffeefbff700  00007ffeefbff740
00007ffeefbff548:  000000000494d93f  bb67ae856a09e667
00007ffeefbff558:  00007ffeefbff700  00007ffeefbff700
00007ffeefbff568:  0000000000000018  00007ffeefbff678
00007ffeefbff578:  00007ffeefbff650  00007ffeefbff5c0
00007ffeefbff588:  000000000494d851  0000000000000002
00007ffeefbff598:  00007ffeefbff650  00007ffeefbff5d0
00007ffeefbff5a8:  0000000000000000  00007ffeefbff780
00007ffeefbff5b8:  00007ffeefbff700  00007ffeefbff630
00007ffeefbff5c8:  000000000493c932  0000000000023000
00007ffeefbff5d8:  000000000493c821  00007ffeefbff678
00007ffeefbff5e8:  00007ffeefbff760  00007ffeefbff6c0
00007ffeefbff5f8: <000000000495ad39  aac4647bdb490014
00007ffeefbff608:  000000000619cc80  fffffffeffffffff
00007ffeefbff618:  00007ffeefbff740  0000000000000000
00007ffeefbff628:  000000c0000361e0  00007ffeefbff800
00007ffeefbff638:  000000000493c5c2  000000c0000361e0
00007ffeefbff648:  0000004800362085  2c34ac54f226cd13
00007ffeefbff658:  0457411c7266c9f5  0ffed9cc91c8af48
00007ffeefbff668:  361f6a78e03f398a  0000000000000063
00007ffeefbff678:  05301e357c33082b  e3c01b7de17a50fe
00007ffeefbff688:  e58d9865e5c74522  919f77a613895c43
00007ffeefbff698:  0000000080023000  0000000000000000
00007ffeefbff6a8:  0000000000000000  1803000000000000
00007ffeefbff6b8:  0000000000000023  41d32213969feba8
00007ffeefbff6c8:  dbbdc9837fa292d2  a0c8e2dd70808b38
00007ffeefbff6d8:  68f88aeacb78f535  4599639097618496
00007ffeefbff6e8:  e961e9a41540d6ff  c433e14ccb226b58

goroutine 1 [syscall]:
runtime.cgocall(0x493bbe0, 0xc0009477c8, 0x41b3e01)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc000947798 sp=0xc000947760 pc=0x4005a4b
github.com/supranational/blst/bindings/go._Cfunc_blst_keygen(0xc0000361e0, 0xc0000361c0, 0x20, 0x0, 0x0)
	_cgo_gotypes.go:300 +0x45 fp=0xc0009477c8 sp=0xc000947798 pc=0x4922d05
github.com/supranational/blst/bindings/go.KeyGen(0xc0000361c0, 0x20, 0x20, 0x0, 0x0, 0x0, 0xe86814c3)
	/Users/spacetimedevx/WorkSpace/EclipseGo/lotus/extern/fil-blst/blst/bindings/go/blst.go:79 +0x96 fp=0xc000947808 sp=0xc0009477c8 pc=0x4924d96
github.com/filecoin-project/lotus/lib/sigs/bls.blsSigner.GenPrivate(0xc000497368, 0x9e9fa4bb0db85301, 0x9e00000000000010, 0x0, 0xc000497360)
	/Users/spacetimedevx/WorkSpace/EclipseGo/lotus/lib/sigs/bls/init.go:32 +0xeb fp=0xc000947868 sp=0xc000947808 pc=0x492e18b
github.com/filecoin-project/lotus/lib/sigs/bls.(*blsSigner).GenPrivate(0x63ce0f0, 0xc0004a2ea0, 0xc0009478df, 0xc000497370, 0xc00003c501, 0x63a3b40)
	<autogenerated>:1 +0x33 fp=0xc0009478a0 sp=0xc000947868 pc=0x492e943
github.com/filecoin-project/lotus/lib/sigs.Generate(0xc000947902, 0x404cbde, 0xc0000a0840, 0xc000478020, 0x8, 0xc0000a0840)
	/Users/spacetimedevx/WorkSpace/EclipseGo/lotus/lib/sigs/sigs.go:58 +0x6d fp=0xc000947900 sp=0xc0009478a0 pc=0x46cd92d
github.com/filecoin-project/lotus/chain/wallet.GenerateKey(0x56ade02, 0xc000478020, 0x1, 0x1)
	/Users/spacetimedevx/WorkSpace/EclipseGo/lotus/chain/wallet/wallet.go:187 +0x2e fp=0xc000947978 sp=0xc000947900 pc=0x4932fee
github.com/filecoin-project/lotus/cmd/lotus-seed/seed.PreSeal(0xc0004ee08d, 0x3, 0x0, 0x0, 0x2, 0xc0004e0330, 0x22, 0xc000947c70, 0xd, 0x20, ...)
	/Users/spacetimedevx/WorkSpace/EclipseGo/lotus/cmd/lotus-seed/seed/seed.go:96 +0xd58 fp=0xc000947bb0 sp=0xc000947978 pc=0x49342e8
main.glob..func4(0xc0000dbb80, 0x8, 0xe)
	/Users/spacetimedevx/WorkSpace/EclipseGo/lotus/cmd/lotus-seed/main.go:136 +0x369 fp=0xc000947ce8 sp=0xc000947bb0 pc=0x493a719
github.com/urfave/cli/v2.(*Command).Run(0x6391160, 0xc0000db900, 0x0, 0x0)
	/Users/spacetimedevx/WorkSpace/EclipseGo/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4e0 fp=0xc000947dc8 sp=0xc000947ce8 pc=0x42357d0
github.com/urfave/cli/v2.(*App).RunContext(0xc00008aa80, 0x5b0d9e0, 0xc0000bc008, 0xc0000be000, 0x5, 0x5, 0x0, 0x0)
	/Users/spacetimedevx/WorkSpace/EclipseGo/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814 fp=0xc000947ef0 sp=0xc000947dc8 pc=0x4232e44
github.com/urfave/cli/v2.(*App).Run(...)
	/Users/spacetimedevx/WorkSpace/EclipseGo/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
	/Users/spacetimedevx/WorkSpace/EclipseGo/lotus/cmd/lotus-seed/main.go:53 +0x299 fp=0xc000947f88 sp=0xc000947ef0 pc=0x4938099
runtime.main()
	/usr/local/go/src/runtime/proc.go:203 +0x1fa fp=0xc000947fe0 sp=0xc000947f88 pc=0x4037e6a
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc000947fe8 sp=0xc000947fe0 pc=0x4065bb1

goroutine 19 [select]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc0000a3e30)
	/Users/spacetimedevx/WorkSpace/EclipseGo/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:71 +0x128
created by github.com/ipfs/go-log/writer.NewMirrorWriter
	/Users/spacetimedevx/WorkSpace/EclipseGo/pkg/mod/github.com/ipfs/go-log@v1.0.4/writer/writer.go:36 +0xb9

goroutine 20 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000e8480)
	/Users/spacetimedevx/WorkSpace/EclipseGo/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:276 +0x100
created by go.opencensus.io/stats/view.init.0
	/Users/spacetimedevx/WorkSpace/EclipseGo/pkg/mod/go.opencensus.io@v0.22.4/stats/view/worker.go:34 +0x68

rax    0xbaa707ac9d80d4bb
rbx    0x619cca0
rcx    0x619cc00
rdx    0x2b6cedcb87925c23
rdi    0xc0000361e0
rsi    0xc000036160
rbp    0x536f1da67922dccb
rsp    0x7ffeefbff5f8
r8     0xfffffffeffffffff
r9     0x2af591067ab8cb96
r10    0xe2d9cd0e627f2b45
r11    0xb456c3df878012bf
r12    0xcdd6a691cd9a4962
r13    0xac434713cd989184
r14    0x4d49e28b6ab86439
r15    0x0
rip    0x495ae17
rflags 0x10246
cs     0x2b
fs     0x0
gs     0x0

**Comment by spacetimedevx** [comment]
go version
go version go1.14.9 darwin/amd64

cargo version
cargo 1.46.0 (149022b1d 2020-07-17)

**Comment by jehunter5811** [comment]
I experience this even when trying to add the env variable for `CGO_CFLAGS`. 

I am on a 2015 Macbook Pro: 

2.5 GHz Quad-Core Intel Core i7 
16 GB 1600 MHz DDR3

**Comment by jehunter5811** [comment]
Update: 

To get around this, you need to set a couple of env variables BEFORE running `make 2k`: 

`export CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"`

Then: 

`export CGO_CFLAGS="-D__BLST_PORTABLE__"`

**Comment by jennijuju** [comment]
tested and worked, closing

**Comment by spacetimedevx** [comment]
It is OK now, Thank you very much!

**Comment by autocatalytic** [comment]
This fix worked for me as well, thanks!

```
$ lotus version
Daemon:  1.2.1+git.d15d9b0fb+api1.0.0
Local: lotus version 1.2.1+git.d15d9b0fb
$ go version
go version go1.15.5 linux/amd64

$ hostnamectl
  Operating System: Ubuntu 20.04.1 LTS
            Kernel: Linux 5.4.0-31-generic
      Architecture: x86-64
```
