### ISSUE TITLE
Socket hang up when client invoke ClientRetrieve 

### ISSUE THREAD

**Issue by liangping** [filecoin-project/lotus#4158]
**Describe the bug**
Socket hang up when client invoke ClientRetrieve. then lotus daemon is killed.

**To Reproduce**
1. send a request from remote.
```
{
  "jsonrpc": "2.0",
  "method": "Filecoin.ClientRetrieve",
  "params": [
    {
        "Root": {
            "/": "bafykbzacecvhk3fojr3rhjnyfrgjsw4kgaaqu23yuvpmwybtg2f56ul7dhrze"
        },
        "Piece": null,
        "Size": 134217728,
        "MinPrice": "268435456",
        "UnsealPrice": "0",
        "PaymentInterval": 1048576,
        "PaymentIntervalIncrease": 1048576,
        "Miner": "t03300",
        "MinerPeer": {
            "Address": "t03339",
            "ID": "12D3KooWHQS12TnY9Bc7ipZNtgRtCcNp2qbHbUtJn6dPTsKyHbcQ",
            "PieceCID": null
        }
    },
    {
    "Path": "/root/test.data",
    "IsCAR": false
    }
  ],
  "id": 1
}
```
2.  show error in web client side:
```
Error: socket hang up
```
3. show error in server side:
```
2020-10-05T00:43:26.547Z        INFO    drand   log/log.go:109          {"level": "info", "optimizing_client": "watching on client", "client": "HTTP(\"https://api2.drand.sh/\").(+verifier)"}
2020-10-05T00:43:26.547Z        INFO    drand   log/log.go:109          {"level": "info", "optimizing_client": "watch ended", "client": "HTTP(\"https://api3.drand.sh/\").(+verifier)"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x66783f]

goroutine 54166888 [running]:
math/big.(*Int).QuoRem(0xc0ed8ca700, 0x0, 0xc0ed8ca6e0, 0xc0f9d65b50, 0x0, 0x0)
        /usr/local/go/src/math/big/int.go:239 +0x5f
math/big.(*Int).Div(0xc0ed8ca700, 0x0, 0xc0ed8ca6e0, 0xc0ed8ca6e0)
        /usr/local/go/src/math/big/int.go:250 +0x6a
github.com/filecoin-project/lotus/chain/types.BigDiv(0x0, 0xc0ed8ca6e0, 0xc0ae0b0a50)
        /root/lotus/chain/types/bigint.go:47 +0x67
github.com/filecoin-project/lotus/node/impl/client.(*API).clientRetrieve(0xc0005b18a0, 0x2fb38c0, 0xc0ae0b0570, 0xc0ca595e90, 0x26, 0x0, 0x8000000, 0x0, 0xc0ed8ca5a0, 0x100000, ...)
        /root/lotus/node/impl/client/client.go:540 +0x29e
created by github.com/filecoin-project/lotus/node/impl/client.(*API).ClientRetrieve
        /root/lotus/node/impl/client/client.go:429 +0xdc
```

**Expected behavior**
Return the Retrieval deal information.

**Screenshots**

**Version (run `lotus version`):**
lotus version 0.8.1+git.0fee5dab

**Additional context**

**Comment by Reiers** [comment]
Hi @liangping 

Thanks for the report. The issue is outdated, and the retrieval is much better now. [v1.15.1 ](https://github.com/filecoin-project/lotus/releases/tag/v1.15.1)

If you encounter this issue again - please open a new ticket.

Thank you !
