### ISSUE TITLE
Invalid memory address or nil pointer dereference in tipset.go

### ISSUE THREAD

**Issue by jennijuju** [filecoin-project/lotus#4358]
lotus version 0.10.0

```bash
"https://api.drand.sh/\").(+verifier)"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1164aec]
goroutine 1 [running]:
github.com/filecoin-project/lotus/chain/types.(*TipSet).Cids(...)
        /lotus/chain/types/tipset.go:140
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).TipSetState(0xc00017c700, 0x3138280, 0xc1a3f8c030, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /lotus/chain/stmgr/stmgr.go:145 +0x10c
github.com/filecoin-project/lotus/chain/messagepool.(*mpoolProvider).GetActorAfter(0xc1a3b55da0, 0xc026fcc180, 0x31, 0x0, 0x61, 0x0, 0x0)
        /lotus/chain/messagepool/provider.go:50 +0x57
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).getStateNonce(0xc1a3b3e2c0, 0xc026fcc180, 0x31, 0x0, 0xc026fd2070, 0x30f3f40, 0xc026fd4000)
        /lotus/chain/messagepool/messagepool.go:794 +0x56
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).addLoaded(0xc1a3b3e2c0, 0xc026fd2000, 0x0, 0x0)
        /lotus/chain/messagepool/messagepool.go:673 +0xf0
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).loadLocal(0xc1a3b3e2c0, 0xc1a3b55df0, 0x0)
        /lotus/chain/messagepool/messagepool.go:1267 +0x308
github.com/filecoin-project/lotus/chain/messagepool.New(0x3152900, 0xc1a3b55da0, 0x3152960, 0xc1a0c9d0b0, 0x2cdd07b, 0xa, 0x3128fc0, 0xc17d477900, 0xc000368b60, 0x70, ...)
        /lotus/chain/messagepool/messagepool.go:371 +0x817
github.com/filecoin-project/lotus/node/modules.MessagePool(0x30f7e00, 0xc000598f58, 0xc00017c700, 0xc027315800, 0x3152960, 0xc1a0c9d0b0, 0x2cdd07b, 0xa, 0x3128fc0, 0xc17d477900, ...)
        /lotus/node/modules/chain.go:57 +0xbd
reflect.Value.call(0x2a46a60, 0x2e90b30, 0x13, 0x2cd387b, 0x4, 0xc1a1926d80, 0x6, 0x6, 0x203068, 0x5265b6, ...)
        /usr/local/go/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x2a46a60, 0x2e90b30, 0x13, 0xc1a1926d80, 0x6, 0x6, 0x10, 0x10, 0xc1a3b55d90)
        /usr/local/go/src/reflect/value.go:321 +0xb4
github.com/filecoin-project/lotus/node.as.func2(0xc1a1926d80, 0x6, 0x6, 0xc1a1926d80, 0xc0007aedd0, 0x2abdfa0)
        /lotus/node/options.go:140 +0xf0
reflect.callReflect(0xc0004d79b0, 0xc000892ac8, 0xc000892ab0)
        /usr/local/go/src/reflect/value.go:549 +0x322
reflect.makeFuncStub(0x30f7e00, 0xc000598f58, 0xc00017c700, 0xc027315800, 0x3152960, 0xc1a0c9d0b0, 0x2cdd07b, 0xa, 0x3128fc0, 0xc17d477900, ...)
        /usr/local/go/src/reflect/asm_amd64.s:20 +0x42
reflect.Value.call(0x2a46a60, 0xc0004d79b0, 0x13, 0x2cd387b, 0x4, 0xc1a1926cf0, 0x6, 0x6, 0x10, 0xc1a3b55d50, ...)
        /usr/local/go/src/reflect/value.go:460 +0x8ab
reflect.Value.Call(0x2a46a60, 0xc0004d79b0, 0x13, 0xc1a1926cf0, 0x6, 0x6, 0x2ab6980, 0x2c12501, 0xc1a3b55d50)
        /usr/local/go/src/reflect/value.go:321 +0xb4
go.uber.org/dig.defaultInvoker(0x2a46a60, 0xc0004d79b0, 0x13, 0xc1a1926cf0, 0x6, 0x6, 0xc0001142d0, 0xc1a1926cf0, 0x6)
        /root/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:284 +0x64
go.uber.org/dig.(*node).Call(0xc000974500, 0x3152f60, 0xc0001142d0, 0x316c9a0, 0x2ca9180)
        /root/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:710 +0x269
go.uber.org/dig.paramSingle.Build(0x0, 0x0, 0x0, 0x316c9a0, 0x2ca9180, 0x3152f60, 0xc0001142d0, 0x2c96720, 0xc1a1911d28, 0x96, ...)
        /root/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:245 +0x2e0
go.uber.org/dig.paramList.BuildList(0x316c9a0, 0x2a12ea0, 0xc1a40222a0, 0x6, 0x6, 0x3152f60, 0xc0001142d0, 0x0, 0x0, 0x58cd42, ...)
        /root/go/pkg/mod/go.uber.org/dig@v1.10.0/param.go:201 +0xb8
go.uber.org/dig.(*Container).Invoke(0xc0001142d0, 0x2a12ea0, 0x2e90b18, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/go.uber.org/dig@v1.10.0/dig.go:432 +0x2ba
go.uber.org/fx.(*App).executeInvokes(0xc0007b8370, 0x2945f40, 0xc00080dca0)
        /root/go/pkg/mod/go.uber.org/fx@v1.9.0/app.go:547 +0x368
go.uber.org/fx.New(0xc0005d1650, 0x3, 0x3, 0xc00061db80)
        /root/go/pkg/mod/go.uber.org/fx@v1.9.0/app.go:345 +0x4a8
github.com/filecoin-project/lotus/node.New(0x3138280, 0xc000702d50, 0xc000114050, 0x9, 0x9, 0x0, 0x0, 0x0)
        /lotus/node/builder.go:576 +0x47c
main.glob..func3(0xc000108fc0, 0x0, 0x0)
        /lotus/cmd/lotus/daemon.go:267 +0xe0d
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000601380, 0xc000108580, 0x0, 0x0)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:432 +0x993
github.com/urfave/cli/v2.(*Command).startApp(0x5560de0, 0xc000108580, 0x7ffdea4b554a, 0x6)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x68c
github.com/urfave/cli/v2.(*Command).Run(0x5560de0, 0xc000108580, 0x0, 0x0)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:94 +0xa12
github.com/urfave/cli/v2.(*App).RunContext(0xc000601200, 0x3138200, 0xc00003e0c0, 0xc00000e080, 0x2, 0x2, 0x0, 0x0)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).Run(...)
        /root/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
github.com/filecoin-project/lotus/cli.RunApp(0xc000601200)
        /lotus/cli/helper.go:34 +0x7c
main.main()
        /lotus/cmd/lotus/main.go:74 +0x649

```

**Comment by Stebalien** [comment]
Are you seeing nay other errors/warnings? Anything with "loading chain state from disk".

**Comment by Stebalien** [comment]
This could happen if `chain.Load()` fails in:

https://github.com/filecoin-project/lotus/blob/d5cea9f402b0af085859c8ce10a81193bfbe9ba6/node/modules/chain.go#L95-L97

Which will cause us to fail to set `cs.heaviest` here:

https://github.com/filecoin-project/lotus/blob/d5cea9f402b0af085859c8ce10a81193bfbe9ba6/chain/store/store.go#L215

Which will cause `GetHeaviestTipSet` to return nil:

https://github.com/filecoin-project/lotus/blob/d5cea9f402b0af085859c8ce10a81193bfbe9ba6/chain/store/store.go#L633-L637

Which will cause `SubscribeHeadChanges` to return nil:

https://github.com/filecoin-project/lotus/blob/d5cea9f402b0af085859c8ce10a81193bfbe9ba6/chain/messagepool/provider.go#L36-L39

Which can cause `curTs` to be initialized to nil:

https://github.com/filecoin-project/lotus/blob/d5cea9f402b0af085859c8ce10a81193bfbe9ba6/chain/messagepool/messagepool.go#L363-L369

Which could cause us to read `nil` here:

https://github.com/filecoin-project/lotus/blob/d5cea9f402b0af085859c8ce10a81193bfbe9ba6/chain/messagepool/messagepool.go#L671-L673
