### ISSUE TITLE
v0.10.1 lotus daemon panic error

### ISSUE THREAD

**Issue by kenshyx** [filecoin-project/lotus#4394]
**Describe the bug**

**To Reproduce**
1. Upgrade to v0.10.1 from v0.10.0 on an intel machine. I've built lotus in 3 different ways( CGO_CFLAGS="-D__BLST_PORTABLE__", native and just simple make clean install).
2. Start the lotus daemon.
3. It panics when it tries to resume data transfer from an existing deal.

**Expected behavior**
To start syncing 

**Screenshots**
```
Oct 14 15:21:32 stor lotus[44531]: 2020-10-14T15:21:32.095+0200        INFO        storagemarket_impl        clientstates/client_states.go:146        restarting data transfer for deal deal bafyreietvpyhlsv5eeld5v6alqlayd5ipdujope2jfgcctcrrvzttikh4y
Oct 14 15:21:32 stor lotus[44531]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 14 15:21:32 stor lotus[44531]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1777d3d]
Oct 14 15:21:32 stor lotus[44531]: goroutine 21436 [running]:
Oct 14 15:21:32 stor lotus[44531]: github.com/filecoin-project/go-fil-markets/storagemarket/impl/clientstates.RestartDataTransfer(0x7f063c9083e0, 0xc0efa10240, 0x7f063c908408, 0xc172d0e1c8, 0xc01f97cff0, 0x27, 0x2000000, 0x0, 0xc08d116000, 0x31, ...)
Oct 14 15:21:32 stor lotus[44531]:         /home/kenny/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v0.9.0/storagemarket/impl/clientstates/client_states.go:151 +0xed
Oct 14 15:21:32 stor lotus[44531]: reflect.Value.call(0x29c2020, 0x2e97178, 0x13, 0x2cd9152, 0x4, 0xc16dfc9710, 0x3, 0x3, 0x5250cf, 0x2b6cda0, ...)
Oct 14 15:21:32 stor lotus[44531]:         /usr/local/go/src/reflect/value.go:460 +0x8ab
Oct 14 15:21:32 stor lotus[44531]: reflect.Value.Call(0x29c2020, 0x2e97178, 0x13, 0xc16e5f8710, 0x3, 0x3, 0x1, 0x0, 0x7f54a624ec01)
Oct 14 15:21:32 stor lotus[44531]:         /usr/local/go/src/reflect/value.go:321 +0xb4
Oct 14 15:21:32 stor lotus[44531]: github.com/filecoin-project/go-statemachine/fsm.fsmHandler.handler.func1(0xc16c00dda0, 0x2, 0x2, 0xc16c00dda0, 0xc16e5f8b48, 0x756ea18d0e18a0)
Oct 14 15:21:32 stor lotus[44531]:         /home/kenny/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/fsm/fsm.go:170 +0x424
Oct 14 15:21:32 stor lotus[44531]: reflect.callReflect(0xc16c00dd40, 0xc16dfc99e0, 0xc16dfc99c8)
Oct 14 15:21:32 stor lotus[44531]:         /usr/local/go/src/reflect/value.go:549 +0x322
Oct 14 15:21:32 stor lotus[44531]: reflect.makeFuncStub(0x31446e0, 0xc00003e080, 0xc17196ba90, 0xc01f97cff0, 0x27, 0x2000000, 0x0, 0xc08d116000, 0x31, 0xc1721d1c70, ...)
Oct 14 15:21:32 stor lotus[44531]:         /usr/local/go/src/reflect/asm_amd64.s:20 +0x42
Oct 14 15:21:32 stor lotus[44531]: reflect.Value.call(0xc16dfda0c0, 0xc16c00dd40, 0x13, 0x2cd9152, 0x4, 0xc16e5f8f70, 0x2, 0x2, 0x5250cf, 0x2a9e520, ...)
Oct 14 15:21:32 stor lotus[44531]:         /usr/local/go/src/reflect/value.go:460 +0x8ab
Oct 14 15:21:32 stor lotus[44531]: reflect.Value.Call(0xc16dfda0c0, 0xc16c00dd40, 0x13, 0xc16dbe5f70, 0x2, 0x2, 0x12, 0x0, 0x100000000000000)
Oct 14 15:21:32 stor lotus[44531]:         /usr/local/go/src/reflect/value.go:321 +0xb4
Oct 14 15:21:32 stor lotus[44531]: github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc17196b9f0, 0x31446e0, 0xc00003e080, 0xc17196ba90, 0xc17196ba00, 0xc16ea57200)
Oct 14 15:21:32 stor lotus[44531]:         /home/kenny/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:102 +0x2bf
Oct 14 15:21:32 stor lotus[44531]: created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
Oct 14 15:21:32 stor lotus[44531]:         /home/kenny/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:100 +0x3da
```

**Version (run `lotus version`):*v0.10.1*

**Additional context**
I've rollbacked to v0.10.0 and it's working now for me

**Comment by kenshyx** [comment]
This issue was fixed in [v0.10.2](https://github.com/filecoin-project/lotus/releases/tag/v0.10.2 )
