### ISSUE TITLE
fil-blst/blst/bindings/go/blst.go:1598  took SIGILL: illegal instruction

### ISSUE THREAD

**Issue by marco-storswift** [filecoin-project/lotus#4416]
**Describe the bug**
miner is crashed

**To Reproduce**
1. Run 'miner run'
2. See error 

**Expected behavior**

**Screenshots**
2020-10-15T15:06:58.121+0800    INFO    markets loggers/loggers.go:19   storage event   {"name": "ProviderEventOpen", "proposal CID": "bafyreiaj4pnjycjmrdsorno4lnmf47zhhuk664lc6oikotwvkuxff2p6pe", "state": "StorageDealValidating", "message": ""}
SIGILL: illegal instruction
PC=0x1a3202e m=46 sigcode=2
instruction bytes: 0xf3 0x4c 0xf 0x38 0xf6 0xcf 0x66 0x4c 0xf 0x38 0xf6 0xd5 0xc4 0xe2 0xc3 0xf6

goroutine 0 [idle]:
runtime: unknown pc 0x1a3202e
stack: frame={sp:0x7efa7d7f98c8, fp:0x0} stack=[0x7efa7cff9ec8,0x7efa7d7f9ac8)
00007efa7d7f97c8:  0000000000000000  0000000000000000
00007efa7d7f97d8:  0000000000000000  0000000000000000
00007efa7d7f97e8:  0000000000000000  0000000000000000
00007efa7d7f97f8:  0000000000000000  0000000000000000
00007efa7d7f9808:  0000000000000000  0000000000000000
00007efa7d7f9818:  0000000000000000  0000000000000000
00007efa7d7f9828:  0000000000000000  0000000000000000
00007efa7d7f9838:  0000000000000000  0000000000000000
00007efa7d7f9848:  0000000000000000  0000000000000000
00007efa7d7f9858:  0000000000000000  0000000000000000
00007efa7d7f9868:  0000000000000000  0000000000000000
00007efa7d7f9878:  0000000000000000  0000000000000000
00007efa7d7f9888:  0000000000000000  0000000000000000
00007efa7d7f9898:  0000000000000000  0000000000000000
00007efa7d7f98a8:  0000000000000000  0000000000000000
00007efa7d7f98b8:  0000000000000000  0000000000000000
00007efa7d7f98c8: <0000000001a31fab  89f3fffcfffcfffd
00007efa7d7f98d8:  e5f644a3b77d60dc  0000000000000000
00007efa7d7f98e8:  00007efa7d7f9920  00007efa7d7f9950
00007efa7d7f98f8:  0000000002eb6c20  0000000002eb6ec0
00007efa7d7f9908:  000000c01ff483c0  0000000000000084
00007efa7d7f9918:  0000000001a2700a  9f1d06261b0894ba
00007efa7d7f9928:  9d436d093f4d2c35  5db45632b5dc5052
00007efa7d7f9938:  71dec9507cdced3f  839794daec683cd2
00007efa7d7f9948:  18a8c0e84f93d4b5  9f1d06261b0894ba
00007efa7d7f9958:  9d436d093f4d2c35  5db45632b5dc5052
00007efa7d7f9968:  71dec9507cdced3f  839794daec683cd2
00007efa7d7f9978:  18a8c0e84f93d4b5  51d234073f5ba704
00007efa7d7f9988:  a9265c1983f04ab2  1fb90403f9fb8928
00007efa7d7f9998:  9371f4abf6a50da7  97b2a30c2eb98815
00007efa7d7f99a8:  044d10bc30f6ac1c  0000000000000000
00007efa7d7f99b8:  0000000000000000  0000000000000001
runtime: unknown pc 0x1a3202e
stack: frame={sp:0x7efa7d7f98c8, fp:0x0} stack=[0x7efa7cff9ec8,0x7efa7d7f9ac8)
00007efa7d7f97c8:  0000000000000000  0000000000000000
00007efa7d7f97d8:  0000000000000000  0000000000000000
00007efa7d7f97e8:  0000000000000000  0000000000000000
00007efa7d7f97f8:  0000000000000000  0000000000000000
00007efa7d7f9808:  0000000000000000  0000000000000000
00007efa7d7f9818:  0000000000000000  0000000000000000
00007efa7d7f9828:  0000000000000000  0000000000000000
00007efa7d7f9838:  0000000000000000  0000000000000000
00007efa7d7f9848:  0000000000000000  0000000000000000
00007efa7d7f9858:  0000000000000000  0000000000000000
00007efa7d7f9868:  0000000000000000  0000000000000000
00007efa7d7f9878:  0000000000000000  0000000000000000
00007efa7d7f9888:  0000000000000000  0000000000000000
00007efa7d7f9898:  0000000000000000  0000000000000000
00007efa7d7f98a8:  0000000000000000  0000000000000000
00007efa7d7f98b8:  0000000000000000  0000000000000000
00007efa7d7f98c8: <0000000001a31fab  89f3fffcfffcfffd
00007efa7d7f98d8:  e5f644a3b77d60dc  0000000000000000
00007efa7d7f98e8:  00007efa7d7f9920  00007efa7d7f9950
00007efa7d7f98f8:  0000000002eb6c20  0000000002eb6ec0
00007efa7d7f9908:  000000c01ff483c0  0000000000000084
00007efa7d7f9918:  0000000001a2700a  9f1d06261b0894ba
00007efa7d7f9928:  9d436d093f4d2c35  5db45632b5dc5052
00007efa7d7f9938:  71dec9507cdced3f  839794daec683cd2
00007efa7d7f9948:  18a8c0e84f93d4b5  9f1d06261b0894ba
00007efa7d7f9958:  9d436d093f4d2c35  5db45632b5dc5052
00007efa7d7f9968:  71dec9507cdced3f  839794daec683cd2
00007efa7d7f9978:  18a8c0e84f93d4b5  51d234073f5ba704
00007efa7d7f9988:  a9265c1983f04ab2  1fb90403f9fb8928
00007efa7d7f9998:  9371f4abf6a50da7  97b2a30c2eb98815
00007efa7d7f99a8:  044d10bc30f6ac1c  0000000000000000
00007efa7d7f99b8:  0000000000000000  0000000000000001

goroutine 198149 [syscall]:
runtime.cgocall(0x1a1d7c0, 0xc015b547b8, 0xc01114bd40)
        /app/go/src/runtime/cgocall.go:133 +0x5b fp=0xc015b54788 sp=0xc015b54750 pc=0x555f7b
github.com/supranational/blst/bindings/go._Cfunc_blst_p2_uncompress(0xc01ff483c0, 0xc0177697a1, 0xc000000000)
        _cgo_gotypes.go:694 +0x4d fp=0xc015b547b8 sp=0xc015b54788 pc=0x132f38d
github.com/supranational/blst/bindings/go.(*_Ctype_struct___5).Uncompress(0xc01ff483c0, 0xc0177697a1, 0x60, 0x60, 0x2808420)
        /mnt/lotus/marco/extern/fil-blst/blst/bindings/go/blst.go:1598 +0x48 fp=0xc015b547e0 sp=0xc015b547b8 pc=0x13359a8
github.com/supranational/blst/bindings/go.(*_Ctype_struct___5).AggregateVerifyCompressed.func1(0x2808420)
        /mnt/lotus/marco/extern/fil-blst/blst/bindings/go/blst.go:357 +0xc5 fp=0xc015b54828 sp=0xc015b547e0 pc=0x1337725
github.com/supranational/blst/bindings/go.coreAggregateVerifyPkInG1(0xc015b549b0, 0xc01a09c420, 0xc017a458c0, 0x1, 0x1, 0xc012404450, 0x2b, 0x2b, 0xc015b549af, 0x1, ...)
        /mnt/lotus/marco/extern/fil-blst/blst/bindings/go/blst.go:461 +0x2a2 fp=0xc015b54948 sp=0xc015b54828 pc=0x1331982
github.com/supranational/blst/bindings/go.(*_Ctype_struct___5).AggregateVerifyCompressed(0xc015b54b18, 0xc0177697a1, 0x60, 0x60, 0xc017a458a0, 0x1, 0x1, 0xc017a458c0, 0x1, 0x1, ...)
        /mnt/lotus/marco/extern/fil-blst/blst/bindings/go/blst.go:383 +0x1a5 fp=0xc015b549e0 sp=0xc015b54948 pc=0x1331665
github.com/supranational/blst/bindings/go.(*_Ctype_struct___5).VerifyCompressed(0xc015b54b18, 0xc0177697a1, 0x60, 0x60, 0xc0124043f0, 0x30, 0x30, 0xc0110c6780, 0xbe, 0x168, ...)
        /mnt/lotus/marco/extern/fil-blst/blst/bindings/go/blst.go:296 +0x225 fp=0xc015b54a80 sp=0xc015b549e0 pc=0x1331125
github.com/filecoin-project/lotus/lib/sigs/bls.blsSigner.Verify(0xc0177697a1, 0x60, 0x60, 0xc0242a2ac0, 0x31, 0xc0110c6780, 0xbe, 0x168, 0x0, 0xc000550dc0)
        /mnt/lotus/marco/lib/sigs/bls/init.go:53 +0x19d fp=0xc015b54bf0 sp=0xc015b54a80 pc=0x133a17d
github.com/filecoin-project/lotus/lib/sigs/bls.(*blsSigner).Verify(0x51fb550, 0xc0177697a1, 0x60, 0x60, 0xc0242a2ac0, 0x31, 0xc0110c6780, 0xbe, 0x168, 0xc0242a2ac0, ...)
        <autogenerated>:1 +0x9d fp=0xc015b54c50 sp=0xc015b54bf0 pc=0x133a65d
github.com/filecoin-project/lotus/lib/sigs.Verify(0xc015b54d48, 0xc0242a2ac0, 0x31, 0xc0110c6780, 0xbe, 0x168, 0x0, 0xc0242a2ac0)
        /mnt/lotus/marco/lib/sigs/sigs.go:48 +0xf9 fp=0xc015b54cc8 sp=0xc015b54c50 pc=0x1197099
github.com/filecoin-project/lotus/markets/storageadapter.(*ProviderNodeAdapter).VerifySignature(0xc00069b100, 0x2e4cb40, 0xc0001ac018, 0x2, 0xc0177697a1, 0x60, 0x60, 0xc01e7a2900, 0x31, 0xc0110c6780, ...)
        /mnt/lotus/marco/markets/storageadapter/provider.go:155 +0xff fp=0xc015b54d30 sp=0xc015b54cc8 pc=0x18552bf
github.com/filecoin-project/go-fil-markets/storagemarket.StorageProviderNode.VerifySignature-fm(0x2e4cb40, 0xc0001ac018, 0x7efc78519902, 0xc0177697a1, 0x60, 0x60, 0xc01e7a2900, 0x31, 0xc0110c6780, 0xbe, ...)
        /home/fil/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v0.9.1/storagemarket/nodes.go:73 +0xf9 fp=0xc015b54dd0 sp=0xc015b54d30 pc=0x15dba59

**Version (run `lotus version`):**
miner version 0.10.2
Intel(R) Xeon(R) CPU E5-2678 v3 @ 2.50GHz

**Additional context**
2020-10-15T15:06:58.121+0800    INFO    markets loggers/loggers.go:19   storage event   {"name": "ProviderEventOpen", "proposal CID": "bafyreiaj4pnjycjmrdsorno4lnmf47zhhuk664lc6oikotwvkuxff2p6pe", "state": "StorageDealValidating", "message": ""}

**Comment by marco-storswift** [comment]
export CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"
export CGO_CFLAGS="-D__BLST_PORTABLE__"
