### ISSUE TITLE
Panic in full node

### ISSUE THREAD

**Issue by mgoelzer** [filecoin-project/lotus#4693]
**Describe the bug**
My lotus full node (daemon) panicked over night and terminated.  The panic was on an out of bounds array access.  We should probably investigate this and/or put some bounds checks in.

**To Reproduce**
I don't know how to reproduce, but I have the full log.

Here's the very end of the log with the panic:

```
2020-11-01T23:54:00.273Z        ^[[31mERROR^[[0m        engine  decision/blockstoremanager.go:99        blockstore.Get(bafy2bzacebfg2jc5aqijvnkwqleppbh6vglps2it222qc2ajdrq2r3qrxidrq) error: Invalid read: Len: 2098 read at:[897683:897721]
panic: runtime error: slice bounds out of range [-10:]

goroutine 1342 [running]:
github.com/dgraph-io/badger/v2.(*header).Decode(0xc04c9936f8, 0x7f6615b7a7b6, 0x838, 0x65881848, 0x7f6615b7a7b6)
        /home/ubuntu/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/structs.go:105 +0x169
github.com/dgraph-io/badger/v2.(*valueLog).Read(0xc0008499d0, 0x838000000e2, 0x1a77e7b6, 0xc2a7246c00, 0x527f90, 0x5145a11, 0x1298edf, 0x4a, 0xc252673220, 0x7fa4c2117e40)
        /home/ubuntu/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/value.go:1584 +0x145
github.com/dgraph-io/badger/v2.(*Item).yieldItemValue(0xc17f4b9130, 0x5145a11, 0x1298edf, 0x0, 0x0, 0xc, 0xc252673212)
        /home/ubuntu/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/iterator.go:170 +0x135
github.com/dgraph-io/badger/v2.(*Item).ValueCopy(0xc17f4b9130, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.2/iterator.go:127 +0x17e
github.com/ipfs/go-ds-badger2.(*txn).get(0xc04c993a70, 0xc252673130, 0x42, 0x0, 0x0, 0xc04c993a80, 0x587b9b, 0xdc9192d03ff5)
        /home/ubuntu/go/pkg/mod/github.com/ipfs/go-ds-badger2@v0.1.1-0.20200708190120-187fc06f714e/datastore.go:512 +0xe5
github.com/ipfs/go-ds-badger2.(*Datastore).Get(0xc000211380, 0xc252673130, 0x42, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/ipfs/go-ds-badger2@v0.1.1-0.20200708190120-187fc06f714e/datastore.go:302 +0x170
github.com/ipfs/go-ds-measure.(*measure).Get(0xc0002c0f00, 0xc252673130, 0x42, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/ubuntu/go/pkg/mod/github.com/ipfs/go-ds-measure@v0.1.0/measure.go:198 +0xf5
github.com/ipfs/go-datastore/keytransform.(*Datastore).Get(0xc000481ca0, 0xc04ef7ca00, 0x3b, 0xc04ef7ca00, 0x3b, 0x0, 0x0, 0x1)
        /home/ubuntu/go/pkg/mod/github.com/ipfs/go-datastore@v0.4.5/keytransform/keytransform.go:47 +0x76
github.com/ipfs/go-ipfs-blockstore.(*blockstore).Get(0xc000481d20, 0xc0dd4edd10, 0x26, 0x0, 0x0, 0x0, 0x990268)
        /home/ubuntu/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v1.0.1/blockstore.go:124 +0xb2
github.com/ipfs/go-ipfs-blockstore.(*idstore).Get(0xc0006fae60, 0xc0dd4edd10, 0x26, 0x1, 0x7e4, 0x1, 0xb220)
        /home/ubuntu/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v1.0.1/idstore.go:62 +0xd7
github.com/ipfs/go-ipfs-blockstore.(*arccache).Get(0xc0908bcec0, 0xc0dd4edd10, 0x26, 0x0, 0x0, 0x0, 0x1e)
        /home/ubuntu/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v1.0.1/arc_cache.go:118 +0xbc
github.com/ipfs/go-ipfs-blockstore.(*idstore).Get(0xc0006faea0, 0xc0dd4edd10, 0x26, 0xc04c993db8, 0xc04c993db8, 0x563c93, 0xc03ed22b38)
        /home/ubuntu/go/pkg/mod/github.com/ipfs/go-ipfs-blockstore@v1.0.1/idstore.go:62 +0xd7
github.com/filecoin-project/lotus/lib/bufbstore.(*BufferedBS).Get(0xc03ed3b160, 0xc0dd4edd10, 0x26, 0x5, 0x1, 0xc203ccb650, 0x0)
        /home/ubuntu/lotus/lib/bufbstore/buf_bstore.go:97 +0x4b
github.com/ipfs/go-bitswap/internal/decision.(*blockstoreManager).getBlocks.func1(0xc0dd4edd10, 0x26)
        /home/ubuntu/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/blockstoremanager.go:95 +0x70
github.com/ipfs/go-bitswap/internal/decision.(*blockstoreManager).jobPerKey.func1()
        /home/ubuntu/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/blockstoremanager.go:116 +0x42
github.com/ipfs/go-bitswap/internal/decision.(*blockstoreManager).worker(0xc00032cab0)
        /home/ubuntu/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/blockstoremanager.go:49 +0x3b
github.com/ipfs/go-bitswap/internal/decision.(*blockstoreManager).start.func1(0x31763a0, 0xc091be5b60)
        /home/ubuntu/go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.20/internal/decision/blockstoremanager.go:38 +0x2a
github.com/jbenet/goprocess.(*process).Go.func1(0xc03ed2d710, 0xc091be5b60, 0xc091be5bc0)
        /home/ubuntu/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:134 +0x3c
created by github.com/jbenet/goprocess.(*process).Go
        /home/ubuntu/go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:133 +0x1fe
```

**Version (run `lotus version`):**
```
Daemon:  1.1.2+git.7d02cd667+api0.17.0
Local: lotus version 1.1.2+git.7d02cd667
```

**Comment by mgoelzer** [comment]
Full node won't restart. Looks like the problem here is chain corruption.  Here's the full log when I try to restart `lotus daemon`:

```
2020-11-02T19:57:10.414Z        ^[[34mINFO^[[0m main    lotus/daemon.go:185     lotus repo: /home/ubuntu/.lotus
2020-11-02T19:57:10.415Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0cfb4f178bbb71cf2ecfcd42accce558b27199ab4fb59cb78f2483fe21ef36d9.vk is ok
2020-11-02T19:57:10.415Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-7d739b8cf60f1b0709eeebee7730e297683552e4b69cab6984ec0285663c5781.vk is ok
2020-11-02T19:57:10.415Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-3ea05428c9d11689f23529cde32fd30aabd50f7d2c93657c1d3650bca3e8ea9e.vk is ok
2020-11-02T19:57:10.415Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.vk is ok
2020-11-02T19:57:10.415Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.vk is ok
2020-11-02T19:57:10.415Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-6babf46ce344ae495d558e7770a585b2382d54f225af8ed0397b8be7c3fcd472.vk is ok
2020-11-02T19:57:10.415Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-b62098629d07946e9028127e70295ed996fe3ed25b0f9f88eb610a0ab4385a3c.vk is ok
2020-11-02T19:57:10.415Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-ecd683648512ab1765faa2a5f14bab48f676e633467f0aa8aad4b55dcb0652bb.vk is ok
2020-11-02T19:57:10.415Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-5294475db5237a2e83c3e52fd6c2b03859a1831d45ed08c4f35dbf9a803165a9.vk is ok
2020-11-02T19:57:10.415Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-2-sha256_hasher-96f1b4a04c5c51e4759bbf224bbc2ef5a42c7100f16ec0637123f16a845ddfb2.vk is ok
2020-11-02T19:57:10.415Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-032d3138d22506ec0082ed72b2dcba18df18477904e35bafee82b3793b06832f.vk is ok
2020-11-02T19:57:10.415Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0170db1f394b35d995252228ee359194b13199d259380541dc529fb0099096b0.vk is ok
2020-11-02T19:57:10.415Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-50c7368dea9593ed0989e70974d28024efa9d156d585b7eea1be22b2e753f331.vk is ok
2020-11-02T19:57:10.423Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-2627e4006b67f99cef990c0a47d5426cb7ab0a0ad58fc1061547bf2d28b09def.vk is ok
2020-11-02T19:57:10.424Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:138    Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c4509eedae8a27555733edc.vk is ok
2020-11-02T19:57:10.424Z        ^[[34mINFO^[[0m build   go-paramfetch@v0.0.2-0.20200701152213-3e0f0afdc261/paramfetch.go:162    parameter and key-fetching complete
2020-11-02T19:57:13.483Z        ^[[34mINFO^[[0m badger  v2@v2.2007.2/levels.go:129      506 tables out of 788 opened in 3.009s

2020-11-02T19:57:15.683Z        ^[[34mINFO^[[0m badger  v2@v2.2007.2/levels.go:183      All 788 tables opened in 5.209s

2020-11-02T19:57:15.732Z        ^[[34mINFO^[[0m badger  v2@v2.2007.2/value.go:1158      Replaying file id: 226 at offset: 437913190

2020-11-02T19:57:15.747Z        ^[[34mINFO^[[0m badger  v2@v2.2007.2/value.go:1079      Truncating vlog file /home/ubuntu/.lotus/datastore/chain/000226.vlog to offset: 440727528
2020-11-02T19:57:15.747Z        ^[[34mINFO^[[0m badger  v2@v2.2007.2/value.go:1178      Replay took: 15.028494ms

2020-11-02T19:57:15.801Z        ^[[34mINFO^[[0m badger  v2@v2.2007.2/levels.go:183      All 0 tables opened in 0s

2020-11-02T19:57:15.802Z        ^[[34mINFO^[[0m badger  v2@v2.2007.2/value.go:1158      Replaying file id: 0 at offset: 0

2020-11-02T19:57:15.802Z        ^[[34mINFO^[[0m badger  v2@v2.2007.2/value.go:1178      Replay took: 2.69µs

2020-11-02T19:57:15.805Z        ^[[34mINFO^[[0m badger  v2@v2.2007.2/levels.go:183      All 1 tables opened in 1ms

2020-11-02T19:57:15.806Z        ^[[34mINFO^[[0m badger  v2@v2.2007.2/value.go:1158      Replaying file id: 0 at offset: 26606

2020-11-02T19:57:15.806Z        ^[[34mINFO^[[0m badger  v2@v2.2007.2/value.go:1178      Replay took: 129.551µs

2020-11-02T19:57:15.808Z        ^[[33mWARN^[[0m modules modules/chain.go:106    loading chain state from disk: loading tipset: get block bafy2bzacebi3fylfscsktxzqn656s5z6rbya7jde5r7sdrb7rqx6vh3urovtc: blockstore: block not found
2020-11-02T19:57:15.942Z        ^[[34mINFO^[[0m p2pnode lp2p/addrs.go:114       Swarm listening at: [/ip4/127.0.0.1/tcp/5555 /ip4/172.31.65.109/tcp/5555]
2020-11-02T19:57:15.990Z        ^[[31mERROR^[[0m        messagepool     messagepool/messagepool.go:1293 adding local message: current tipset not loaded:
    github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).addLoaded
        /home/ubuntu/lotus/chain/messagepool/messagepool.go:698
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x143ff2d]

goroutine 366 [running]:
github.com/filecoin-project/lotus/chain/types.(*TipSet).Height(...)
        /home/ubuntu/lotus/chain/types/tipset.go:151
github.com/filecoin-project/lotus/chain/events.(*tipSetCache).add(0xc0c27940a0, 0x0, 0x0, 0x0)
        /home/ubuntu/lotus/chain/events/tscache.go:50 +0xad
github.com/filecoin-project/lotus/chain/events.(*Events).listenHeadChangesOnce(0xc0c279a1b0, 0x315bba0, 0xc00003e098, 0x0, 0x0)
        /home/ubuntu/lotus/chain/events/events.go:131 +0x198
github.com/filecoin-project/lotus/chain/events.(*Events).listenHeadChanges(0xc0c279a1b0, 0x315bba0, 0xc00003e098)
        /home/ubuntu/lotus/chain/events/events.go:94 +0xe6
created by github.com/filecoin-project/lotus/chain/events.NewEvents
        /home/ubuntu/lotus/chain/events/events.go:83 +0x597
```

**Comment by Stebalien** [comment]
Did you run out of disk space or memory (check your system log for OOM).

**Comment by mgoelzer** [comment]
@Stebalien You're right.  It was disk space.  Thanks!  (closing)
