### ISSUE TITLE
p2： Cannot get device list for platform: Clover!

### ISSUE THREAD

**Issue by CD-oursoft** [filecoin-project/lotus#4735]
my displaycard nvidia 2080Ti
![image](https://user-images.githubusercontent.com/69950374/98253512-144c8480-1fb6-11eb-90cd-c9a69ecb110d.png)

P2：
2020-11-05T20:38:16.939 INFO filcrypto::proofs::api > seal_pre_commit_phase2: start
2020-11-05T20:38:16.940 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:start
2020-11-05T20:38:16.940 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:finish
2020-11-05T20:38:16.940 INFO filecoin_proofs::api::seal > seal_pre_commit_phase2:start
2020-11-05T20:38:16.948 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase2
2020-11-05T20:38:16.948 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree c using the GPU
2020-11-05T20:38:16.948 INFO storage_proofs_porep::stacked::vanilla::proof > Building column hashes
2020-11-05T20:38:16.949 INFO neptune::cl > getting context for ~Index(0)
2020-11-05T20:38:16.949 WARN neptune::cl > Cannot get device list for platform: Clover!
2020-11-05T20:38:16.949 WARN neptune::cl > Cannot get device list for platform: Clover!
2020-11-05T20:40:57.260 INFO storage_proofs_porep::stacked::vanilla::proof > persisting base tree_c 1/8 of length 153391689
2020-11-05T20:43:44.989 INFO storage_proofs_porep::stacked::vanilla::proof > persisting base tree_c 2/8 of length 153391689
2020-11-05T20:46:36.181 INFO storage_proofs_porep::stacked::vanilla::proof > persisting base tree_c 3/8 of length 153391689
2020-11-05T20:49:30.275 INFO storage_proofs_porep::stacked::vanilla::proof > persisting base tree_c 4/8 of length 153391689
2020-11-05T20:52:25.104 INFO storage_proofs_porep::stacked::vanilla::proof > persisting base tree_c 5/8 of length 153391689
2020-11-05T20:55:23.083 INFO storage_proofs_porep::stacked::vanilla::proof > persisting base tree_c 6/8 of length 153391689

C2：
2020-11-05T21:43:59.755 INFO bellperson::groth16::prover > Bellperson 0.11.0 is being used!
2020-11-05T21:56:00.916 INFO bellperson::gpu::locks > GPU is available for FFT!
2020-11-05T21:56:00.916 DEBUG bellperson::gpu::locks > Acquiring GPU lock...
2020-11-05T21:56:00.916 DEBUG bellperson::gpu::locks > GPU lock acquired!
2020-11-05T21:56:01.007 INFO bellperson::gpu::fft > FFT: 1 working device(s) selected.
2020-11-05T21:56:01.007 INFO bellperson::gpu::fft > FFT: Device 0: GeForce RTX 2080 Ti
2020-11-05T21:56:01.007 INFO bellperson::domain > GPU FFT kernel instantiated!
2020-11-05T21:59:31.822 DEBUG bellperson::gpu::locks > GPU lock released!
2020-11-05T22:00:01.161 INFO bellperson::gpu::locks > GPU is available for Multiexp!
2020-11-05T22:00:01.161 DEBUG bellperson::gpu::locks > Acquiring GPU lock...
2020-11-05T22:00:01.161 DEBUG bellperson::gpu::locks > GPU lock acquired!
2020-11-05T22:00:01.260 INFO bellperson::gpu::multiexp > Multiexp: 1 working device(s) selected. (CPU utilization: 0)
2020-11-05T22:00:01.261 INFO bellperson::gpu::multiexp > Multiexp: Device 0: GeForce RTX 2080 Ti (Chunk-size: 7488999)
2020-11-05T22:00:01.261 INFO bellperson::multiexp > GPU Multiexp kernel instantiated!

**Version**
Daemon:  1.1.2+git.2a294f048+api0.17.0
Local: lotus version 1.1.2+git.2a294f048
lotus-miner version 1.1.2+git.2a294f048
lotus-worker version 1.1.2+git.2a294f048

**Comment by jennijuju** [comment]
This warning should be ignorable.

are you suspecting any issue caused by this warning?

**Comment by porcuquine** [comment]
I'm copying my response from elsewhere, since this keeps coming up:

The existence of a log line about Clover is a non-issue. If there was or is some other problem also that might not be, but I didn't notice that in this case. Basically, Clover is some OpenCL thing which some machines have installed but which doesn't have any device we can use, so it gets probed when looking for GPUs.

**Comment by CD-oursoft** [comment]
Yes, I'm afraid it will cause other problems，But what you said can be ignored, I'm relieved，thank you

**Comment by kenshyx** [comment]
This is a real issue, I run PC1 and PC2 on the same machine, the PC2 job never continues after this warning `Cannot get device list for platform: Clover!`. I'm running lotus version `1.1.2+git.9deda06ec`.

**Comment by Shekelme** [comment]
Agreed, this is an issue, here is what I see with v1.1.3 and nvidia driver 450.80.02:

```
2020-11-15T10:17:55.932 INFO filecoin_proofs::api::seal > seal_pre_commit_phase1:finish: SectorId(1)
2020-11-15T10:17:55.947 INFO filcrypto::proofs::api > seal_pre_commit_phase1: finish
2020-11-15T10:17:56.001+0300	INFO	lotus-bench	lotus-bench/main.go:531	[1] Running replication(2)...
2020-11-15T10:17:56.027 INFO filcrypto::proofs::api > seal_pre_commit_phase2: start
2020-11-15T10:17:56.031 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:start
2020-11-15T10:17:56.032 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:finish
2020-11-15T10:17:56.034 INFO filecoin_proofs::api::seal > seal_pre_commit_phase2:start
2020-11-15T10:17:56.037 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase2
2020-11-15T10:17:56.038 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree c using the GPU
2020-11-15T10:17:56.038 INFO storage_proofs_porep::stacked::vanilla::proof > Building column hashes
2020-11-15T10:17:56.050 INFO neptune::cl > getting context for ~Index(0)
2020-11-15T10:17:56.271 WARN neptune::cl > Cannot get device list for platform: Clover!
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /home/don_genaro/.cargo/registry/src/github.com-1ecc6299db9ec823/neptune-2.1.1/src/cl.rs:252:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to send columns: "SendError(..)"', /home/don_genaro/.cargo/registry/src/github.com-1ecc6299db9ec823/storage-proofs-porep-5.3.0/src/stacked/vanilla/proof.rs:502:34
2020-11-15T10:18:07.039+0300	WARN	lotus-bench	lotus-bench/main.go:91	failed to run seals:
    main.glob..func3
        /home/don_genaro/lotus/cmd/lotus-bench/main.go:251
  - commit:
    main.runSeals.func1.1
        /home/don_genaro/lotus/cmd/lotus-bench/main.go:534
  - presealing sector 1 ():
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).SealPreCommit2
        /home/don_genaro/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:477
  - Rust panic: no unwind information
    github.com/filecoin-project/filecoin-ffi.SealPreCommitPhase2
    	/home/don_genaro/lotus/extern/filecoin-ffi/proofs.go:321
    github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*Sealer).SealPreCommit2
    	/home/don_genaro/lotus/extern/sector-storage/ffiwrapper/sealer_cgo.go:475
    main.runSeals.func1.1
    	/home/don_genaro/lotus/cmd/lotus-bench/main.go:532
    main.runSeals.func1
    	/home/don_genaro/lotus/cmd/lotus-bench/main.go:643
    runtime.goexit
    	/usr/local/go/src/runtime/asm_amd64.s:1374
```

**Comment by porcuquine** [comment]
The issue described here ('Cannot get device list for platform: Clover!') really is not a problem. It happens to be the case that if you *do* get this warning, it's likely to happen right before you have the other problem some people are experience. The problem is that no available GPU devices are found. Neptune 2.2.0 cleans up some of this handling by delegating to`rust-gpu-tools`. `rust-fil-proofs` may still panic though if you request GPU (column-)tree-building when no devices are available.

The most likely root cause of this is misconfiguration. I think people tend to have this problem when they upgrade GPU drivers, or need to update GPU drivers but didn't, etc. If you are seeing this error (not the Clover warning, the 'index out of bounds' error, please run `clinfo` and ensure the expected GPU is visible. If so and the problem persists, please report and include clinfo output.

**Comment by Storage-Hive** [comment]
I had similar issue, was able to resolve it by removing the mesa libraries:
rpm -e mesa-libOpenCL mesa-libOpenCL-devel
After that the Clover messages went away and system is working well.

**Comment by porcuquine** [comment]
That is good to hear. I guess people experiencing problems should see if this helps:

```
rpm -e mesa-libOpenCL mesa-libOpenCL-devel
```

(I copied the command mostly to help me find it in the future if need be.)

**Comment by Eterion-com** [comment]
I resolved an issue by replacing newest nvidia drivers with nvidia-driver-450 and recompiling lotus.
