### ISSUE TITLE
Rust panic: no unwind information , lotus-miner version v1.1.2

### ISSUE THREAD

**Issue by vonhenry** [filecoin-project/lotus#4766]
:46:43.500+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWQL1dQwdfrNWLJkE1T75QKsuJt9jacAnFsULTSAhjNEib
2020-11-09T10:46:43.500+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWCWiwhgpPfYBHq4brdmwN7kyHWyuVNWxVSVyVLAvoB3ag
2020-11-09T10:46:43.500+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWQyhxzkPneX8BWhtLHQahtKvxpinomtkXQvsb82B4HUbC
2020-11-09T10:46:43.500+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWRz8u4n4qJd1JggaKVaFmjopnizuy4yibf3UDWcErfZZW
2020-11-09T10:46:43.500+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWCFm9CfPeW8PTgMr92n3bDLhro2e6apCH4hwWzGcZY4uJ
2020-11-09T10:46:43.500+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWJmWNSJPDzFgcm6sQYZKMWHu3ZrLCt1DadnEUUWNgRFrX
2020-11-09T10:46:43.500+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWCBmYqUCKBZCWH1v37PPEko9jvHiomnEHJqNnLCgw257o
2020-11-09T10:46:43.500+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWMjEQmqrHgLmGsHVrzZepNXdhfLLczVcwGmXykBq5p8fV
2020-11-09T10:46:43.501+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWA4rH4ygTHfsDWZoNTkS7tpRfr3pxdbEYwrw1WxnX8q6L
2020-11-09T10:46:43.501+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWGeaYbwHn8ks9HRbCpbqUm1mS3i6EA4HBLoUY91D3kLi2
2020-11-09T10:46:43.501+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWC5FFgvJp3ec3izdGXo5CkiKHCmohvGqENcCeTTHwv4HZ
2020-11-09T10:46:43.501+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWEbJCjnCeyzAF4pHfag698sBy3DpkR4ZdqF6AznbmMy3Z
2020-11-09T10:47:03.148+0800	INFO	swarm2	go-libp2p-swarm@v0.2.8/swarm_dial.go:533	got error on dial: dial tcp4 112.47.13.99:31193: i/o timeout
thread '<unnamed>' panicked at 'index 86465168160 out of range for slice of length 34359738368', src/libcore/slice/mod.rs:2725:5
stack backtrace:
   0:          0x25f7d74 - backtrace::backtrace::libunwind::trace::h5d52ba5f20882f09
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/libunwind.rs:86
   1:          0x25f7d74 - backtrace::backtrace::trace_unsynchronized::hceee092869668a74
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.44/src/backtrace/mod.rs:66
   2:          0x25f7d74 - std::sys_common::backtrace::_print_fmt::ha312c2904605e4d5
                               at src/libstd/sys_common/backtrace.rs:78
   3:          0x25f7d74 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5b9981092140b727
                               at src/libstd/sys_common/backtrace.rs:59
   4:          0x262bd7c - core::fmt::write::h5f6d7d8de88b4173
                               at src/libcore/fmt/mod.rs:1063
   5:          0x25e9a93 - std::io::Write::write_fmt::h893169117de3cc15
                               at src/libstd/io/mod.rs:1426
   6:          0x25fcba5 - std::sys_common::backtrace::_print::h8ab61d4120f7a335
                               at src/libstd/sys_common/backtrace.rs:62
   7:          0x25fcba5 - std::sys_common::backtrace::print::h8aae19fbb153bf2a
                               at src/libstd/sys_common/backtrace.rs:49
   8:          0x25fcba5 - std::panicking::default_hook::{{closure}}::h1ee5b7d8b6f83429
                               at src/libstd/panicking.rs:204
   9:          0x25fc8f2 - std::panicking::default_hook::hd6c32c13403f9210
                               at src/libstd/panicking.rs:224
  10:          0x25fd202 - std::panicking::rust_panic_with_hook::h1f2449d529a25f22
                               at src/libstd/panicking.rs:470
  11:          0x25fcdeb - rust_begin_unwind
                               at src/libstd/panicking.rs:378
  12:          0x2628a11 - core::panicking::panic_fmt::h2c05f81b567d1861
                               at src/libcore/panicking.rs:85
  13:          0x262d9d6 - core::slice::slice_index_len_fail::hbb0886f69c1b24c2
                               at src/libcore/slice/mod.rs:2725
  14:          0x1a5e16b - storage_proofs_porep::stacked::vanilla::graph::StackedGraph<H,G>::copy_parents_data_inner::he14633a701ea0381
  15:          0x1a5de35 - storage_proofs_porep::stacked::vanilla::graph::StackedGraph<H,G>::copy_parents_data::h1dfa9cd19a568c67
  16:          0x1a97bff - storage_proofs_porep::stacked::vanilla::create_label::create_label::he4b5584548f30069
  17:          0x1b8ff17 - storage_proofs_porep::stacked::vanilla::proof::StackedDrg<Tree,G>::generate_labels::h7e4e7bd3f16977f1
  18:          0x1b90eab - storage_proofs_porep::stacked::vanilla::proof::StackedDrg<Tree,G>::replicate_phase1::h9b9fd0c2b28f8c44
  19:          0x19de6f9 - filecoin_proofs::api::seal::seal_pre_commit_phase1::h6319c0873375daac
  20:          0x1c0b133 - filecoin_proofs_api::seal::seal_pre_commit_phase1_inner::hb568fbd8934fc0fb
  21:          0x1bf9880 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hf34381d962f0974a
  22:          0x26620a0 - std::panicking::try::do_call::hf480f09dacf61731
  23:          0x260e567 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:86
  24:          0x1a893ed - ffi_toolkit::catch_panic_response::h3920e80f0e7d8f21
  25:          0x1a35a3e - fil_seal_pre_commit_phase1
  26:          0x18f8d70 - _cgo_b45de461e0cc_Cfunc_fil_seal_pre_commit_phase1
                               at /tmp/go-build/cgo-gcc-prolog:1008
  27:           0x581a60 - runtime.asmcgocall
                               at /go/go-1.14.4/src/runtime/asm_amd64.s:655
2020-11-09T10:47:14.075+0800	WARN	sectors	storage-sealing/fsm.go:475	sector 1 got error event sealing.SectorSealPreCommit1Failed: seal pre commit(1) failed: presealing sector 1 (/sata_data/lotus_seal_store_path/unsealed/s-t067657-1): Rust panic: no unwind information
2020-11-09T10:47:14.113+0800	INFO	sectors	storage-sealing/states_failed.go:26	SealPreCommit1Failed(1), waiting 59.886738191s before retrying
2020-11-09T10:47:43.499+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWQeVCXFtERsWmMahYjwpo8eUJpRft5tj7F6ioxriQsJa2
2020-11-09T10:47:43.499+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWNmiEmXV3bByzfxNubUupbqVABN9adoEpcCQ7mze3U35Z
2020-11-09T10:47:43.499+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWBoub37aj49D5F5BnB7xN6atk2faqEvyWgyQAaAm2Uov7
2020-11-09T10:47:43.499+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWRjJR8SKAMroLsEwS3P1JPPGkv23DJFoc8GzSeprmXq5K
2020-11-09T10:47:43.499+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWQE3MRyhNwqBcVCsq85485CY98Tb91QWjD1sa56yLVfuV
2020-11-09T10:47:43.500+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWLvi1dmkLEkLFEPZFHa8n7eRj3qunDt3eBe8UmWqaqxLb
2020-11-09T10:47:43.500+0800	INFO	connmgr	go-libp2p-connmgr@v0.2.4/connmgr.go:291	closing conn: 12D3KooWL4qmyCJAaEnPxteAq1e3nrdurbwvHdXjXn7bija8rgNX
2020-11-09T10:47:43.500+0800	INFO	connmgr	go

**Comment by jennijuju** [comment]
an I/O timeout indicates faulty hardware, or something going on with the system. we'd recommend checking system logs for failed disk reads.

**Comment by Reiers** [comment]
Hi @vonhenry 

Thanks for the report. The issue you are experiencing lies elsewhere.

Moving this issue to Lotus Discussions for help and troubleshooting.

Closing Lotus issue ticket.
