### ISSUE TITLE
lotus异常退出

### ISSUE THREAD

**Issue by yzn5555** [filecoin-project/lotus#4838]
lotus程序正在运行中发现异常退出，服务器资源使用率也不高，查看日志发现以下报错信息：
2020-11-12T21:11:14.412Z	WARN	messagepool	messagepool/messagepool.go:1218	could not recover signature for bls message bafy2bzacecea4xdtexddphj5zuy5iefd2jvwjfg64lb76rc7afvb643phl5jw
2020-11-12T21:11:14.412Z	WARN	messagepool	messagepool/messagepool.go:1218	could not recover signature for bls message bafy2bzacecr5ldcrh6yfl3zxx2c3aznlbokzdsndvyzi4tccgeau727wbp3m4
2020-11-12T21:11:20.654Z	INFO	chain	chain/sync.go:716	block validation	{"took": 12.407166848, "height": "230302", "age": 20.654150181}
2020-11-12T21:11:20.655Z	INFO	chain	chain/sync.go:716	block validation	{"took": 13.1306661, "height": "230302", "age": 20.655864265}
2020-11-12T21:11:20.657Z	INFO	chainstore	store/store.go:441	New heaviest tipset! [bafy2bzacebe35ej34hozqaz5myuozzao7oydh2ip4tqjtm26rz7n467bungfy bafy2bzacebmmpvqw6awy7ixg3feqk3wlu5eqa24fqlgd2kojfxganj33cvlou] (height=230302)
2020-11-12T21:11:20.657Z	WARN	chainstore	store/store.go:263	head change sub is slow, has 4 buffered entries
2020-11-12T21:11:20.658Z	INFO	chain	chain/sync.go:716	block validation	{"took": 14.163439931, "height": "230302", "age": 20.658382216}
2020-11-12T21:11:20.661Z	INFO	chainstore	store/store.go:441	New heaviest tipset! [bafy2bzacebe2zwqe6kpiacvdoqmfnd6grtwxplzd4io4vqjxc6ta7yjatzj6g bafy2bzacebe35ej34hozqaz5myuozzao7oydh2ip4tqjtm26rz7n467bungfy bafy2bzacebmmpvqw6awy7ixg3feqk3wlu5eqa24fqlgd2kojfxganj33cvlou] (height=230302)
panic: runtime error: index out of range [-1]

goroutine 3830 [running]:
github.com/filecoin-project/lotus/chain.(*Syncer).collectHeaders(0xc3146abe10, 0x3160380, 0xc6c7585590, 0xc1f11db4c0, 0xc0bf178a00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/circleci/project/chain/sync.go:1396 +0x317f
github.com/filecoin-project/lotus/chain.(*Syncer).collectChain(0xc3146abe10, 0x3160380, 0xc6c7585530, 0xc1f11db4c0, 0x0, 0x0)
	/home/circleci/project/chain/sync.go:1694 +0x1a6
github.com/filecoin-project/lotus/chain.(*Syncer).Sync(0xc3146abe10, 0x3160380, 0xc6c7585530, 0xc1f11db4c0, 0x0, 0x0)
	/home/circleci/project/chain/sync.go:574 +0x1be
github.com/filecoin-project/lotus/chain.(*syncManager).syncWorker(0xc314777ef0, 0x0)
	/home/circleci/project/chain/sync_manager.go:452 +0x149
created by github.com/filecoin-project/lotus/chain.(*syncManager).Start
	/home/circleci/project/chain/sync_manager.go:112 +0x6f
nohup: ignoring input

**Comment by jennijuju** [comment]
Please re-file the issue in English otherwise it’s less likely the team will respond to the tickets as they dont speak Chinese.

**Comment by jennijuju** [comment]
Also, please always provide lotus version, full stack trace, or `lotus pprof gorountines` for sync issues. And I’m pretty sure it’s fixed in #4696
