### ISSUE TITLE
Lotus-miner divide by zero during retrieval

### ISSUE THREAD

**Issue by xinaxu** [filecoin-project/lotus#5140]
**Describe the bug**
lotus-miner crashed when handling retrieval deal.
```
Dec 07 22:15:02 lotus lotus-miner[792533]: 2020-12-07T22:15:02.125Z        INFO        markets        loggers/loggers.go:30        retrieval event        {"name": "ProviderEventUnsealComplete", "deal ID": "512", "receiver": "12D3KooWJesyZarYF6WQiSPNUvbfEvjKGpaLs4kPCH8HsMPPyZxp", "state": "DealStatusUnsealed", "message": ""}
Dec 07 22:15:02 lotus lotus-miner[792533]: panic: division by zero
Dec 07 22:15:02 lotus lotus-miner[792533]: goroutine 12134364 [running]:
Dec 07 22:15:02 lotus lotus-miner[792533]: math/big.nat.div(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /usr/local/go/src/math/big/nat.go:656 +0x490
Dec 07 22:15:02 lotus lotus-miner[792533]: math/big.(*Int).QuoRem(0xc01260ef40, 0xc01260eee0, 0xc0384bcea0, 0xc012f46f40, 0x0, 0x0)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /usr/local/go/src/math/big/int.go:239 +0xbf
Dec 07 22:15:02 lotus lotus-miner[792533]: math/big.(*Int).Div(0xc01260ef40, 0xc01260eee0, 0xc0384bcea0, 0x0)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /usr/local/go/src/math/big/int.go:250 +0x6a
Dec 07 22:15:02 lotus lotus-miner[792533]: github.com/filecoin-project/go-state-types/big.Div(0xc01260eee0, 0xc0384bcea0, 0xc01260eee0)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /home/shane/go/pkg/mod/github.com/filecoin-project/go-state-types@v0.0.0-20201102161440-c8033295a1fc/big/int.go:78 +0x67
Dec 07 22:15:02 lotus lotus-miner[792533]: github.com/filecoin-project/go-fil-markets/retrievalmarket/impl/requestvalidation.(*ProviderRevalidator).writeDealState(0xc000f442d0, 0xc017514420, 0x26, 0x200, 0xc0384bce60, 0x0, 0xc0384bcea0, 0x100000, 0x100000, 0xc0384bcec0, ...)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /home/shane/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v1.0.9/retrievalmarket/impl/requestvalidation/revalidator.go:87 +0xc5
Dec 07 22:15:02 lotus lotus-miner[792533]: github.com/filecoin-project/go-fil-markets/retrievalmarket/impl/requestvalidation.(*ProviderRevalidator).TrackChannel(0xc000f442d0, 0xc017514420, 0x26, 0x200, 0xc0384bce60, 0x0, 0xc0384bcea0, 0x100000, 0x100000, 0xc0384bcec0, ...)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /home/shane/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v1.0.9/retrievalmarket/impl/requestvalidation/revalidator.go:60 +0x1c5
Dec 07 22:15:02 lotus lotus-miner[792533]: github.com/filecoin-project/go-fil-markets/retrievalmarket/impl.(*providerDealEnvironment).TrackTransfer(0xc0007301f0, 0xc017514420, 0x26, 0x200, 0xc0384bce60, 0x0, 0xc0384bcea0, 0x100000, 0x100000, 0xc0384bcec0, ...)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /home/shane/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v1.0.9/retrievalmarket/impl/provider_environments.go:138 +0x78
Dec 07 22:15:02 lotus lotus-miner[792533]: github.com/filecoin-project/go-fil-markets/retrievalmarket/impl/providerstates.UnpauseDeal(0x7f92340faa18, 0xc00dddee10, 0x7f8f526e51d8, 0xc0007301f0, 0xc017514420, 0x26, 0x200, 0xc0384bce60, 0x0, 0xc0384bcea0, ...)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /home/shane/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v1.0.9/retrievalmarket/impl/providerstates/provider_states.go:66 +0x76
Dec 07 22:15:02 lotus lotus-miner[792533]: reflect.Value.call(0x2b22160, 0x30d7f20, 0x13, 0x2e3245d, 0x4, 0xc012f47810, 0x3, 0x3, 0x540cdf, 0x2cc4980, ...)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /usr/local/go/src/reflect/value.go:476 +0x8c7
Dec 07 22:15:02 lotus lotus-miner[792533]: reflect.Value.Call(0x2b22160, 0x30d7f20, 0x13, 0xc00d9e4810, 0x3, 0x3, 0x200000003, 0xc00f5c2a80, 0xc000048000)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /usr/local/go/src/reflect/value.go:337 +0xb9
Dec 07 22:15:02 lotus lotus-miner[792533]: github.com/filecoin-project/go-statemachine/fsm.fsmHandler.handler.func1(0xc03529b290, 0x2, 0x2, 0xc03529b290, 0xc01836f890, 0xc00d9e4a20)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /home/shane/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/fsm/fsm.go:170 +0x437
Dec 07 22:15:02 lotus lotus-miner[792533]: reflect.callReflect(0xc001e25860, 0xc012f47ae0, 0xc012f47ac8)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /usr/local/go/src/reflect/value.go:565 +0x32a
Dec 07 22:15:02 lotus lotus-miner[792533]: reflect.makeFuncStub(0x32cf0e0, 0xc00003eb90, 0xc00d896f30, 0xc017514420, 0x26, 0x200, 0xc0384bce60, 0x0, 0xc0384bcea0, 0x100000, ...)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /usr/local/go/src/reflect/asm_amd64.s:20 +0x42
Dec 07 22:15:02 lotus lotus-miner[792533]: reflect.Value.call(0xc00fe6e720, 0xc001e25860, 0x13, 0x2e3245d, 0x4, 0xc00d9e4f70, 0x2, 0x2, 0x540cdf, 0x2bfab60, ...)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /usr/local/go/src/reflect/value.go:476 +0x8c7
Dec 07 22:15:02 lotus lotus-miner[792533]: reflect.Value.Call(0xc00fe6e720, 0xc001e25860, 0x13, 0xc00c661f70, 0x2, 0x2, 0xc00cd94000, 0x57043c, 0xc00c661ed0)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /usr/local/go/src/reflect/value.go:337 +0xb9
Dec 07 22:15:02 lotus lotus-miner[792533]: github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc01a2e05b0, 0x32cf0e0, 0xc00003eb90, 0xc00d896f30, 0xc01a2e05c0, 0xc00fe6e2a0)
Dec 07 22:15:02 lotus lotus-miner[792533]:         /home/shane/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:102 +0x2c8
Dec 07 22:15:02 lotus lotus-miner[792533]: created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
Dec 07 22:15:02 lotus lotus-miner[792533]:         /home/shane/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:100 +0x3f2
Dec 07 22:15:03 lotus systemd[1]: lotus-miner.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 07 22:15:03 lotus systemd[1]: lotus-miner.service: Failed with result 'exit-code'.
```
```
$ sudo -E lotus-miner retrieval-deals list
Receiver                                              DealID  Payload      State                PricePerByte  BytesSent  Message
12D3KooWGSMixJZE6HMUcymXfGgHF8jyUvae8TBj8g5GxUyAjh2u  1041    ...Zfk6s5PU  DealStatusCompleted  2             125032704
12D3KooWGSMixJZE6HMUcymXfGgHF8jyUvae8TBj8g5GxUyAjh2u  1291    ...Zfk6s5PU  DealStatusCompleted  2             125032704
12D3KooWGSMixJZE6HMUcymXfGgHF8jyUvae8TBj8g5GxUyAjh2u  1488    ...Zfk6s5PU  DealStatusCompleted  2             125032704
12D3KooWJesyZarYF6WQiSPNUvbfEvjKGpaLs4kPCH8HsMPPyZxp  512     ...axytolmg  DealStatusUnsealed   0             0
```
**To Reproduce**
Unsure. I have made changes to retrieval unseal price, i.e. change to 0.1 and change back to 0

**Expected behavior**
The retrieval deal should not fail. If it does fail, it should not crash the whole process

**Version (run `lotus version`):**
lotus-miner version 1.2.2+git.b13226bc2.dirty

**Comment by dirkmc** [comment]
Another example of the same issue:
https://github.com/filecoin-project/lotus/issues/5409#issuecomment-766818577
