### ISSUE TITLE
run lotus daemon errors

### ISSUE THREAD

**Issue by LyyDandelion** [filecoin-project/lotus#5437]
system: CentOS 7.5.1804  8cpu 32G  2T SSD
lotus  version: lotus version 1.4.1+mainnet+git.d5addf7

run the cmd "lotus daemon" ,when happened immediately before the program died,print these info:
goroutine 6062 [IO wait]:
internal/poll.runtime_pollWait(0x7f04e3020578, 0x72, 0x33eae60)
        /usr/local/go/src/runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc02198f098, 0x72, 0x33eae00, 0x5d2ee18, 0x0)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc02198f080, 0xc023195000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:159 +0x1a5
net.(*netFD).Read(0xc02198f080, 0xc023195000, 0x1000, 0x1000, 0xc021fdc540, 0xc01ad4cd40, 0xc01ad4ccd0)
        /usr/local/go/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc01d06b5b8, 0xc023195000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:182 +0x8e
bufio.(*Reader).Read(0xc02339cc60, 0xc0221ba980, 0x2, 0x2, 0xc022953c80, 0xc01ad4cd40, 0x321a401)
        /usr/local/go/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x33e24c0, 0xc02339cc60, 0xc0221ba980, 0x2, 0x2, 0x2, 0xc0224f9638, 0x0, 0x0)
        /usr/local/go/src/io/io.go:314 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:333
github.com/libp2p/go-libp2p-noise.(*secureSession).readNextInsecureMsgLen(0xc0221ba8f0, 0xc01d6bbc9e, 0xc, 0x22)
        /home/go/goProject/pkg/mod/github.com/libp2p/go-libp2p-noise@v0.1.2/rw.go:134 +0x66
github.com/libp2p/go-libp2p-noise.(*secureSession).Read(0xc0221ba8f0, 0xc0229c5c74, 0xc, 0xc, 0x0, 0x0, 0x0)
        /home/go/goProject/pkg/mod/github.com/libp2p/go-libp2p-noise@v0.1.2/rw.go:53 +0x20e
io.ReadAtLeast(0x7f06ad45b1d8, 0xc0221ba8f0, 0xc0229c5c74, 0xc, 0xc, 0xc, 0xc, 0x0, 0x0)
        /usr/local/go/src/io/io.go:314 +0x87
io.ReadFull(...)
        /usr/local/go/src/io/io.go:333
github.com/libp2p/go-yamux.(*Session).recvLoop(0xc021ba7770, 0x0, 0x0)
        /home/go/goProject/pkg/mod/github.com/libp2p/go-yamux@v1.4.1/session.go:564 +0xda
github.com/libp2p/go-yamux.(*Session).recv(0xc021ba7770)
        /home/go/goProject/pkg/mod/github.com/libp2p/go-yamux@v1.4.1/session.go:543 +0x2b
created by github.com/libp2p/go-yamux.newSession
        /home/go/goProject/pkg/mod/github.com/libp2p/go-yamux@v1.4.1/session.go:129 +0x3e8

goroutine 6213 [select]:
github.com/ipfs/go-bitswap/internal/messagequeue.(*MessageQueue).runQueue(0xc023cdf600)
        /home/go/goProject/pkg/mod/github.com/ipfs/go-bitswap@v0.3.2/internal/messagequeue/messagequeue.go:405 +0x25d
created by github.com/ipfs/go-bitswap/internal/messagequeue.(*MessageQueue).Startup
        /home/go/goProject/pkg/mod/github.com/ipfs/go-bitswap@v0.3.2/internal/messagequeue/messagequeue.go:374 +0x98

goroutine 6133 [chan receive]:
github.com/ipfs/go-graphsync/notifications.(*publisher).start(0xc0233a9110)
        /home/go/goProject/pkg/mod/github.com/ipfs/go-graphsync@v0.5.2/notifications/publisher.go:114 +0x1ba
created by github.com/ipfs/go-graphsync/notifications.(*publisher).Startup
        /home/go/goProject/pkg/mod/github.com/ipfs/go-graphsync@v0.5.2/notifications/publisher.go:39 +0x3f

rax    0x862a043dd8fb9cc5
rbx    0x4ae8760
rcx    0x4ae8980
rdx    0xf4df1f341c341746
rdi    0x583d2933624e7658
rsi    0x7f06b4921f90
rbp    0x17c85789e74a3596
rsp    0x7f06b4921f80
r8     0x89f3fffcfffcfffd
r9     0xaff39d8a0467a41e
r10    0x862a043dd8fb9cc5
r11    0x46c9f74fe9260666
r12    0x46c9f74fe9260666
r13    0x4ae8760
r14    0x6aab896f78814b4f
r15    0xaff39d8a0467a41e
rip    0x261a381
rflags 0x10286
cs     0x33
fs     0x0
gs     0x0

**Comment by LyyDandelion** [comment]
I try the relase version(v1.4.1),get same error results.

**Comment by LyyDandelion** [comment]
I find the many issues have this condition.why!

**Comment by LyyDandelion** [comment]
I finded
