### ISSUE TITLE
pc2 error and back to pc1

### ISSUE THREAD

**Issue by yann1989** [filecoin-project/lotus#5706]
2021-03-03T13:21:39.988 INFO filcrypto::proofs::api > seal_pre_commit_phase2: start
2021-03-03T13:21:40.000 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:start
2021-03-03T13:21:40.004 INFO filecoin_proofs::api > validate_cache_for_precommit_phase2:finish
2021-03-03T13:21:40.010 INFO filecoin_proofs::api::seal > seal_pre_commit_phase2:start
2021-03-03T13:21:40.019 INFO storage_proofs_porep::stacked::vanilla::proof > replicate_phase2
2021-03-03T13:21:40.035 INFO storage_proofs_porep::stacked::vanilla::proof > generating tree c using the GPU
2021-03-03T13:21:40.035 INFO storage_proofs_porep::stacked::vanilla::proof > Building column hashes
2021-03-03T13:21:40.044 INFO neptune::triton::cl > getting default futhark context
2021-03-03T13:21:40.047 INFO neptune::triton::cl > getting context for ~Index(0)
thread '<unnamed>' panicked at 'failed to create ColumnTreeBuilder: ClError(BusIdNotAvailable)', /root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/proof.rs:516:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to send columns: "SendError(..)"', /root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/proof.rs:502:34

**Comment by jburnett** [comment]
We're experiencing this panic as well. This miner is not able to proceed to PC2 at all.
Ubuntu 20.04 srv; NVidia Quadro M5000 using 460.39 drivers (2/21/2021).

Key time frame is 03-02T16:09 in attached files:
1. [systemd-miner-20210302-edited.log](https://github.com/filecoin-project/lotus/files/6077231/systemd-miner-20210302-edited.log): includes Rust full backtraces
2. [miner-20210302-2056.log](https://github.com/filecoin-project/lotus/files/6077233/miner-20210302-2056.log): notice "caller":"storage-sealing/states_failed.go:25","msg":"SealPreCommit2Failed(3)..." 
3. [daemon-20210302-partial.log](https://github.com/filecoin-project/lotus/files/6077230/daemon-20210302-partial.log): included in case relevant to others

Most other miners are using older version of NVidia drivers.  We'll install 450.66 and see if that changes our results.
