### ISSUE TITLE
[BUG] GetPaych hangs if called with an amount of zero

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/lotus#5824]
I have an existing payment channel with funds, and I call `GetPaych` with an amount of 0. This seems to hang indefinitely.

**Comment by whyrusleeping** [comment]
And if i call `GetPaych` with an amount equal to the available balance, It then sends that much to the channel. Thats... not what I wanted it to do.

**Comment by whyrusleeping** [comment]
Heres a stack showing the hang: 
```
goroutine 3049 [select, 2 minutes]:
github.com/filecoin-project/lotus/paychmgr.(*channelAccessor).getPaych(0xc000207080, 0x2fdadd0, 0xc0000440d8, 0xc002982520, 0x3, 0xc000207080, 0x0, 0x0, 0x0, 0x0)
	/home/why/code/lotus/paychmgr/simple.go:163 +0x14f
github.com/filecoin-project/lotus/paychmgr.(*Manager).GetPaych(0xc000253860, 0x2fdadd0, 0xc0000440d8, 0xc00075a580, 0x31, 0xc00063e0bb, 0x3, 0xc002982520, 0x0, 0xc000030f90, ...)
	/home/why/code/lotus/paychmgr/manager.go:109 +0xfc
github.com/whyrusleeping/estuary/filclient.(*FilClient).RetrieveContent(0xc00039c2a0, 0x2fdadd0, 0xc0000440d8, 0xc000ea06a5, 0x3, 0xc002dbcb40, 0x3, 0x6)
	/home/why/code/estuary/filclient/filclient.go:740 +0x527
main.(*ContentManager).tryRetrieve(0xc002592600, 0x2fdadd0, 0xc0000440d8, 0xc000ea06a5, 0x3, 0xc002f98690, 0x22, 0xc003b0b920, 0x6, 0x6)
	/home/why/code/estuary/retrieval.go:109 +0x110
main.(*ContentManager).runRetrieval(0xc002592600, 0x2fdadd0, 0xc0000440d8, 0xc, 0xc002cb5300, 0xc002cb53c8)
	/home/why/code/estuary/replication.go:1125 +0xb39
main.(*ContentManager).retrieveContent(0xc002592600, 0x2fdadd0, 0xc0000440d8, 0xc, 0x0, 0x0)
	/home/why/code/estuary/replication.go:1077 +0x227
main.(*ContentManager).RefreshContent(0xc002592600, 0x2fdadd0, 0xc0000440d8, 0xc, 0x0, 0xc000e80c00)
	/home/why/code/estuary/replication.go:1045 +0x2e6
main.(*Server).handleRefreshContent(0xc00288d800, 0x3000688, 0xc0003f9b80, 0x0, 0xc001f12b40)
	/home/why/code/estuary/handlers.go:651 +0xc5
github.com/labstack/echo/v4.(*Echo).add.func1(0x3000688, 0xc0003f9b80, 0x0, 0x0)
	/home/why/go/pkg/mod/github.com/labstack/echo/v4@v4.2.0/echo.go:536 +0x62
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1(0x3000688, 0xc0003f9b80, 0x1, 0x1)
	/home/why/go/pkg/mod/github.com/labstack/echo/v4@v4.2.0/middleware/cors.go:118 +0x15a5
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc00003ea00, 0x2fd2cc0, 0xc002fac000, 0xc001693000)
	/home/why/go/pkg/mod/github.com/labstack/echo/v4@v4.2.0/echo.go:646 +0x2ce
net/http.serverHandler.ServeHTTP(0xc002db21c0, 0x2fd2cc0, 0xc002fac000, 0xc001693000)
	/usr/lib/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc0003f9a40, 0x2fdae40, 0xc00151bd40)
	/usr/lib/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:3013 +0x39b
```

**Comment by whyrusleeping** [comment]
The above call stack is the result of me calling GetPaych for a channel that already exists and has funds, and im requesting 0.2 FIL from it. I believe the channel already has the proper funds in it. 

Notable:
processQueue runs, and exits through the `if res == nil {` return branch, which seems odd...

**Comment by dirkmc** [comment]
I want to make sure I understand the ask here - why do you want to call GetPaych with an amount of zero?

> And if i call GetPaych with an amount equal to the available balance, It then sends that much to the channel

With regards to the "always add" behaviour of GetPaych, I believe the thinking there is that it's complex to keep track of and query the amount of FIL that is pending landing on chain, particularly when dealing with error states. So we went the simpler route of just always adding and letting the caller keep track of the accounting.

**Comment by raulk** [comment]
@whyrusleeping ^^ question
