### ISSUE TITLE
[BUG]  Query ask causes segmentation violation

### ISSUE THREAD

**Issue by marvic2409** [filecoin-project/lotus#5933]
When running ```lotus client query-ask minerid``` lotus fails and returns:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1404b8c]

goroutine 1 [running]:
github.com/filecoin-project/lotus/cli.glob..func22(0xc000ed2200, 0x0, 0x0)
        /home/user/lotus/cli/client.go:1495 +0xaec
github.com/urfave/cli/v2.(*Command).Run(0x5aaaaa0, 0xc000ed2080, 0x0, 0x0)
        /home/user/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4dd
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc001302a80, 0xc00137dd80, 0x0, 0x0)
        /home/user/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:427 +0xa49
github.com/urfave/cli/v2.(*Command).startApp(0x5aab700, 0xc00137dd80, 0x7ffd91b21407, 0x6)
        /home/user/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x6bb
github.com/urfave/cli/v2.(*Command).Run(0x5aab700, 0xc00137dd80, 0x0, 0x0)
        /home/user/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:94 +0x9cd
github.com/urfave/cli/v2.(*App).RunContext(0xc001302900, 0x3447050, 0xc000040160, 0xc00003c080, 0x4, 0x4, 0x0, 0x0)
        /home/user/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
        /home/user/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
github.com/filecoin-project/lotus/cli.RunApp(0xc001302900)
        /home/user/lotus/cli/helper.go:35 +0x7c
main.main()
        /home/user/lotus/cmd/lotus/main.go:75 +0x647
```

I'm not very familiar with GoLang so I have no clue whats going on.

**Comment by magik6k** [comment]
What version are you running (`lotus version`)

**Comment by marvic2409** [comment]
Daemon:  1.7.0-dev+mainnet+git.f10bb9e23+api1.1.0
Local: lotus version 1.7.0-dev+mainnet+git.f10bb9e23

**Comment by jennijuju** [comment]
@marvic2409 we aren't able to reproduce this issue - do you still face this issue and share how we may repro it?

**Comment by marvic2409** [comment]
I don't have the issue anymore. Thanks!
