### ISSUE TITLE
[Mining Issue]

### ISSUE THREAD

**Issue by ZyanWlayor** [filecoin-project/lotus#6089]
**Describe the problem**
My lotusworker run into a mistake randomly with some strange logs when process precommit1.

**Version**

lotus-worker version 1.6.0+mainnet+git.3fc23a785c

**Setup**
My machine have a AMD EPYC 7542 32-Core Processor,1TB ECC RAM and a NVIDIA GeForce RTX 2080 Ti

**Lotus daemon and miner logs**

2021-04-21T22:33:21.776 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > generated layer 2 store with id layer-2
2021-04-21T22:33:21.776 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 3
2021-04-21T22:33:21.777 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 3
2021-04-21T22:33:21.777 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.777 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.777 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.823 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > generated layer 2 store with id layer-2
2021-04-21T22:33:21.823 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 3
2021-04-21T22:33:21.823 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 3
2021-04-21T22:33:21.824 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.824 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.824 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.882 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > generated layer 2 store with id layer-2
2021-04-21T22:33:21.882 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 3
2021-04-21T22:33:21.882 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 3
2021-04-21T22:33:21.883 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.883 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.883 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.941 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > generated layer 2 store with id layer-2
2021-04-21T22:33:21.941 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 3
2021-04-21T22:33:21.941 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 3
2021-04-21T22:33:21.952 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.952 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.952 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.996 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > generated layer 2 store with id layer-2
2021-04-21T22:33:21.996 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Layer 3
2021-04-21T22:33:21.996 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > Creating labels for layer 3
2021-04-21T22:33:21.996 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.996 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner
2021-04-21T22:33:21.996 INFO storage_proofs_porep::stacked::vanilla::create_label::multi > created label runner

thread 'thread 'thread '' panicked at 'thread 'thread 'range end index 18089479344 out of range for slice of length 17179869184thread 'thread '' panicked at 'thread '' panicked at '', ' panicked at 'range end index 18089479344 out of range for slice of length 17179869184' panicked at 'range end index 25025297232 out of range for slice of length 17179869184' panicked at 'range end index 18089479344 out of range for slice of length 17179869184' panicked at '', ' panicked at 'range end index 25025297232 out of range for slice of length 17179869184', range end index 25025297232 out of range for slice of length 17179869184', range end index 18089479344 out of range for slice of length 17179869184range end index 25025297232 out of range for slice of length 17179869184', ', ', ', /root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs:/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs:::112::::112112112:112112112112:::18::::181818
18181818

note: run with RUST_BACKTRACE=1 environment variable to display a backtrace

thread 'thread '' panicked at '' panicked at 'range end index 18089479344 out of range for slice of length 17179869184range end index 25025297232 out of range for slice of length 17179869184', ', /root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs::112112::1818

thread 'thread '' panicked at '' panicked at 'range end index 25025297232 out of range for slice of length 17179869184range end index 18089479344 out of range for slice of length 17179869184', ', /root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs/root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs::112112::1818

thread '' panicked at 'range end index 18089479344 out of range for slice of length 17179869184', /root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs:112:18
thread '' panicked at 'range end index 25025297232 out of range for slice of length 17179869184', /root/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/storage-proofs-porep-5.4.0/src/stacked/vanilla/create_label/multi.rs:112:18

** Code modifications **
no

**Comment by CodingJzy** [comment]
你是个人挖矿还是矿商呀

**Comment by rjan90** [comment]
Hi, I think this issue has been fixed on newer versions of Lotus, and can be closed now? #rengjøring
