### ISSUE TITLE
Getting `panic: runtime error: invalid memory address or nil pointer dereference` when running `lotus daemon`.

### ISSUE THREAD

**Issue by johnnymatthews** [filecoin-project/lotus#6596]
**Describe the bug**
Attempting to run `FULLNODE_API_INFO=wss://api.chain.love lotus daemon --lite` gives me a `panic: runtime error: invalid memory address or nil pointer dereference` error.

**Version (run `lotus version`):**
Can't run `lotus version` since `lotus daemon` won't run, but `lotus --version` gives me `lotus version 1.10.0+mainnet+git.764fa9dae`

OS:

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

**To Reproduce**
This is a bit of a tricky one, since this is clearly an issue with something in my personal `.lotus` folder, and likely can't be reproduced easily by anyone else here...

**Logs**
Here's what Lotus spits out after running `FULLNODE_API_INFO=wss://api.chain.love lotus daemon --lite`

```
λ › FULLNODE_API_INFO=wss://api.chain.love lotus daemon --lite                                                                                        ~
2021-06-25T10:54:11.342-0400    INFO    main    lotus/daemon.go:214     lotus repo: /home/controller/.lotus
2021-06-25T10:54:11.352-0400    WARN    cliutil util/apiinfo.go:81      API Token not set and requested, capabilities might be limited.
2021-06-25T10:54:11.568-0400    INFO    modules modules/core.go:64      memory limits initialized       {"max_mem_heap": 0, "total_system_mem": 16995692544, "effective_mem_limit": 16995692544}
2021-06-25T10:54:11.571-0400    WARN    modules modules/core.go:124     failed to initialize cgroup-driven watchdog; err: failed to load cgroup for process: unable to find subsystem memory
2021-06-25T10:54:11.572-0400    WARN    modules modules/core.go:125     trying a system-driven watchdog
2021-06-25T10:54:11.572-0400    INFO    watchdog        go-watchdog@v1.0.1/watermarks.go:16     initialized watermark watchdog policy; watermarks: []; thresholds: [8497846272 10197415526 11896984780 14446338662 15296123289 15721015603 16145907916]
2021-06-25T10:54:11.573-0400    INFO    watchdog        go-watchdog@v1.0.1/watchdog.go:457      initialized heap profile capture; threshold: 0.900000; max captures: 10; dir: /home/controller/.lotus/heapprof
2021-06-25T10:54:11.573-0400    INFO    modules modules/core.go:130     initialized system-driven watchdog
2021-06-25T10:54:11.642-0400    INFO    badger  v2@v2.2007.2/levels.go:183      All 0 tables opened in 0s

2021-06-25T10:54:11.644-0400    INFO    badger  v2@v2.2007.2/value.go:1158      Replaying file id: 0 at offset: 0

2021-06-25T10:54:11.645-0400    INFO    badger  v2@v2.2007.2/value.go:1178      Replay took: 83.8µs

2021-06-25T10:54:11.656-0400    INFO    badger  v2@v2.2007.2/levels.go:183      All 1 tables opened in 0s

2021-06-25T10:54:11.663-0400    INFO    badger  v2@v2.2007.2/value.go:1158      Replaying file id: 7 at offset: 216660584

2021-06-25T10:54:11.665-0400    INFO    badger  v2@v2.2007.2/value.go:1178      Replay took: 2.1343ms

2021-06-25T10:54:11.668-0400    INFO    backupds        backupds/log.go:125     opening log     {"file": "/home/controller/.lotus/kvlog/metadata/1624565125.log.cbor"}
2021-06-25T10:54:12.553-0400    INFO    backupds        backupds/log.go:205     log opened      {"file": "/home/controller/.lotus/kvlog/metadata/1624565125.log.cbor", "openCount": 14, "baseValues": 9761, "logValues": 18727}
2021-06-25T10:54:12.556-0400    INFO    backupds        backupds/log.go:230     new log head    {"loghead": "1624565125.log.cbor;a5de4415-260e-4fea-9a7a-9c9beb73c1e8;1624632852"}
2021-06-25T10:54:12.568-0400    INFO    badgerbs        v2@v2.2007.2/levels.go:183      All 1 tables opened in 1ms

2021-06-25T10:54:12.578-0400    INFO    badgerbs        v2@v2.2007.2/value.go:1158      Replaying file id: 0 at offset: 13886362

2021-06-25T10:54:12.622-0400    INFO    badgerbs        v2@v2.2007.2/value.go:1178      Replay took: 43.6758ms

2021-06-25T10:54:12.643-0400    INFO    p2pnode lp2p/addrs.go:114       Swarm listening at: [/ip4/192.168.0.17/tcp/57788 /ip4/169.254.147.19/tcp/57788 /ip4/127.0.0.1/tcp/57788 /ip4/169.254.104.43/tcp/57788 /ip4/169.254.227.196/tcp/57788 /ip4/169.254.85.219/tcp/57788 /ip6/fd00:f81d:fb4:ce72:8887:f3c0:de1c:b88c/tcp/57789 /ip6/2607:f2c0:e2be:b2:8887:f3c0:de1c:b88c/tcp/57789 /ip6/2607:f2c0:e2be:b2::9/tcp/57789 /ip6/2607:f2c0:e2be:b2:f5bc:d461:5c7f:592f/tcp/57789 /ip6/fd00:f81d:fb4:ce72:f5bc:d461:5c7f:592f/tcp/57789 /ip6/::1/tcp/57789]
2021-06-25T10:54:12.689-0400    INFO    messagepool     messagepool/messagepool.go:421  mpool ready
2021-06-25T10:54:12.691-0400    INFO    dt-chanmon      channelmonitor/channelmonitor.go:195    Starting data-transfer channel monitor with 10 checks per 1m0s interval (check interval 6s); min bytes per interval: 1024, restart backoff: 1m0s; max consecutive restarts: 3
2021-06-25T10:54:12.737-0400    INFO    dt-impl impl/impl.go:144        start data-transfer module
2021-06-25T10:54:12.750-0400    INFO    markets loggers/loggers.go:56   module ready    {"module": "client data transfer"}
2021-06-25T10:54:12.754-0400    INFO    markets loggers/loggers.go:56   module ready    {"module": "retrieval client"}
2021-06-25T10:54:12.758-0400    INFO    markets loggers/loggers.go:56   module ready    {"module": "discovery"}
2021-06-25T10:54:12.761-0400    INFO    markets loggers/loggers.go:56   module ready    {"module": "storage client"}
2021-06-25T10:54:12.863-0400    INFO    markets loggers/loggers.go:15   storage client event    {"name": "ClientEventRestart", "proposal CID": "bafyreic6tzcs7ph3otsrrmsprrc7nhshqhx5rz4pcbo24oqiau3qnbowgq", "state": "StorageDealAwaitingPreCommit", "message": ""}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1514062]

goroutine 265 [running]:
github.com/filecoin-project/lotus/extern/storage-sealing.(*CurrentDealInfoManager).dealIDFromPublishDealsMsg(0xc000301c40, 0x365c070, 0xc000122008, 0xc013da0480, 0xbe, 0xc0, 0xc013cab780, 0xc013cde900, 0x26, 0xc002870908, ...)
        /home/controller/lotus/extern/storage-sealing/currentdealinfo.go:72 +0xa2
github.com/filecoin-project/lotus/extern/storage-sealing.(*CurrentDealInfoManager).GetCurrentDealInfo(0xc000301c40, 0x365c070, 0xc000122008, 0xc013da0480, 0xbe, 0xc0, 0xc013cab780, 0xc013cde900, 0x26, 0x0, ...)
        /home/controller/lotus/extern/storage-sealing/currentdealinfo.go:41 +0xca
github.com/filecoin-project/lotus/markets/storageadapter.(*SectorCommittedManager).checkIfDealAlreadyActive(0xc0025e5f20, 0x365c070, 0xc000122008, 0xc00286a240, 0xc013cab780, 0xc013cde900, 0x26, 0x0, 0x0, 0x0, ...)
        /home/controller/lotus/markets/storageadapter/ondealsectorcommitted.go:335 +0x126
github.com/filecoin-project/lotus/markets/storageadapter.(*SectorCommittedManager).OnDealSectorPreCommitted.func2(0xc00286a240, 0xc00286a240, 0x0, 0x0)
        /home/controller/lotus/markets/storageadapter/ondealsectorcommitted.go:68 +0xd4
github.com/filecoin-project/lotus/chain/events.(*hcEvents).onHeadChanged(0xc000e79e60, 0xc000142be0, 0xc0025b0408, 0x34327a8, 0x6, 0xdb87b, 0x0, 0x0, 0x0)
        /home/controller/lotus/chain/events/events_called.go:318 +0x18b
github.com/filecoin-project/lotus/chain/events.(*messageEvents).Called(0xc000e79ec8, 0xc000142be0, 0xc0003dd240, 0x34327a8, 0x6, 0xdb87b, 0xc0025b03f0, 0x0, 0x0)
        /home/controller/lotus/chain/events/events_called.go:602 +0xc9
github.com/filecoin-project/lotus/markets/storageadapter.(*SectorCommittedManager).OnDealSectorPreCommitted(0xc0025e5f20, 0x365c070, 0xc000122008, 0xc001a8c728, 0x4, 0xc013cde540, 0x27, 0x40000000, 0x0, 0xc000056660, ...)
        /home/controller/lotus/markets/storageadapter/ondealsectorcommitted.go:168 +0x2fe
github.com/filecoin-project/lotus/markets/storageadapter.(*ClientNodeAdapter).OnDealSectorPreCommitted(0xc0025e5ef0, 0x365c070, 0xc000122008, 0xc001a8c728, 0x4, 0x20f1f8, 0xc013cde540, 0x27, 0x40000000, 0x0, ...)
        /home/controller/lotus/markets/storageadapter/client.go:236 +0xd8
github.com/filecoin-project/go-fil-markets/storagemarket/impl/clientstates.VerifyDealPreCommitted(0x7fdfc270c8f8, 0xc002861950, 0x7fdfc270c920, 0xc000306470, 0xc013cde540, 0x27, 0x40000000, 0x0, 0xc000056660, 0x15, ...)
        /home/controller/go/pkg/mod/github.com/filecoin-project/go-fil-markets@v1.2.5/storagemarket/impl/clientstates/client_states.go:256 +0x16d
reflect.Value.call(0x2e0c1c0, 0x34316c8, 0x13, 0x3183680, 0x4, 0xc002871728, 0x3, 0x3, 0x5606ff, 0x2fe2420, ...)
        /usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x2e0c1c0, 0x34316c8, 0x13, 0xc002886728, 0x3, 0x3, 0x53, 0x53, 0x1)
        /usr/local/go/src/reflect/value.go:337 +0xb9
github.com/filecoin-project/go-statemachine/fsm.fsmHandler.handler.func1(0xc013da87e0, 0x2, 0x2, 0xc013da87e0, 0x292453eb538a6b36, 0xc0003da410)
        /home/controller/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/fsm/fsm.go:170 +0x437
reflect.Value.call(0xc001209ce0, 0xc013da8780, 0x13, 0x3183680, 0x4, 0xc002886f70, 0x2, 0x2, 0x5606ff, 0x2efeea0, ...)
        /usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc001209ce0, 0xc013da8780, 0x13, 0xc0003e5770, 0x2, 0x2, 0xc001209bc0, 0xc0003dd1c0, 0x0)
        /usr/local/go/src/reflect/value.go:337 +0xb9
github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc0003a98c0, 0x365c070, 0xc000122008, 0xc0003a9a70, 0xc0003a98d0, 0xc001209bc0)
        /home/controller/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:102 +0x2c9
created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
        /home/controller/go/pkg/mod/github.com/filecoin-project/go-statemachine@v0.0.0-20200925024713-05bd7c71fbfe/machine.go:100 +0x372
```

**Additional context**
I've tried changing to different Lotus branches (`master` and `v1.9.0`) but that didn't fix this. I'm _guessing_ that someone's gone wrong with the datastore in my `.lotus` folder, but I've no idea how to start debugging this.

**Comment by raulk** [comment]
@johnnymatthews Thanks for reporting this. Could you please go into your `$LOTUS_HOME/journal` directory and paste the output of `grep bafyreic6tzcs7ph3otsrrmsprrc7nhshqhx5rz4pcbo24oqiau3qnbowgq *`?

Thanks!

**Comment by johnnymatthews** [comment]
Oh boy, I made a  huge mistake. I essentially did the Windows Subsystem for Linux (WSL) version of `rm -rf /` and uninstalled the Ubuntu app, so now I don't have anything. I'm gonna close this issue. I'll re-attempt what I was doing _before_ I got this error, and I'll reopen this issue if I get the same problem.

**Comment by whhpc19891120** [comment]
I have the problem too , does it resolved ?

**Comment by johnnymatthews** [comment]
@whhpc19891120 unfortunately not. I wasn't able to debug the issue further because I deleted my OS.
