### ISSUE TITLE
[BUG] panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by frankffenn** [filecoin-project/lotus#6641]
> Note: For security-related bugs/issues, please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).

**Describe the bug**
FailedSectors are not initialized 

```
panic: assignment to entry in nil map

goroutine 49348 [running]:
github.com/filecoin-project/lotus/extern/storage-sealing.(*CommitBatcher).processBatch(0xc00e02c540, 0x28, 0x0, 0x0, 0x68c61714000, 0x10000, 0x32, 0x1a3185c5000, 0x9d29229e000, 0x1, ...)
        /root/golang/gopath/src/github.com/filecoin-project/lotus/extern/storage-sealing/commit_batch.go:250 +0x4b7
github.com/filecoin-project/lotus/extern/storage-sealing.(*CommitBatcher).maybeStartBatch(0xc00e02c540, 0xc00da38e01, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/golang/gopath/src/github.com/filecoin-project/lotus/extern/storage-sealing/commit_batch.go:197 +0x5c5
github.com/filecoin-project/lotus/extern/storage-sealing.(*CommitBatcher).run(0xc00e02c540)
        /root/golang/gopath/src/github.com/filecoin-project/lotus/extern/storage-sealing/commit_batch.go:126 +0x234
created by github.com/filecoin-project/lotus/extern/storage-sealing.NewCommitBatcher
        /root/golang/gopath/src/github.com/filecoin-project/lotus/extern/storage-sealing/commit_batch.go:90 +0x245
```

**Version (run `lotus version`):**
Daemon:  1.10.0+mainnet+git.79ae224b8+api1.3.0
Local: lotus version 1.10.0+mainnet+git.79ae224b8

**Comment by magik6k** [comment]
Thanks for reporting this, the fix is in https://github.com/filecoin-project/lotus/pull/6647, and will be included in v1.10.1 as well
