### ISSUE TITLE
[BUG] lotus client deal => panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/lotus#6816]
**Describe the bug**

When trying to make a deal, lotus client panics.

This has been observed with 2 different miners on the network: `f01016240` and `f01075157`.

**Version (run `lotus version`):**

```
Daemon:  1.11.1-dev+mainnet+git.c1f0ebbef+api1.3.0
Local: lotus version 1.11.1-dev+mainnet+git.c1f0ebbef
```

**To Reproduce**

```
$ lotus client deal
Data CID (from lotus client import): bafk2bzaced4dne5p7dcfhundap5r3bcceid5n23vxw2ajimns3z77ze7mfg6i
.. calculating data size
Deal duration (days): 180
Miner Addresses (f0.. f0..), none to find: f01075157
.. querying miner asks
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16b30b6]

goroutine 1 [running]:
github.com/filecoin-project/lotus/cli.interactiveDeal(0xc000c5ef40, 0x0, 0x0)
	/home/ubuntu/lotus/cli/client.go:855 +0xa56
github.com/filecoin-project/lotus/cli.glob..func21(0xc000c5ef40, 0x0, 0x0)
	/home/ubuntu/lotus/cli/client.go:357 +0x1466
github.com/urfave/cli/v2.(*Command).Run(0x53cb8c0, 0xc000c5ec40, 0x0, 0x0)
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x4dd
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000103500, 0xc000c5e940, 0x0, 0x0)
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:427 +0xa49
github.com/urfave/cli/v2.(*Command).startApp(0x53c1240, 0xc000c5e940, 0x7ffe1dfc069d, 0x6)
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x6bb
github.com/urfave/cli/v2.(*Command).Run(0x53c1240, 0xc000c5e940, 0x0, 0x0)
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:94 +0x9cd
github.com/urfave/cli/v2.(*App).RunContext(0xc000103380, 0x4033cf0, 0xc000052078, 0xc00004e090, 0x3, 0x3, 0x0, 0x0)
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x810
github.com/urfave/cli/v2.(*App).Run(...)
	/home/ubuntu/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
github.com/filecoin-project/lotus/cli.RunApp(0xc000103380)
	/home/ubuntu/lotus/cli/helper.go:35 +0x7c
main.main()
	/home/ubuntu/lotus/cmd/lotus/main.go:92 +0x707
```

**Comment by rjan90** [comment]
Closing as outdated!
