### ISSUE TITLE
panic: runtime error for market node

### ISSUE THREAD

**Issue by tmyuu** [filecoin-project/lotus#6951]
### Checklist

- [x] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

lotus miner/market - storage deal

### Lotus Version

```text
Daemon:  1.11.1-rc1+mainnet+git.7d70ef79a+api1.3.1
Local: lotus version 1.11.1-rc1+mainnet+git.7d70ef79a
```

### Describe the Bug

Market node crashed suddenly.
There is another issue that failed sectors are under recovering because I had got a gas related error during batch processing, so I have no idea what the direct cause of error is at this point. Please let me know if you have the required log.

### Logging Information

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x15b7096]

goroutine 1001982 [running]:
github.com/ipld/go-car.(*selectiveCarTraverser).loader(0xc051270ae0, 0x37a9020, 0xc053f04630, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/code/.go/pkg/mod/github.com/ipld/go-car@v0.1.1-0.20201119040415-11b6074b6d4d/selectivecar.go:218 +0x76
github.com/ipld/go-ipld-prime/linking/cid.Link.Load(0xc0158ffdd0, 0x22, 0x37b3570, 0xc0001a8858, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/code/.go/pkg/mod/github.com/ipld/go-ipld-prime@v0.5.1-0.20201021195245-109253e8a018/linking/cid/cidLink.go:29 +0xa6
github.com/ipld/go-car.(*selectiveCarTraverser).traverseBlocks(0xc051270ae0, 0x0, 0x0)
	/home/code/.go/pkg/mod/github.com/ipld/go-car@v0.1.1-0.20201119040415-11b6074b6d4d/selectivecar.go:257 +0x27f
github.com/ipld/go-car.(*selectiveCarTraverser).traverse(0xc051270ae0, 0xc051270ae0, 0x561bf8, 0x10)
	/home/code/.go/pkg/mod/github.com/ipld/go-car@v0.1.1-0.20201119040415-11b6074b6d4d/selectivecar.go:184 +0x50
github.com/ipld/go-car.SelectiveCar.traverse(0x37b3570, 0xc0001a8858, 0xc02fecc260, 0x1, 0x1, 0x0, 0x0, 0xc053f04530, 0xc053f04540, 0x120, ...)
	/home/code/.go/pkg/mod/github.com/ipld/go-car@v0.1.1-0.20201119040415-11b6074b6d4d/selectivecar.go:71 +0xe5
github.com/ipld/go-car.SelectiveCar.Prepare(0x37b3570, 0xc0001a8858, 0xc02fecc260, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/code/.go/pkg/mod/github.com/ipld/go-car@v0.1.1-0.20201119040415-11b6074b6d4d/selectivecar.go:88 +0x13f
github.com/filecoin-project/go-commp-utils/pieceio/cario.carIO.PrepareCar(0x37b3570, 0xc0001a8858, 0x0, 0x0, 0xc0158ffdd0, 0x22, 0x37e0f58, 0xc04194ff60, 0x0, 0x0, ...)
	/home/code/.go/pkg/mod/github.com/filecoin-project/go-commp-utils@v0.1.1-0.20210427191551-70bf140d31c7/pieceio/cario/cario.go:30 +0x21b
github.com/filecoin-project/go-commp-utils/pieceio.(*pieceIO).GeneratePieceReader(0xc00c5c0060, 0xc0158ffdd0, 0x22, 0x37e0f58, 0xc04194ff60, 0x0, 0x0, 0x0, 0x0, 0x379e210, ...)
	/home/code/.go/pkg/mod/github.com/filecoin-project/go-commp-utils@v0.1.1-0.20210427191551-70bf140d31c7/pieceio/pieceio.go:57 +0x143
github.com/filecoin-project/go-fil-markets/storagemarket/impl.(*providerDealEnvironment).GeneratePieceReader(0xc0001ac878, 0x0, 0xc0158ffdd0, 0x22, 0x37e0f58, 0xc04194ff60, 0xc00026e5c0, 0xc01cd36f00, 0x699c77, 0x37728c0, ...)
	/home/code/.go/pkg/mod/github.com/filecoin-project/go-fil-markets@v1.6.2/storagemarket/impl/provider_environments.go:92 +0x90
github.com/filecoin-project/go-fil-markets/storagemarket/impl/providerstates.HandoffDeal(0x7fdf54031548, 0xc02bddacf0, 0x7fdf54031570, 0xc0001ac878, 0xc0158ff9e0, 0x27, 0x80000000, 0x1, 0xc0259db340, 0x31, ...)
	/home/code/.go/pkg/mod/github.com/filecoin-project/go-fil-markets@v1.6.2/storagemarket/impl/providerstates/provider_states.go:319 +0x956
reflect.Value.call(0x2f2bd00, 0x3574968, 0x13, 0x32b19fb, 0x4, 0xc01cd376c0, 0x3, 0x3, 0x55ecdf, 0x310a4a0, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x2f2bd00, 0x3574968, 0x13, 0xc01cd376c0, 0x3, 0x3, 0xc013fe46d0, 0x14e5ad0, 0xc03050e680)
	/usr/local/go/src/reflect/value.go:337 +0xb9
github.com/filecoin-project/go-statemachine/fsm.fsmHandler.handler.func1(0xc0150c1b60, 0x2, 0x2, 0xc0150c1b60, 0xfbbe56f1af1f1c00, 0x55)
	/home/code/.go/pkg/mod/github.com/filecoin-project/go-statemachine@v1.0.1/fsm/fsm.go:187 +0x437
reflect.Value.call(0xc0011bc240, 0xc0150c1b00, 0x13, 0x32b19fb, 0x4, 0xc013fe4f30, 0x2, 0x2, 0x55ecdf, 0x301fce0, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc0011bc240, 0xc0150c1b00, 0x13, 0xc00f9c0730, 0x2, 0x2, 0x4ea7ee0, 0x2f21ac0, 0x7fdfc8eb2900)
	/usr/local/go/src/reflect/value.go:337 +0xb9
github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc00e9da540, 0xc053f04240, 0x37b3570, 0xc0001a8870, 0xc053f04360, 0xc053f04250, 0xc00e9fc120)
	/home/code/.go/pkg/mod/github.com/filecoin-project/go-statemachine@v1.0.1/machine.go:108 +0x3cc
created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
	/home/code/.go/pkg/mod/github.com/filecoin-project/go-statemachine@v1.0.1/machine.go:103 +0x451
```

### Repo Steps

lotus daemon, the others subsystem node and lotus-worker with some tasks were running for recovering the sectors from failed status, and also for mining in normal operation.

**Comment by jacobheun** [comment]
@tmyuu did you happen to upgrade to an `m1.x` tag and then change to the RC?

**Comment by tmyuu** [comment]
@acobheun yes, I upgrade m1.2 to rc.

**Comment by tmyuu** [comment]
After updating version from m1.2 tag to v1.11.1-rc1, I solved panic shutdown by doing the following steps.

>Optional: If you have run m1.2 and have started a DAG store migration, do
>rm -rf ~/.lotusminer/dagStore to start fresh or you can keep it and lotus will pick it up.
https://github.com/filecoin-project/lotus/discussions/6852
