### ISSUE TITLE
WARN	sectors	storage-sealing/states_failed.go:357	piece 3 (of 8) of sector 16366 refers deal 2343888 with wrong PieceCID: baga6ea4seaqmzq6acl23axubdiv37xipnaz3qqtvwr57ekoaauviescphqnfwpi != baga6ea4seaqkloqjjw5nkhz5azw4g4bz5ylcshoh5ewbx6ex4tconddpmyttcda

### ISSUE THREAD

**Issue by cryptowhizzard** [filecoin-project/lotus#7231]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.11.3-dev+mainnet+git.7c484cae1
```

### Describe the Bug

piece 0 (of 8) of sector 16366 refers deal 2348100 with wrong PieceCID: baga6ea4seaqdsvqopmj2soyhujb72jza76t4wpq5fzifvm3ctz47iyytkewnubq != baga6ea4seaqczc4oqkxdxb4yehllzffnjeeawricaotaorqgkk5mojviv2lkyei

After that a segfault of lotus-miner.

### Logging Information

```text
2021-08-31T12:22:51.716 INFO filecoin_proofs::api::winning_post > generate_winning_post:finish
2021-08-31T12:22:51.718 INFO filcrypto::proofs::api > generate_winning_post: finish
2021-08-31T12:22:51.718+0200	INFO	storageminer	storage/miner.go:297	GenerateWinningPoSt took 2.054941601s
2021-08-31T12:22:51.718+0200	INFO	miner	miner/warmup.go:75	winning PoSt warmup successful	{"took": 2.055493001}
2021-08-31T12:22:52.203+0200	INFO	stores	stores/index.go:142	New sector storage: 5c7fefe1-f7dd-404d-90f9-59f2b01e336d
2021-08-31T12:22:52.216+0200	INFO	node	impl/storminer.go:400	Connected to a remote worker at http://192.168.0.198:2346/rpc/v0
2021-08-31T12:22:52.544+0200	DEBUG	advmgr	sector-storage/sched.go:354	SCHED 0 queued; 12 open windows
2021-08-31T12:22:52.888+0200	INFO	stores	stores/index.go:142	New sector storage: 1c358e2f-347b-4a8d-ab5b-ba6b51e02968
2021-08-31T12:22:52.891+0200	INFO	node	impl/storminer.go:400	Connected to a remote worker at http://192.168.0.206:2345/rpc/v0
2021-08-31T12:22:52.894+0200	DEBUG	advmgr	sector-storage/sched.go:354	SCHED 0 queued; 14 open windows
2021-08-31T12:22:54.287+0200	INFO	stores	stores/index.go:142	New sector storage: 8adf5657-76ce-4e01-9b55-7b4ef6644389
2021-08-31T12:22:54.292+0200	INFO	node	impl/storminer.go:400	Connected to a remote worker at http://192.168.0.208:2345/rpc/v0
2021-08-31T12:22:54.294+0200	DEBUG	advmgr	sector-storage/sched.go:354	SCHED 0 queued; 16 open windows
2021-08-31T12:22:54.988+0200	WARN	rpc	go-jsonrpc@v0.1.4-0.20210217175800-45ea43ac2bec/handler.go:279	error in RPC call to 'Filecoin.StorageReportHealth': health report for unknown storage: b6a6a599-4db7-46b7-b6cd-5faa06a9a886:
    github.com/filecoin-project/lotus/extern/sector-storage/stores.(*Index).StorageReportHealth
        /root/lotus/extern/sector-storage/stores/index.go:184
2021-08-31T12:22:55.021+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.022+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.026+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.026+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.028+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.029+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.030+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.032+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.035+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.054+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.056+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.057+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.058+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.058+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.059+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.070+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.072+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.076+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.082+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.082+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.087+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.118+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.118+0200	ERROR	sectors	storage-sealing/fsm.go:456	unexpected sector update state: AddPieceFailed
2021-08-31T12:22:55.209+0200	DEBUG	advmgr	sector-storage/sched.go:354	SCHED 1 queued; 16 open windows
2021-08-31T12:22:55.210+0200	WARN	events	events/tscache.go:68	tipSetCache.get: cache is empty, requesting from storage (h=1068349)
2021-08-31T12:22:55.210+0200	WARN	events	events/tscache.go:68	tipSetCache.get: cache is empty, requesting from storage (h=1068349)
2021-08-31T12:22:55.210+0200	WARN	sectors	storage-sealing/states_failed.go:357	piece 0 (of 8) of sector 16366 refers deal 2348100 with wrong PieceCID: baga6ea4seaqdsvqopmj2soyhujb72jza76t4wpq5fzifvm3ctz47iyytkewnubq != baga6ea4seaqczc4oqkxdxb4yehllzffnjeeawricaotaorqgkk5mojviv2lkyei
2021-08-31T12:22:55.210+0200	WARN	events	events/tscache.go:68	tipSetCache.get: cache is empty, requesting from storage (h=1068323)
2021-08-31T12:22:55.210+0200	WARN	events	events/tscache.go:68	tipSetCache.get: cache is empty, requesting from storage (h=1068367)
2021-08-31T12:22:55.211+0200	WARN	events	events/tscache.go:68	tipSetCache.get: cache is empty, requesting from storage (h=1068424)
2021-08-31T12:22:55.212+0200	WARN	sectors	storage-sealing/states_failed.go:357	piece 2 (of 8) of sector 16366 refers deal 2343890 with wrong PieceCID: baga6ea4seaqmzq6acl23axubdiv37xipnaz3qqtvwr57ekoaauviescphqnfwpi != baga6ea4seaqijhl3xfpg4koet42zilg5arzoil3t4agxp5cbzaydeozelvxtyia
2021-08-31T12:22:55.212+0200	WARN	sectors	storage-sealing/states_failed.go:357	piece 3 (of 8) of sector 16366 refers deal 2343888 with wrong PieceCID: baga6ea4seaqmzq6acl23axubdiv37xipnaz3qqtvwr57ekoaauviescphqnfwpi != baga6ea4seaqkloqjjw5nkhz5azw4g4bz5ylcshoh5ewbx6ex4tconddpmyttcda
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13b4e5d]

goroutine 53803 [running]:
github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).HandleRecoverDealIDs(0xc0109e2d80, 0x373e4a0, 0xc031b21b48, 0xc0237886a0, 0xe, 0x3fee, 0x8, 0x612d33ef, 0xc00fe4e200, 0x8, ...)
	/root/lotus/extern/storage-sealing/states_failed.go:397 +0x65d
github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).plan.func2.1(0x3759170, 0xc000052940, 0xc032b9c710, 0xc0237886a0, 0xe, 0x3fee, 0x8, 0x612d33ef, 0xc00fe4e200, 0x8, ...)
	/root/lotus/extern/storage-sealing/fsm.go:357 +0xd5
github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).Plan.func1(0x3759170, 0xc000052940, 0xc032b9c710, 0xc0237886a0, 0xe, 0x3fee, 0x8, 0x612d33ef, 0xc00fe4e200, 0x8, ...)
	/root/lotus/extern/storage-sealing/fsm.go:26 +0x95
reflect.Value.call(0x2e56820, 0xc032b9c700, 0x13, 0x32389ab, 0x4, 0xc04d40af30, 0x2, 0x2, 0x54729f, 0x2f8dee0, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0x2e56820, 0xc032b9c700, 0x13, 0xc00029b730, 0x2, 0x2, 0x3791e50, 0x3077520, 0xc00029b7c8)
	/usr/local/go/src/reflect/value.go:337 +0xb9
github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc037655a70, 0xc03c8aad70, 0x3759170, 0xc000052940, 0xc032b9c710, 0xc03c8aad80, 0xc03a9f1da0)
	/root/go/pkg/mod/github.com/filecoin-project/go-statemachine@v1.0.1/machine.go:108 +0x3cc
created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
	/root/go/pkg/mod/github.com/filecoin-project/go-statemachine@v1.0.1/machine.go:103 +0x451
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by neondragon** [comment]
> {"level":"info","ts":"2021-08-31T12:39:39.849+0000","logger":"filcrypto::proofs::api","caller":"src/proofs/api.rs:987","msg":"generate_winning_post: finish"}
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13b137d]
> goroutine 1106 [running]:
> github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).HandleRecoverDealIDs(0xc0006c3080, 0x377cb60, 0xc019559698, 0xc011f840d0, 0xe, 0x1a3, 0x9, 0x61262f3d, 0xc00eebeb40, 0x2, ...)
> 	/root/lotus/extern/storage-sealing/states_failed.go:397 +0x65d
> github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).plan.func2.1(0x37976d0, 0xc0000528f0, 0xc000c80730, 0xc011f840d0, 0xe, 0x1a3, 0x9, 0x61262f3d, 0xc00eebeb40, 0x2, ...)
> 	/root/lotus/extern/storage-sealing/fsm.go:357 +0xd5
> github.com/filecoin-project/lotus/extern/storage-sealing.(*Sealing).Plan.func1(0x37976d0, 0xc0000528f0, 0xc000c80730, 0xc011f840d0, 0xe, 0x1a3, 0x9, 0x61262f3d, 0xc00eebeb40, 0x2, ...)
> 	/root/lotus/extern/storage-sealing/fsm.go:26 +0x95
> reflect.Value.call(0x2e98ce0, 0xc000c80720, 0x13, 0x3279185, 0x4, 0xc000630f30, 0x2, 0x2, 0x54723f, 0x2fcfc00, ...)
> 	/usr/local/go/src/reflect/value.go:476 +0x8e7
> reflect.Value.Call(0x2e98ce0, 0xc000c80720, 0x13, 0xc000cc4730, 0x2, 0x2, 0x0, 0x0, 0x0)
> 	/usr/local/go/src/reflect/value.go:337 +0xb9
> github.com/filecoin-project/go-statemachine.(*StateMachine).run.func3(0xc00eeece88, 0xc00ee9f650, 0x37976d0, 0xc0000528f0, 0xc000c80730, 0xc00ee9f660, 0xc0155d0300)
> 	/root/go/pkg/mod/github.com/filecoin-project/go-statemachine@v1.0.1/machine.go:108 +0x3cc
> created by github.com/filecoin-project/go-statemachine.(*StateMachine).run
> 	/root/go/pkg/mod/github.com/filecoin-project/go-statemachine@v1.0.1/machine.go:103 +0x451
