### ISSUE TITLE
v1.13.2-rc1 lotus offline import causes market node to crash and not restart

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#7723]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [X] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
lotus-miner version
Daemon:  1.13.2-rc1+mainnet+git.52c7fa242+api1.2.0
Local: lotus-miner version 1.13.2-rc1+mainnet+git.52c7fa242
```

### Describe the Bug

I was able to start the market node (located on a separate machine) with the new code.
But once I tried an offline lotus import, the market node crashed.
Upon trying to restart, the market node will not start displaying this error

> 2021-12-01T15:12:43.020Z	INFO	backupds	backupds/log.go:125	opening log	{"file": "/market/.lotusmarkets/kvlog/metadata/1637292955.log.cbor"}
ERROR: creating node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/home/stuart/lotus/node/modules/lp2p/addrs.go:85): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:14): failed to build lp2p.RawHost: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:14): could not build value group []config.Option[group="libp2p"]: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".ConnGaterOption (/home/stuart/lotus/node/modules/lp2p/conngater.go:14): failed to build *conngater.BasicConnectionGater: could not build arguments for function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:14): failed to build dtypes.MetadataDS: received non-nil error from function "reflect".makeFuncStub (/usr/local/go/src/reflect/asm_amd64.s:14): opening backupds: opening log: reading backup part of the logfile: log entry potentially truncated, set LOTUS_ALLOW_TRUNCATED_LOG=1 to proceed: EOF

### Logging Information

```text
See log at https://drive.google.com/file/d/1T1xKiOvs63znfYqUZ2emhfecZmPbJioK/view?usp=sharing
```

### Repo Steps

1. Run `LOTUS_MINER_PATH=/market/.lotusmarkets nohup lotus-miner run >> /market/logs/markets.log 2>&1 &`
2. Observe logs - see crash
3. See error '...'
...

**Comment by stuberman** [comment]
Added env "LOTUS_ALLOW_TRUNCATED_LOG=1" and restarting markets node.

**Comment by jennijuju** [comment]
Did restart then make another deal help or it keeps crash? 
Can you confirm market node was also updated to later at version?

**Comment by stuberman** [comment]
Still waiting for market node to fully come up.

**Comment by stuberman** [comment]
Logs shows this (have not tried an import yet)

> 2021-12-01T16:06:14.280Z	ERROR	backupds	backupds/read.go:102	log entry potentially truncated
2021-12-01T16:06:14.280Z	INFO	backupds	backupds/log.go:182	compacting log	{"current": "/market/.lotusmarkets/kvlog/metadata/1637292955.log.cbor", "openCount": 10, "baseValues": 11182017, "logValues": 20158558, "truncated": true}
2021-12-01T16:06:14.280Z	INFO	backupds	backupds/log.go:104	creating log	{"file": "/market/.lotusmarkets/kvlog/metadata/1638374774.log.cbor"}
2021-12-01T16:06:14.280Z	INFO	backupds	backupds/datastore.go:75	Starting datastore backup
2021-12-01T16:09:11.173Z	INFO	backupds	backupds/datastore.go:130	Datastore backup done
2021-12-01T16:09:11.284Z	INFO	backupds	backupds/log.go:117	log opened	{"file": "/market/.lotusmarkets/kvlog/metadata/1638374774.log.cbor"}
2021-12-01T16:09:11.284Z	ERROR	backupds	backupds/log.go:199	LOG FILE WAS TRUNCATED, KEEPING THE FILE	{"old": "/market/.lotusmarkets/kvlog/metadata/1637292955.log.cbor", "new": "1638374774.log.cbor"}
2021-12-01T16:09:11.285Z	INFO	backupds	backupds/log.go:230	new log head	{"loghead": "1638374774.log.cbor;c140a791-109a-4528-83e5-8c5b89c3df80;1638374951"}
2021-12-01T16:09:11.303Z	INFO	p2pnode	lp2p/addrs.go:101	Swarm listening at: [/ip4/127.0.0.1/tcp/46717 /ip4/192.168.1.98/tcp/46717]
2021-12-01T16:09:11.303Z	INFO	modules	modules/storageminer_svc.go:68	Connecting storage service to miner
2021-12-01T16:09:11.303Z	INFO	modules	modules/storageminer_svc.go:31	Checking (svc) api version of ws://192.168.1.95:2345/rpc/v0
2021-12-01T16:09:11.316Z	INFO	modules	modules/storageminer_svc.go:61	Connecting sealing service to miner
2021-12-01T16:09:11.316Z	INFO	modules	modules/storageminer_svc.go:31	Checking (svc) api version of ws://192.168.1.95:2345/rpc/v0
2021-12-01T16:09:11.341Z	INFO	dt-impl	impl/impl.go:145	start data-transfer module
2021-12-01T16:09:11.344Z	INFO	markets	loggers/loggers.go:56	module ready	{"module": "provider data transfer"}
2021-12-01T16:09:11.345Z	INFO	markets	loggers/loggers.go:56	module ready	{"module": "piecestore"}

**Comment by stuberman** [comment]
Now trying an import using
`lotus-miner storage-deals import-data bafyreigcpgaorsw764vitolvwc6wurw2lkukmp3qhdn3y3nr2cfq5tdafe /market/deals/feiyan/Covid19-SARS-CoV-1-10705.car
`

**Comment by stuberman** [comment]
Still waiting for import to complete... more than an hour and looks like little CPU priority is allocated to import...


![lotus import from HTOP](https://user-images.githubusercontent.com/49840642/144279843-0967e5d3-f565-4297-ba7a-d2f696d3dce4.png)

**Comment by stuberman** [comment]
And just as I posted this the import published

> 2021-12-01T17:07:33.762Z	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventVerifiedData", "proposal CID": "bafyreigcpgaorsw764vitolvwc6wurw2lkukmp3qhdn3y3nr2cfq5tdafe", "state": "StorageDealReserveProviderFunds", "message": ""}
2021-12-01T17:07:34.005Z	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventFundsReserved", "proposal CID": "bafyreigcpgaorsw764vitolvwc6wurw2lkukmp3qhdn3y3nr2cfq5tdafe", "state": "StorageDealReserveProviderFunds", "message": ""}
2021-12-01T17:07:34.022Z	INFO	markets	loggers/loggers.go:20	storage provider event	{"name": "ProviderEventFunded", "proposal CID": "bafyreigcpgaorsw764vitolvwc6wurw2lkukmp3qhdn3y3nr2cfq5tdafe", "state": "StorageDealPublish", "message": ""}
2021-12-01T17:07:34.065Z	INFO	storageadapter	storageadapter/dealpublisher.go:211	add deal with piece CID baga6ea4seaqajcwfr5d5wcuynpbp7rtoai472jdip6ddd6h6aozqhe7lgewk4cy to publish deals queue - 1 deals in queue (max queue size 16)
2021-12-01T17:07:34.067Z	INFO	storageadapter	storageadapter/dealpublisher.go:236	waiting publish deals queue period of 1h0m0s before publishing

**Comment by stuberman** [comment]
After setting the new env var and restarting, markets node is now working and able to import deals both offline and online.

**Comment by jennijuju** [comment]
> After setting the new env var and restarting, markets node is now working and able to import deals both offline and online.

Ooh this was a fast turnaround! Thanks for following through - but ideally market node shouldn’t crash in the first place

**Comment by NSC-FIL** [comment]
I observed the same type of crash during online deal process.  Crash occurred initially with the following error:
github.com/ipfs/go-graphsync/messagequeue.(*MessageQueue).runQueue(0xc00f97e540)
	/home/go/pkg/mod/github.com/ipfs/go-graphsync@v0.10.6/messagequeue/messagequeue.go:143 +0x10b
created by github.com/ipfs/go-graphsync/messagequeue.(*MessageQueue).Startup
	/home/go/pkg/mod/github.com/ipfs/go-graphsync@v0.10.6/messagequeue/messagequeue.go:128 +0x5b

goroutine 7327517 [select, 13 minutes]:
github.com/libp2p/go-libp2p/p2p/protocol/identify.(*peerHandler).loop(0xc069acc410, {0x3439858, 0xc39fbd5a00}, 0xc0020fcb40)
	/home/go/pkg/mod/github.com/libp2p/go-libp2p@v0.15.0/p2p/protocol/identify/peer_loop.go:90 +0x10a
created by github.com/libp2p/go-libp2p/p2p/protocol/identify.(*peerHandler).start
	/home/go/pkg/mod/github.com/libp2p/go-libp2p@v0.15.0/p2p/protocol/identify/peer_loop.go:72 +0xef 
	
Subsequent restart of lotus-miner resulted in these errors:
2021-12-03T21:15:55.632-0500	INFO	badger	v2@v2.2007.2/levels.go:183	All 0 tables opened in 0s

2021-12-03T21:15:55.633-0500	INFO	badger	v2@v2.2007.2/value.go:1158	Replaying file id: 0 at offset: 0

2021-12-03T21:15:55.633-0500	INFO	badger	v2@v2.2007.2/value.go:1178	Replay took: 1.353µs

2021-12-03T21:15:55.633-0500	INFO	backupds	backupds/log.go:125	opening log	{"file": "/home/lotusminer_main/kvlog/metadata/1638543890.log.cbor"}
ERROR: creating node: starting node: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".StartListening.func1 (/home/lotus/node/modules/lp2p/addrs.go:85): failed to build host.Host: could not build arguments for function "reflect".makeFuncStub (/usr/lib/go-1.17/src/reflect/asm_amd64.s:30): failed to build lp2p.RawHost: could not build arguments for function "reflect".makeFuncStub (/usr/lib/go-1.17/src/reflect/asm_amd64.s:30): could not build value group []config.Option[group="libp2p"]: could not build arguments for function "github.com/filecoin-project/lotus/node/modules/lp2p".ConnGaterOption (/home/lotus/node/modules/lp2p/conngater.go:14): failed to build *conngater.BasicConnectionGater: could not build arguments for function "reflect".makeFuncStub (/usr/lib/go-1.17/src/reflect/asm_amd64.s:30): failed to build dtypes.MetadataDS: received non-nil error from function "reflect".makeFuncStub (/usr/lib/go-1.17/src/reflect/asm_amd64.s:30): opening backupds: opening log: reading backup part of the logfile: log entry potentially truncated, set LOTUS_ALLOW_TRUNCATED_LOG=1 to proceed: EOF

**Comment by NSC-FIL** [comment]
Set environment variable using "export LOTUS_ALLOW_TRUNCATED_LOG=1" to restart lotus-miner.  See google docs in folder  'Nelson_v1.13.2-rc1' under 'Ticket_#7723'.

**Comment by magik6k** [comment]
Messages about the backupds log being truncated are expected after the node has crashed in an unclean way.

Why the node has crashed is a much better question - I don't see anything obvious in the linked logs.
* How long does it take for the node to crash after starting the import?
* How big is the CAR being imported?
* Is there anything in dmesg/system logs that looks related to the crash?

**Comment by stuberman** [comment]
This only occurred once after the initial upgrade from v1.13.1 to v1.13.2-rc1
After the initial crash, the markets node would not restart until I added `LOTUS_ALLOW_TRUNCATED_LOG=1`
There were no other symptoms that I could see including dmesg logs.

The car file was a 32GiB deal using manual (offline) import.
Since this initial crash and change, I have not had further problems.

**Comment by TippyFlitsUK** [comment]
Hey Stu

Are you still seeing this behaviour in the more recent versions of Lotus?

**Comment by stuberman** [comment]
I have not seen this issue since December 2022. Closing this now.
