### ISSUE TITLE
assertion failed: new_window as usize * self.window_size < self.size

### ISSUE THREAD

**Issue by pocy9901** [filecoin-project/lotus#7793]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.13.0+mainnet+git.7a55e8e89
lotus-worker version 1.13.0+mainnet+git.7a55e8e89
lotus-miner version 1.13.0+mainnet+git.7a55e8e89.dirty
```

### Describe the Bug

Get an error when sealing a task , and then the task not compelete over 24 hours.

### Logging Information

```text
thread '<unnamed>' panicked at 'assertion failed: new_window as usize * self.window_size < self.size', /home/filcoin/.cargo/registry/src/m-1ecc6299db9ec823/storage-proofs-porep-10.0.0/src/stacked/vanilla/memory_handling.rs:260:9
stack backtrace:
   0:          0x2150a30 - std::backtrace_rs::backtrace::libunwind::trace::hdcf4f90f85129e83
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/../../backtrace/src/backtrace/libunwind
   1:          0x2150a30 - std::backtrace_rs::backtrace::trace_unsynchronized::h2669e30cb82f6732
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:          0x2150a30 - std::sys_common::backtrace::_print_fmt::hfbda19e17f6db318
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:67:5
   3:          0x2150a30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1a8751bf59281272
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:46:22
   4:          0x21c0c9f - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/core/src/fmt/mod.rs:1094:17
   5:          0x21451c5 - std::io::Write::write_fmt::hd7dd3a1df9b6befb
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/io/mod.rs:1580:15
   6:          0x215478b - std::sys_common::backtrace::_print::h551e9ec8a9fa8106
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:49:5
   7:          0x215478b - std::sys_common::backtrace::print::ha4b1c5e95fa040b3
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:36:9
   8:          0x215478b - std::panicking::default_hook::{{closure}}::h0b34c9ab7fb9f857
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:208:50
   9:          0x215426d - std::panicking::default_hook::h3067e8318decd17a
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:225:9
  10:          0x2154e7d - std::panicking::rust_panic_with_hook::h81b8facc50f34daa
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:591:17
  11:          0x2154a47 - std::panicking::begin_panic_handler::{{closure}}::ha376ab85d95a000e
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:495:13
  12:          0x2150eec - std::sys_common::backtrace::__rust_end_short_backtrace::h6795c8afdd1a77e6
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys_common/backtrace.rs:141:18
  13:          0x21549d9 - rust_begin_unwind
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/panicking.rs:493:5
  14:           0x510111 - core::panicking::panic_fmt::hbe99dddd3092ba3c
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/core/src/panicking.rs:92:14
  15:           0x51005d - core::panicking::panic::h3de4db67bd397eb3
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/core/src/panicking.rs:50:5
  16:          0x1f8e4c5 - storage_proofs_porep::stacked::vanilla::memory_handling::IncrementingCursor::increment::h126646fb848c850e
  17:          0x1f850b0 - storage_proofs_porep::stacked::vanilla::create_label::multi::create_label_runner::h090aca36f9914ee4
  18:          0x1f94404 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h0579751fe9341df7
  19:          0x1f898e2 - std::sys_common::backtrace::__rust_begin_short_backtrace::h962705ad3b4aedc9
  20:          0x1f7ff43 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf1264bdcae671a27
  21:          0x2163947 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h3aa31cb6360b59d9
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/alloc/src/boxed.rs:1546:9
  22:          0x2163947 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7719d3c7c5841461
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/alloc/src/boxed.rs:1546:9
  23:          0x2163947 - std::sys::unix::thread::Thread::new::thread_start::hfbe13ead469fd0bc
                               at /rustc/bb491ed23937aef876622e4beb68ae95938b3bf9/library/std/src/sys/unix/thread.rs:71:17
  24:     0x7fd013431609 - start_thread
  25:     0x7fd012f8d293 - clone
  26:                0x0 - <unknown>
```

### Repo Steps

lotus-worker run --addpiece=false --precommit1=true --precommit2=true --commit=true --parallel-fetch-limit=5

**Comment by Reiers** [comment]
Hi @pocy9901 

Thanks for the report. The issue you are experiencing lies elsewhere.

Moving this issue to [Lotus Discussions](https://github.com/filecoin-project/lotus/discussions) for help and troubleshooting.

Closing Lotus issue ticket. Someone will get back to you soon ! Thanks again
