### ISSUE TITLE
2k  devtest  not  save file and get it

### ISSUE THREAD

**Issue by alanmoleapfive** [filecoin-project/lotus#8259]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [X] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [X] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.14.4+2k+git.5b33555fd+api1.5.0
Local: lotus version 1.14.4+2k+git.5b33555fd

Daemon:  1.14.4+2k+git.5b33555fd+api1.4.0
Local: lotus-miner version 1.14.4+2k+git.5b33555fd
```

### Describe the Bug

wait  

2022-03-08T06:04:13.988Z        INFO    main    lotus-miner/init.go:748 Pushed CreateMiner message: bafy2bzacecybks5nb65oprkfnketzc4a774r3ppvya4c2yuw74t7kibx2akpe
2022-03-08T06:04:13.993Z        INFO    main    lotus-miner/init.go:749 Waiting for confirmation

lotus client list-deals
DealCid      DealId  Provider  State                     On Chain?  Slashed?  PieceCID     Size    Price            Duration  Verified  
...3q3uopfu  0       t01000    StorageDealFundsReserved  N          N         ...5qtonkdq  1016 B  0.000260639 FIL  521278    false     
root@0d3872e3afdd:/home/lotus# lotus-miner storage-deals list -v
Creation  Verified  ProposalCid  DealId  State  Client  Size  Price  Duration  TransferChannelID  Message
root@0d3872e3afdd:/home/lotus# lotus client list-deals
DealCid      DealId  Provider  State                     On Chain?  Slashed?  PieceCID     Size    Price            Duration  Verified  
...3q3uopfu  0       t01000    StorageDealFundsReserved  N          N         ...5qtonkdq  1016 B  0.000260639 FIL  521278    false     
root@0d3872e3afdd:/home/lotus# lotus state search-msg bafy2bzacealsmph4t3ta54zww6rwcyrdbdu276jjrx5wncka4xaiqawi7c6qa
Executed in tipset: [bafy2bzaceducqnrrl42varmavjvqewqwo44qqcxlatyvt7vhjchho6lxrlcws]
Exit Code: 0
Gas Used: 5014527
Return: 
root@0d3872e3afdd:/home/lotus# lotus client find bafy2bzacealsmph4t3ta54zww6rwcyrdbdu276jjrx5wncka4xaiqawi7c6qa
ERROR: no import found for root bafy2bzacealsmph4t3ta54zww6rwcyrdbdu276jjrx5wncka4xaiqawi7c6qa: no client blockstore for root bafy2bzacealsmph4t3ta54zww6rwcyrdbdu276jjrx5wncka4xaiqawi7c6qa

root@0d3872e3afdd:/home/lotus# lotus client retrieve bafy2bzacealsmph4t3ta54zww6rwcyrdbdu276jjrx5wncka4xaiqawi7c6qa hello2.txt
Failed to find file
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x17d5102]

goroutine 1 [running]:
github.com/filecoin-project/lotus/cli.glob..func33(0xc00083b440)
        /home/alan/lotus/cli/client_retr.go:321 +0x502
github.com/urfave/cli/v2.(*Command).Run(0x568cc60, 0xc000701e40)
        /home/alan/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:164 +0x64a
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000292300, 0xc000701ac0)
        /home/alan/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:427 +0x9a6
github.com/urfave/cli/v2.(*Command).startApp(0x568d0e0, 0xc000701ac0)
        /home/alan/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:279 +0x71b
github.com/urfave/cli/v2.(*Command).Run(0xc0006e5680, 0x7ffe4445d856)
        /home/alan/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/command.go:94 +0x7d9
github.com/urfave/cli/v2.(*App).RunContext(0xc000292000, {0x3eed3b0, 0xc000054050}, {0xc00004e0a0, 0x5, 0x5})
        /home/alan/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:306 +0x926
github.com/urfave/cli/v2.(*App).Run(...)
        /home/alan/go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
github.com/filecoin-project/lotus/cli.RunApp(0x30e51c0)
        /home/alan/lotus/cli/helper.go:35 +0x4e
main.main()
        /home/alan/lotus/cmd/lotus/main.go:109 +0x8ec

### Logging Information

```text
gs-unverifiedbs
ffi-wrapper
peerstore
lock
repo
beacon
bitswap_network
dt-chanmon
providerstates
panic-reporter
ffiwrapper
builder
types
sub
vm
dht
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by Reiers** [comment]
Hi @alanmoleapfive 

Moving to Discussions for help and troubleshooting!

Thanks for taking the time to create this ticket, but your issue lies elsewhere.
