### ISSUE TITLE
lotus-storage-miner process hang up

### ISSUE THREAD

**Issue by zhang-dong-dong** [filecoin-project/lotus#851]
## Linux PC 4.15.0-29deepin-generic #31 SMP Fri Jul 27 07:12:08 UTC 2018 x86_64 GNU/Linux
lotus-storage-miner run for a while and hung up ，This error is still reported after restart
```
2019-12-11T12:42:30.003+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:42:30.006+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:43:00.003+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:43:00.005+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:43:30.002+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:43:30.005+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:44:00.003+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:44:00.005+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:44:14.999+0800	WARN	storageminer	storage/sector_states.go:162	revert in interactive commit sector step
2019-12-11T12:44:19.119+0800	WARN	storageminer	storage/sector_states.go:162	revert in interactive commit sector step
2019-12-11T12:44:25.300+0800	WARN	storageminer	storage/sector_states.go:162	revert in interactive commit sector step
2019-12-11T12:44:30.003+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:44:30.005+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:44:33.149+0800	WARN	storageminer	storage/sector_states.go:162	revert in interactive commit sector step
2019-12-11T12:44:38.011+0800	WARN	storageminer	storage/sector_states.go:162	revert in interactive commit sector step
2019-12-11T12:44:46.741+0800	WARN	storageminer	storage/sector_states.go:162	revert in interactive commit sector step
2019-12-11T12:45:00.002+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:45:00.004+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:45:30.000+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 60s
2019-12-11T12:45:34.614+0800	WARN	storageminer	storage/sector_states.go:162	revert in interactive commit sector step
2019-12-11T12:46:00.002+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:46:00.004+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:46:30.003+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:46:30.008+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:47:00.002+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:47:00.005+0800	INFO	miner	miner/miner.go:173	Time delta between now and our mining base: 30s
2019-12-11T12:47:01.850+0800	INFO	storageminer	storage/sectors.go:162	Sector 2 updated state to Committing
2019-12-11T12:47:01.977+0800	INFO	storageminer	storage/sector_states.go:174	scheduling seal proof computation...
memory allocation of 1744830464 bytes failedSIGABRT: abort
PC=0x7fbb4980ee7b m=20 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: unknown pc 0x7fbb4980ee7b
stack: frame={sp:0x7fbb0d7f3140, fp:0x0} stack=[0x7fbb0cff9f08,0x7fbb0d7f9b08)
00007fbb0d7f3040:  0000000000000003  0000000000000000 
00007fbb0d7f3050:  7bf9df223e0e699b  0000000000000000 
00007fbb0d7f3060:  00000000014efed0  00000000014f05b0 
00007fbb0d7f3070:  0c4e0c02228ed8dc  0addcd00baa0c524 
00007fbb0d7f3080:  b1b759d18eb5d8e6  4b862de1449e708c 
00007fbb0d7f3090:  fdb7b4b290028276  0997a9d1ce2face2 
00007fbb0d7f30a0:  0000000000000000  6a0c610e61add196 
00007fbb0d7f30b0:  19899015fc1b1570  3b42e64f748db198 
00007fbb0d7f30c0:  94b501430ea54a8a  376c6ad608e83382 
00007fbb0d7f30d0:  1865dbe743be9b9e  b6b96954db5fea2b 
00007fbb0d7f30e0:  c1f720cc0fe813d0  12f6d1b562806622 
00007fbb0d7f30f0:  0000000000000000  0000000000000000 
00007fbb0d7f3100:  0000000000000000  0000000000000000 
00007fbb0d7f3110:  e2771a769c9418b4  00007fbb49dbc94c 
00007fbb0d7f3120:  a205b430638e0640  000000000000000a 
00007fbb0d7f3130:  000000000000000a  00007fbb49dbc8f0 
00007fbb0d7f3140: <0000000000000000  00007fbb49dbc94c 
00007fbb0d7f3150:  9b3819f0d8bfa6f9  000000000000000d 
00007fbb0d7f3160:  000000000000000d  00007fbb49dbc8f0 
00007fbb0d7f3170:  00007fbb49dbf760  000000000152e4c1 
00007fbb0d7f3180:  0000000000000001  00000000028f07b0 
00007fbb0d7f3190:  0000000000000000  000000000000000d 
00007fbb0d7f31a0:  0000000000000000  00007fbb0d7f32b8 
00007fbb0d7f31b0:  0000000000000001  00000000028f07b0 
00007fbb0d7f31c0:  fffffffe7fffffff  ffffffffffffffff 
00007fbb0d7f31d0:  ffffffffffffffff  ffffffffffffffff 
00007fbb0d7f31e0:  ffffffffffffffff  ffffffffffffffff 
00007fbb0d7f31f0:  ffffffffffffffff  ffffffffffffffff 
00007fbb0d7f3200:  ffffffffffffffff  ffffffffffffffff 
00007fbb0d7f3210:  ffffffffffffffff  ffffffffffffffff 
00007fbb0d7f3220:  ffffffffffffffff  ffffffffffffffff 
00007fbb0d7f3230:  ffffffffffffffff  ffffffffffffffff 
runtime: unknown pc 0x7fbb4980ee7b
stack: frame={sp:0x7fbb0d7f3140, fp:0x0} stack=[0x7fbb0cff9f08,0x7fbb0d7f9b08)
00007fbb0d7f3040:  0000000000000003  0000000000000000 
00007fbb0d7f3050:  7bf9df223e0e699b  0000000000000000 
00007fbb0d7f3060:  00000000014efed0  00000000014f05b0 
00007fbb0d7f3070:  0c4e0c02228ed8dc  0addcd00baa0c524 
00007fbb0d7f3080:  b1b759d18eb5d8e6  4b862de1449e708c 
00007fbb0d7f3090:  fdb7b4b290028276  0997a9d1ce2face2 
00007fbb0d7f30a0:  0000000000000000  6a0c610e61add196 
00007fbb0d7f30b0:  19899015fc1b1570  3b42e64f748db198 
00007fbb0d7f30c0:  94b501430ea54a8a  376c6ad608e83382 
00007fbb0d7f30d0:  1865dbe743be9b9e  b6b96954db5fea2b 
00007fbb0d7f30e0:  c1f720cc0fe813d0  12f6d1b562806622 
00007fbb0d7f30f0:  0000000000000000  0000000000000000 
00007fbb0d7f3100:  0000000000000000  0000000000000000 
00007fbb0d7f3110:  e2771a769c9418b4  00007fbb49dbc94c 
00007fbb0d7f3120:  a205b430638e0640  000000000000000a 
00007fbb0d7f3130:  000000000000000a  00007fbb49dbc8f0 
00007fbb0d7f3140: <0000000000000000  00007fbb49dbc94c 
00007fbb0d7f3150:  9b3819f0d8bfa6f9  000000000000000d 
00007fbb0d7f3160:  000000000000000d  00007fbb49dbc8f0 
00007fbb0d7f3170:  00007fbb49dbf760  000000000152e4c1 
00007fbb0d7f3180:  0000000000000001  00000000028f07b0 
00007fbb0d7f3190:  0000000000000000  000000000000000d 
00007fbb0d7f31a0:  0000000000000000  00007fbb0d7f32b8 
00007fbb0d7f31b0:  0000000000000001  00000000028f07b0 
00007fbb0d7f31c0:  fffffffe7fffffff  ffffffffffffffff 
00007fbb0d7f31d0:  ffffffffffffffff  ffffffffffffffff 
00007fbb0d7f31e0:  ffffffffffffffff  ffffffffffffffff 
00007fbb0d7f31f0:  ffffffffffffffff  ffffffffffffffff 
00007fbb0d7f3200:  ffffffffffffffff  ffffffffffffffff 
00007fbb0d7f3210:  ffffffffffffffff  ffffffffffffffff 
00007fbb0d7f3220:  ffffffffffffffff  ffffffffffffffff 
00007fbb0d7f3230:  ffffffffffffffff  ffffffffffffffff 

goroutine 10199 [syscall]:
runtime.cgocall(0xfc0c50, 0xc005b16ed0, 0xc74a824c8f27e0f)
	/usr/local/go/src/runtime/cgocall.go:128 +0x5b fp=0xc005b16e48 sp=0xc005b16e10 pc=0x4e49ab
github.com/filecoin-project/filecoin-ffi._Cfunc_seal_commit(0x10000000, 0xa, 0x7fba6c001af0, 0x2, 0x7fba6c0044a0, 0x7fba6c0044d0, 0x7fba6c004180, 0x7fba6c008560, 0x13, 0x109c7c7b70cb5e2e, ...)
	_cgo_gotypes.go:701 +0x54 fp=0xc005b16ed0 sp=0xc005b16e48 pc=0x9e2494
github.com/filecoin-project/filecoin-ffi.SealCommit(0x10000000, 0xc005b1730a, 0xc00641af30, 0x27, 0x2, 0x118e, 0x0, 0x0, 0x0, 0xde7cfef1ca5ca01, ...)
	/home/fy/work/code/lotus/extern/filecoin-ffi/proofs.go:474 +0x4ab fp=0xc005b171f8 sp=0xc005b16ed0 pc=0x9e657b
github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).sealCommitLocal(0xc00037a000, 0x2, 0x3e50, 0xde7cfef1ca5ca01, 0x7fc35fd2009de572, 0xcf3ccd4c650cc0bb, 0xe27f60309913973c, 0x3e66, 0xa9c3b20e61a5fe50, 0xb39be4c1af4b70b3, ...)
	/home/fy/work/code/lotus/lib/sectorbuilder/sectorbuilder.go:540 +0x2b0 fp=0xc005b17500 sp=0xc005b171f8 pc=0xa95380
github.com/filecoin-project/lotus/lib/sectorbuilder.(*SectorBuilder).SealCommit(0xc00037a000, 0x2, 0x3e50, 0xde7cfef1ca5ca01, 0x7fc35fd2009de572, 0xcf3ccd4c650cc0bb, 0xe27f60309913973c, 0x3e66, 0xa9c3b20e61a5fe50, 0xb39be4c1af4b70b3, ...)
	/home/fy/work/code/lotus/lib/sectorbuilder/sectorbuilder.go:593 +0x40d fp=0xc005b178e0 sp=0xc005b17500 pc=0xa95c6d
github.com/filecoin-project/lotus/storage.(*Miner).handleCommitting(0xc0004d2400, 0x1ce8000, 0xc00010c480, 0x6, 0x2, 0x0, 0xc0005f2000, 0x13, 0x13, 0x2a2c7b8, ...)
	/home/fy/work/code/lotus/storage/sector_states.go:176 +0x3c6 fp=0xc005b17bc0 sp=0xc005b178e0 pc=0xcfbb46
github.com/filecoin-project/lotus/storage.(*Miner).handleCommitting-fm(0x1ce8000, 0xc00010c480, 0x6, 0x2, 0x0, 0xc0005f2000, 0x13, 0x13, 0x2a2c7b8, 0x0, ...)

goroutine 20 [select, 54 minutes]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0xc0000bb770)
	/home/fy/go/pkg/mod/github.com/ipfs/go-log@v1.0.0/writer/writer.go:76 +0x144
created by github.com/ipfs/go-log/writer.NewMirrorWriter
	/home/fy/go/pkg/mod/github.com/ipfs/go-log@v1.0.0/writer/writer.go:41 +0xb9

...
	/home/fy/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.2.2/swarm_conn.go:93 +0x3f

goroutine 5047 [select]:
github.com/ipfs/go-bitswap/messagequeue.(*MessageQueue).runQueue(0xc005d0da20)
	/home/fy/go/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/messagequeue/messagequeue.go:104 +0x101
created by github.com/ipfs/go-bitswap/messagequeue.(*MessageQueue).Startup
	/home/fy/go/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/messagequeue/messagequeue.go:94 +0x98

goroutine 5199 [select]:
github.com/ipfs/go-bitswap/messagequeue.(*MessageQueue).runQueue(0xc005c03550)
	/home/fy/go/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/messagequeue/messagequeue.go:104 +0x101
created by github.com/ipfs/go-bitswap/messagequeue.(*MessageQueue).Startup
	/home/fy/go/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/messagequeue/messagequeue.go:94 +0x98

goroutine 5427 [select]:
github.com/ipfs/go-bitswap/messagequeue.(*MessageQueue).runQueue(0xc005d0a4d0)
	/home/fy/go/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/messagequeue/messagequeue.go:104 +0x101
created by github.com/ipfs/go-bitswap/messagequeue.(*MessageQueue).Startup
	/home/fy/go/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/messagequeue/messagequeue.go:94 +0x98

goroutine 5493 [select]:
github.com/ipfs/go-bitswap/messagequeue.(*MessageQueue).runQueue(0xc005e62420)
	/home/fy/go/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/messagequeue/messagequeue.go:104 +0x101
created by github.com/ipfs/go-bitswap/messagequeue.(*MessageQueue).Startup
	/home/fy/go/pkg/mod/github.com/ipfs/go-bitswap@v0.1.8/messagequeue/messagequeue.go:94 +0x98

goroutine 10198 [IO wait]:
internal/poll.runtime_pollWait(0x7fbb4a964f38, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc0004ceb98, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0004ceb80, 0xc0004de000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc0004ceb80, 0xc0004de000, 0x1000, 0x1000, 0xc005a4a790, 0x2, 0xc005a4a790)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0000d0370, 0xc0004de000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
bufio.(*Reader).fill(0xc00047de00)
	/usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc00047de00, 0x2, 0x17d4780, 0xc000334b20, 0x197, 0x2a0e800, 0x1)
	/usr/local/go/src/bufio/bufio.go:138 +0x4f
github.com/gorilla/websocket.(*Conn).read(0xc0000e0dc0, 0x2, 0xc0004f07a0, 0x1, 0x17e9480, 0xc0059d62a0, 0x12)
	/home/fy/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:370 +0x40
github.com/gorilla/websocket.(*Conn).advanceFrame(0xc0000e0dc0, 0x0, 0x0, 0x0)
	/home/fy/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:798 +0x5c
github.com/gorilla/websocket.(*Conn).NextReader(0xc0000e0dc0, 0x197, 0x0, 0x5410a1, 0xc0002d9980, 0xc0003c01d8)
	/home/fy/go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:980 +0xa0
github.com/filecoin-project/lotus/lib/jsonrpc.(*wsConn).nextMessage(0xc0001206c0)
	/home/fy/work/code/lotus/lib/jsonrpc/websocket.go:85 +0x3a
created by github.com/filecoin-project/lotus/lib/jsonrpc.(*wsConn).handleWsConn
	/home/fy/work/code/lotus/lib/jsonrpc/websocket.go:442 +0x810

rax    0x0
rbx    0x6
rcx    0x7fbb4980ee7b
rdx    0x0
rdi    0x2
rsi    0x7fbb0d7f3140
rbp    0x7fbb0d7f33e7
rsp    0x7fbb0d7f3140
r8     0x0
r9     0x7fbb0d7f3140
r10    0x8
r11    0x246
r12    0xffffff
r13    0x7fbb0d7f39c8
r14    0x7fbb0d7f36e0
r15    0x68000000
rip    0x7fbb4980ee7b
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by yanwankun** [comment]
I also encountered the same problem！

**Comment by bob2325168** [comment]
maybe you should try to use GPU and it will work.

**Comment by zhang-dong-dong** [comment]
Thank you for your advice. I'll try，but how to use GPU to run lotus-storage-miner ? @bob2325168

**Comment by yanwankun** [comment]
It's not how to use it, because your machine does not have a GPU. If your machine has a GPU, it may not report this error, so you can add a GPU to your miner.

**Comment by whyrusleeping** [comment]
This error means that your miner ran out of memory while executing rust code.

**Comment by whyrusleeping** [comment]
I don't know if theres anything we can do about it

**Comment by magik6k** [comment]
Try reducing `WorkerCount` in `~/.lotusstorage/config.toml` to 2, and see if that helps. Not much more we can do here other than advise to add more RAM to the machine.
