### ISSUE TITLE
Disabled index-provider causes "panic: runtime error: invalid memory address or nil pointer dereference" - v1.17.0.rc1

### ISSUE THREAD

**Issue by donkabat** [filecoin-project/lotus#8916]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus-miner version 1.17.0-rc1+calibnet+git.d2fe153e3
```

### Describe the Bug

I'm not able to run lotus miner with disabled IndexProvider.

New lotus-miner's installation & calibnet.
Before first run I set config.toml:
[IndexProvider]
  Enable = false
  
It worked for a day and next it didnt want to run after restart. Probably it was the first restart after first storage deal.

### Logging Information

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x2013e37]

goroutine 15347 [running]:
github.com/filecoin-project/index-provider/engine.(*Engine).Start(0xc00ef98770, {0x43aa8c0, 0xc000f432f0})
        /home/filecoin/go/pkg/mod/github.com/filecoin-project/index-provider@v0.6.1/engine/engine.go:123 +0x437
github.com/filecoin-project/lotus/node/modules.IndexProvider.func1.1({0x43aa8c0, 0xc000f432f0})
        /home/filecoin/networks/calibration/build/lotus/node/modules/storageminer_idxprov.go:97 +0x34
go.uber.org/fx/internal/lifecycle.(*Lifecycle).runStartHook(0xc00034c8c0, {0x43aa8c0, 0xc000f432f0}, {0xc00ef873a0, 0xc00ef873b0, {{0xc00dde4370, 0x42}, {0x7e2cb8f, 0x54}, 0x5c}})
        /home/filecoin/go/pkg/mod/go.uber.org/fx@v1.15.0/internal/lifecycle/lifecycle.go:118 +0x1fd
go.uber.org/fx/internal/lifecycle.(*Lifecycle).Start(0xc00034c8c0, {0x43aa8c0, 0xc000f432f0})
        /home/filecoin/go/pkg/mod/go.uber.org/fx@v1.15.0/internal/lifecycle/lifecycle.go:83 +0x2a5
go.uber.org/fx.(*App).start(0xc001086c30, {0x43aa8c0, 0xc000f432f0})
        /home/filecoin/go/pkg/mod/go.uber.org/fx@v1.15.0/app.go:745 +0x36
go.uber.org/fx.withTimeout.func1()
        /home/filecoin/go/pkg/mod/go.uber.org/fx@v1.15.0/app.go:977 +0x32
created by go.uber.org/fx.withTimeout
        /home/filecoin/go/pkg/mod/go.uber.org/fx@v1.15.0/app.go:977 +0xf1
```

**Comment by donkabat** [comment]
After change to v1.16.0 the error is gone.
On v1.17.0_rc1 still the same.

**Comment by rjan90** [comment]
Hey @donkabat Thank you so much for the issue-report! This should and must be fixed before the final release is cut. I have raised the issue to the devs, and will come back to you later when we have found a solution.

I will repro tomorrow to confirm that I see this on my side as well!

**Comment by masih** [comment]
Fixed already in index-provider version `0.7.0` and later. The fix in lotus requires upgrading index-provider dependency. This [is currently in progress](https://github.com/filecoin-project/lotus/pull/8890) pending transient dependency upgrades for go-cid `0.2.0` which is unrelated to index-provider.
