### ISSUE TITLE
lotus --import-snapshot failed

### ISSUE THREAD

**Issue by lcgogo** [filecoin-project/lotus#8968]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.16.0+mainnet+git.01254ab
```

### Describe the Bug

According to 
https://lotus.filecoin.io/lotus/manage/chain-management/#lightweight-snapshot
I run import-snapshot failed after 1.15.1

lotus daemon --import-snapshot https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car

This command works fine at and before 1.15.0

### Logging Information

```text
docker logs -f --tail 20 fil-1.16.0

2022-07-05T09:12:17.091Z	INFO	badgerbs	v2@v2.2007.3/levels.go:1010	[Compactor: 1] Compaction for level: 2 DONE
2022-07-05T09:12:18.773Z	INFO	badgerbs	v2@v2.2007.3/levels.go:1000	[Compactor: 1] Running compaction: {level:2 score:1.0096495769917966 dropPrefixes:[]} for level: 2

2022-07-05T09:12:18.788Z	INFO	badgerbs	v2@v2.2007.3/levels.go:962	LOG Compact 1->2, del 6 tables, add 6 tables, took 2.297303517s

2022-07-05T09:12:18.788Z	INFO	badgerbs	v2@v2.2007.3/levels.go:1010	[Compactor: 0] Compaction for level: 1 DONE
2022-07-05T09:12:18.789Z	INFO	badgerbs	v2@v2.2007.3/levels.go:1000	[Compactor: 0] Running compaction: {level:1 score:1.0409182012081146 dropPrefixes:[]} for level: 1

2022-07-05T09:12:20.729Z	INFO	badgerbs	v2@v2.2007.3/levels.go:962	LOG Compact 2->3, del 3 tables, add 3 tables, took 1.956024058s

2022-07-05T09:12:20.729Z	INFO	badgerbs	v2@v2.2007.3/levels.go:1010	[Compactor: 1] Compaction for level: 2 DONE
2022-07-05T09:12:22.061Z	INFO	badgerbs	v2@v2.2007.3/levels.go:962	LOG Compact 1->2, del 5 tables, add 5 tables, took 3.272324844s

2022-07-05T09:12:22.061Z	INFO	badgerbs	v2@v2.2007.3/levels.go:1010	[Compactor: 0] Compaction for level: 1 DONE
2022-07-05T09:12:22.073Z	INFO	badgerbs	v2@v2.2007.3/levels.go:1000	[Compactor: 1] Running compaction: {level:2 score:1.0094876904040575 dropPrefixes:[]} for level: 2

2022-07-05T09:12:23.247Z	INFO	badgerbs	v2@v2.2007.3/levels.go:962	LOG Compact 2->3, del 3 tables, add 3 tables, took 1.173874678s

2022-07-05T09:12:23.247Z	INFO	badgerbs	v2@v2.2007.3/levels.go:1010	[Compactor: 1] Compaction for level: 2 DONE
2022-07-05T09:15:54.883Z	WARN	chainstore	store/store.go:641	no heaviest tipset found, using [bafy2bzacecnamqgqmifpluoeldx7zzglxcljo6oja4vrmtj7432rphldpdmm2]
2022-07-05T09:15:54.884Z	INFO	chainstore	store/store.go:646	New heaviest tipset! [bafy2bzacecnamqgqmifpluoeldx7zzglxcljo6oja4vrmtj7432rphldpdmm2] (height=0)
2022-07-05T09:15:54.885Z	INFO	main	lotus/daemon.go:535	accepting [bafy2bzacedsh5et42pgqwzq5vdau6itm2sn4tf3msbfddiwxlrgabifkdnn7o bafy2bzacebnb6ql56xh5eu2oe2sux2bw5et63k26ypn3o7jir5ktm4wkccvaw bafy2bzacebcudgnksxvwp7sbj3lr44frxfsbtstycu66pbx32hn75va25osf4 bafy2bzacederqjrk7imfvpmrsh7qxlsnmj55cqfktfya5a5qhimqyeu3pklpo bafy2bzacecyykjms4n4t37ykpuct3jan3zwcmsgy5a64i2bpiomx4pvhcq34k] as new head
2022-07-05T09:15:54.885Z	WARN	chainstore	store/store.go:525	(!!!) forcing a new head silently; new head: [bafy2bzacedsh5et42pgqwzq5vdau6itm2sn4tf3msbfddiwxlrgabifkdnn7o bafy2bzacebnb6ql56xh5eu2oe2sux2bw5et63k26ypn3o7jir5ktm4wkccvaw bafy2bzacebcudgnksxvwp7sbj3lr44frxfsbtstycu66pbx32hn75va25osf4 bafy2bzacederqjrk7imfvpmrsh7qxlsnmj55cqfktfya5a5qhimqyeu3pklpo bafy2bzacecyykjms4n4t37ykpuct3jan3zwcmsgy5a64i2bpiomx4pvhcq34k]
2022-07-05T09:15:54.886Z	WARN	chainstore	store/store.go:618	reorgWorker quit
2022-07-05T09:15:55.402Z	INFO	badgerbs	v2@v2.2007.3/db.go:1031	Storing value log head: {Fid:76 Len:33 Offset:337501811}

2022-07-05T09:15:55.791Z	INFO	badgerbs	v2@v2.2007.3/levels.go:1000	[Compactor: 173] Running compaction: {level:0 score:1.73 dropPrefixes:[]} for level: 0

2022-07-05T09:15:58.357Z	INFO	badgerbs	v2@v2.2007.3/levels.go:962	LOG Compact 0->1, del 4 tables, add 4 tables, took 2.566757717s

2022-07-05T09:15:58.358Z	INFO	badgerbs	v2@v2.2007.3/levels.go:1010	[Compactor: 173] Compaction for level: 0 DONE
2022-07-05T09:15:58.358Z	INFO	badgerbs	v2@v2.2007.3/db.go:554	Force compaction on level 0 done
2022-07-05T09:15:58.662Z	INFO	modules	modules/core.go:64	memory limits initialized	{"max_mem_heap": 0, "total_system_mem": 401262403584, "effective_mem_limit": 401262403584}
2022-07-05T09:15:58.813Z	INFO	watchdog	go-watchdog@v1.2.0/watermarks.go:16	initialized watermark watchdog policy; watermarks: []; thresholds: [4611686018427385856 5534023222112863232 6456360425798339584 7839866231326556160 8301034833169294336 8531619134090663936 8762203435012032512]
2022-07-05T09:15:58.814Z	INFO	watchdog	go-watchdog@v1.2.0/watchdog.go:471	initialized heap profile capture; threshold: 0.900000; max captures: 10; dir: /data/fil/heapprof
2022-07-05T09:15:58.814Z	INFO	modules	modules/core.go:120	initialized cgroup-driven watchdog
2022-07-05T09:15:58.881Z	INFO	p2pnode	lp2p/rcmgr.go:38	libp2p resource manager is enabled
2022-07-05T09:15:58.882Z	INFO	p2pnode	lp2p/rcmgr.go:69	adjusted default resource manager limits
2022-07-05T09:15:58.898Z	INFO	badger	v2@v2.2007.3/levels.go:183	All 0 tables opened in 0s

2022-07-05T09:15:58.898Z	INFO	badger	v2@v2.2007.3/value.go:1158	Replaying file id: 0 at offset: 0

2022-07-05T09:15:58.898Z	INFO	badger	v2@v2.2007.3/value.go:1178	Replay took: 4.334µs

2022-07-05T09:15:58.900Z	INFO	badger	v2@v2.2007.3/levels.go:183	All 0 tables opened in 0s

2022-07-05T09:15:58.901Z	INFO	badger	v2@v2.2007.3/value.go:1158	Replaying file id: 0 at offset: 0

2022-07-05T09:15:58.901Z	INFO	badger	v2@v2.2007.3/value.go:1178	Replay took: 4.362µs

2022-07-05T09:16:01.949Z	INFO	badgerbs	v2@v2.2007.3/levels.go:183	All 61 tables opened in 2.981s

2022-07-05T09:16:01.980Z	INFO	badgerbs	v2@v2.2007.3/value.go:1158	Replaying file id: 76 at offset: 337501844

2022-07-05T09:16:01.980Z	INFO	badgerbs	v2@v2.2007.3/value.go:1178	Replay took: 4.044µs

2022-07-05T09:16:01.991Z	INFO	p2pnode	lp2p/addrs.go:101	Swarm listening at: [/ip4/127.0.0.1/tcp/1235 /ip4/192.168.188.3/tcp/1235]
2022-07-05T09:16:02.173Z	INFO	modules	modules/services.go:163	subscribing to pubsub topic /fil/blocks/testnetnet
2022-07-05T09:16:02.173Z	INFO	messagepool	messagepool/messagepool.go:439	mpool ready
2022-07-05T09:16:02.196Z	INFO	modules	modules/services.go:228	relaying messages for pubsub topic /indexer/ingest/mainnet
2022-07-05T09:16:02.227Z	INFO	importmgr	imports/manager.go:62	sanity checking imports
2022/07/05 09:16:02 storess: Query
2022/07/05 09:16:02 storess: q.Prefix:
2022/07/05 09:16:02 storess: q.KeysOnly: true
2022/07/05 09:16:02 storess: q.Filters: 0
2022/07/05 09:16:02 storess: q.Orders: 0
2022/07/05 09:16:02 storess: q.Offset: 0
2022-07-05T09:16:02.228Z	INFO	importmgr	imports/manager.go:99	sanity check completed	{"broken": 0, "total": 0}
2022-07-05T09:16:02.234Z	INFO	dt-impl	impl/impl.go:145	start data-transfer module
2022-07-05T09:16:02.235Z	INFO	markets	loggers/loggers.go:64	module ready	{"module": "client data transfer"}
2022-07-05T09:16:02.242Z	INFO	markets	loggers/loggers.go:64	module ready	{"module": "retrieval client"}
2022-07-05T09:16:02.240Z	INFO	markets	loggers/loggers.go:64	module ready	{"module": "discovery"}
2022-07-05T09:16:02.241Z	INFO	markets	loggers/loggers.go:64	module ready	{"module": "storage client"}
2022-07-05T09:16:03.951Z	INFO	basichost	basic/natmgr.go:84	DiscoverNAT error:no NAT found
2022-07-05T09:16:04.588Z	WARN	auth	auth/handler.go:31	missing Bearer prefix in auth header
2022-07-05T09:16:07.166Z	INFO	peermgr	peermgr/peermgr.go:210	connecting to bootstrap peers
2022-07-05T09:16:07.671Z	WARN	peermgr	peermgr/peermgr.go:217	failed to connect to bootstrap peer: failed to dial 12D3KooWGHpBMeZbestVEWkfdnC9u7p6uFHXL1n7m1ZBqsEmiUzz:
  * [/ip4/61.147.123.111/tcp/12757] failed to negotiate security protocol: peer id mismatch: expected 12D3KooWGHpBMeZbestVEWkfdnC9u7p6uFHXL1n7m1ZBqsEmiUzz, but remote key matches 12D3KooWDqaZkm3oSczUm3dvAJ5aL2rdSeQ5VQbnHRTQNEFShhmc
2022-07-05T09:16:07.709Z	WARN	peermgr	peermgr/peermgr.go:217	failed to connect to bootstrap peer: failed to dial 12D3KooWQZrGH1PxSNZPum99M1zNvjNFM33d1AAu5DcvdHptuU7u:
  * [/ip4/61.147.123.121/tcp/12757] failed to negotiate security protocol: peer id mismatch: expected 12D3KooWQZrGH1PxSNZPum99M1zNvjNFM33d1AAu5DcvdHptuU7u, but remote key matches 12D3KooWSkxqRYoFwtoHJ8cVcoeSpAkfrr4f3wzBUGxhNLYr8Dyb
2022-07-05T09:16:07.770Z	WARN	peermgr	peermgr/peermgr.go:217	failed to connect to bootstrap peer: failed to dial 12D3KooWGhufNmZHF3sv48aQeS13ng5XVJZ9E6qy2Ms4VzqeUsHk:
  * [/ip4/47.115.22.33/tcp/41778] failed to negotiate security protocol: read tcp4 192.168.188.3:1235->47.115.22.33:41778: read: connection reset by peer
2022-07-05T09:16:08.159Z	INFO	chain	chain/sync_manager.go:218	selected initial sync target: [bafy2bzacedvsfyhjel7sqvaf3a5winwphhodjtssrqsitjmn44wqdkjohkmlu bafy2bzacecj53tgeupbt47mf6245itfos4uckuokjacemqhzdadd2ktgmr2j6 bafy2bzacebu27vxg3fzxwh4obi5y7fbo7l4t3zsnzrc5tgy2266ujr4wpaila]
2022-07-05T09:16:08.159Z	INFO	chain	chain/sync_manager.go:314	worker 0 syncing in [bafy2bzacedvsfyhjel7sqvaf3a5winwphhodjtssrqsitjmn44wqdkjohkmlu bafy2bzacecj53tgeupbt47mf6245itfos4uckuokjacemqhzdadd2ktgmr2j6 bafy2bzacebu27vxg3fzxwh4obi5y7fbo7l4t3zsnzrc5tgy2266ujr4wpaila]
2022-07-05T09:16:08.946Z	WARN	sub	sub/incoming.go:100	received block with large delay from miner	{"block": "bafy2bzacecj53tgeupbt47mf6245itfos4uckuokjacemqhzdadd2ktgmr2j6", "delay": 8, "miner": "f062334"}
2022-07-05T09:16:08.946Z	WARN	sub	sub/incoming.go:100	received block with large delay from miner	{"block": "bafy2bzacebu27vxg3fzxwh4obi5y7fbo7l4t3zsnzrc5tgy2266ujr4wpaila", "delay": 8, "miner": "f01466173"}
2022-07-05T09:16:08.946Z	WARN	sub	sub/incoming.go:100	received block with large delay from miner	{"block": "bafy2bzacedvsfyhjel7sqvaf3a5winwphhodjtssrqsitjmn44wqdkjohkmlu", "delay": 8, "miner": "f01049102"}
2022-07-05T09:16:09.122Z	INFO	chain	chain/sync.go:789	Got blocks: 1956871 390
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 309
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 317
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 293
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 301
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 349
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 269
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 333
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 381
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 357
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 325
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 285
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 365
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 373
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 341
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 277
2022-07-05T09:16:09.140Z	INFO	chain	chain/sync.go:1088	fetching messages at 261
2022-07-05T09:16:12.206Z	WARN	peermgr	peermgr/peermgr.go:217	failed to connect to bootstrap peer: failed to dial 12D3KooWQjaNmbz9b1XmheQB3RWsRjKSzuRLfjeiDZHyX7Y5RcBr:
  * [/ip4/3.133.11.133/tcp/61256] dial tcp4 0.0.0.0:1235->3.133.11.133:61256: i/o timeout
2022-07-05T09:16:12.399Z	WARN	peermgr	peermgr/peermgr.go:217	failed to connect to bootstrap peer: failed to dial 12D3KooWQnwEGNqcM2nAcPtRR9rAX8Hrg4k9kJLCHoTR5chJfz6d:
  * [/ip4/36.103.232.198/tcp/34721] dial tcp4 0.0.0.0:1235->36.103.232.198:34721: i/o timeout
2022-07-05T09:16:12.410Z	WARN	peermgr	peermgr/peermgr.go:217	failed to connect to bootstrap peer: failed to dial 12D3KooWMKxMkD5DMpSWsW7dBddKxKT7L2GgbNuckz9otxvkvByP:
  * [/ip4/36.103.232.198/tcp/34723] dial tcp4 0.0.0.0:1235->36.103.232.198:34723: i/o timeout
2022-07-05T09:16:17.587Z	INFO	chain	chain/sync.go:1130	fetching messages for 128 tipsets at 261 done; took 8.447252567s
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
SIGILL: illegal instruction
PC=0x36f0bc3 m=35 sigcode=2
signal arrived during cgo execution
instruction bytes: 0x41 0xf 0x38 0xcb 0xd5 0xc5 0xf9 0x70 0xc0 0xe 0xc5 0x79 0x7f 0xe9 0xf 0x38

goroutine 9406626 [syscall]:
runtime.cgocall(0x220723a, 0xc017bfd710)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc017bfd6e8 sp=0xc017bfd6b0 pc=0x63b11c
github.com/filecoin-project/filecoin-ffi/cgo._Cfunc_generate_winning_post_sector_challenge(0x3, 0xc0335849e0, 0x50c3c, 0xc0335849c0)
	_cgo_gotypes.go:1302 +0x4d fp=0xc017bfd710 sp=0xc017bfd6e8 pc=0x14ec76d
github.com/filecoin-project/filecoin-ffi/cgo.GenerateWinningPoStSectorChallenge(0x4485c9?, 0x0?, 0x0?, 0x0?)
	/fil-src/lotus/extern/filecoin-ffi/cgo/proofs.go:152 +0x66 fp=0xc017bfd7b0 sp=0xc017bfd710 pc=0x14f3846
github.com/filecoin-project/filecoin-ffi.GenerateWinningPoStSectorChallenge(0x0?, 0x8?, {0xc03207c620, 0x20, 0x0?}, 0x0?)
	/fil-src/lotus/extern/filecoin-ffi/proofs.go:535 +0x176 fp=0xc017bfd870 sp=0xc017bfd7b0 pc=0x15012d6
github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.proofVerifier.GenerateWinningPoStSectorChallenge(...)
	/fil-src/lotus/extern/sector-storage/ffiwrapper/verifier_cgo.go:168
github.com/filecoin-project/lotus/extern/sector-storage/ffiwrapper.(*proofVerifier).GenerateWinningPoStSectorChallenge(0xc016241058?, {0x4?, 0xc001d0f3bc?}, 0x4?, 0xc00f222150?, {0xc03207c620?, 0x3?, 0x0?}, 0x0?)
	<autogenerated>:1 +0x5c fp=0xc017bfd8b0 sp=0xc017bfd870 pc=0x15cb95c
github.com/filecoin-project/lotus/chain/stmgr.GetSectorsForWinningPoSt({0x4ac22d0?, 0xc0292d4d20}, 0xf, {0x4acbce0, 0x81c07f8}, 0xc002708b40, {{0xc031dbb410?, 0xc0036bc000?}}, {{0xc016241058, 0x4}}, ...)
	/fil-src/lotus/chain/stmgr/actors.go:179 +0x9bc fp=0xc017bfdd30 sp=0xc017bfd8b0 pc=0x17de9dc
github.com/filecoin-project/lotus/chain/consensus/filcns.(*FilecoinEC).VerifyWinningPoStProof(0xc004366540, {0x4ac22d0, 0xc0292d4d20}, 0xc061c22180?, 0xc016262d20, {0xc0003f83c0?, {0xc05006e120?, 0xc04ef19260?, 0xc0002757d0?}}, {{0xc031dbb410, ...}}, ...)
```

### Repo Steps

1. lotus daemon --import-snapshot https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car

**Comment by lcgogo** [comment]
There is the full log file which has more than 10k lines
[filecoin.log.zip](https://github.com/filecoin-project/lotus/files/9046239/filecoin.log.zip)
.

**Comment by lcgogo** [comment]
I use go1.18 and ubuntu 20.04 to build filecoin docker

**Comment by TippyFlitsUK** [comment]
Hey @lcgogo, thank you for your report!

Did you fully remove the previous Go version before installing 1.18?

**Comment by lcgogo** [comment]
> Hey @lcgogo, thank you for your report!
> 
> Did you fully remove the previous Go version before installing 1.18?

I use dockerhub golang:1.18 to build

**Comment by TippyFlitsUK** [comment]
Thanks @lcgogo 

Can you please try removing the dockerhub Go package and reinstall Go using the steps provided in the lotus docs.

https://lotus.filecoin.io/lotus/install/linux/#go

**Comment by lcgogo** [comment]
> Thanks @lcgogo
> 
> Can you please try removing the dockerhub Go package and reinstall Go using the steps provided in the lotus docs.
> 
> https://lotus.filecoin.io/lotus/install/linux/#go

I tried the release version: https://github.com/filecoin-project/lotus/releases/download/v1.16.0/lotus_v1.16.0_linux-amd64.tar.gz
But the result is same too.

**Comment by lcgogo** [comment]
I add
```shell
ENV CGO_CFLAGS_ALLOW="-D__BLST_PORTABLE__"
```
Now it's ok
I only use
```shell
ENV CGO_CFLAGS="-D__BLST_PORTABLE__"
ENV RUSTFLAGS="-C target-cpu=native -g"
ENV FFI_BUILD_FROM_SOURCE=1
```
in 1.15.0 and before version
