### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-8]

### ISSUE THREAD

**Issue by yangyueqiangyy** [filecoin-project/lotus#9005]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.16.0+mainnet+git.01254ab32
```

### Describe the Bug

The chain synchronization has been normal all the time. Suddenly, an exception occurs, and then the restart still reports the following error.

### Logging Information

```text
panic: runtime error: slice bounds out of range [:-8]

goroutine 3502 [running]:
github.com/dgraph-io/badger/v2/y.CompareKeys({0xc1ed11fb30, 0xc2a02af050, 0x1438529}, {0xc2a09125f0, 0x1439048, 0xc2a02af068})
        /root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/y/y.go:139 +0x109
github.com/dgraph-io/badger/v2/table.(*MergeIterator).fix(0xc2a03ad290)
        /root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/table/merge_iterator.go:107 +0x7d
github.com/dgraph-io/badger/v2/table.(*MergeIterator).Next(0xc2a03ad290)
        /root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/table/merge_iterator.go:159 +0x38
github.com/dgraph-io/badger/v2.(*levelsController).compactBuildTables(0xc000178d90, 0x3, {{0x4aff050, 0xc29ec3eea0}, 0xc001d301e0, 0xc001d30240, {0xc2a0396440, 0x1, 0x1}, {0xc29f7cf500, ...}, ...})
        /root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/levels.go:576 +0x1313
github.com/dgraph-io/badger/v2.(*levelsController).runCompactDef(0xc000178d90, 0xc002cb6b68, {{0x4aff050, 0xc29ec3eea0}, 0xc001d301e0, 0xc001d30240, {0xc2a0396440, 0x1, 0x1}, {0xc29f7cf500, ...}, ...})
        /root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/levels.go:933 +0xc9
github.com/dgraph-io/badger/v2.(*levelsController).doCompact(0xc000178d90, 0xc002cb6ed0, {0x3, 0x3ff01449c25c28f6, {0x0, 0x0, 0x0}})
        /root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/levels.go:1003 +0x668
github.com/dgraph-io/badger/v2.(*levelsController).runCompactor(0xc000178d90, 0x1, 0xc0012bbca0)
        /root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/levels.go:404 +0x32d
created by github.com/dgraph-io/badger/v2.(*levelsController).startCompact
        /root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/levels.go:371 +0x55
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by cryptowhizzard** [comment]
2022-10-21T14:10:13.519+0200	INFO	markets	loggers/loggers.go:65	module ready	{"module": "discovery"}
2022-10-21T14:10:13.520+0200	INFO	markets	loggers/loggers.go:65	module ready	{"module": "storage client"}
2022-10-21T14:10:13.520+0200	INFO	markets	loggers/loggers.go:65	module ready	{"module": "retrieval client"}
2022-10-21T14:10:13.521+0200	INFO	healthcheck	node/health.go:57	waiting 1s before starting ChainNotify channel
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
2022-10-21T14:10:13.911+0200	WARN	data_transfer_network	shared/retrystream.go:92	failed to open stream to 12D3KooWRzogEQ6aSXNWHyTVCfcWvutTdsL496CGWGRDn3TCcYjT on attempt 1 of 15, waiting 1s to try again, err: failed to find any peer in table
2022-10-21T14:10:14.408+0200	INFO	badgerbs	v2@v2.2007.3/levels.go:1000	[Compactor: 1] Running compaction: {level:2 score:1.0242194898426533 dropPrefixes:[]} for level: 2

2022-10-21T14:10:14.521+0200	INFO	healthcheck	node/health.go:70	started ChainNotify channel
2022-10-21T14:10:14.912+0200	WARN	data_transfer_network	shared/retrystream.go:92	failed to open stream to 12D3KooWRzogEQ6aSXNWHyTVCfcWvutTdsL496CGWGRDn3TCcYjT on attempt 2 of 15, waiting 11.133413981s to try again, err: failed to find any peer in table
2022-10-21T14:10:15.049+0200	INFO	net/identify	identify/id.go:364	failed negotiate identify protocol with peer	{"peer": "12D3KooWAiHp1bUF9BQsFDDnVVMy6pLWjQe9pFtQZQNYCeZF5CPg", "error": "stream reset"}
2022-10-21T14:10:15.360+0200	INFO	net/identify	identify/id.go:364	failed negotiate identify protocol with peer	{"peer": "12D3KooWRRBb1MV3CMtrqx7qwYmshncVZtWEkZs4qcpLTdNXN55M", "error": "stream reset"}
2022-10-21T14:10:17.748+0200	INFO	chain	chain/sync_manager.go:219	selected initial sync target: [bafy2bzacecwhige24tz4xqghhhmhuedhyad2yznitqkqasva4tl7c6sjlr6j6 bafy2bzacedtne6wvull4honjtfu7i2in4jtyq6nnmqjizxegbtvgbc7oq56cy bafy2bzacea3t25le56dyhg4ge2dp7ciyl4mdyih5pkvcuu4kf4ffqbi5zwqze bafy2bzacec3ixnnhxmlajhah54fpoaclftp5nwuroovfxmgiezaqbvo66xrr2 bafy2bzacebb67j6mkgg7lvm7tqrsr6trzikad2r6t5m4xi4vqxcqf7g7edlwg bafy2bzacecchcsadnycf5jyznoe24l5mmph6qbxlfbb5lsq7wf33qi4ljwfo2]
2022-10-21T14:10:17.748+0200	INFO	chain	chain/sync_manager.go:315	worker 0 syncing in [bafy2bzacecwhige24tz4xqghhhmhuedhyad2yznitqkqasva4tl7c6sjlr6j6 bafy2bzacedtne6wvull4honjtfu7i2in4jtyq6nnmqjizxegbtvgbc7oq56cy bafy2bzacea3t25le56dyhg4ge2dp7ciyl4mdyih5pkvcuu4kf4ffqbi5zwqze bafy2bzacec3ixnnhxmlajhah54fpoaclftp5nwuroovfxmgiezaqbvo66xrr2 bafy2bzacebb67j6mkgg7lvm7tqrsr6trzikad2r6t5m4xi4vqxcqf7g7edlwg bafy2bzacecchcsadnycf5jyznoe24l5mmph6qbxlfbb5lsq7wf33qi4ljwfo2]
2022-10-21T14:10:18.263+0200	INFO	chain	chain/sync.go:790	Got blocks: 2268259 17
2022-10-21T14:10:18.265+0200	INFO	chain	chain/sync.go:1089	fetching messages at 16
2022-10-21T14:10:18.265+0200	INFO	chain	chain/sync.go:1089	fetching messages at 0
2022-10-21T14:10:18.265+0200	INFO	chain	chain/sync.go:1089	fetching messages at 8
panic: runtime error: slice bounds out of range [4263:241]

goroutine 679 [running]:
github.com/dgraph-io/badger/v2/table.(*blockIterator).setIdx(0x4a0000?, 0x4a?)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/table/iterator.go:80 +0x476
github.com/dgraph-io/badger/v2/table.(*blockIterator).next(...)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/table/iterator.go:145
github.com/dgraph-io/badger/v2/table.(*Iterator).next(0xc060c69b00)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/table/iterator.go:307 +0x20c
github.com/dgraph-io/badger/v2/table.(*Iterator).Next(0x200000042?)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/table/iterator.go:367 +0x2c
github.com/dgraph-io/badger/v2/table.(*node).next(0xc06158cdc0)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/table/merge_iterator.go:84 +0x49
github.com/dgraph-io/badger/v2/table.(*MergeIterator).Next(0xc06158cdc0)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/table/merge_iterator.go:158 +0x2e
github.com/dgraph-io/badger/v2.(*levelsController).compactBuildTables(0xc0007ce460, 0x2, {{0x4a79fc0, 0xc05c0b69c0}, 0xc0008a1980, 0xc0008a19e0, {0xc0613a68b8, 0x1, 0x1}, {0xc061591170, ...}, ...})
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/levels.go:576 +0x131a
github.com/dgraph-io/badger/v2.(*levelsController).runCompactDef(0xc0007ce460, 0x0?, {{0x4a79fc0, 0xc05c0b69c0}, 0xc0008a1980, 0xc0008a19e0, {0xc0613a68b8, 0x1, 0x1}, {0xc061591170, ...}, ...})
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/levels.go:933 +0xc9
github.com/dgraph-io/badger/v2.(*levelsController).doCompact(0xc0007ce460, 0xc000b84ed8?, {0x2, 0x3ff06333f9cccccd, {0x0, 0x0, 0x0}})
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/levels.go:1003 +0x612
github.com/dgraph-io/badger/v2.(*levelsController).runCompactor(0xc0007ce460, 0x1, 0xc000b14510)
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/levels.go:404 +0x317
created by github.com/dgraph-io/badger/v2.(*levelsController).startCompact
	/root/go/pkg/mod/github.com/dgraph-io/badger/v2@v2.2007.3/levels.go:371 +0x50


Version : v1.17.2

**Comment by cryptowhizzard** [comment]
Btw :

Running with:

[Chainstore]
 EnableSplitstore = true

[Chainstore.Splitstore]
 ColdStoreType = "universal"
 EnableColdStoreAutoPrune = true
