### ISSUE TITLE
“lotus daemon” 运行不起来。  It doesn't work。

### ISSUE THREAD

**Issue by ChaiWenyu1983** [filecoin-project/lotus#9176]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
V1.17.0
```

### Describe the Bug

Suddenly, the "Lotus miner sectors list" cannot be executed. Close the "Lotus daemon" and reopen it. The information displayed is as follows:
2022-08-17T16:54:24.835+0800	WARN	modules	modules/chain.go:89	loading chain state from disk: loading tipset: get block bafy2bzaceavngqh74vhv26nrjfz2tkhd3qv2bh6xyhyvkzgjws6z57dbgtljc: ipld: could not find bafy2bzaceavngqh74vhv26nrjfz2tkhd3qv2bh6xyhyvkzgjws6z57dbgtljc
2022-08-17T16:54:24.847+0800	INFO	p2pnode	lp2p/addrs.go:101	Swarm listening at: [/ip6/::1/tcp/36575 /ip4/127.0.0.1/tcp/24002 /ip4/192.168.0.2/tcp/24002 /ip4/192.168.0.13/tcp/24002]
2022-08-17T16:54:24.852+0800	INFO	modules	modules/services.go:162	subscribing to pubsub topic /fil/blocks/testnetnet
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x20852d2]

goroutine 1 [running]:
github.com/filecoin-project/lotus/chain/types.(*TipSet).Blocks(...)
	/home/chaiwenyu/lotus/chain/types/tipset.go:160
github.com/filecoin-project/lotus/chain/types.(*TipSet).MinTimestamp(...)
	/home/chaiwenyu/lotus/chain/types/tipset.go:199
github.com/filecoin-project/lotus/node/modules.waitForSync(0xc001170900, 0xa, 0xc064853380)
	/home/chaiwenyu/lotus/node/modules/services.go:109 +0x32
github.com/filecoin-project/lotus/node/modules.HandleIncomingMessages({0x7fc84c2d7b80?, 0xc000b24ab0?}, {0x4a9f160?, 0xc000010768?}, 0xc06483f800, 0x4?, 0xc0653f41a0, {0x4ac8180, 0xc000b76320}, {0x3d2c763, ...}, ...)
	/home/chaiwenyu/lotus/node/modules/services.go:198 +0x27e
reflect.Value.call({0x39cc820?, 0x47c2208?, 0x4acfa08?}, {0x3cf94df, 0x4}, {0xc062bf8180, 0x8, 0x0?})
	/usr/local/go/src/reflect/value.go:556 +0x845
reflect.Value.Call({0x39cc820?, 0x47c2208?, 0x8?}, {0xc062bf8180, 0x8, 0x8})
	/usr/local/go/src/reflect/value.go:339 +0xbf
go.uber.org/dig.defaultInvoker({0x39cc820?, 0x47c2208?, 0xc0029b1680?}, {0xc062bf8180?, 0x8?, 0x4ac1e58?})
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/dig@v1.12.0/dig.go:355 +0x28
go.uber.org/dig.(*Container).Invoke(0xc0004b0910, {0x39cc820?, 0x47c2208}, {0x183615a?, 0x1?, 0x1?})
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/dig@v1.12.0/dig.go:510 +0x3a5
go.uber.org/fx.(*App).executeInvoke(0xc000a5f1e0, {{0x39cc820, 0x47c2208}, {0xc000a1bcc0, 0x7, 0x8}})
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/fx@v1.15.0/app.go:964 +0x39f
go.uber.org/fx.(*App).executeInvokes(...)
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/fx@v1.15.0/app.go:929
go.uber.org/fx.New({0xc000a15458, 0x3, 0x1b?})
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/fx@v1.15.0/app.go:596 +0xa4b
github.com/filecoin-project/lotus/node.New({0x4ab3040, 0xc0012a5bc0}, {0xc0004b0050, 0x9, 0x9})

### Logging Information

```text
all
```

### Repo Steps

1. Run 'Lotus daemon'
2. 
2022-08-17T16:54:24.835+0800	WARN	modules	modules/chain.go:89	loading chain state from disk: loading tipset: get block bafy2bzaceavngqh74vhv26nrjfz2tkhd3qv2bh6xyhyvkzgjws6z57dbgtljc: ipld: could not find bafy2bzaceavngqh74vhv26nrjfz2tkhd3qv2bh6xyhyvkzgjws6z57dbgtljc
2022-08-17T16:54:24.847+0800	INFO	p2pnode	lp2p/addrs.go:101	Swarm listening at: [/ip6/::1/tcp/36575 /ip4/127.0.0.1/tcp/24002 /ip4/192.168.0.2/tcp/24002 /ip4/192.168.0.13/tcp/24002]
2022-08-17T16:54:24.852+0800	INFO	modules	modules/services.go:162	subscribing to pubsub topic /fil/blocks/testnetnet
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x20852d2]

goroutine 1 [running]:
github.com/filecoin-project/lotus/chain/types.(*TipSet).Blocks(...)
	/home/chaiwenyu/lotus/chain/types/tipset.go:160
github.com/filecoin-project/lotus/chain/types.(*TipSet).MinTimestamp(...)
	/home/chaiwenyu/lotus/chain/types/tipset.go:199
github.com/filecoin-project/lotus/node/modules.waitForSync(0xc001170900, 0xa, 0xc064853380)
	/home/chaiwenyu/lotus/node/modules/services.go:109 +0x32
github.com/filecoin-project/lotus/node/modules.HandleIncomingMessages({0x7fc84c2d7b80?, 0xc000b24ab0?}, {0x4a9f160?, 0xc000010768?}, 0xc06483f800, 0x4?, 0xc0653f41a0, {0x4ac8180, 0xc000b76320}, {0x3d2c763, ...}, ...)
	/home/chaiwenyu/lotus/node/modules/services.go:198 +0x27e
reflect.Value.call({0x39cc820?, 0x47c2208?, 0x4acfa08?}, {0x3cf94df, 0x4}, {0xc062bf8180, 0x8, 0x0?})
	/usr/local/go/src/reflect/value.go:556 +0x845
reflect.Value.Call({0x39cc820?, 0x47c2208?, 0x8?}, {0xc062bf8180, 0x8, 0x8})
	/usr/local/go/src/reflect/value.go:339 +0xbf
go.uber.org/dig.defaultInvoker({0x39cc820?, 0x47c2208?, 0xc0029b1680?}, {0xc062bf8180?, 0x8?, 0x4ac1e58?})
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/dig@v1.12.0/dig.go:355 +0x28
go.uber.org/dig.(*Container).Invoke(0xc0004b0910, {0x39cc820?, 0x47c2208}, {0x183615a?, 0x1?, 0x1?})
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/dig@v1.12.0/dig.go:510 +0x3a5
go.uber.org/fx.(*App).executeInvoke(0xc000a5f1e0, {{0x39cc820, 0x47c2208}, {0xc000a1bcc0, 0x7, 0x8}})
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/fx@v1.15.0/app.go:964 +0x39f
go.uber.org/fx.(*App).executeInvokes(...)
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/fx@v1.15.0/app.go:929
go.uber.org/fx.New({0xc000a15458, 0x3, 0x1b?})
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/fx@v1.15.0/app.go:596 +0xa4b
github.com/filecoin-project/lotus/node.New({0x4ab3040, 0xc0012a5bc0}, {0xc0004b0050, 0x9, 0x9})
	/home/chaiwenyu/lotus/node/builder.go:358 +0x477
main.glob..func5(0xc0012b6740)
	/home/chaiwenyu/lotus/cmd/lotus/daemon.go:317 +0x1609
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000702680, 0xc0012b6240)
	/home/chaiwenyu/gowork/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:495 +0xaff
github.com/urfave/cli/v2.(*Command).startApp(0x9404dc0, 0xc0012b6240)
	/home/chaiwenyu/gowork/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:287 +0x77b
github.com/urfave/cli/v2.(*Command).Run(0xc0005fc960?, 0xc0005fc960?)
	/home/chaiwenyu/gowork/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:95 +0xba
github.com/urfave/cli/v2.(*App).RunContext(0xc000603ba0, {0x4ab2fd0?, 0xc0001a8000}, {0xc0001a6000, 0x2, 0x2})
	/home/chaiwenyu/gowork/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:341 +0xbc8
github.com/urfave/cli/v2.(*App).Run(...)
	/home/chaiwenyu/gowork/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:247
github.com/filecoin-project/lotus/cli.RunApp(0x3941a60?)
	/home/chaiwenyu/lotus/cli/helper.go:35 +0x4e
main.main()
	/home/chaiwenyu/lotus/cmd/lotus/main.go:111 +0x90

**Comment by rjan90** [comment]
Hey @ChaiWenyu1983!
- Which network are you on?
- When does this exavtly happen, on startup of the Lotus-node?
- Which lotus-version are you exactly using? I would need the commits and such after just the version name to help you out.

**Comment by ChaiWenyu1983** [comment]
> 
@rjan90 
1.mainnet.
2.Execute "Lotus daemon”Command, which occurs in a few seconds.
3.V1.17.0。
The records are as follows:
chaiwenyu@chaiwenyu-System-Product-Name:~$ lotus daemon
2022-08-17T17:55:06.777+0800	INFO	main	lotus/daemon.go:218	lotus repo: /home/chaiwenyu/.lotus
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-032d3138d22506ec0082ed72b2dcba18df18477904e35bafee82b3793b06832f.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-empty-sector-update-merkletree-poseidon_hasher-8-8-0-3b7f44a9362e3985369454947bc94022e118211e49fd672d52bec1cbfd599d18.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-ecd683648512ab1765faa2a5f14bab48f676e633467f0aa8aad4b55dcb0652bb.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-3ea05428c9d11689f23529cde32fd30aabd50f7d2c93657c1d3650bca3e8ea9e.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-empty-sector-update-merkletree-poseidon_hasher-8-0-0-61fa69f38b9cc771ba27b670124714b4ea77fbeae05e377fb859c4a43b73a30c.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-empty-sector-update-merkletree-poseidon_hasher-8-8-2-102e1444a7e9a97ebf1e3d6855dcc77e66c011ea66f936d9b2c508f87f2f83a7.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-7d739b8cf60f1b0709eeebee7730e297683552e4b69cab6984ec0285663c5781.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-2-sha256_hasher-96f1b4a04c5c51e4759bbf224bbc2ef5a42c7100f16ec0637123f16a845ddfb2.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0cfb4f178bbb71cf2ecfcd42accce558b27199ab4fb59cb78f2483fe21ef36d9.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-5294475db5237a2e83c3e52fd6c2b03859a1831d45ed08c4f35dbf9a803165a9.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-b62098629d07946e9028127e70295ed996fe3ed25b0f9f88eb610a0ab4385a3c.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-empty-sector-update-merkletree-poseidon_hasher-8-0-0-92180959e1918d26350b8e6cfe217bbdd0a2d8de51ebec269078b364b715ad63.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0170db1f394b35d995252228ee359194b13199d259380541dc529fb0099096b0.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-50c7368dea9593ed0989e70974d28024efa9d156d585b7eea1be22b2e753f331.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-6babf46ce344ae495d558e7770a585b2382d54f225af8ed0397b8be7c3fcd472.vk is ok
2022-08-17T17:55:06.778+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-empty-sector-update-merkletree-poseidon_hasher-8-0-0-fb9e095bebdd77511c0269b967b4d87ba8b8a525edaa0e165de23ba454510194.vk is ok
2022-08-17T17:55:06.783+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c4509eedae8a27555733edc.vk is ok
2022-08-17T17:55:06.784+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-2627e4006b67f99cef990c0a47d5426cb7ab0a0ad58fc1061547bf2d28b09def.vk is ok
2022-08-17T17:55:07.115+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /mnt/ssd2/parameter_cache/v28-fil-inner-product-v1.srs is ok
2022-08-17T17:55:07.115+0800	INFO	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:233	parameter and key-fetching complete
2022-08-17T17:55:07.120+0800	INFO	modules	modules/core.go:64	memory limits initialized	{"max_mem_heap": 0, "total_system_mem": 270109818880, "effective_mem_limit": 270109818880}
2022-08-17T17:55:07.120+0800	WARN	modules	modules/core.go:124	failed to initialize cgroup-driven watchdog; err: failed to load cgroup for process: cgroups: cgroup mountpoint does not exist
2022-08-17T17:55:07.120+0800	WARN	modules	modules/core.go:125	trying a system-driven watchdog
2022-08-17T17:55:07.120+0800	INFO	watchdog	go-watchdog@v1.2.0/watermarks.go:16	initialized watermark watchdog policy; watermarks: []; thresholds: [135054909440 162065891328 189076873216 229593346048 243098836992 249851582464 256604327936]
2022-08-17T17:55:07.120+0800	INFO	watchdog	go-watchdog@v1.2.0/watchdog.go:471	initialized heap profile capture; threshold: 0.900000; max captures: 10; dir: /home/chaiwenyu/.lotus/heapprof
2022-08-17T17:55:07.120+0800	INFO	modules	modules/core.go:130	initialized system-driven watchdog
2022-08-17T17:55:07.120+0800	INFO	p2pnode	lp2p/rcmgr.go:35	libp2p resource manager is enabled
2022-08-17T17:55:07.120+0800	INFO	p2pnode	lp2p/rcmgr.go:66	adjusted default resource manager limits
2022-08-17T17:55:07.139+0800	INFO	badger	v2@v2.2007.3/levels.go:183	All 0 tables opened in 0s

2022-08-17T17:55:07.140+0800	INFO	badger	v2@v2.2007.3/value.go:1158	Replaying file id: 0 at offset: 0

2022-08-17T17:55:07.140+0800	INFO	badger	v2@v2.2007.3/value.go:1178	Replay took: 3.026µs

2022-08-17T17:55:07.147+0800	INFO	badger	v2@v2.2007.3/levels.go:183	All 0 tables opened in 0s

2022-08-17T17:55:07.148+0800	INFO	badger	v2@v2.2007.3/value.go:1158	Replaying file id: 0 at offset: 0

2022-08-17T17:55:07.148+0800	INFO	badger	v2@v2.2007.3/value.go:1178	Replay took: 4.188µs

2022-08-17T17:55:08.508+0800	INFO	badgerbs	v2@v2.2007.3/levels.go:183	All 340 tables opened in 1.346s

2022-08-17T17:55:08.549+0800	INFO	badgerbs	v2@v2.2007.3/value.go:1158	Replaying file id: 450 at offset: 5340902

2022-08-17T17:55:08.601+0800	INFO	badgerbs	v2@v2.2007.3/value.go:1178	Replay took: 52.674071ms

2022-08-17T17:55:08.602+0800	WARN	modules	modules/chain.go:89	loading chain state from disk: loading tipset: get block bafy2bzaceavngqh74vhv26nrjfz2tkhd3qv2bh6xyhyvkzgjws6z57dbgtljc: ipld: could not find bafy2bzaceavngqh74vhv26nrjfz2tkhd3qv2bh6xyhyvkzgjws6z57dbgtljc
2022-08-17T17:55:08.613+0800	INFO	p2pnode	lp2p/addrs.go:101	Swarm listening at: [/ip4/127.0.0.1/tcp/24002 /ip4/192.168.0.2/tcp/24002 /ip4/192.168.0.13/tcp/24002 /ip6/::1/tcp/39141]
2022-08-17T17:55:08.618+0800	INFO	modules	modules/services.go:162	subscribing to pubsub topic /fil/blocks/testnetnet
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x20852d2]

goroutine 1 [running]:
github.com/filecoin-project/lotus/chain/types.(*TipSet).Blocks(...)
	/home/chaiwenyu/lotus/chain/types/tipset.go:160
github.com/filecoin-project/lotus/chain/types.(*TipSet).MinTimestamp(...)
	/home/chaiwenyu/lotus/chain/types/tipset.go:199
github.com/filecoin-project/lotus/node/modules.waitForSync(0xc001343200, 0xa, 0xc06728e000)
	/home/chaiwenyu/lotus/node/modules/services.go:109 +0x32
github.com/filecoin-project/lotus/node/modules.HandleIncomingMessages({0x7f5fac05d818?, 0xc000b66ab0?}, {0x4a9f160?, 0xc000613948?}, 0xc067020000, 0x4?, 0xc067275380, {0x4ac8180, 0xc001896600}, {0x3d2c763, ...}, ...)
	/home/chaiwenyu/lotus/node/modules/services.go:198 +0x27e
reflect.Value.call({0x39cc820?, 0x47c2208?, 0x4acfa08?}, {0x3cf94df, 0x4}, {0xc00065b500, 0x8, 0x0?})
	/usr/local/go/src/reflect/value.go:556 +0x845
reflect.Value.Call({0x39cc820?, 0x47c2208?, 0x8?}, {0xc00065b500, 0x8, 0x8})
	/usr/local/go/src/reflect/value.go:339 +0xbf
go.uber.org/dig.defaultInvoker({0x39cc820?, 0x47c2208?, 0xc0007ddc80?}, {0xc00065b500?, 0x8?, 0x4ac1e58?})
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/dig@v1.12.0/dig.go:355 +0x28
go.uber.org/dig.(*Container).Invoke(0xc00061e910, {0x39cc820?, 0x47c2208}, {0x183615a?, 0x1?, 0x1?})
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/dig@v1.12.0/dig.go:510 +0x3a5
go.uber.org/fx.(*App).executeInvoke(0xc0002185b0, {{0x39cc820, 0x47c2208}, {0xc000fedcc0, 0x7, 0x8}})
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/fx@v1.15.0/app.go:964 +0x39f
go.uber.org/fx.(*App).executeInvokes(...)
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/fx@v1.15.0/app.go:929
go.uber.org/fx.New({0xc0006e9458, 0x3, 0x1b?})
	/home/chaiwenyu/gowork/pkg/mod/go.uber.org/fx@v1.15.0/app.go:596 +0xa4b
github.com/filecoin-project/lotus/node.New({0x4ab3040, 0xc001377d70}, {0xc00061e050, 0x9, 0x9})
	/home/chaiwenyu/lotus/node/builder.go:358 +0x477
main.glob..func5(0xc001404740)
	/home/chaiwenyu/lotus/cmd/lotus/daemon.go:317 +0x1609
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000702b60, 0xc001404240)
	/home/chaiwenyu/gowork/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:495 +0xaff
github.com/urfave/cli/v2.(*Command).startApp(0x9404dc0, 0xc001404240)
	/home/chaiwenyu/gowork/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:287 +0x77b
github.com/urfave/cli/v2.(*Command).Run(0xc00025fd60?, 0xc00025fd60?)
	/home/chaiwenyu/gowork/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:95 +0xba
github.com/urfave/cli/v2.(*App).RunContext(0xc000702820, {0x4ab2fd0?, 0xc000222000}, {0xc000220000, 0x2, 0x2})
	/home/chaiwenyu/gowork/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:341 +0xbc8
github.com/urfave/cli/v2.(*App).Run(...)
	/home/chaiwenyu/gowork/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:247
github.com/filecoin-project/lotus/cli.RunApp(0x3941a60?)
	/home/chaiwenyu/lotus/cli/helper.go:35 +0x4e
main.main()
	/home/chaiwenyu/lotus/cmd/lotus/main.go:111 +0x90c

**Comment by rjan90** [comment]
Try to re-import from new snapshot:
```
install aria2c
lotus daemon stop
rm -r .lotus/datastore/chain/*
aria2c -x5 https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car
----Wait untill finished----
lotus daemon --import-snapshot <the file you downloaded> --halt-after-import
----Wait until the process is done, and halted.----
lotus daemon
lotus sync wait
```

**Comment by rjan90** [comment]
Hey @ChaiWenyu1983! Have you been able to re-import from a new snapshot, and restart your daemon yet?
