### ISSUE TITLE
Lotus-miner sealing abort does not end task

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#9191]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [X] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.17.1-rc3+mainnet+git.079dab0d7+api1.5.0
Local: lotus-miner version 1.17.1-rc3+mainnet+git.079dab0d7
```

### Describe the Bug

Lotus-miner started two unseal jobs prior to wdpost.
I attempted to abort both unseal jobs but commands had no affect on running jobs.
wdpost failed due to GPU barely running - see issue https://github.com/filecoin-project/lotus/issues/8918
Unseal does not work on lotus-worker machines.

` lotus-miner sealing jobs`

 |  ID | Sector | Worker | Hostname | Task | State | Time | 
 | - | - | - | - | - | - | - | 
 |  0b4d2081 | 5092 | 8b79d15f | sealer | PC1 | running | 2h20m52.3s | 
 |  e9bce0bc | 5091 | 8b79d15f | sealer | PC1 | running | 2h20m51.4s | 
 |  83e013c5 | 1076 | bc36dd3a | filecoin | UNS | running | 1h57m27.5s | 
 |  665756d1 | 1158 | bc36dd3a | filecoin | UNS | running | 1h54m44.3s | 
 |  df29fb7b | 5089 | 8b79d15f | sealer | PC1 | running | 1h22m57.3s | 
 |  7034d81f | 5085 | 8b79d15f | sealer | C2 | running | 1h12m16.6s | 
 |  00000000 | 5093 | 8b79d15f | sealer | PC1 | prepared | 2h20m50.6s | 
 |  00000000 | 5090 | 8b79d15f | sealer | PC1 | prepared | 2h20m50.5s | 
 |  00000000 | 5095 | 8b79d15f | sealer | PC1 | prepared | 1h22m57.2s | 
 |  00000000 | 5084 | 8b79d15f | sealer | C2 | prepared | 1h12m18.9s | 
 |  00000000 | 5086 | 8b79d15f | sealer | PC2 | assigned(1) | 1h22m57.2s | 

### Logging Information

```text
2022-08-19T13:37:47.180Z	WARN	rpc	go-jsonrpc@v0.1.5/handler.go:279	error in RPC call to 'Filecoin.SectorsUnsealPiece': worker UnsealPiece call:
    github.com/filecoin-project/lotus/storage/sealer.(*Manager).SectorsUnsealPiece
        /home/stuart/lotus/storage/sealer/manager.go:392
  - storage call error 0: task aborted


lotus-miner
```

### Repo Steps

`lotus-miner sealing abort cea7a22e`
aborting job 1278-1072-cea7a22e-6c96-454a-9146-1246f0c3e7db, task UNS, sector 1072, running on host 

`lotus-miner sealing abort bde2a202`
aborting job 1278-1158-bde2a202-5eed-4e27-87d3-74e971df6167, task UNS, sector 1158, running on host 

Tasks continue to run despite this command - also tried

`lotus-miner sealing abort --sched bde2a202`

> panic: invalid UUID length: 8
> 
> goroutine 1 [running]:
> github.com/google/uuid.Must(...)
> 	/home/stuart/go/pkg/mod/github.com/google/uuid@v1.3.0/uuid.go:178
> main.glob..func64(0xc00128ac40)
> 	/home/stuart/lotus/cmd/lotus-miner/sealing.go:388 +0x498
> github.com/urfave/cli/v2.(*Command).Run(0x6fc7b80, 0xc00128ab40)
> 	/home/stuart/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:169 +0x631
> github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000603a00, 0xc00128a980)
> 	/home/stuart/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:490 +0xd0a
> github.com/urfave/cli/v2.(*Command).startApp(0x6fc7dc0, 0xc00128a980)
> 	/home/stuart/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:287 +0x77b
> github.com/urfave/cli/v2.(*Command).Run(0xc00128a980?, 0xc000244500?)
> 	/home/stuart/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:95 +0xba
> github.com/urfave/cli/v2.(*App).RunContext(0xc0006036c0, {0x441c3c8?, 0xc000052928}, {0xc00004e0a0, 0x5, 0x5})
> 	/home/stuart/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:341 +0xbc8
> github.com/urfave/cli/v2.(*App).Run(...)
> 	/home/stuart/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:247
> github.com/filecoin-project/lotus/cli.RunApp(0x38f0a00?)
> 	/home/stuart/lotus/cli/helper.go:35 +0x4e
> main.main()
> 	/home/stuart/lotus/cmd/lotus-miner/main.go:168 +0x10e5

**Comment by stuberman** [comment]
Seems to work now. Closing
