### ISSUE TITLE
Lotus 1.17.2-rc1 Unable to PoST large deadline

### ISSUE THREAD

**Issue by stuberman** [filecoin-project/lotus#9376]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [X] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
Daemon:  1.17.2-rc1+mainnet+git.39604faa0+api1.5.0
Local: lotus-miner version 1.17.2-rc1+mainnet+git.39604faa0
```

### Describe the Bug

Deadline 2 (largest deadline currently) attempted to run Window PoST 3 times and fails as shown below.

I upgraded to v1.17.2-rc2 five days ago without any PoST issues

Error: thread '<unnamed>' panicked at 'range end index 1152921517236374952 out of range for slice of length 60780374232', library/core/src/slice/index.rs:73:5

### Logging Information

```text
2022-09-26T16:09:55.434Z	WARN	wdpost	wdpost/wdpost_run.go:234	Checked sectors	{"checked": 2282, "good": 2282}
2022-09-26T16:09:55.522Z	INFO	wdpost	wdpost/wdpost_run.go:388	running window post	{"chain-random": "1ZrO2bkr9QCkdohTgl/uu0L0nOE4jKYXCUouzOqXf9Y=", "deadline": {"CurrentEpoch":2196735,"PeriodStart":2196589,"Index":2,"Open":2196709,"Close":2196769,"Challenge":2196689,"FaultCutoff":2196639,"WPoStPeriodDeadlines":48,"WPoStProvingPeriod":2880,"WPoStChallengeWindow":60,"WPoStChallengeLookback":20,"FaultDeclarationCutoff":70}, "height": "2196735", "skipped": 0}
2022-09-26T16:09:55.522Z	INFO	advmgr	sealer/manager_post.go:84	GenerateWindowPoSt run at lotus-miner
2022-09-26T16:09:55.545 INFO filcrypto::util::types > generate_window_post: start
2022-09-26T16:09:55.597 INFO filecoin_proofs::api::window_post > generate_window_post:start
2022-09-26T16:09:55.602 INFO filecoin_proofs::caches > trying parameters memory cache for: Window_POST[34359738368]
2022-09-26T16:09:55.603 INFO filecoin_proofs::caches > found params in memory cache for Window_POST[34359738368]
2022-09-26T16:09:56.076 INFO storage_proofs_core::compound_proof > vanilla_proofs:start
2022-09-26T16:10:03.298 INFO storage_proofs_core::compound_proof > vanilla_proofs:finish
2022-09-26T16:10:04.132 INFO storage_proofs_core::compound_proof > snark_proof:start
2022-09-26T16:10:04.229 INFO bellperson::groth16::prover > Bellperson 0.22.0 is being used!
2022-09-26T16:10:10.333Z	INFO	miner	miner/miner.go:475	completed mineOne	{"tookMilliseconds": 14, "forRound": 2196741, "baseEpoch": 2196740, "baseDeltaSeconds": 10, "nullRounds": 0, "lateStart": false, "beaconEpoch": 2292586, "lookbackEpochs": 900, "networkPowerAtLookback": "21377140215153491968", "minerPowerAtLookback": "1207357525098496", "isEligible": true, "isWinner": false, "error": null}
2022-09-26T16:10:34.608 INFO bellperson::groth16::prover > synthesis time: 30.378009998s
2022-09-26T16:10:34.609 INFO bellperson::groth16::prover > starting proof timer
2022-09-26T16:10:38.780 INFO bellperson::gpu::locks > GPU is available for FFT!
2022-09-26T16:10:38.787 INFO ec_gpu_gen::program > Using kernel on CUDA.
2022-09-26T16:10:38.856 INFO ec_gpu_gen::fft > FFT: 1 working device(s) selected. 
2022-09-26T16:10:38.856 INFO ec_gpu_gen::fft > FFT: Device 0: NVIDIA GeForce RTX 2080 Ti
2022-09-26T16:10:38.856 INFO bellperson::gpu::locks > GPU FFT kernel instantiated!
2022-09-26T16:10:40.025Z	INFO	miner	miner/miner.go:475	completed mineOne	{"tookMilliseconds": 16, "forRound": 2196742, "baseEpoch": 2196741, "baseDeltaSeconds": 10, "nullRounds": 0, "lateStart": false, "beaconEpoch": 2292587, "lookbackEpochs": 900, "networkPowerAtLookback": "21377236216262492160", "minerPowerAtLookback": "1207357525098496", "isEligible": true, "isWinner": false, "error": null}
thread '<unnamed>' panicked at 'range end index 1152921517236374952 out of range for slice of length 60780374232', library/core/src/slice/index.rs:73:5
stack backtrace:
   0:          0x34b7e2d - std::backtrace_rs::backtrace::libunwind::trace::h02bdfeed412ba77b
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:          0x34b7e2d - std::backtrace_rs::backtrace::trace_unsynchronized::h5721e9ec9537655b
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:          0x34b7e2d - std::sys_common::backtrace::_print_fmt::h10137ddb502bbd3d
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys_common/backtrace.rs:66:5
   3:          0x34b7e2d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1437c86ead09a95e
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys_common/backtrace.rs:45:22
   4:          0x3513f3c - core::fmt::write::hdf7e5ac637575708
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/fmt/mod.rs:1196:17
   5:          0x34a9511 - std::io::Write::write_fmt::h00341f121451a31a
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/io/mod.rs:1655:15
   6:          0x34bab45 - std::sys_common::backtrace::_print::he4ececdb06ab9d22
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys_common/backtrace.rs:48:5
   7:          0x34bab45 - std::sys_common::backtrace::print::h55b32276835ed858
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys_common/backtrace.rs:35:9
   8:          0x34bab45 - std::panicking::default_hook::{{closure}}::h6999a27c7f7e27cf
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:295:22
   9:          0x34ba7b9 - std::panicking::default_hook::hcc406adc7605c4f5
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:314:9
  10:          0x34bb268 - std::panicking::rust_panic_with_hook::haf8e1f62f460c64d
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:698:17
  11:          0x34bb117 - std::panicking::begin_panic_handler::{{closure}}::hf3a68aa6ac5cd357
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:588:13
  12:          0x34b82e4 - std::sys_common::backtrace::__rust_end_short_backtrace::h1515778c280a0daf
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys_common/backtrace.rs:138:18
  13:          0x34bae49 - rust_begin_unwind
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:584:5
  14:           0x646b43 - core::panicking::panic_fmt::hfe413bf5e72d349d
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/panicking.rs:142:14
  15:          0x3516696 - core::slice::index::slice_end_index_len_fail_rt::ha15640a178740d01
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/slice/index.rs:73:5
  16:          0x3508467 - core::ops::function::FnOnce::call_once::hcd3611316170667c
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/ops/function.rs:248:5
  17:          0x350f2d6 - core::intrinsics::const_eval_select::hd1241a9a797e240a
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/intrinsics.rs:2370:5
  18:           0x646c56 - core::slice::index::slice_end_index_len_fail::haad05540ea8143e6
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/slice/index.rs:67:9
  19:          0x30478b2 - bellperson::groth16::mapped_params::read_g1::hd8feac103a41645e
  20:          0x36899b3 - <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend::h5634b2f39d2c9ed5
  21:          0x2f72061 - <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume_iter::hb417fb8bfef53f6c
  22:          0x3202c51 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7881401b4621a212
  23:          0x2fc9d31 - std::panicking::try::hff13245298972f4e
  24:          0x2d16c87 - rayon_core::registry::in_worker::h4e3660ddab9d93b9
  25:          0x3202d86 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7881401b4621a212
  26:          0x2fc9d31 - std::panicking::try::hff13245298972f4e
  27:          0x2d16c87 - rayon_core::registry::in_worker::h4e3660ddab9d93b9
  28:          0x3202d86 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7881401b4621a212
  29:          0x2fea284 - rayon_core::job::StackJob<L,F,R>::run_inline::hc3778daea20a9b15
  30:          0x2d16d48 - rayon_core::registry::in_worker::h4e3660ddab9d93b9
  31:          0x3202d86 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7881401b4621a212
  32:          0x2fea284 - rayon_core::job::StackJob<L,F,R>::run_inline::hc3778daea20a9b15
  33:          0x2d16d48 - rayon_core::registry::in_worker::h4e3660ddab9d93b9
  34:          0x3202d86 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7881401b4621a212
  35:          0x2fea284 - rayon_core::job::StackJob<L,F,R>::run_inline::hc3778daea20a9b15
  36:          0x2d16d48 - rayon_core::registry::in_worker::h4e3660ddab9d93b9
  37:          0x3202d86 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7881401b4621a212
  38:          0x2fc9d31 - std::panicking::try::hff13245298972f4e
  39:          0x2d16c87 - rayon_core::registry::in_worker::h4e3660ddab9d93b9
  40:          0x3202d86 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7881401b4621a212
  41:          0x2fb8f24 - std::panicking::try::h9218031b3cbf4549
  42:          0x3022e76 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h7a03958631981ad5
  43:           0x643195 - rayon_core::registry::WorkerThread::wait_until_cold::h6cef8b582c19156e
  44:          0x2d16e0e - rayon_core::registry::in_worker::h4e3660ddab9d93b9
  45:          0x3202d86 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7881401b4621a212
  46:          0x2fc9d31 - std::panicking::try::hff13245298972f4e
  47:          0x2d16c87 - rayon_core::registry::in_worker::h4e3660ddab9d93b9
  48:          0x3202d86 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7881401b4621a212
  49:          0x2fea284 - rayon_core::job::StackJob<L,F,R>::run_inline::hc3778daea20a9b15
  50:          0x2d16d48 - rayon_core::registry::in_worker::h4e3660ddab9d93b9
  51:          0x3202d86 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7881401b4621a212
  52:          0x2fc9d31 - std::panicking::try::hff13245298972f4e
  53:          0x2d16c87 - rayon_core::registry::in_worker::h4e3660ddab9d93b9
  54:          0x3202d86 - rayon::iter::plumbing::bridge_producer_consumer::helper::h7881401b4621a212
  55:          0x2fb8f24 - std::panicking::try::h9218031b3cbf4549
  56:          0x3022e76 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h7a03958631981ad5
  57:           0x643195 - rayon_core::registry::WorkerThread::wait_until_cold::h6cef8b582c19156e
  58:          0x342055b - rayon_core::registry::ThreadBuilder::run::h7155fc373805026b
  59:          0x3425a6f - std::sys_common::backtrace::__rust_begin_short_backtrace::h23b741c68b6b43d2
  60:          0x341d224 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h6592b88b571107bd
  61:          0x34c5263 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb34b480b2d661101
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/alloc/src/boxed.rs:1872:9
  62:          0x34c5263 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf9c0dea5d98fc73a
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/alloc/src/boxed.rs:1872:9
  63:          0x34c5263 - std::sys::unix::thread::Thread::new::thread_start::h70e37c0af4b187ae
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys/unix/thread.rs:108:17
  64:     0x7fef47e8a609 - start_thread
                               at /build/glibc-SzIz7B/glibc-2.31/nptl/pthread_create.c:477:8
  65:     0x7fef47c58133 - clone
                               at /build/glibc-SzIz7B/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95
  66:                0x0 - <unknown>
thread '<unnamed>' panicked at 'Worker Pool was poisoned', /home/stuart/.cargo/registry/src/github.com-1ecc6299db9ec823/yastl-0.1.2/src/wait.rs:50:13
stack backtrace:
   0:          0x34b7e2d - std::backtrace_rs::backtrace::libunwind::trace::h02bdfeed412ba77b
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:          0x34b7e2d - std::backtrace_rs::backtrace::trace_unsynchronized::h5721e9ec9537655b
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:          0x34b7e2d - std::sys_common::backtrace::_print_fmt::h10137ddb502bbd3d
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys_common/backtrace.rs:66:5
   3:          0x34b7e2d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1437c86ead09a95e
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys_common/backtrace.rs:45:22
   4:          0x3513f3c - core::fmt::write::hdf7e5ac637575708
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/core/src/fmt/mod.rs:1196:17
   5:          0x34a9511 - std::io::Write::write_fmt::h00341f121451a31a
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/io/mod.rs:1655:15
   6:          0x34bab45 - std::sys_common::backtrace::_print::he4ececdb06ab9d22
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys_common/backtrace.rs:48:5
   7:          0x34bab45 - std::sys_common::backtrace::print::h55b32276835ed858
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/sys_common/backtrace.rs:35:9
   8:          0x34bab45 - std::panicking::default_hook::{{closure}}::h6999a27c7f7e27cf
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:295:22
   9:          0x34ba7b9 - std::panicking::default_hook::hcc406adc7605c4f5
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:314:9
  10:          0x34bb268 - std::panicking::rust_panic_with_hook::haf8e1f62f460c64d
                               at /rustc/cb121987158d69bb894ba1bcc21dc45d1e0a488f/library/std/src/panicking.rs:698:17
  11:          0x334d8db - std::panicking::begin_panic::{{closure}}::h3e0e94e5424ba012
  12:          0x334d804 - std::sys_common::backtrace::__rust_end_short_backtrace::h7fcd9a1fcdde61a9
  13:           0x641b6a - std::panicking::begin_panic::h1fdfec220853e8b1
  14:          0x334aa56 - yastl::wait::WaitGroup::join::h6389584f3add3b67
  15:          0x2d8f30b - yastl::scope::Scope::zoom::h331d1c116e734682
  16:          0x2e76c9c - bellperson::groth16::prover::create_random_proof_batch_priority::hb079d34ded0f9299
  17:          0x3136870 - storage_proofs_core::compound_proof::CompoundProof::circuit_proofs::hff3193ee008b6d3d
  18:          0x3137a7c - storage_proofs_core::compound_proof::CompoundProof::prove::h80a304941a763266
  19:          0x31c155d - filecoin_proofs::api::window_post::generate_window_post::hb742b8e8215d792a
  20:          0x310043a - filecoin_proofs_api::post::generate_window_post_inner::h13bd706423e75d68
  21:          0x30fee5c - filecoin_proofs_api::post::generate_window_post::hea43e6937673c56d
  22:          0x25abefd - std::panicking::try::h3e00865efac9c20b
  23:          0x25f31b3 - filcrypto::util::types::catch_panic_response_raw::hbc528fdca13ea1da
  24:          0x27f8669 - generate_window_post
  25:          0x2220f77 - _cgo_2555bda33df2_Cfunc_generate_window_post
                               at /tmp/go-build/cgo-gcc-prolog:390:11
  26:           0x6cc0e4 - runtime.asmcgocall
                               at /usr/local/go/src/runtime/asm_amd64.s:821
2022-09-26T16:11:01.437Z	INFO	wdpost	wdpost/wdpost_run.go:403	computing window post	{"batch": 0, "elapsed": 65.914417241, "skip": 0, "err": "Rust panic: Worker Pool was poisoned"}
2022-09-26T16:11:01.450Z	ERROR	wdpost	wdpost/wdpost_run.go:405	error generating window post: Rust panic: Worker Pool was poisoned
2022-09-26T16:11:01.458Z	ERROR	wdpost	wdpost/wdpost_run.go:97	runPoStCycle failed: running window post failed:
    github.com/filecoin-project/lotus/storage/wdpost.(*WindowPoStScheduler).runPoStCycle
        /home/stuart/lotus/storage/wdpost/wdpost_run.go:466
  - Rust panic: Worker Pool was poisoned
2022-09-26T16:11:01.534Z	WARN	wdpost	wdpost/wdpost_changehandler.go:254	Aborted window post Proving (Deadline: &{CurrentEpoch:2196735 PeriodStart:2196589 Index:2 Open:2196709 Close:2196769 Challenge:2196689 FaultCutoff:2196639 WPoStPeriodDeadlines:48 WPoStProvingPeriod:2880 WPoStChallengeWindow:60 WPoStChallengeLookback:20 FaultDeclarationCutoff:70})
```

### Repo Steps

1. Run '...'
2. Do '...'
3. See error '...'
...

**Comment by stuberman** [comment]
Ran proving checks and restarted all Lotus and Boost systems. I assume this will PoST tomorrow although no changes made other than a restart.

`lotus-miner proving compute window-post 2`

> Took 14m49.249669504s
> [{"Deadline":2,"Partitions":[{"Index":0,"Skipped":[0]}],"Proofs":[{"PoStProof":8,"ProofBytes":"k23oJXHrlLlaKoKkxV8+pPdTmE95JBEHorlaL/rwlHqSxSyrmFYoeFHL5mu6uVfQh0lV3PYs/abjFHBcZZKEOp1WyLrErEdd84ohMpP4uMJ+4YfwapCAIOumgsHsOpRhDu8O6MUwpLcxzOcEh4s6zreXv40ddf93DW1Y6KIWZJbHusNNXFXRK3MVk+AqBG5Et4iZGmxWpUUn5078JtXgfFgYshKTMkO2HkR0h4XYKhMbWyWe9aLvzcW3HvqzgBj1"}],"ChainCommitEpoch":0,"ChainCommitRand":null}]

`lotus-miner proving check --slow 2`
(all good)

`lotus-miner proving deadlines`

> Miner: f01278
> deadline  partitions  sectors (faults)  proven partitions
> 0         1           1717 (0)          0
> 1         1           57 (0)            0
> 2         1           2282 (2282)       0
> 3         1           43 (0)            0

**Comment by rjan90** [comment]
Hey @stuberman! I posted your question to the proofs-team and to them it sounded [like a data issue based on the error messages.](https://filecoinproject.slack.com/archives/CEGB67XJ8/p1664261063962349). It might be that the data got corrupted during reading the challenges for the windowPoSt, and since the `lotus-miner proving compute window-post 2` and the `lotus-miner proving check --slow 2` command I expect that it will go through PoSt tomorrow.

But as a general rule it would probably be good to run a memtest, and checking disk health just to make sure the hardware is okay 😄 Lets keep this issue open for a bit to make sure you pass PoSt a couple of days
