### ISSUE TITLE
Panic during Chain Sync

### ISSUE THREAD

**Issue by protocolin** [filecoin-project/lotus#946]
**Describe the bug**

Seems to incite a panic during chain sync

**To Reproduce**
1. Run:  
`lotus daemon`
`lotus sync wait`

2. See error

From chain sync:
```
Worker 2: Target: [bafy2bzacebowvgdwyfl236bofet3sqhgeik6bkaf7b7sturo3y3v4krtp72p6]	State: header sync	Height: 105392019-12-16T21:13:47.892-0800	WARN	rpc	jsonrpc/websocket.go:426	websocket error	{"error": "read tcp 127.0.0.1:60235->127.0.0.1:1234: read: connection reset by peer"}
2019-12-16T21:13:47.893-0800	WARN	main	lotus/main.go:74	handler: websocket connection closed
```

from daemon:
```
2019-12-16T21:13:47.674-0800	WARN	sub	sub/incoming.go:85	failed to add message from network to message pool (From: t3valpkvr6y4la6t7ywlfkmdldwnmjlgrh7iompfj4hy7epqb4udjgqilhmvnhtti4ecg6nlcsm564qtkscqga, To: t03, Nonce: 8215, Value: 0): failed to look up actor state nonce: resolution lookup failed (t3valpkvr6y4la6t7ywlfkmdldwnmjlgrh7iompfj4hy7epqb4udjgqilhmvnhtti4ecg6nlcsm564qtkscqga): actor not found
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x47bc6ce]
goroutine 14618994 [running]:
github.com/dgraph-io/badger.(*valueLog).write(0xc0004aaf88, 0xc009e77b80, 0x1, 0xa, 0x0, 0x0)
	/Users/colinevran/pkg/mod/github.com/dgraph-io/badger@v1.6.0-rc1/value.go:1037 +0x25e
github.com/dgraph-io/badger.(*DB).writeRequests(0xc0004aae00, 0xc009e77b80, 0x1, 0xa, 0x0, 0x4039d06)
	/Users/colinevran/pkg/mod/github.com/dgraph-io/badger@v1.6.0-rc1/db.go:619 +0x106
github.com/dgraph-io/badger.(*DB).doWrites.func1(0xc009e77b80, 0x1, 0xa)
	/Users/colinevran/pkg/mod/github.com/dgraph-io/badger@v1.6.0-rc1/db.go:692 +0x5a
created by github.com/dgraph-io/badger.(*DB).doWrites
	/Users/colinevran/pkg/mod/github.com/dgraph-io/badger@v1.6.0-rc1/db.go:741 +0x329

```

**Expected behavior**
Syncs the chain

**Comment by AlexLuya** [comment]
same error here

**Comment by whyrusleeping** [comment]
@protocolin (or @AlexLuya ) did you see this error while shutting down the daemon? or during normal execution?

**Comment by tesla809** [comment]
Having a similar issue here.

**Comment by Kubuxu** [comment]
We've updated badger to version where it is fixed.
