### ISSUE TITLE
Abort a `lotus-miner withdraw` will output a `panic`

### ISSUE THREAD

**Issue by Reiers** [filecoin-project/lotus#9596]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [X] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [X] Other

### Lotus Version

```text
Daemon:  1.18.0-rc5+mainnet+git.c1e1d00d0+api1.5.0
Local: lotus version 1.18.0-rc5+mainnet+git.c1e1d00d0
```

### Describe the Bug

Expected behaviour: the output should be "`aborted by user`, exit or something similar"

### Logging Information

```text
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x216bc75]
goroutine 1 [running]:
main.glob..func3(0xc000644f00)
	/home/reiers/lotus/cmd/lotus-miner/actor.go:293 +0x6f5
github.com/urfave/cli/v2.(*Command).Run(0x7775280, 0xc000644d80)
	/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:169 +0x631
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc00060fa00, 0xc000644bc0)
	/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:490 +0xd0a
github.com/urfave/cli/v2.(*Command).startApp(0x77741a0, 0xc000644bc0)
	/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:287 +0x77b
github.com/urfave/cli/v2.(*Command).Run(0xc000644bc0?, 0xc000016700?)
	/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:95 +0xba
github.com/urfave/cli/v2.(*App).RunContext(0xc00060f6c0, {0x4683598?, 0xc000052d60}, {0xc00004e180, 0x3, 0x3})
	/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:341 +0xbc8
github.com/urfave/cli/v2.(*App).Run(...)
	/home/reiers/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:247
github.com/filecoin-project/lotus/cli.RunApp(0x3a34440?)
	/home/reiers/lotus/cli/helper.go:39 +0x4e
main.main()
	/home/reiers/lotus/cmd/lotus-miner/main.go:168 +0x10e5
```
```


### Repo Steps

1.` lotus-miner actor withdraw `
2. abort before 5 epoch has passed (ctrl+c)
3. see panic

**Comment by Reiers** [comment]
Tested, panic is gone. Fixed by https://github.com/filecoin-project/lotus/pull/9704
