### ISSUE TITLE
Lotus Daemon chain prune broken on 1.18.0

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/lotus#9697]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [ ] I did not make any code changes to lotus.

### Lotus component

- [ ] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
1.18.0
```

### Describe the Bug

The panic says enough;
```
panic: interface conversion: *blockstore.discardstore is not blockstore.BlockstoreIterator: missing method ForEachKey

goroutine 143496878 [running]:
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).doPrune(0xc000273400, 0xc047b33800, 0x2?, 0xc0378e7f98)
        /home/filecoinnew/lotus/blockstore/splitstore/splitstore_prune.go:220 +0x93c
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).prune(0x39eb180?, 0x0?, 0x0?, 0xc0004bd380?)
        /home/filecoinnew/lotus/blockstore/splitstore/splitstore_prune.go:131 +0x194
github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).HeadChange.func2()
        /home/filecoinnew/lotus/blockstore/splitstore/splitstore_compact.go:167 +0x2a5
created by github.com/filecoin-project/lotus/blockstore/splitstore.(*SplitStore).HeadChange
        /home/filecoinnew/lotus/blockstore/splitstore/splitstore_compact.go:140 +0x338

```

### Logging Information

```text
See above
```

### Repo Steps

1. Run 1.18.0 with chain prune enabled

**Comment by RobQuistNL** [comment]
In the slack, @TippyFlitsUK mentioned "you can't run a discard store with autoprune enabled"

But, when running the "discard" store and not enabling coldstoreautoprune, it looks like the chain data keeps growing to > 800gb

Also, the config docs do not state anything about this behaviour.

**Comment by mrworkdev** [comment]
Currently have same crash.
BTW I run discard+autoprune on 1.16.1, 1.17.2 and few months was without any issues. On 1.18.0 start to crash.

**Comment by RobQuistNL** [comment]
Same here, looks like it works fine on 1.17.2.
