### ISSUE TITLE
signal arrived during cgo execution

### ISSUE THREAD

**Issue by free1139** [filecoin-project/lotus#9770]
### Checklist

- [X] This is **not** a security-related bug/issue. If it is, please follow please follow the [security policy](https://github.com/filecoin-project/lotus/security/policy).
- [X] This is **not** a question or a support request. If you have any lotus related questions, please ask in the [lotus forum](https://github.com/filecoin-project/lotus/discussions).
- [X] This is **not** a new feature request. If it is, please file a [feature request](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Ffeature&template=feature_request.yml) instead.
- [X] This is **not** an enhancement request. If it is, please file a [improvement suggestion](https://github.com/filecoin-project/lotus/issues/new?assignees=&labels=need%2Ftriage%2Ckind%2Fenhancement&template=enhancement.yml) instead.
- [X] I **have** searched on the [issue tracker](https://github.com/filecoin-project/lotus/issues) and the [lotus forum](https://github.com/filecoin-project/lotus/discussions), and there is no existing related issue or discussion.
- [X] I am running the [`Latest release`](https://github.com/filecoin-project/lotus/releases), or the most recent RC(release canadiate) for the upcoming release or the dev branch(master), or have an issue updating to any of these.
- [X] I did not make any code changes to lotus.

### Lotus component

- [X] lotus daemon - chain sync
- [ ] lotus miner - mining and block production
- [ ] lotus miner/worker - sealing
- [ ] lotus miner - proving(WindowPoSt)
- [ ] lotus miner/market - storage deal
- [ ] lotus miner/market - retrieval deal
- [ ] lotus miner/market - data transfer
- [ ] lotus client
- [ ] lotus JSON-RPC API
- [ ] lotus message management (mpool)
- [ ] Other

### Lotus Version

```text
lotus version 1.18.1+mainnet+git.e68b8e96c
```

### Describe the Bug

Ran lotus on `Intel(R) Xeon(R) Gold 5220R CPU`, go version: `1.19.1`, It panic when the cgo call, and ran failed.
But it is successful on lotus-v1.16.1

### Logging Information

```text
nohup: ignoring input
2022-12-01T19:01:26.803+0800	[34mINFO[0m	main	lotus/daemon.go:218	lotus repo: /data/.lotus
2022-12-01T19:01:26.804+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-ecd683648512ab1765faa2a5f14bab48f676e633467f0aa8aad4b55dcb0652bb.vk is ok
2022-12-01T19:01:26.804+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-7d739b8cf60f1b0709eeebee7730e297683552e4b69cab6984ec0285663c5781.vk is ok
2022-12-01T19:01:26.804+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-50c7368dea9593ed0989e70974d28024efa9d156d585b7eea1be22b2e753f331.vk is ok
2022-12-01T19:01:26.804+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-559e581f022bb4e4ec6e719e563bf0e026ad6de42e56c18714a2c692b1b88d7e.vk is ok
2022-12-01T19:01:26.804+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-0-0-61fa69f38b9cc771ba27b670124714b4ea77fbeae05e377fb859c4a43b73a30c.vk is ok
2022-12-01T19:01:26.804+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-0-0-92180959e1918d26350b8e6cfe217bbdd0a2d8de51ebec269078b364b715ad63.vk is ok
2022-12-01T19:01:26.805+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-0-0-fb9e095bebdd77511c0269b967b4d87ba8b8a525edaa0e165de23ba454510194.vk is ok
2022-12-01T19:01:26.805+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-2-sha256_hasher-96f1b4a04c5c51e4759bbf224bbc2ef5a42c7100f16ec0637123f16a845ddfb2.vk is ok
2022-12-01T19:01:26.805+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-8-0-3b7f44a9362e3985369454947bc94022e118211e49fd672d52bec1cbfd599d18.vk is ok
2022-12-01T19:01:26.805+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-empty-sector-update-merkletree-poseidon_hasher-8-8-2-102e1444a7e9a97ebf1e3d6855dcc77e66c011ea66f936d9b2c508f87f2f83a7.vk is ok
2022-12-01T19:01:26.805+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0170db1f394b35d995252228ee359194b13199d259380541dc529fb0099096b0.vk is ok
2022-12-01T19:01:26.805+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-5294475db5237a2e83c3e52fd6c2b03859a1831d45ed08c4f35dbf9a803165a9.vk is ok
2022-12-01T19:01:26.805+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-8-0-sha256_hasher-82a357d2f2ca81dc61bb45f4a762807aedee1b0a53fd6c4e77b46a01bfef7820.vk is ok
2022-12-01T19:01:26.805+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-3ea05428c9d11689f23529cde32fd30aabd50f7d2c93657c1d3650bca3e8ea9e.vk is ok
2022-12-01T19:01:26.805+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-0-0-0cfb4f178bbb71cf2ecfcd42accce558b27199ab4fb59cb78f2483fe21ef36d9.vk is ok
2022-12-01T19:01:26.805+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-b62098629d07946e9028127e70295ed996fe3ed25b0f9f88eb610a0ab4385a3c.vk is ok
2022-12-01T19:01:26.805+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-6babf46ce344ae495d558e7770a585b2382d54f225af8ed0397b8be7c3fcd472.vk is ok
2022-12-01T19:01:26.805+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-stacked-proof-of-replication-merkletree-poseidon_hasher-8-0-0-sha256_hasher-032d3138d22506ec0082ed72b2dcba18df18477904e35bafee82b3793b06832f.vk is ok
2022-12-01T19:01:26.809+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-0-0377ded656c6f524f1618760bffe4e0a1c51d5a70c4509eedae8a27555733edc.vk is ok
2022-12-01T19:01:26.810+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-proof-of-spacetime-fallback-merkletree-poseidon_hasher-8-8-2-2627e4006b67f99cef990c0a47d5426cb7ab0a0ad58fc1061547bf2d28b09def.vk is ok
2022-12-01T19:01:27.234+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:209	Parameter file /var/tmp/filecoin-proof-parameters/v28-fil-inner-product-v1.srs is ok
2022-12-01T19:01:27.234+0800	[34mINFO[0m	paramfetch	go-paramfetch@v0.0.4/paramfetch.go:233	parameter and key-fetching complete
2022-12-01T19:01:27.252+0800	[34mINFO[0m	modules	modules/core.go:64	memory limits initialized	{"max_mem_heap": 0, "total_system_mem": 269938728960, "effective_mem_limit": 269938728960}
2022-12-01T19:01:27.254+0800	[33mWARN[0m	modules	modules/core.go:124	failed to initialize cgroup-driven watchdog; err: failed to load memory cgroup stats: open /sys/fs/cgroup/memory/user.slice/memory.memsw.usage_in_bytes: no such file or directory
2022-12-01T19:01:27.254+0800	[33mWARN[0m	modules	modules/core.go:125	trying a system-driven watchdog
2022-12-01T19:01:27.254+0800	[34mINFO[0m	watchdog	go-watchdog@v1.3.0/watermarks.go:16	initialized watermark watchdog policy; watermarks: []; thresholds: [134969364480 161963237376 188957110272 229447919616 242944856064 249693324288 256441792512]
2022-12-01T19:01:27.254+0800	[34mINFO[0m	watchdog	go-watchdog@v1.3.0/watchdog.go:472	initialized heap profile capture; threshold: 0.900000; max captures: 10; dir: /data/.lotus/heapprof
2022-12-01T19:01:27.254+0800	[34mINFO[0m	modules	modules/core.go:130	initialized system-driven watchdog
2022-12-01T19:01:27.281+0800	[34mINFO[0m	badger	v2@v2.2007.3/levels.go:183	All 0 tables opened in 0s

2022-12-01T19:01:27.282+0800	[34mINFO[0m	badger	v2@v2.2007.3/value.go:1158	Replaying file id: 0 at offset: 0

2022-12-01T19:01:27.282+0800	[34mINFO[0m	badger	v2@v2.2007.3/value.go:1178	Replay took: 5.43µs

2022-12-01T19:01:27.292+0800	[34mINFO[0m	badger	v2@v2.2007.3/levels.go:183	All 0 tables opened in 0s

2022-12-01T19:01:27.293+0800	[34mINFO[0m	badger	v2@v2.2007.3/value.go:1158	Replaying file id: 0 at offset: 0

2022-12-01T19:01:27.293+0800	[34mINFO[0m	badger	v2@v2.2007.3/value.go:1178	Replay took: 2.251µs

2022-12-01T19:01:27.297+0800	[34mINFO[0m	p2pnode	lp2p/rcmgr.go:38	libp2p resource manager is enabled
2022-12-01T19:01:27.298+0800	[35mDEBUG[0m	rcmgr	resource-manager/limit.go:84	initializing new limiter with config	{"limits": {"System":{"Streams":66406,"StreamsInbound":33203,"StreamsOutbound":66406,"Conns":4150,"ConnsInbound":2075,"ConnsOutbound":4150,"FD":8192,"Memory":4294967296},"Transient":{"Streams":8300,"StreamsInbound":4150,"StreamsOutbound":8300,"Conns":1069,"ConnsInbound":534,"ConnsOutbound":1069,"FD":2048,"Memory":4251320320},"AllowlistedSystem":{"Streams":66406,"StreamsInbound":33203,"StreamsOutbound":66406,"Conns":4150,"ConnsInbound":2075,"ConnsOutbound":4150,"FD":8192,"Memory":33876344832},"AllowlistedTransient":{"Streams":8300,"StreamsInbound":4150,"StreamsOutbound":8300,"Conns":1069,"ConnsInbound":534,"ConnsOutbound":1069,"FD":2048,"Memory":4251320320},"ServiceDefault":{"Streams":68454,"StreamsInbound":17113,"StreamsOutbound":68454,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":4284874752},"Service":{"libp2p.autonat":{"Streams":189,"StreamsInbound":189,"StreamsOutbound":189,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":70096896},"libp2p.holepunch":{"Streams":566,"StreamsInbound":283,"StreamsOutbound":283,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":135999488},"libp2p.identify":{"Streams":4150,"StreamsInbound":2075,"StreamsOutbound":2075,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":135999488},"libp2p.ping":{"Streams":2075,"StreamsInbound":2075,"StreamsOutbound":2075,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":135999488},"libp2p.relay/v1":{"Streams":8300,"StreamsInbound":8300,"StreamsOutbound":8300,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":543997952},"libp2p.relay/v2":{"Streams":8300,"StreamsInbound":8300,"StreamsOutbound":8300,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":543997952}},"ServicePeerDefault":{"Streams":507,"StreamsInbound":253,"StreamsOutbound":507,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":148582400},"ServicePeer":{"libp2p.autonat":{"Streams":2,"StreamsInbound":2,"StreamsOutbound":2,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":1048576},"libp2p.holepunch":{"Streams":2,"StreamsInbound":2,"StreamsOutbound":2,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":1048576},"libp2p.identify":{"Streams":32,"StreamsInbound":16,"StreamsOutbound":16,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":1048576},"libp2p.ping":{"Streams":4,"StreamsInbound":2,"StreamsOutbound":3,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":8590458880},"libp2p.relay/v1":{"Streams":64,"StreamsInbound":64,"StreamsOutbound":64,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":1048576},"libp2p.relay/v2":{"Streams":64,"StreamsInbound":64,"StreamsOutbound":64,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":1048576}},"ProtocolDefault":{"Streams":18137,"StreamsInbound":8556,"StreamsOutbound":18137,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":5471121408},"Protocol":{"/ipfs/id/1.0.0":{"Streams":4150,"StreamsInbound":2075,"StreamsOutbound":2075,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":135999488},"/ipfs/id/push/1.0.0":{"Streams":4150,"StreamsInbound":2075,"StreamsOutbound":2075,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":135999488},"/ipfs/ping/1.0.0":{"Streams":2075,"StreamsInbound":2075,"StreamsOutbound":2075,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":135999488},"/libp2p/autonat/1.0.0":{"Streams":189,"StreamsInbound":189,"StreamsOutbound":189,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":70096896},"/libp2p/circuit/relay/0.1.0":{"Streams":20751,"StreamsInbound":20751,"StreamsOutbound":20751,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":543997952},"/libp2p/circuit/relay/0.2.0/hop":{"Streams":20751,"StreamsInbound":20751,"StreamsOutbound":20751,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":543997952},"/libp2p/circuit/relay/0.2.0/stop":{"Streams":20751,"StreamsInbound":20751,"StreamsOutbound":20751,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":543997952},"/libp2p/dcutr":{"Streams":566,"StreamsInbound":283,"StreamsOutbound":283,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":135999488},"/p2p/id/delta/1.0.0":{"Streams":4150,"StreamsInbound":2075,"StreamsOutbound":2075,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":135999488}},"ProtocolPeerDefault":{"Streams":758,"StreamsInbound":189,"StreamsOutbound":379,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":16777341},"ProtocolPeer":{"/ipfs/id/1.0.0":{"Streams":32,"StreamsInbound":16,"StreamsOutbound":16,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":8590458880},"/ipfs/id/push/1.0.0":{"Streams":32,"StreamsInbound":16,"StreamsOutbound":16,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":8590458880},"/ipfs/ping/1.0.0":{"Streams":4,"StreamsInbound":2,"StreamsOutbound":3,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":8590458880},"/libp2p/autonat/1.0.0":{"Streams":2,"StreamsInbound":2,"StreamsOutbound":2,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":1048576},"/libp2p/circuit/relay/0.1.0":{"Streams":128,"StreamsInbound":128,"StreamsOutbound":128,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":33554432},"/libp2p/circuit/relay/0.2.0/hop":{"Streams":128,"StreamsInbound":128,"StreamsOutbound":128,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":33554432},"/libp2p/circuit/relay/0.2.0/stop":{"Streams":128,"StreamsInbound":128,"StreamsOutbound":128,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":33554432},"/libp2p/dcutr":{"Streams":2,"StreamsInbound":2,"StreamsOutbound":2,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":1048576},"/p2p/id/delta/1.0.0":{"Streams":32,"StreamsInbound":16,"StreamsOutbound":16,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":8590458880}},"PeerDefault":{"Streams":8556,"StreamsInbound":4278,"StreamsOutbound":8556,"Conns":8,"ConnsInbound":4,"ConnsOutbound":8,"FD":128,"Memory":4284874752},"Conn":{"Streams":0,"StreamsInbound":0,"StreamsOutbound":0,"Conns":1,"ConnsInbound":1,"ConnsOutbound":1,"FD":1,"Memory":1048576},"Stream":{"Streams":1,"StreamsInbound":1,"StreamsOutbound":1,"Conns":0,"ConnsInbound":0,"ConnsOutbound":0,"FD":0,"Memory":16777216}}}
2022-12-01T19:01:30.371+0800	[34mINFO[0m	badgerbs	v2@v2.2007.3/levels.go:129	467 tables out of 1767 opened in 3.005s

2022-12-01T19:01:33.367+0800	[34mINFO[0m	badgerbs	v2@v2.2007.3/levels.go:129	939 tables out of 1767 opened in 6.001s

2022-12-01T19:01:36.371+0800	[34mINFO[0m	badgerbs	v2@v2.2007.3/levels.go:129	1423 tables out of 1767 opened in 9.004s

2022-12-01T19:01:37.305+0800	[34mINFO[0m	basichost	basic/natmgr.go:93	DiscoverNAT error:no NAT found
2022-12-01T19:01:38.809+0800	[34mINFO[0m	badgerbs	v2@v2.2007.3/levels.go:183	All 1767 tables opened in 11.443s

2022-12-01T19:01:39.073+0800	[34mINFO[0m	badgerbs	v2@v2.2007.3/value.go:1158	Replaying file id: 2403 at offset: 930332963

2022-12-01T19:01:39.395+0800	[34mINFO[0m	badgerbs	v2@v2.2007.3/value.go:1178	Replay took: 321.24231ms

2022-12-01T19:01:39.395+0800	[34mINFO[0m	badgerbs	v2@v2.2007.3/value.go:1158	Replaying file id: 2404 at offset: 0

2022-12-01T19:01:39.958+0800	[34mINFO[0m	badgerbs	v2@v2.2007.3/value.go:1178	Replay took: 562.745366ms

2022-12-01T19:01:39.975+0800	[34mINFO[0m	p2pnode	lp2p/addrs.go:101	Swarm listening at: [/ip4/127.0.0.1/tcp/41879 /ip4/10.11.61.5/tcp/41879 /ip6/::1/tcp/46103]
2022-12-01T19:01:40.096+0800	[34mINFO[0m	modules	modules/services.go:162	subscribing to pubsub topic /fil/blocks/testnetnet
2022-12-01T19:01:40.097+0800	[34mINFO[0m	modules	modules/services.go:227	relaying messages for pubsub topic /indexer/ingest/mainnet
2022-12-01T19:01:40.100+0800	[34mINFO[0m	importmgr	imports/manager.go:61	sanity checking imports
2022/12/01 19:01:40 storess: Query
2022/12/01 19:01:40 storess: q.Prefix: 
2022/12/01 19:01:40 storess: q.KeysOnly: true
2022/12/01 19:01:40 storess: q.Filters: 0
2022/12/01 19:01:40 storess: q.Orders: 0
2022/12/01 19:01:40 storess: q.Offset: 0
2022-12-01T19:01:40.102+0800	[34mINFO[0m	importmgr	imports/manager.go:98	sanity check completed	{"broken": 0, "total": 0}
2022-12-01T19:01:40.104+0800	[34mINFO[0m	dt-impl	impl/impl.go:145	start data-transfer module
2022-12-01T19:01:40.105+0800	[34mINFO[0m	markets	loggers/loggers.go:65	module ready	{"module": "discovery"}
2022-12-01T19:01:40.105+0800	[34mINFO[0m	markets	loggers/loggers.go:65	module ready	{"module": "client data transfer"}
2022-12-01T19:01:40.105+0800	[34mINFO[0m	markets	loggers/loggers.go:65	module ready	{"module": "retrieval client"}
2022-12-01T19:01:40.105+0800	[34mINFO[0m	markets	loggers/loggers.go:65	module ready	{"module": "storage client"}
2022-12-01T19:01:40.111+0800	[34mINFO[0m	healthcheck	node/health.go:57	waiting 1s before starting ChainNotify channel
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
SIGILL: illegal instruction
PC=0x385ae33 m=20 sigcode=2
signal arrived during cgo execution
instruction bytes: 0x41 0xf 0x38 0xcb 0xd5 0xc5 0xf9 0x70 0xc0 0xe 0xc5 0x79 0x7f 0xe9 0xf 0x38

goroutine 3058 [syscall]:
runtime.cgocall(0x22bd9b5, 0xc1db8b70d0)
	/usr/local/go/src/runtime/cgocall.go:157 +0x5c fp=0xc1db8b7098 sp=0xc1db8b7060 pc=0x683f3c
github.com/filecoin-project/filecoin-ffi/cgo._Cfunc_create_fvm_machine(0x0, 0x2464bf, 0x0, 0x50ae, 0x149f1b9, 0xab93388e556c8a36, 0x11, {0xc18370c060, 0x26}, {0x701ef91, ...}, ...)
	_cgo_gotypes.go:684 +0x50 fp=0xc1db8b70d0 sp=0xc1db8b7098 pc=0x1681790
github.com/filecoin-project/filecoin-ffi/cgo.CreateFvmMachine(0xff?, 0xc1db8b71f0?, 0x68df67?, 0xc1db8b71f0?, 0x6f8f26?, 0xc18093d301?, 0xc1db8b7250?, {0xc18370c060?, 0x3ae2280?}, {0x701ef91, ...}, ...)
	/root/xyp/lotus/extern/filecoin-ffi/cgo/fvm.go:12 +0xc7 fp=0xc1db8b7198 sp=0xc1db8b70d0 pc=0x16879a7
github.com/filecoin-project/filecoin-ffi.CreateFVM(0xc182a5cd90)
	/root/xyp/lotus/extern/filecoin-ffi/fvm.go:64 +0x2df fp=0xc1db8b7280 sp=0xc1db8b7198 pc=0x169507f
github.com/filecoin-project/lotus/chain/vm.NewFVM({0x52b8960?, 0xc183206060?}, 0xc182a5ccb0)
	/root/xyp/lotus/chain/vm/fvm.go:330 +0x193 fp=0xc1db8b72e0 sp=0xc1db8b7280 pc=0x1808373
github.com/filecoin-project/lotus/chain/vm.NewVM({0x52b8960?, 0xc183206060?}, 0x701f801?)
	/root/xyp/lotus/chain/vm/vmi.go:41 +0x45 fp=0xc1db8b7308 sp=0xc1db8b72e0 pc=0x18229a5
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).VMConstructor.func1({0x52b8960?, 0xc183206060?}, 0xc00060cc00?)
	/root/xyp/lotus/chain/stmgr/stmgr.go:397 +0x2e fp=0xc1db8b7330 sp=0xc1db8b7308 pc=0x187f3ae
github.com/filecoin-project/lotus/chain/consensus/filcns.(*TipSetExecutor).ApplyBlocks.func2({{0xc18087b920?, 0x52b8960?}}, 0x2464bf)
	/root/xyp/lotus/chain/consensus/filcns/compute_state.go:106 +0x29f fp=0xc1db8b73d8 sp=0xc1db8b7330 pc=0x195701f
github.com/filecoin-project/lotus/chain/consensus/filcns.(*TipSetExecutor).ApplyBlocks(0x2a839d05b6?, {0x52b8960, 0xc0334f44b0}, 0xc000cfbb00, 0x2464be, {{0xc18087b920?, 0x8?}}, {0xc0003a3680, 0x1, 0x1}, ...)
	/root/xyp/lotus/chain/consensus/filcns/compute_state.go:141 +0x3b8 fp=0xc1db8b7868 sp=0xc1db8b73d8 pc=0x1954f18
github.com/filecoin-project/lotus/chain/consensus/filcns.(*TipSetExecutor).ExecuteTipSet(0x3adff40?, {0x52b8960?, 0xc0334f4480?}, 0xc000cfbb00, 0xc13fbdd740, {0x0, 0x0}, 0x0?)
	/root/xyp/lotus/chain/consensus/filcns/compute_state.go:313 +0x745 fp=0xc1db8b7a68 sp=0xc1db8b7868 pc=0x1957805
github.com/filecoin-project/lotus/chain/stmgr.(*StateManager).TipSetState(0xc000cfbb00, {0x52b88f0?, 0xc000056100?}, 0xc13fbdd740)
	/root/xyp/lotus/chain/stmgr/execute.go:63 +0x7f7 fp=0xc1db8b7bf0 sp=0xc1db8b7a68 pc=0x1876a17
github.com/filecoin-project/lotus/chain/messagepool.(*mpoolProvider).GetActorAfter(0xc000736200, {{0xc18201e240?, 0xc12c0ec240?}}, 0xc0334f42a0?)
	/root/xyp/lotus/chain/messagepool/provider.go:95 +0x21b fp=0xc1db8b7c68 sp=0xc1db8b7bf0 pc=0x19e5c3b
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).getStateNonce(0xc181c7c1a0, {0x52b88b8?, 0xc181bd8900?}, {{0xc18201e240?, 0x0?}}, 0xc13fbdd740)
	/root/xyp/lotus/chain/messagepool/messagepool.go:1035 +0x1c6 fp=0xc1db8b7d18 sp=0xc1db8b7c68 pc=0x19e02e6
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).addLoaded(0xc181c7c1a0, {0x52b88b8, 0xc181bd8900}, 0xc18201a090)
	/root/xyp/lotus/chain/messagepool/messagepool.go:884 +0x73 fp=0xc1db8b7d80 sp=0xc1db8b7d18 pc=0x19debd3
github.com/filecoin-project/lotus/chain/messagepool.(*MessagePool).loadLocal(0xc181c7c1a0, {0x52b88b8, 0xc181bd8900})
	/root/xyp/lotus/chain/messagepool/messagepool.go:1513 +0x28e fp=0xc1db8b7f28 sp=0xc1db8b7d80 pc=0x19e4bce
github.com/filecoin-project/lotus/chain/messagepool.New.func2()
	/root/xyp/lotus/chain/messagepool/messagepool.go:427 +0x6b fp=0xc1db8b7fe0 sp=0xc1db8b7f28 pc=0x19dbc2b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc1db8b7fe8 sp=0xc1db8b7fe0 pc=0x6ec941
created by github.com/filecoin-project/lotus/chain/messagepool.New
	/root/xyp/lotus/chain/messagepool/messagepool.go:425 +0xb9e

goroutine 1 [chan receive]:
main.glob..func5(0xc001b12100)
	/root/xyp/lotus/cmd/lotus/daemon.go:385 +0x1be5
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc000783380, 0xc000793b80)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:495 +0xaff
github.com/urfave/cli/v2.(*Command).startApp(0x6c981c0, 0xc000793b80)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:287 +0x77b
github.com/urfave/cli/v2.(*Command).Run(0xc0005da1e0?, 0xc0005da1e0?)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/command.go:95 +0xba
github.com/urfave/cli/v2.(*App).RunContext(0xc000783040, {0x52b88f0?, 0xc0000560e8}, {0xc00004e040, 0x2, 0x2})
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:341 +0xbc8
github.com/urfave/cli/v2.(*App).Run(...)
	/root/go/pkg/mod/github.com/urfave/cli/v2@v2.8.1/app.go:247
github.com/filecoin-project/lotus/cli.RunApp(0x3ae23a0?)
	/root/xyp/lotus/cli/helper.go:39 +0x4e
main.main()
	/root/xyp/lotus/cmd/lotus/main.go:111 +0x90c
```

### Repo Steps

`lotus deamon`

**Comment by YuXiaoCoder** [comment]
I have the same problem

**Comment by Swift-scouts** [comment]
me too,  ubuntu 18.04

**Comment by DoubleBallTiger** [comment]
how to slave the problem

**Comment by DoubleBallTiger** [comment]
do not use fmt.Print or fmt.Sprint
