### ISSUE TITLE
Transaction Hash Mismatch when deploying contract using Open Zeppelin Upgrades

### ISSUE THREAD

**Issue by scotthconner** [filecoin-project/lotus#9839]
Edited by @jennijuju 

To mitigate this issue, we will expand the existing scope of the sqlite DB that is introduced for events indexing to cover the etherum tx id <> filecoin message CID mapping. We should introduce a configurable variable for node operators to choose if they wanna store this mapping or not, it should be disabled by default.

For the mapping, when we get an ethereum transaction, we reformat it into a ["filecoin" message and get a filecoin CID](https://github.com/filecoin-project/lotus/blob/f681a350fcc9c39a3022a6708fa5da777dd83efa/node/impl/full/eth.go#L516).  We need to keep that tx id <> Filecoin CID mapping.

---
I am trying to deploy an OpenZeppelin ERC1155 contract to FEVM wallaby using the UUPSUpgradeable proxy pattern, and Hardhat upgrades plugin. The code looks as follows:

```js
const deployment = await upgrades.deployProxy(contract, preparedArguments);
        await deployment.deployed();`
```

I've had to override the provider to manually set the gas prices to prevent a legacy transaction error:

```js
if (chainId.toString() === '31415') {
      // Wrap the provider so we can override fee data.
      const provider = new ethers.providers.FallbackProvider([ethers.provider], 1);
      provider.getFeeData = async () => FEE_DATA;
      // override the signer, connected to the provider with hardcoded fee data
      owner = new ethers.Wallet(process.env.MY_PRIVATE_KEY, provider);
    }
```

However, upon deployment I get an error around mismatch expected transaction hash. The hash that comes back is different than the one expected. I'm not certain if this is a post-deployment issue, and the contract is fine, or if this prevented the deployment altogether. It's worth noting that I am using a private key from ethereum, and not certain if that would cause a hash difference. In either case, this is currently blocking FEVM users from using deployable contracts like they would on ethereum, as far as I can tell,

```bash
$ npx hardhat deploy --network wallaby --contract KeyVault

==== GENIE, DEPLOY! ====

{
  "contract": "KeyVault",
  "force": false,
  "upgrade": false
}

=== SIGNER INFO ===

 Signer Network Chain ID: 31415
 Signer Wallet Address: 0x4E5d95F1D3d1b1FB4a169554A6bff1fD164ACa2c
 Signer Balance: 4998.9

=== CONTRACT INFO ===

 Input alias: KeyVault
 Factory Signer Chain ID: 31415
 Factory Signer Address:0x4E5d95F1D3d1b1FB4a169554A6bff1fD164ACa2c

=== NETWORK CONDITIONS ===

 Gas Price: 0.000200278

=== Contract Dependencies ===


Determined Dependencies:
[]

=== Deploying ... ===

Preparing dependency arguments...
Local Code Hash: 0x20b0e0d5ebf32eeee43f6d3bfda7015fee5aa7834abd54d91e2acf352f734987
Calling upgrades.deployProxy with #initialize([])
oooops!: Error: Transaction hash mismatch from Provider.sendTransaction. (expectedHash="0xf8888767ae4f58c6c6650b48ad28f7aa6b7390e13c033d541c8949cfaee2cd1d", returnedHash="0xb5df9c57a34a2807171473190d212f4f7db04da110d64d3534f6dca04d782fc2", code=UNKNOWN_ERROR, version=providers/5.7.0)
An unexpected error occurred:

**Error: Transaction hash mismatch from Provider.sendTransaction.** **(expectedHash="0xf8888767ae4f58c6c6650b48ad28f7aa6b7390e13c033d541c8949cfaee2cd1d", returnedHash="0xb5df9c57a34a2807171473190d212f4f7db04da110d64d3534f6dca04d782fc2",** code=UNKNOWN_ERROR, version=providers/5.7.0)
    at Logger.makeError (/Users/scotthconner/projects/smartrust/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/scotthconner/projects/smartrust/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at EthersProviderWrapper.BaseProvider._wrapTransaction (/Users/scotthconner/projects/smartrust/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1522:20)
    at EthersProviderWrapper.<anonymous> (/Users/scotthconner/projects/smartrust/node_modules/@ethersproject/providers/src.ts/base-provider.ts:1569:25)
    at step (/Users/scotthconner/projects/smartrust/node_modules/@ethersproject/providers/lib/base-provider.js:48:23)
    at Object.next (/Users/scotthconner/projects/smartrust/node_modules/@ethersproject/providers/lib/base-provider.js:29:53)
    at fulfilled (/Users/scotthconner/projects/smartrust/node_modules/@ethersproject/providers/lib/base-provider.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'Transaction hash mismatch from Provider.sendTransaction.',
  code: 'UNKNOWN_ERROR',
  expectedHash: '0xf8888767ae4f58c6c6650b48ad28f7aa6b7390e13c033d541c8949cfaee2cd1d',
  returnedHash: '0xb5df9c57a34a2807171473190d212f4f7db04da110d64d3534f6dca04d782fc2',
  transaction: {
    type: 2,
    chainId: 31415,
    nonce: 11,
    maxPriorityFeePerGas: BigNumber { value: "10000000000" },
    maxFeePerGas: BigNumber { value: "10000000000" },
    gasPrice: null,
    gasLimit: BigNumber { value: "181941066" },
    to: null,
    value: BigNumber { value: "0" },
    data: '0x60a0604052306080523480156200001557600080fd5b506200002062000026565b620000e8565b600054610100900460ff1615620000935760405162461bcd60e51b815260206004820152602760248201527f496e697469616c697a61626c653a20636f6e747261637420697320696e697469604482015266616c697a696e6760c81b606482015260840160405180910390fd5b60005460ff9081161015620000e6576000805460ff191660ff9081179091556040519081527f7f26b83ff96e1f2b6a682f133852f6798a09c465da95921460cefb38474024989060200160405180910390a15b565b6080516130f36200012060003960008181610869015281816108ee01528181610bdd01528181610c620152610d4c01526130f36000f3fe6080604052600436106101695760003560e01c80634e1273f4116100cb5780638f17ae321161007f578063e985e9c511610059578063e985e9c5146103fd578063f242432a14610446578063f5298aca1461046657600080fd5b80638f17ae321461038257806392707869146103b0578063a22cb465146103dd57600080fd5b806352d1902d116100b057806352d1902d14610338578063731133e91461034d5780638129fc1c1461036d57600080fd5b80634e1273f4146103055780634f1ef2861461032557600080fd5b80632e9d4d851161012257806334e80c341161010757806334e80c34146102985780633659cfe6146102c55780633faf3d6b146102e557600080fd5b80632e9d4d85146102565780632eb2c2d61461027857600080fd5b80630e89341c116101535780630e89341c146101d157806313fb817e146101fe5780631eba59aa1461023657600080fd5b8062fdd58e1461016e57806301ffc9a7146101a1575b600080fd5b34801561017a57600080fd5b5061018e6101893660046127b5565b610486565b6040519081526020015b60405180910390f35b3480156101ad57600080fd5b506101c16101bc3660046127f5565b610534565b6040519015158152602001610198565b3480156101dd57600080fd5b506101f16101ec366004612812565b6105cf565b604051610198919061287b565b34801561020a57600080fd5b5060fc5461021e906001600160a01b031681565b6040516001600160a01b039091168152602001610198565b34801561024257600080fd5b5061018e61025136600461289e565b610663565b34801561026257600080fd5b506102766102713660046128da565b610724565b005b34801561028457600080fd5b50610276610293366004612a41565b610799565b3480156102a457600080fd5b506102b86102b33660046128da565b61083b565b6040516101989190612b26565b3480156102d157600080fd5b506102766102e03660046128da565b61085f565b3480156102f157600080fd5b50610276610300366004612b39565b6109da565b34801561031157600080fd5b506102b8610320366004612b6c565b610a95565b610276610333366004612c37565b610bd3565b34801561034457600080fd5b5061018e610d3f565b34801561035957600080fd5b50610276610368366004612c7b565b610e05565b34801561037957600080fd5b50610276610eb7565b34801561038e57600080fd5b5061018e61039d366004612812565b6101006020526000908152604090205481565b3480156103bc57600080fd5b506103d06103cb366004612812565b610ff5565b6040516101989190612d0f565b3480156103e957600080fd5b506102766103f8366004612d5c565b61100f565b34801561040957600080fd5b506101c1610418366004612d8f565b6001600160a01b03918216600090815260666020908152604080832093909416825291909152205460ff1690565b34801561045257600080fd5b50610276610461366004612db9565b61101a565b34801561047257600080fd5b50610276610481366004612b39565b6110b5565b60006001600160a01b0383166105095760405162461bcd60e51b815260206004820152602a60248201527f455243313135353a2061646472657373207a65726f206973206e6f742061207660448201527f616c6964206f776e65720000000000000000000000000000000000000000000060648201526084015b60405180910390fd5b5060008181526065602090815260408083206001600160a01b03861684529091529020545b92915050565b60006001600160e01b031982167fd9b67a2600000000000000000000000000000000000000000000000000000000148061059757506001600160e01b031982167f0e89341c00000000000000000000000000000000000000000000000000000000145b8061052e57507f01ffc9a7000000000000000000000000000000000000000000000000000000006001600160e01b031983161461052e565b6060606780546105de90612e1e565b80601f016020809104026020016040519081016040528092919081815260200182805461060a90612e1e565b80156106575780601f1061062c57610100808354040283529160200191610657565b820191906000526020600020905b81548152906001019060200180831161063a57829003601f168201915b50505050509050919050565b6000816106f5576040517efdd58e0000000000000000000000000000000000000000000000000000000081526001600160a01b038516600482015260248101849052309062fdd58e90604401602060405180830381865afa1580156106cc573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906106f09190612e58565b61071a565b6001600160a01b038416600090815260fd602090815260408083208684529091529020545b90505b9392505050565b60fb546001600160a01b0316331461076a5760405162461bcd60e51b81526020600482015260096024820152682727aa2fa7aba722a960b91b6044820152606401610500565b60fc805473ffffffffffffffffffffffffffffffffffffffff19166001600160a01b0392909216919091179055565b6001600160a01b0385163314806107b557506107b58533610418565b6108275760405162461bcd60e51b815260206004820152602f60248201527f455243313135353a2063616c6c6572206973206e6f7420746f6b656e206f776e60448201527f6572206e6f7220617070726f76656400000000000000000000000000000000006064820152608401610500565b6108348585858585611134565b5050505050565b6001600160a01b038116600090815260fe6020526040902060609061052e906113b8565b6001600160a01b037f00000000000000000000000000000000000000000000000000000000000000001630036108ec5760405162461bcd60e51b815260206004820152602c60248201527f46756e6374696f6e206d7573742062652063616c6c6564207468726f7567682060448201526b19195b1959d85d1958d85b1b60a21b6064820152608401610500565b7f00000000000000000000000000000000000000000000000000000000000000006001600160a01b03166109477f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc546001600160a01b031690565b6001600160a01b0316146109b25760405162461bcd60e51b815260206004820152602c60248201527f46756e6374696f6e206d7573742062652063616c6c6564207468726f7567682060448201526b6163746976652070726f787960a01b6064820152608401610500565b6109bb816113c5565b604080516000808252602082019092526109d79183919061140b565b50565b60fc546001600160a01b03163314610a245760405162461bcd60e51b815260206004820152600d60248201526c09c9ea8be989e8696a69a92a89609b1b6044820152606401610500565b6001600160a01b038316600081815260fd602090815260408083208684528252918290208490558151338152908101929092528101839052606081018290527fdd4ed73814d490cf0c19636b7b143543516fb68cc7d4fff60b44805e18913f449060800160405180910390a1505050565b60608151835114610b0e5760405162461bcd60e51b815260206004820152602960248201527f455243313135353a206163636f756e747320616e6420696473206c656e67746860448201527f206d69736d6174636800000000000000000000000000000000000000000000006064820152608401610500565b6000835167ffffffffffffffff811115610b2a57610b2a6128f5565b604051908082528060200260200182016040528015610b53578160200160208202803683370190505b50905060005b8451811015610bcb57610b9e858281518110610b7757610b77612e71565b6020026020010151858381518110610b9157610b91612e71565b6020026020010151610486565b828281518110610bb057610bb0612e71565b6020908102919091010152610bc481612e9d565b9050610b59565b509392505050565b6001600160a01b037f0000000000000000000000000000000000000000000000000000000000000000163003610c605760405162461bcd60e51b815260206004820152602c60248201527f46756e6374696f6e206d7573742062652063616c6c6564207468726f7567682060448201526b19195b1959d85d1958d85b1b60a21b6064820152608401610500565b7f00000000000000000000000000000000000000000000000000000000000000006001600160a01b0316610cbb7f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc546001600160a01b031690565b6001600160a01b031614610d265760405162461bcd60e51b815260206004820152602c60248201527f46756e6374696f6e206d7573742062652063616c6c6564207468726f7567682060448201526b6163746976652070726f787960a01b6064820152608401610500565b610d2f826113c5565b610d3b8282600161140b565b5050565b6000306001600160a01b037f00000000000000000000000000000000000000000000000000000000000000001614610ddf5760405162461bcd60e51b815260206004820152603860248201527f555550535570677261646561626c653a206d757374206e6f742062652063616c60448201527f6c6564207468726f7567682064656c656761746563616c6c00000000000000006064820152608401610500565b507f360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc5b90565b60fc546001600160a01b03163314610e4f5760405162461bcd60e51b815260206004820152600d60248201526c09c9ea8be989e8696a69a92a89609b1b6044820152606401610500565b6000848152610100602052604081208054859290610e6e908490612eb6565b9250508190555061083485858585858080601f0160208091040260200160405190810160405280939291908181526020018383808284376000920191909152506115ab92505050565b600054610100900460ff1615808015610ed75750600054600160ff909116105b80610ef15750303b158015610ef1575060005460ff166001145b610f635760405162461bcd60e51b815260206004820152602e60248201527f496e697469616c697a61626c653a20636f6e747261637420697320616c72656160448201527f647920696e697469616c697a65640000000000000000000000000000000000006064820152608401610500565b6000805460ff191660011790558015610f86576000805461ff0019166101001790555b60fb805473ffffffffffffffffffffffffffffffffffffffff191633179055610fad6116ec565b80156109d7576000805461ff0019169055604051600181527f7f26b83ff96e1f2b6a682f133852f6798a09c465da95921460cefb38474024989060200160405180910390a150565b600081815260ff6020526040902060609061052e906113b8565b610d3b33838361176b565b6001600160a01b03851633148061103657506110368533610418565b6110a85760405162461bcd60e51b815260206004820152602f60248201527f455243313135353a2063616c6c6572206973206e6f7420746f6b656e206f776e60448201527f6572206e6f7220617070726f76656400000000000000000000000000000000006064820152608401610500565b610834858585858561185f565b60fc546001600160a01b031633146110ff5760405162461bcd60e51b815260206004820152600d60248201526c09c9ea8be989e8696a69a92a89609b1b6044820152606401610500565b600082815261010060205260408120805483929061111e908490612ec9565b9091555061112f9050838383611a1c565b505050565b81518351146111ab5760405162461bcd60e51b815260206004820152602860248201527f455243313135353a2069647320616e6420616d6f756e7473206c656e6774682060448201527f6d69736d617463680000000000000000000000000000000000000000000000006064820152608401610500565b6001600160a01b03841661120f5760405162461bcd60e51b815260206004820152602560248201527f455243313135353a207472616e7366657220746f20746865207a65726f206164604482015264647265737360d81b6064820152608401610500565b3361121e818787878787611be3565b60005b845181101561134a57600085828151811061123e5761123e612e71565b60200260200101519050600085838151811061125c5761125c612e71565b60209081029190910181'... 15640 more characters,
    accessList: [],
    hash: '0xf8888767ae4f58c6c6650b48ad28f7aa6b7390e13c033d541c8949cfaee2cd1d',
    v: 0,
    r: '0x163db65be4aed27f72485245b36be1e4f5c1e1e520fb20ef256d90f61c29b334',
    s: '0x6b255de6b9e9c32857a62e3e59514934639fb52abe6d523fcaf46acfbb4121da',
    from: '0x4E5d95F1D3d1b1FB4a169554A6bff1fD164ACa2c',
    confirmations: 0
  },
  transactionHash: '0xf8888767ae4f58c6c6650b48ad28f7aa6b7390e13c033d541c8949cfaee2cd1d'
```

**Comment by raulk** [comment]
@jennijuju hm, please discuss issue management with @maciejwitowski. We track all FVM items in ref-fvm even if they solely impact the client.

**Comment by jennijuju** [comment]
@raulk we have identified this as a gap and have started to move client issues to its right home. With this, two teams should also  talk to each other more often on over all nv18 (which include not only ref-fvm but also client- lotus) progress, which was missing earlier.

**Comment by scotthconner** [comment]
@jennijuju what are the implications of not having/storing this index by default? Does this mean that solidity/EVM developers would need to either run, or find, a node that supports proper ethereum transaction hashes? If a developer deploys a contract to a node that doesn't have this index, do they still get a proper eth transaction back? If so, can they not poll against the receipt on the same node? What about block explorers?
